// Generated by XIcons
// 2025-08-17 11:03:46
package cn.enaium.xicons.compose.antd

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.AntdIcons

public val AntdIcons.Outlined.Gif: ImageVector
    get() {
        if (_Gif != null) {
            return _Gif!!
        }
        _Gif = ImageVector.Builder(
            name = "Gif",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.0234375f, scaleY = 0.0234375f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(944.00f, 299.00f)
                    horizontalLineTo(692.00f)
                    curveTo(687.60f, 299.00f, 684.00f, 302.60f, 684.00f, 307.00f)
                    verticalLineTo(713.00f)
                    curveTo(684.00f, 717.40f, 687.60f, 721.00f, 692.00f, 721.00f)
                    horizontalLineTo(751.20f)
                    curveTo(755.60f, 721.00f, 759.20f, 717.40f, 759.20f, 713.00f)
                    verticalLineTo(549.90f)
                    horizontalLineTo(927.40f)
                    curveTo(931.80f, 549.90f, 935.40f, 546.30f, 935.40f, 541.90f)
                    verticalLineTo(495.00f)
                    curveTo(935.40f, 490.60f, 931.80f, 487.00f, 927.40f, 487.00f)
                    horizontalLineTo(759.20f)
                    verticalLineTo(364.20f)
                    horizontalLineTo(944.00f)
                    curveTo(948.40f, 364.20f, 952.00f, 360.60f, 952.00f, 356.20f)
                    verticalLineTo(307.00f)
                    curveTo(952.00f, 302.60f, 948.40f, 299.00f, 944.00f, 299.00f)
                    close()
                    moveTo(588.00f, 300.00f)
                    horizontalLineTo(532.00f)
                    curveTo(527.60f, 300.00f, 524.00f, 303.60f, 524.00f, 308.00f)
                    verticalLineTo(714.00f)
                    curveTo(524.00f, 718.40f, 527.60f, 722.00f, 532.00f, 722.00f)
                    horizontalLineTo(588.00f)
                    curveTo(592.40f, 722.00f, 596.00f, 718.40f, 596.00f, 714.00f)
                    verticalLineTo(308.00f)
                    curveTo(596.00f, 303.60f, 592.40f, 300.00f, 588.00f, 300.00f)
                    close()
                    moveTo(452.00f, 500.90f)
                    horizontalLineTo(290.50f)
                    curveTo(286.10f, 500.90f, 282.50f, 504.50f, 282.50f, 508.90f)
                    verticalLineTo(552.60f)
                    curveTo(282.50f, 557.00f, 286.10f, 560.60f, 290.50f, 560.60f)
                    horizontalLineTo(385.40f)
                    lineTo(385.10f, 569.50f)
                    curveTo(383.90f, 628.30f, 339.50f, 668.00f, 274.20f, 668.00f)
                    curveTo(198.00f, 668.00f, 150.30f, 608.30f, 150.30f, 511.30f)
                    curveTo(150.30f, 415.50f, 197.10f, 356.10f, 271.80f, 356.10f)
                    curveTo(326.60f, 356.10f, 364.90f, 383.00f, 380.30f, 431.50f)
                    horizontalLineTo(456.50f)
                    curveTo(442.90f, 344.30f, 370.50f, 288.10f, 271.80f, 288.10f)
                    curveTo(150.00f, 288.00f, 72.00f, 375.20f, 72.00f, 511.90f)
                    curveTo(72.00f, 650.20f, 149.10f, 736.00f, 273.00f, 736.00f)
                    curveTo(387.10f, 736.00f, 460.00f, 665.30f, 460.00f, 554.40f)
                    verticalLineTo(508.90f)
                    curveTo(460.00f, 504.50f, 456.40f, 500.90f, 452.00f, 500.90f)
                    close()
                }
            }
        }.build()
        return _Gif!!
    }

private var _Gif: ImageVector? = null
