// Generated by XIcons
// 2025-08-17 11:03:47
package cn.enaium.xicons.compose.antd

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.AntdIcons

public val AntdIcons.Outlined.PicLeft: ImageVector
    get() {
        if (_PicLeft != null) {
            return _PicLeft!!
        }
        _PicLeft = ImageVector.Builder(
            name = "PicLeft",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.0234375f, scaleY = 0.0234375f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(952.00f, 792.00f)
                    horizontalLineTo(72.00f)
                    curveTo(67.60f, 792.00f, 64.00f, 795.60f, 64.00f, 800.00f)
                    verticalLineTo(856.00f)
                    curveTo(64.00f, 860.40f, 67.60f, 864.00f, 72.00f, 864.00f)
                    horizontalLineTo(952.00f)
                    curveTo(956.40f, 864.00f, 960.00f, 860.40f, 960.00f, 856.00f)
                    verticalLineTo(800.00f)
                    curveTo(960.00f, 795.60f, 956.40f, 792.00f, 952.00f, 792.00f)
                    close()
                    moveTo(952.00f, 160.00f)
                    horizontalLineTo(72.00f)
                    curveTo(67.60f, 160.00f, 64.00f, 163.60f, 64.00f, 168.00f)
                    verticalLineTo(224.00f)
                    curveTo(64.00f, 228.40f, 67.60f, 232.00f, 72.00f, 232.00f)
                    horizontalLineTo(952.00f)
                    curveTo(956.40f, 232.00f, 960.00f, 228.40f, 960.00f, 224.00f)
                    verticalLineTo(168.00f)
                    curveTo(960.00f, 163.60f, 956.40f, 160.00f, 952.00f, 160.00f)
                    close()
                    moveTo(608.00f, 660.00f)
                    curveTo(616.80f, 660.00f, 624.00f, 652.80f, 624.00f, 644.00f)
                    verticalLineTo(380.00f)
                    curveTo(624.00f, 371.20f, 616.80f, 364.00f, 608.00f, 364.00f)
                    horizontalLineTo(96.00f)
                    curveTo(87.20f, 364.00f, 80.00f, 371.20f, 80.00f, 380.00f)
                    verticalLineTo(644.00f)
                    curveTo(80.00f, 652.80f, 87.20f, 660.00f, 96.00f, 660.00f)
                    horizontalLineTo(608.00f)
                    close()
                    moveTo(152.00f, 436.00f)
                    horizontalLineTo(552.00f)
                    verticalLineTo(588.00f)
                    horizontalLineTo(152.00f)
                    verticalLineTo(436.00f)
                    close()
                    moveTo(704.00f, 646.00f)
                    curveTo(704.00f, 650.40f, 707.60f, 654.00f, 712.00f, 654.00f)
                    horizontalLineTo(936.00f)
                    curveTo(940.40f, 654.00f, 944.00f, 650.40f, 944.00f, 646.00f)
                    verticalLineTo(590.00f)
                    curveTo(944.00f, 585.60f, 940.40f, 582.00f, 936.00f, 582.00f)
                    horizontalLineTo(712.00f)
                    curveTo(707.60f, 582.00f, 704.00f, 585.60f, 704.00f, 590.00f)
                    verticalLineTo(646.00f)
                    close()
                    moveTo(712.00f, 442.00f)
                    horizontalLineTo(936.00f)
                    curveTo(940.40f, 442.00f, 944.00f, 438.40f, 944.00f, 434.00f)
                    verticalLineTo(378.00f)
                    curveTo(944.00f, 373.60f, 940.40f, 370.00f, 936.00f, 370.00f)
                    horizontalLineTo(712.00f)
                    curveTo(707.60f, 370.00f, 704.00f, 373.60f, 704.00f, 378.00f)
                    verticalLineTo(434.00f)
                    curveTo(704.00f, 438.40f, 707.60f, 442.00f, 712.00f, 442.00f)
                    close()
                }
            }
        }.build()
        return _PicLeft!!
    }

private var _PicLeft: ImageVector? = null
