// Generated by XIcons
// 2025-08-14 22:08:56
package cn.enaium.xicons.jfx.icons.carbon;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class Csv extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(28.00, 9.00);
        path.lineTo(26.00, 22.00);
        path.lineTo(24.00, 9.00);
        path.horizontalLineTo(22.00);
        path.lineTo(24.52, 23.00);
        path.horizontalLineTo(27.48);
        path.lineTo(30.00, 9.00);
        path.horizontalLineTo(28.00);
        path.close();
        path.moveTo(18.00, 23.00);
        path.horizontalLineTo(12.00);
        path.verticalLineTo(21.00);
        path.horizontalLineTo(18.00);
        path.verticalLineTo(17.00);
        path.horizontalLineTo(14.00);
        path.arcTo(2.00, 2.00, 0.00, false, true, 12.00, 15.00);
        path.verticalLineTo(11.00);
        path.arcTo(2.00, 2.00, 0.00, false, true, 14.00, 9.00);
        path.horizontalLineTo(20.00);
        path.verticalLineTo(11.00);
        path.horizontalLineTo(14.00);
        path.verticalLineTo(15.00);
        path.horizontalLineTo(18.00);
        path.arcTo(2.00, 2.00, 0.00, false, true, 20.00, 17.00);
        path.verticalLineTo(21.00);
        path.arcTo(2.00, 2.00, 0.00, false, true, 18.00, 23.00);
        path.close();
        path.moveTo(10.00, 23.00);
        path.horizontalLineTo(4.00);
        path.arcTo(2.00, 2.00, 0.00, false, true, 2.00, 21.00);
        path.verticalLineTo(11.00);
        path.arcTo(2.00, 2.00, 0.00, false, true, 4.00, 9.00);
        path.horizontalLineTo(10.00);
        path.verticalLineTo(11.00);
        path.horizontalLineTo(4.00);
        path.verticalLineTo(21.00);
        path.horizontalLineTo(10.00);
        path.close();
        path.scale(0.75, 0.75);
        return path;
    }
}
