// Generated by XIcons
// 2025-08-14 22:08:58
package cn.enaium.xicons.jfx.icons.carbon;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class ObjectStorageAlt extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(28.00, 20.00);
        path.horizontalLineTo(26.00);
        path.verticalLineTo(22.00);
        path.horizontalLineTo(28.00);
        path.verticalLineTo(28.00);
        path.horizontalLineTo(4.00);
        path.verticalLineTo(22.00);
        path.horizontalLineTo(14.00);
        path.verticalLineTo(20.00);
        path.horizontalLineTo(4.00);
        path.arcTo(2.00, 2.00, 0.00, false, false, 2.00, 22.00);
        path.verticalLineTo(28.00);
        path.arcTo(2.00, 2.00, 0.00, false, false, 4.00, 30.00);
        path.horizontalLineTo(28.00);
        path.arcTo(2.00, 2.00, 0.00, false, false, 30.00, 28.00);
        path.verticalLineTo(22.00);
        path.arcTo(2.00, 2.00, 0.00, false, false, 28.00, 20.00);
        path.close();
        path.moveTo(21.00, 14.00);
        path.arcTo(2.98, 2.98, 0.00, false, false, 18.96, 14.81);
        path.lineTo(14.96, 12.41);
        path.arcTo(2.96, 2.96, 0.00, false, false, 15.00, 12.00);
        path.arcTo(2.96, 2.96, 0.00, false, false, 14.96, 11.59);
        path.lineTo(18.96, 9.19);
        path.arcTo(2.99, 2.99, 0.00, true, false, 18.00, 7.00);
        path.arcTo(2.93, 2.93, 0.00, false, false, 18.04, 7.41);
        path.lineTo(14.04, 9.81);
        path.arcTo(3.00, 3.00, 0.00, true, false, 14.04, 14.19);
        path.lineTo(18.04, 16.59);
        path.arcTo(2.93, 2.93, 0.00, false, false, 18.00, 17.00);
        path.arcTo(3.00, 3.00, 0.00, true, false, 21.00, 14.00);
        path.close();
        path.moveTo(21.00, 6.00);
        path.arcTo(1.00, 1.00, 0.00, true, true, 20.00, 7.00);
        path.arcTo(1.00, 1.00, 0.00, false, true, 21.00, 6.00);
        path.close();
        path.moveTo(12.00, 13.00);
        path.arcTo(1.00, 1.00, 0.00, true, true, 13.00, 12.00);
        path.arcTo(1.00, 1.00, 0.00, false, true, 12.00, 13.00);
        path.close();
        path.moveTo(21.00, 18.00);
        path.arcTo(1.00, 1.00, 0.00, true, true, 22.00, 17.00);
        path.arcTo(1.00, 1.00, 0.00, false, true, 21.00, 18.00);
        path.close();
        path.scale(0.75, 0.75);
        return path;
    }
}
