// Generated by XIcons
// 2025-08-14 22:08:58
package cn.enaium.xicons.jfx.icons.carbon;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class Playlist extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(4.00, 6.00);
        path.horizontalLineTo(22.00);
        path.verticalLineTo(8.00);
        path.horizontalLineTo(4.00);
        path.close();
        path.moveTo(4.00, 12.00);
        path.horizontalLineTo(22.00);
        path.verticalLineTo(14.00);
        path.horizontalLineTo(4.00);
        path.close();
        path.moveTo(4.00, 18.00);
        path.horizontalLineTo(16.00);
        path.verticalLineTo(20.00);
        path.horizontalLineTo(4.00);
        path.close();
        path.moveTo(21.00, 18.00);
        path.lineTo(28.00, 23.00);
        path.lineTo(21.00, 28.00);
        path.verticalLineTo(18.00);
        path.close();
        path.scale(0.75, 0.75);
        return path;
    }
}
