// Generated by XIcons
// 2025-08-14 22:08:58
package cn.enaium.xicons.jfx.icons.carbon;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class Send extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(27.45, 15.11);
        path.lineTo(5.45, 4.11);
        path.arcTo(1.00, 1.00, 0.00, false, false, 4.37, 4.23);
        path.arcTo(1.00, 1.00, 0.00, false, false, 4.04, 5.23);
        path.lineTo(7.00, 16.00);
        path.lineTo(4.00, 26.74);
        path.arcTo(1.00, 1.00, 0.00, false, false, 5.00, 28.00);
        path.arcTo(1.00, 1.00, 0.00, false, false, 5.45, 27.89);
        path.lineTo(27.45, 16.89);
        path.arcTo(1.00, 1.00, 0.00, false, false, 27.45, 15.11);
        path.close();
        path.moveTo(6.55, 25.11);
        path.lineTo(8.76, 17.00);
        path.horizontalLineTo(18.00);
        path.verticalLineTo(15.00);
        path.horizontalLineTo(8.76);
        path.lineTo(6.55, 6.89);
        path.lineTo(24.76, 16.00);
        path.close();
        path.scale(0.75, 0.75);
        return path;
    }
}
