// Generated by XIcons
// 2025-08-14 22:08:59
package cn.enaium.xicons.jfx.icons.carbon;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class TrafficCone extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(24.80, 28.00);
        path.lineTo(18.98, 2.78);
        path.arcTo(1.00, 1.00, 0.00, false, false, 18.00, 2.00);
        path.horizontalLineTo(14.00);
        path.arcTo(1.00, 1.00, 0.00, false, false, 13.03, 2.78);
        path.lineTo(7.21, 28.00);
        path.horizontalLineTo(4.00);
        path.verticalLineTo(30.00);
        path.horizontalLineTo(28.00);
        path.verticalLineTo(28.00);
        path.close();
        path.moveTo(19.97, 16.00);
        path.horizontalLineTo(12.03);
        path.lineTo(12.95, 12.00);
        path.horizontalLineTo(19.05);
        path.close();
        path.moveTo(20.44, 18.00);
        path.lineTo(21.36, 22.00);
        path.horizontalLineTo(10.64);
        path.lineTo(11.57, 18.00);
        path.close();
        path.moveTo(14.79, 4.00);
        path.horizontalLineTo(17.21);
        path.lineTo(18.59, 10.00);
        path.horizontalLineTo(13.41);
        path.close();
        path.moveTo(10.18, 24.00);
        path.horizontalLineTo(21.82);
        path.lineTo(22.74, 28.00);
        path.horizontalLineTo(9.26);
        path.close();
        path.scale(0.75, 0.75);
        return path;
    }
}
