// Generated by XIcons
// 2025-08-14 22:10:36
package cn.enaium.xicons.swing.icons.antd;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class ShareAltOutlined extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(752.00, 664.00);
        path.curveTo(723.50, 664.00, 697.20, 674.00, 676.60, 690.70);
        path.lineTo(469.40, 540.80);
        path.arcTo(160.68, 160.68, 0.00, false, false, 469.40, 483.20);
        path.lineTo(676.60, 333.30);
        path.curveTo(697.20, 350.00, 723.50, 360.00, 752.00, 360.00);
        path.curveTo(818.20, 360.00, 872.00, 306.20, 872.00, 240.00);
        path.curveTo(872.00, 173.80, 818.20, 120.00, 752.00, 120.00);
        path.curveTo(685.80, 120.00, 632.00, 173.80, 632.00, 240.00);
        path.curveTo(632.00, 251.60, 633.60, 262.70, 636.70, 273.30);
        path.lineTo(439.90, 415.80);
        path.curveTo(410.70, 377.10, 364.30, 352.00, 312.00, 352.00);
        path.curveTo(223.60, 352.00, 152.00, 423.60, 152.00, 512.00);
        path.curveTo(152.00, 600.40, 223.60, 672.00, 312.00, 672.00);
        path.curveTo(364.30, 672.00, 410.70, 646.90, 439.90, 608.20);
        path.lineTo(636.70, 750.70);
        path.curveTo(633.60, 761.30, 632.00, 772.50, 632.00, 784.00);
        path.curveTo(632.00, 850.20, 685.80, 904.00, 752.00, 904.00);
        path.curveTo(818.20, 904.00, 872.00, 850.20, 872.00, 784.00);
        path.curveTo(872.00, 717.80, 818.20, 664.00, 752.00, 664.00);
        path.close();
        path.moveTo(752.00, 188.00);
        path.curveTo(780.70, 188.00, 804.00, 211.30, 804.00, 240.00);
        path.curveTo(804.00, 268.70, 780.70, 292.00, 752.00, 292.00);
        path.curveTo(723.30, 292.00, 700.00, 268.70, 700.00, 240.00);
        path.curveTo(700.00, 211.30, 723.30, 188.00, 752.00, 188.00);
        path.close();
        path.moveTo(312.00, 600.00);
        path.curveTo(263.50, 600.00, 224.00, 560.50, 224.00, 512.00);
        path.curveTo(224.00, 463.50, 263.50, 424.00, 312.00, 424.00);
        path.curveTo(360.50, 424.00, 400.00, 463.50, 400.00, 512.00);
        path.curveTo(400.00, 560.50, 360.50, 600.00, 312.00, 600.00);
        path.close();
        path.moveTo(752.00, 836.00);
        path.curveTo(723.30, 836.00, 700.00, 812.70, 700.00, 784.00);
        path.curveTo(700.00, 755.30, 723.30, 732.00, 752.00, 732.00);
        path.curveTo(780.70, 732.00, 804.00, 755.30, 804.00, 784.00);
        path.curveTo(804.00, 812.70, 780.70, 836.00, 752.00, 836.00);
        path.close();
        path.scale(0.0234375, 0.0234375);
        return path;
    }
}
