// Generated by XIcons
// 2025-08-14 22:10:37
package cn.enaium.xicons.swing.icons.antd;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class ZoomOutOutlined extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(637.00, 443.00);
        path.horizontalLineTo(325.00);
        path.curveTo(320.60, 443.00, 317.00, 446.60, 317.00, 451.00);
        path.verticalLineTo(511.00);
        path.curveTo(317.00, 515.40, 320.60, 519.00, 325.00, 519.00);
        path.horizontalLineTo(637.00);
        path.curveTo(641.40, 519.00, 645.00, 515.40, 645.00, 511.00);
        path.verticalLineTo(451.00);
        path.curveTo(645.00, 446.60, 641.40, 443.00, 637.00, 443.00);
        path.close();
        path.moveTo(921.00, 867.00);
        path.lineTo(775.00, 721.00);
        path.curveTo(897.10, 572.10, 888.60, 351.50, 749.00, 212.00);
        path.curveTo(601.00, 63.90, 360.60, 63.90, 212.00, 212.00);
        path.curveTo(63.90, 360.60, 63.90, 601.00, 212.00, 749.00);
        path.curveTo(351.50, 888.60, 572.10, 897.10, 721.00, 775.00);
        path.lineTo(867.00, 921.00);
        path.curveTo(870.20, 923.80, 875.30, 923.80, 878.00, 921.00);
        path.lineTo(921.00, 878.00);
        path.curveTo(923.80, 875.30, 923.80, 870.20, 921.00, 867.00);
        path.close();
        path.moveTo(696.00, 696.00);
        path.curveTo(577.20, 814.70, 384.80, 814.70, 266.00, 696.00);
        path.curveTo(147.30, 577.20, 147.30, 384.80, 266.00, 266.00);
        path.curveTo(384.80, 147.30, 577.20, 147.30, 696.00, 266.00);
        path.curveTo(814.70, 384.80, 814.70, 577.20, 696.00, 696.00);
        path.close();
        path.scale(0.0234375, 0.0234375);
        return path;
    }
}
