// Generated by XIcons
// 2025-08-14 22:09:07
package cn.enaium.xicons.jfx.icons.fluent;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class ClipboardPulseFilled extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(10.25, 2.00);
        path.horizontalLineTo(13.75);
        path.arcTo(2.25, 2.25, 0.00, false, true, 15.99, 4.00);
        path.horizontalLineTo(17.75);
        path.arcTo(2.25, 2.25, 0.00, false, true, 20.00, 6.25);
        path.verticalLineTo(13.00);
        path.horizontalLineTo(17.74);
        path.lineTo(16.75, 11.35);
        path.arcTo(1.75, 1.75, 0.00, false, false, 13.69, 11.47);
        path.lineTo(13.17, 12.49);
        path.lineTo(11.93, 8.26);
        path.arcTo(1.75, 1.75, 0.00, false, false, 8.69, 7.97);
        path.lineTo(6.17, 13.00);
        path.horizontalLineTo(4.00);
        path.verticalLineTo(6.25);
        path.arcTo(2.25, 2.25, 0.00, false, true, 6.25, 4.00);
        path.horizontalLineTo(8.01);
        path.arcTo(2.25, 2.25, 0.00, false, true, 10.25, 2.00);
        path.close();
        path.moveTo(13.75, 3.50);
        path.horizontalLineTo(10.25);
        path.arcTo(0.75, 0.75, 0.00, false, false, 10.25, 5.00);
        path.horizontalLineTo(13.75);
        path.arcTo(0.75, 0.75, 0.00, false, false, 13.75, 3.50);
        path.close();
        path.moveTo(16.75, 16.50);
        path.horizontalLineTo(20.00);
        path.verticalLineTo(19.75);
        path.arcTo(2.25, 2.25, 0.00, false, true, 17.75, 22.00);
        path.horizontalLineTo(6.25);
        path.arcTo(2.25, 2.25, 0.00, false, true, 4.00, 19.75);
        path.verticalLineTo(16.50);
        path.horizontalLineTo(7.25);
        path.arcTo(1.75, 1.75, 0.00, false, false, 8.82, 15.53);
        path.lineTo(9.83, 13.51);
        path.lineTo(11.07, 17.74);
        path.arcTo(1.75, 1.75, 0.00, false, false, 14.31, 18.03);
        path.lineTo(15.40, 15.86);
        path.curveTo(15.73, 16.26, 16.22, 16.50, 16.75, 16.50);
        path.close();
        path.moveTo(10.97, 8.54);
        path.arcTo(0.75, 0.75, 0.00, false, false, 9.58, 8.42);
        path.lineTo(6.79, 14.00);
        path.horizontalLineTo(2.75);
        path.arcTo(0.75, 0.75, 0.00, false, false, 2.75, 15.50);
        path.horizontalLineTo(7.25);
        path.arcTo(0.75, 0.75, 0.00, false, false, 7.92, 15.09);
        path.lineTo(10.07, 10.79);
        path.lineTo(12.03, 17.46);
        path.arcTo(0.75, 0.75, 0.00, false, false, 13.42, 17.59);
        path.lineTo(15.31, 13.81);
        path.lineTo(16.11, 15.14);
        path.arcTo(0.75, 0.75, 0.00, false, false, 16.75, 15.50);
        path.horizontalLineTo(21.25);
        path.arcTo(0.75, 0.75, 0.00, false, false, 21.25, 14.00);
        path.horizontalLineTo(17.18);
        path.lineTo(15.89, 11.86);
        path.arcTo(0.75, 0.75, 0.00, false, false, 14.58, 11.91);
        path.lineTo(12.93, 15.21);
        path.lineTo(10.97, 8.54);
        path.close();
        return path;
    }
}
