// Generated by XIcons
// 2025-08-14 22:09:07
package cn.enaium.xicons.jfx.icons.fluent;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class DataUsageEditRegular extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(20.00, 4.75);
        path.arcTo(2.75, 2.75, 0.00, false, false, 17.25, 2.00);
        path.horizontalLineTo(4.75);
        path.arcTo(2.75, 2.75, 0.00, false, false, 2.00, 4.75);
        path.verticalLineTo(17.25);
        path.arcTo(2.75, 2.75, 0.00, false, false, 4.75, 20.00);
        path.horizontalLineTo(11.42);
        path.lineTo(11.52, 19.58);
        path.curveTo(11.62, 19.19, 11.77, 18.83, 11.98, 18.50);
        path.horizontalLineTo(4.75);
        path.curveTo(4.06, 18.50, 3.50, 17.94, 3.50, 17.25);
        path.verticalLineTo(4.75);
        path.curveTo(3.50, 4.06, 4.06, 3.50, 4.75, 3.50);
        path.horizontalLineTo(17.25);
        path.curveTo(17.94, 3.50, 18.50, 4.06, 18.50, 4.75);
        path.verticalLineTo(11.86);
        path.curveTo(18.94, 11.46, 19.46, 11.20, 20.00, 11.08);
        path.verticalLineTo(4.75);
        path.close();
        path.moveTo(16.00, 14.35);
        path.verticalLineTo(6.73);
        path.lineTo(15.99, 6.63);
        path.arcTo(0.74, 0.74, 0.00, false, false, 15.25, 6.00);
        path.arcTo(0.74, 0.74, 0.00, false, false, 14.50, 6.73);
        path.verticalLineTo(15.27);
        path.lineTo(14.51, 15.37);
        path.curveTo(14.52, 15.50, 14.57, 15.61, 14.65, 15.71);
        path.lineTo(16.00, 14.36);
        path.close();
        path.moveTo(7.49, 8.64);
        path.arcTo(0.75, 0.75, 0.00, false, false, 6.75, 8.00);
        path.arcTo(0.75, 0.75, 0.00, false, false, 6.00, 8.75);
        path.verticalLineTo(15.25);
        path.lineTo(6.01, 15.36);
        path.curveTo(6.06, 15.72, 6.37, 16.00, 6.75, 16.00);
        path.curveTo(7.16, 16.00, 7.50, 15.67, 7.50, 15.25);
        path.verticalLineTo(8.75);
        path.lineTo(7.49, 8.65);
        path.close();
        path.moveTo(11.71, 11.62);
        path.arcTo(0.73, 0.73, 0.00, false, false, 10.98, 11.00);
        path.arcTo(0.73, 0.73, 0.00, false, false, 10.25, 11.73);
        path.lineTo(10.29, 15.28);
        path.lineTo(10.29, 15.38);
        path.arcTo(0.73, 0.73, 0.00, false, false, 11.03, 16.00);
        path.arcTo(0.73, 0.73, 0.00, false, false, 11.75, 15.26);
        path.lineTo(11.72, 11.72);
        path.lineTo(11.71, 11.62);
        path.close();
        path.moveTo(19.10, 12.67);
        path.lineTo(13.20, 18.57);
        path.arcTo(2.69, 2.69, 0.00, false, false, 12.49, 19.82);
        path.lineTo(12.03, 21.65);
        path.arcTo(1.09, 1.09, 0.00, false, false, 13.35, 22.97);
        path.lineTo(15.18, 22.51);
        path.arcTo(2.69, 2.69, 0.00, false, false, 16.43, 21.80);
        path.lineTo(22.33, 15.90);
        path.arcTo(2.29, 2.29, 0.00, false, false, 19.10, 12.67);
        path.close();
        return path;
    }
}
