// Generated by XIcons
// 2025-08-14 22:09:08
package cn.enaium.xicons.jfx.icons.fluent;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class DocumentQuestionMarkFilled extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(12.00, 2.00);
        path.verticalLineTo(8.00);
        path.arcTo(2.00, 2.00, 0.00, false, false, 14.00, 10.00);
        path.horizontalLineTo(20.00);
        path.verticalLineTo(20.00);
        path.arcTo(2.00, 2.00, 0.00, false, true, 18.00, 22.00);
        path.horizontalLineTo(11.19);
        path.arcTo(6.50, 6.50, 0.00, false, false, 4.00, 11.50);
        path.verticalLineTo(4.00);
        path.arcTo(2.00, 2.00, 0.00, false, true, 6.00, 2.00);
        path.horizontalLineTo(12.00);
        path.close();
        path.moveTo(13.50, 2.50);
        path.verticalLineTo(8.00);
        path.arcTo(0.50, 0.50, 0.00, false, false, 14.00, 8.50);
        path.horizontalLineTo(19.50);
        path.lineTo(13.50, 2.50);
        path.close();
        path.moveTo(1.00, 17.50);
        path.arcTo(5.50, 5.50, 0.00, true, false, 12.00, 17.50);
        path.arcTo(5.50, 5.50, 0.00, false, false, 1.00, 17.50);
        path.close();
        path.moveTo(5.75, 20.75);
        path.arcTo(0.75, 0.75, 0.00, true, true, 7.25, 20.75);
        path.arcTo(0.75, 0.75, 0.00, false, true, 5.75, 20.75);
        path.close();
        path.moveTo(4.50, 16.00);
        path.arcTo(2.00, 2.00, 0.00, true, true, 8.50, 16.00);
        path.curveTo(8.50, 16.73, 8.29, 17.14, 7.75, 17.71);
        path.lineTo(7.48, 17.98);
        path.lineTo(7.37, 18.10);
        path.curveTo(7.08, 18.42, 7.00, 18.63, 7.00, 19.00);
        path.arcTo(0.50, 0.50, 0.00, false, true, 6.00, 19.00);
        path.curveTo(6.00, 18.27, 6.21, 17.86, 6.75, 17.29);
        path.lineTo(7.02, 17.02);
        path.lineTo(7.13, 16.90);
        path.curveTo(7.42, 16.58, 7.50, 16.37, 7.50, 16.00);
        path.arcTo(1.00, 1.00, 0.00, true, false, 5.50, 16.00);
        path.arcTo(0.50, 0.50, 0.00, false, true, 4.50, 16.00);
        path.close();
        return path;
    }
}
