// Generated by XIcons
// 2025-08-14 22:09:08
package cn.enaium.xicons.jfx.icons.fluent;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class DocumentPageBottomRightRegular extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(17.75, 2.00);
        path.arcTo(2.25, 2.25, 0.00, false, true, 19.99, 4.09);
        path.lineTo(20.00, 4.25);
        path.verticalLineTo(19.74);
        path.arcTo(2.25, 2.25, 0.00, false, true, 17.90, 21.99);
        path.lineTo(17.75, 21.99);
        path.horizontalLineTo(6.25);
        path.arcTo(2.25, 2.25, 0.00, false, true, 4.00, 19.90);
        path.lineTo(4.00, 19.74);
        path.verticalLineTo(4.25);
        path.arcTo(2.25, 2.25, 0.00, false, true, 6.09, 2.00);
        path.lineTo(6.25, 2.00);
        path.horizontalLineTo(17.75);
        path.close();
        path.moveTo(17.75, 3.50);
        path.horizontalLineTo(6.25);
        path.arcTo(0.75, 0.75, 0.00, false, false, 5.50, 4.14);
        path.lineTo(5.50, 4.25);
        path.verticalLineTo(19.74);
        path.curveTo(5.50, 20.12, 5.78, 20.44, 6.14, 20.49);
        path.lineTo(6.25, 20.49);
        path.horizontalLineTo(17.75);
        path.arcTo(0.75, 0.75, 0.00, false, false, 18.49, 19.85);
        path.lineTo(18.50, 19.74);
        path.verticalLineTo(4.25);
        path.arcTo(0.75, 0.75, 0.00, false, false, 17.85, 3.50);
        path.lineTo(17.75, 3.50);
        path.close();
        path.moveTo(15.02, 19.90);
        path.arcTo(0.75, 0.75, 0.00, false, true, 14.40, 19.04);
        path.lineTo(14.50, 18.38);
        path.horizontalLineTo(13.02);
        path.lineTo(12.88, 19.28);
        path.arcTo(0.75, 0.75, 0.00, false, true, 11.40, 19.04);
        path.lineTo(11.50, 18.38);
        path.horizontalLineTo(10.75);
        path.arcTo(0.75, 0.75, 0.00, true, true, 10.75, 16.88);
        path.horizontalLineTo(11.74);
        path.lineTo(11.98, 15.38);
        path.horizontalLineTo(11.25);
        path.arcTo(0.75, 0.75, 0.00, true, true, 11.25, 13.88);
        path.horizontalLineTo(12.21);
        path.lineTo(12.41, 12.62);
        path.arcTo(0.75, 0.75, 0.00, false, true, 13.89, 12.86);
        path.lineTo(13.73, 13.88);
        path.horizontalLineTo(15.21);
        path.lineTo(15.41, 12.62);
        path.arcTo(0.75, 0.75, 0.00, false, true, 16.90, 12.86);
        path.lineTo(16.73, 13.88);
        path.horizontalLineTo(17.25);
        path.arcTo(0.75, 0.75, 0.00, false, true, 17.25, 15.38);
        path.horizontalLineTo(16.50);
        path.lineTo(16.26, 16.88);
        path.horizontalLineTo(16.75);
        path.arcTo(0.75, 0.75, 0.00, false, true, 16.75, 18.38);
        path.horizontalLineTo(16.02);
        path.lineTo(15.88, 19.28);
        path.arcTo(0.75, 0.75, 0.00, false, true, 15.02, 19.90);
        path.close();
        path.moveTo(13.49, 15.38);
        path.lineTo(13.26, 16.88);
        path.horizontalLineTo(14.74);
        path.lineTo(14.98, 15.38);
        path.horizontalLineTo(13.50);
        path.close();
        return path;
    }
}
