// Generated by XIcons
// 2025-08-14 22:09:08
package cn.enaium.xicons.jfx.icons.fluent;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class DrawTextFilled extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(12.24, 13.15);
        path.horizontalLineTo(7.76);
        path.lineTo(10.00, 6.74);
        path.lineTo(12.24, 13.15);
        path.close();
        path.moveTo(12.94, 15.15);
        path.lineTo(13.27, 16.08);
        path.lineTo(14.84, 14.51);
        path.lineTo(11.08, 3.76);
        path.curveTo(10.72, 2.75, 9.28, 2.75, 8.93, 3.76);
        path.lineTo(4.06, 17.67);
        path.arcTo(1.00, 1.00, 0.00, true, false, 5.94, 18.33);
        path.lineTo(7.06, 15.15);
        path.horizontalLineTo(12.94);
        path.close();
        path.moveTo(13.20, 17.57);
        path.lineTo(19.10, 11.67);
        path.arcTo(2.29, 2.29, 0.00, true, true, 22.33, 14.90);
        path.lineTo(16.43, 20.80);
        path.arcTo(2.68, 2.68, 0.00, false, true, 15.18, 21.51);
        path.lineTo(13.35, 21.97);
        path.curveTo(13.30, 21.98, 13.25, 21.99, 13.20, 22.00);
        path.curveTo(12.61, 22.20, 10.22, 22.57, 9.38, 21.91);
        path.curveTo(8.80, 21.46, 8.92, 20.57, 9.16, 20.09);
        path.curveTo(9.20, 20.01, 9.14, 19.91, 9.05, 19.92);
        path.curveTo(8.39, 20.03, 7.81, 20.37, 7.23, 20.72);
        path.curveTo(6.44, 21.19, 5.66, 21.66, 4.68, 21.54);
        path.curveTo(3.70, 21.42, 3.21, 20.81, 2.97, 20.28);
        path.curveTo(2.87, 20.07, 3.15, 19.88, 3.36, 20.00);
        path.curveTo(3.82, 20.25, 4.46, 20.49, 4.99, 20.38);
        path.curveTo(5.36, 20.29, 5.89, 19.92, 6.48, 19.50);
        path.curveTo(7.55, 18.75, 8.82, 17.85, 9.77, 18.23);
        path.curveTo(10.61, 18.57, 11.23, 19.38, 10.80, 20.34);
        path.curveTo(10.75, 20.46, 10.80, 20.61, 10.93, 20.64);
        path.curveTo(11.35, 20.73, 11.71, 20.70, 12.06, 20.53);
        path.lineTo(12.49, 18.82);
        path.curveTo(12.61, 18.35, 12.85, 17.92, 13.20, 17.57);
        path.close();
        return path;
    }
}
