// Generated by XIcons
// 2025-08-14 22:09:09
package cn.enaium.xicons.jfx.icons.fluent;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class HighlightAccentFilled extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(20.00, 4.00);
        path.lineTo(20.00, 7.75);
        path.lineTo(19.99, 7.85);
        path.arcTo(0.75, 0.75, 0.00, false, true, 19.28, 8.50);
        path.horizontalLineTo(4.74);
        path.lineTo(4.65, 8.49);
        path.arcTo(0.75, 0.75, 0.00, false, true, 4.00, 7.75);
        path.verticalLineTo(4.00);
        path.horizontalLineTo(20.00);
        path.close();
        path.moveTo(15.51, 13.50);
        path.horizontalLineTo(8.50);
        path.verticalLineTo(21.00);
        path.lineTo(15.08, 17.89);
        path.arcTo(0.75, 0.75, 0.00, false, false, 15.50, 17.32);
        path.lineTo(15.51, 17.22);
        path.lineTo(15.51, 13.50);
        path.close();
        return path;
    }
}
