// Generated by XIcons
// 2025-08-14 22:09:10
package cn.enaium.xicons.jfx.icons.fluent;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class NumberSymbolDismissFilled extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(10.99, 3.17);
        path.arcTo(1.00, 1.00, 0.00, false, false, 9.01, 2.84);
        path.lineTo(8.15, 8.00);
        path.lineTo(4.00, 8.00);
        path.arcTo(1.00, 1.00, 0.00, false, false, 4.00, 10.00);
        path.lineTo(7.82, 10.00);
        path.lineTo(7.15, 14.00);
        path.lineTo(3.00, 14.00);
        path.arcTo(1.00, 1.00, 0.00, true, false, 3.00, 16.00);
        path.lineTo(6.82, 16.00);
        path.lineTo(6.01, 20.84);
        path.arcTo(1.00, 1.00, 0.00, true, false, 7.98, 21.17);
        path.lineTo(8.84, 16.00);
        path.lineTo(11.17, 16.00);
        path.curveTo(11.34, 15.28, 11.64, 14.60, 12.02, 14.00);
        path.lineTo(9.18, 14.00);
        path.lineTo(9.84, 10.00);
        path.lineTo(14.82, 9.99);
        path.lineTo(14.53, 11.71);
        path.arcTo(6.46, 6.46, 0.00, false, true, 16.67, 11.05);
        path.lineTo(16.85, 9.99);
        path.lineTo(21.00, 9.99);
        path.arcTo(1.00, 1.00, 0.00, false, false, 21.00, 7.99);
        path.lineTo(17.18, 7.99);
        path.lineTo(17.99, 3.17);
        path.arcTo(1.00, 1.00, 0.00, true, false, 16.01, 2.84);
        path.lineTo(15.15, 7.99);
        path.lineTo(10.18, 8.00);
        path.lineTo(10.98, 3.17);
        path.close();
        path.moveTo(23.00, 17.50);
        path.arcTo(5.50, 5.50, 0.00, true, true, 12.00, 17.50);
        path.arcTo(5.50, 5.50, 0.00, false, true, 23.00, 17.50);
        path.close();
        path.moveTo(15.85, 15.15);
        path.arcTo(0.50, 0.50, 0.00, false, false, 15.15, 15.85);
        path.lineTo(16.79, 17.50);
        path.lineTo(15.15, 19.15);
        path.arcTo(0.50, 0.50, 0.00, false, false, 15.85, 19.85);
        path.lineTo(17.50, 18.21);
        path.lineTo(19.15, 19.85);
        path.arcTo(0.50, 0.50, 0.00, false, false, 19.85, 19.15);
        path.lineTo(18.21, 17.50);
        path.lineTo(19.85, 15.85);
        path.arcTo(0.50, 0.50, 0.00, false, false, 19.15, 15.15);
        path.lineTo(17.50, 16.79);
        path.lineTo(15.85, 15.15);
        path.close();
        return path;
    }
}
