// Generated by XIcons
// 2025-08-14 22:09:10
package cn.enaium.xicons.jfx.icons.fluent;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class PhonePageHeaderFilled extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(18.00, 6.01);
        path.verticalLineTo(19.75);
        path.arcTo(2.25, 2.25, 0.00, false, true, 15.75, 22.00);
        path.horizontalLineTo(8.25);
        path.arcTo(2.25, 2.25, 0.00, false, true, 6.00, 19.75);
        path.verticalLineTo(6.01);
        path.horizontalLineTo(18.00);
        path.close();
        path.moveTo(15.75, 2.00);
        path.arcTo(2.25, 2.25, 0.00, false, true, 18.00, 4.25);
        path.verticalLineTo(5.00);
        path.horizontalLineTo(6.00);
        path.verticalLineTo(4.25);
        path.arcTo(2.25, 2.25, 0.00, false, true, 8.25, 2.00);
        path.horizontalLineTo(15.75);
        path.close();
        return path;
    }
}
