// Generated by XIcons
// 2025-08-14 22:09:11
package cn.enaium.xicons.jfx.icons.fluent;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class SaveRegular extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(3.00, 5.75);
        path.arcTo(2.75, 2.75, 0.00, false, true, 5.75, 3.00);
        path.horizontalLineTo(15.71);
        path.arcTo(3.25, 3.25, 0.00, false, true, 18.01, 3.95);
        path.lineTo(20.05, 5.99);
        path.curveTo(20.66, 6.60, 21.00, 7.42, 21.00, 8.29);
        path.verticalLineTo(18.25);
        path.arcTo(2.75, 2.75, 0.00, false, true, 18.25, 21.00);
        path.horizontalLineTo(5.75);
        path.arcTo(2.75, 2.75, 0.00, false, true, 3.00, 18.25);
        path.verticalLineTo(5.75);
        path.close();
        path.moveTo(5.75, 4.50);
        path.curveTo(5.06, 4.50, 4.50, 5.06, 4.50, 5.75);
        path.verticalLineTo(18.25);
        path.curveTo(4.50, 18.94, 5.06, 19.50, 5.75, 19.50);
        path.horizontalLineTo(6.00);
        path.verticalLineTo(14.25);
        path.arcTo(2.25, 2.25, 0.00, false, true, 8.25, 12.00);
        path.horizontalLineTo(15.75);
        path.arcTo(2.25, 2.25, 0.00, false, true, 18.00, 14.25);
        path.verticalLineTo(19.50);
        path.horizontalLineTo(18.25);
        path.curveTo(18.94, 19.50, 19.50, 18.94, 19.50, 18.25);
        path.verticalLineTo(8.29);
        path.curveTo(19.50, 7.82, 19.32, 7.38, 18.99, 7.05);
        path.lineTo(16.95, 5.01);
        path.arcTo(1.75, 1.75, 0.00, false, false, 16.00, 4.52);
        path.verticalLineTo(7.25);
        path.arcTo(2.25, 2.25, 0.00, false, true, 13.75, 9.50);
        path.horizontalLineTo(9.25);
        path.arcTo(2.25, 2.25, 0.00, false, true, 7.00, 7.25);
        path.verticalLineTo(4.50);
        path.horizontalLineTo(5.75);
        path.close();
        path.moveTo(16.50, 19.50);
        path.verticalLineTo(14.25);
        path.arcTo(0.75, 0.75, 0.00, false, false, 15.75, 13.50);
        path.horizontalLineTo(8.25);
        path.arcTo(0.75, 0.75, 0.00, false, false, 7.50, 14.25);
        path.verticalLineTo(19.50);
        path.horizontalLineTo(16.50);
        path.close();
        path.moveTo(8.50, 4.50);
        path.verticalLineTo(7.25);
        path.curveTo(8.50, 7.66, 8.84, 8.00, 9.25, 8.00);
        path.horizontalLineTo(13.75);
        path.arcTo(0.75, 0.75, 0.00, false, false, 14.50, 7.25);
        path.verticalLineTo(4.50);
        path.horizontalLineTo(8.50);
        path.close();
        return path;
    }
}
