// Generated by XIcons
// 2025-08-14 22:09:11
package cn.enaium.xicons.jfx.icons.fluent;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class ShieldFilled extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(3.00, 5.75);
        path.arcTo(0.75, 0.75, 0.00, false, true, 3.75, 5.00);
        path.curveTo(6.41, 5.00, 9.01, 4.06, 11.55, 2.15);
        path.arcTo(0.75, 0.75, 0.00, false, true, 12.45, 2.15);
        path.curveTo(14.99, 4.06, 17.59, 5.00, 20.25, 5.00);
        path.arcTo(0.75, 0.75, 0.00, false, true, 21.00, 5.75);
        path.verticalLineTo(11.00);
        path.curveTo(21.00, 16.00, 18.04, 19.68, 12.28, 21.95);
        path.arcTo(0.75, 0.75, 0.00, false, true, 11.73, 21.95);
        path.curveTo(5.96, 19.68, 3.00, 16.00, 3.00, 11.00);
        path.verticalLineTo(5.75);
        path.close();
        return path;
    }
}
