// Generated by XIcons
// 2025-08-14 22:09:12
package cn.enaium.xicons.jfx.icons.fluent;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class TextboxRotate90Filled extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(18.25, 21.00);
        path.arcTo(2.75, 2.75, 0.00, false, false, 21.00, 18.25);
        path.verticalLineTo(5.75);
        path.arcTo(2.75, 2.75, 0.00, false, false, 18.25, 3.00);
        path.horizontalLineTo(5.75);
        path.arcTo(2.75, 2.75, 0.00, false, false, 3.00, 5.75);
        path.verticalLineTo(18.25);
        path.arcTo(2.75, 2.75, 0.00, false, false, 5.75, 21.00);
        path.horizontalLineTo(18.25);
        path.close();
        path.moveTo(12.50, 14.25);
        path.arcTo(0.75, 0.75, 0.00, false, true, 11.01, 14.35);
        path.lineTo(11.00, 14.25);
        path.verticalLineTo(6.75);
        path.arcTo(0.75, 0.75, 0.00, false, true, 12.49, 6.65);
        path.lineTo(12.50, 6.75);
        path.verticalLineTo(14.25);
        path.close();
        path.moveTo(8.50, 6.75);
        path.verticalLineTo(17.25);
        path.arcTo(0.75, 0.75, 0.00, false, true, 7.01, 17.35);
        path.lineTo(7.00, 17.25);
        path.verticalLineTo(6.75);
        path.arcTo(0.75, 0.75, 0.00, false, true, 8.49, 6.65);
        path.lineTo(8.50, 6.75);
        path.close();
        path.moveTo(16.50, 17.25);
        path.arcTo(0.75, 0.75, 0.00, false, true, 15.01, 17.35);
        path.lineTo(15.00, 17.25);
        path.verticalLineTo(6.75);
        path.arcTo(0.75, 0.75, 0.00, false, true, 16.49, 6.65);
        path.lineTo(16.50, 6.75);
        path.verticalLineTo(17.25);
        path.close();
        return path;
    }
}
