// Generated by XIcons
// 2025-08-14 22:09:12
package cn.enaium.xicons.jfx.icons.fluent;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class TextAlignJustifyLowRegular extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(13.00, 5.75);
        path.arcTo(0.75, 0.75, 0.00, false, true, 13.75, 5.00);
        path.horizontalLineTo(21.25);
        path.arcTo(0.75, 0.75, 0.00, false, true, 21.25, 6.50);
        path.horizontalLineTo(13.75);
        path.arcTo(0.75, 0.75, 0.00, false, true, 13.00, 5.75);
        path.close();
        path.moveTo(2.00, 18.75);
        path.arcTo(0.75, 0.75, 0.00, false, true, 2.75, 18.00);
        path.horizontalLineTo(21.25);
        path.arcTo(0.75, 0.75, 0.00, false, true, 21.25, 19.50);
        path.horizontalLineTo(2.75);
        path.arcTo(0.75, 0.75, 0.00, false, true, 2.00, 18.75);
        path.close();
        path.moveTo(13.75, 11.50);
        path.arcTo(0.75, 0.75, 0.00, false, false, 13.75, 13.00);
        path.horizontalLineTo(21.25);
        path.arcTo(0.75, 0.75, 0.00, false, false, 21.25, 11.50);
        path.horizontalLineTo(13.75);
        path.close();
        return path;
    }
}
