// Generated by XIcons
// 2025-08-14 22:09:12
package cn.enaium.xicons.jfx.icons.fluent;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class VehicleBusRegular extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(8.00, 16.00);
        path.arcTo(1.00, 1.00, 0.00, true, false, 8.00, 14.00);
        path.arcTo(1.00, 1.00, 0.00, false, false, 8.00, 16.00);
        path.close();
        path.moveTo(17.00, 15.00);
        path.arcTo(1.00, 1.00, 0.00, true, true, 15.00, 15.00);
        path.arcTo(1.00, 1.00, 0.00, false, true, 17.00, 15.00);
        path.close();
        path.moveTo(10.75, 5.00);
        path.arcTo(0.75, 0.75, 0.00, false, false, 10.75, 6.50);
        path.horizontalLineTo(13.25);
        path.arcTo(0.75, 0.75, 0.00, false, false, 13.25, 5.00);
        path.horizontalLineTo(10.75);
        path.close();
        path.moveTo(7.75, 2.00);
        path.arcTo(3.75, 3.75, 0.00, false, false, 4.00, 5.75);
        path.verticalLineTo(9.50);
        path.horizontalLineTo(2.75);
        path.arcTo(0.75, 0.75, 0.00, true, false, 2.75, 11.00);
        path.horizontalLineTo(4.00);
        path.verticalLineTo(19.75);
        path.curveTo(4.00, 20.72, 4.78, 21.50, 5.75, 21.50);
        path.horizontalLineTo(7.25);
        path.arcTo(1.75, 1.75, 0.00, false, false, 9.00, 19.75);
        path.verticalLineTo(18.50);
        path.horizontalLineTo(15.00);
        path.verticalLineTo(19.75);
        path.curveTo(15.00, 20.72, 15.78, 21.50, 16.75, 21.50);
        path.horizontalLineTo(18.25);
        path.arcTo(1.75, 1.75, 0.00, false, false, 20.00, 19.75);
        path.verticalLineTo(11.00);
        path.horizontalLineTo(21.23);
        path.arcTo(0.75, 0.75, 0.00, false, false, 21.23, 9.50);
        path.horizontalLineTo(20.00);
        path.verticalLineTo(5.75);
        path.arcTo(3.75, 3.75, 0.00, false, false, 16.25, 2.00);
        path.horizontalLineTo(7.75);
        path.close();
        path.moveTo(18.50, 18.50);
        path.verticalLineTo(19.75);
        path.arcTo(0.25, 0.25, 0.00, false, true, 18.25, 20.00);
        path.horizontalLineTo(16.75);
        path.arcTo(0.25, 0.25, 0.00, false, true, 16.50, 19.75);
        path.verticalLineTo(18.50);
        path.horizontalLineTo(18.50);
        path.close();
        path.moveTo(18.50, 17.00);
        path.horizontalLineTo(5.50);
        path.verticalLineTo(13.00);
        path.horizontalLineTo(18.50);
        path.verticalLineTo(17.00);
        path.close();
        path.moveTo(5.50, 19.75);
        path.verticalLineTo(18.50);
        path.horizontalLineTo(7.50);
        path.verticalLineTo(19.75);
        path.arcTo(0.25, 0.25, 0.00, false, true, 7.25, 20.00);
        path.horizontalLineTo(5.75);
        path.arcTo(0.25, 0.25, 0.00, false, true, 5.50, 19.75);
        path.close();
        path.moveTo(5.50, 5.75);
        path.arcTo(2.25, 2.25, 0.00, false, true, 7.75, 3.50);
        path.horizontalLineTo(16.25);
        path.arcTo(2.25, 2.25, 0.00, false, true, 18.50, 5.75);
        path.verticalLineTo(11.50);
        path.horizontalLineTo(5.50);
        path.verticalLineTo(5.75);
        path.close();
        return path;
    }
}
