// Generated by XIcons
// 2025-08-14 22:10:40
package cn.enaium.xicons.swing.icons.carbon;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class CloudSatelliteServices extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(29.00, 26.00);
        path.arcTo(2.97, 2.97, 0.00, false, false, 27.15, 26.66);
        path.lineTo(25.00, 25.42);
        path.verticalLineTo(23.82);
        path.arcTo(3.00, 3.00, 0.00, true, false, 23.00, 23.82);
        path.verticalLineTo(25.42);
        path.lineTo(20.86, 26.66);
        path.arcTo(2.97, 2.97, 0.00, false, false, 19.00, 26.00);
        path.arcTo(3.02, 3.02, 0.00, true, false, 21.93, 28.35);
        path.lineTo(24.00, 27.15);
        path.lineTo(26.08, 28.35);
        path.arcTo(3.00, 3.00, 0.00, true, false, 29.00, 26.00);
        path.close();
        path.moveTo(19.00, 30.00);
        path.arcTo(1.00, 1.00, 0.00, true, true, 20.00, 29.00);
        path.arcTo(1.00, 1.00, 0.00, false, true, 19.00, 30.00);
        path.close();
        path.moveTo(24.00, 20.00);
        path.arcTo(1.00, 1.00, 0.00, true, true, 23.00, 21.00);
        path.arcTo(1.00, 1.00, 0.00, false, true, 24.00, 20.00);
        path.close();
        path.moveTo(29.00, 30.00);
        path.arcTo(1.00, 1.00, 0.00, true, true, 30.00, 29.00);
        path.arcTo(1.00, 1.00, 0.00, false, true, 29.00, 30.00);
        path.close();
        path.moveTo(14.00, 20.00);
        path.arcTo(4.00, 4.00, 0.00, true, true, 18.00, 16.00);
        path.arcTo(4.01, 4.01, 0.00, false, true, 14.00, 20.00);
        path.close();
        path.moveTo(14.00, 14.00);
        path.arcTo(2.00, 2.00, 0.00, true, false, 16.00, 16.00);
        path.arcTo(2.01, 2.01, 0.00, false, false, 14.00, 14.00);
        path.close();
        path.moveTo(13.02, 28.27);
        path.lineTo(3.00, 22.43);
        path.verticalLineTo(9.57);
        path.lineTo(14.00, 3.16);
        path.lineTo(25.50, 9.86);
        path.lineTo(26.50, 8.14);
        path.lineTo(14.50, 1.14);
        path.arcTo(1.00, 1.00, 0.00, false, false, 13.50, 1.14);
        path.lineTo(1.50, 8.14);
        path.arcTo(1.00, 1.00, 0.00, false, false, 1.00, 9.00);
        path.verticalLineTo(23.00);
        path.arcTo(1.00, 1.00, 0.00, false, false, 1.50, 23.86);
        path.lineTo(12.01, 30.00);
        path.close();
        path.scale(0.75, 0.75);
        return path;
    }
}
