// Generated by XIcons
// 2025-08-14 22:10:41
package cn.enaium.xicons.swing.icons.carbon;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class DirectionBearRight01 extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(12.00, 4.00);
        path.verticalLineTo(6.00);
        path.horizontalLineTo(18.59);
        path.lineTo(12.05, 12.54);
        path.arcTo(6.95, 6.95, 0.00, false, false, 10.00, 17.49);
        path.verticalLineTo(28.00);
        path.horizontalLineTo(12.00);
        path.verticalLineTo(17.49);
        path.arcTo(4.97, 4.97, 0.00, false, true, 13.46, 13.95);
        path.lineTo(20.00, 7.41);
        path.verticalLineTo(14.00);
        path.horizontalLineTo(22.00);
        path.verticalLineTo(4.00);
        path.close();
        path.scale(0.75, 0.75);
        return path;
    }
}
