// Generated by XIcons
// 2025-08-14 22:10:41
package cn.enaium.xicons.swing.icons.carbon;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class IbmCloudDedicatedHost extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(26.00, 2.00);
        path.horizontalLineTo(6.00);
        path.arcTo(2.00, 2.00, 0.00, false, false, 4.00, 4.00);
        path.verticalLineTo(8.00);
        path.arcTo(2.00, 2.00, 0.00, false, false, 6.00, 10.00);
        path.horizontalLineTo(15.00);
        path.verticalLineTo(14.00);
        path.horizontalLineTo(17.00);
        path.verticalLineTo(10.00);
        path.horizontalLineTo(26.00);
        path.arcTo(2.00, 2.00, 0.00, false, false, 28.00, 8.00);
        path.verticalLineTo(4.00);
        path.arcTo(2.00, 2.00, 0.00, false, false, 26.00, 2.00);
        path.close();
        path.moveTo(26.00, 8.00);
        path.horizontalLineTo(6.00);
        path.verticalLineTo(4.00);
        path.horizontalLineTo(26.00);
        path.close();
        path.moveTo(17.00, 28.00);
        path.verticalLineTo(26.00);
        path.horizontalLineTo(15.00);
        path.verticalLineTo(28.00);
        path.horizontalLineTo(4.00);
        path.verticalLineTo(30.00);
        path.horizontalLineTo(28.00);
        path.verticalLineTo(28.00);
        path.horizontalLineTo(17.00);
        path.close();
        path.moveTo(6.00, 24.00);
        path.horizontalLineTo(26.00);
        path.arcTo(2.00, 2.00, 0.00, false, false, 28.00, 22.00);
        path.verticalLineTo(18.00);
        path.arcTo(2.00, 2.00, 0.00, false, false, 26.00, 16.00);
        path.horizontalLineTo(6.00);
        path.arcTo(2.00, 2.00, 0.00, false, false, 4.00, 18.00);
        path.verticalLineTo(22.00);
        path.arcTo(2.00, 2.00, 0.00, false, false, 6.00, 24.00);
        path.close();
        path.moveTo(6.00, 18.00);
        path.horizontalLineTo(26.00);
        path.verticalLineTo(22.00);
        path.horizontalLineTo(6.00);
        path.close();
        path.scale(0.75, 0.75);
        return path;
    }
}
