// Generated by XIcons
// 2025-08-14 22:11:16
package cn.enaium.xicons.swing.icons.material;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class BedtimeOffRound extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(11.65, 3.46);
        path.curveTo(11.92, 2.75, 11.29, 2.01, 10.53, 2.12);
        path.curveTo(9.05, 2.33, 7.68, 2.88, 6.49, 3.66);
        path.lineTo(11.08, 8.25);
        path.curveTo(10.88, 6.69, 11.04, 5.05, 11.65, 3.46);
        path.close();
        path.moveTo(2.10, 3.51);
        path.arcTo(1.00, 1.00, 0.00, false, false, 2.10, 4.92);
        path.lineTo(3.66, 6.48);
        path.curveTo(2.26, 8.59, 1.64, 11.25, 2.20, 14.04);
        path.curveTo(2.99, 17.98, 6.19, 21.11, 10.14, 21.82);
        path.curveTo(12.88, 22.31, 15.44, 21.67, 17.49, 20.31);
        path.lineTo(19.06, 21.88);
        path.arcTo(1.00, 1.00, 0.00, true, false, 20.47, 20.47);
        path.lineTo(3.51, 3.51);
        path.arcTo(1.00, 1.00, 0.00, false, false, 2.10, 3.51);
        path.close();
        return path;
    }
}
