// Generated by XIcons
// 2025-08-14 22:11:16
package cn.enaium.xicons.swing.icons.material;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class Brightness7Twotone extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(18.00, 9.52);
        path.verticalLineTo(6.00);
        path.horizontalLineTo(14.48);
        path.lineTo(12.00, 3.52);
        path.lineTo(9.52, 6.00);
        path.horizontalLineTo(6.00);
        path.verticalLineTo(9.52);
        path.lineTo(3.52, 12.00);
        path.lineTo(6.00, 14.48);
        path.verticalLineTo(18.00);
        path.horizontalLineTo(9.52);
        path.lineTo(12.00, 20.48);
        path.lineTo(14.48, 18.00);
        path.horizontalLineTo(18.00);
        path.verticalLineTo(14.48);
        path.lineTo(20.48, 12.00);
        path.lineTo(18.00, 9.52);
        path.close();
        path.moveTo(12.00, 17.50);
        path.curveTo(8.97, 17.50, 6.50, 15.03, 6.50, 12.00);
        path.curveTo(6.50, 8.97, 8.97, 6.50, 12.00, 6.50);
        path.curveTo(15.03, 6.50, 17.50, 8.97, 17.50, 12.00);
        path.curveTo(17.50, 15.03, 15.03, 17.50, 12.00, 17.50);
        path.close();
        path.moveTo(20.00, 8.69);
        path.verticalLineTo(4.00);
        path.horizontalLineTo(15.31);
        path.lineTo(12.00, 0.69);
        path.lineTo(8.69, 4.00);
        path.horizontalLineTo(4.00);
        path.verticalLineTo(8.69);
        path.lineTo(0.69, 12.00);
        path.lineTo(4.00, 15.31);
        path.verticalLineTo(20.00);
        path.horizontalLineTo(8.69);
        path.lineTo(12.00, 23.31);
        path.lineTo(15.31, 20.00);
        path.horizontalLineTo(20.00);
        path.verticalLineTo(15.31);
        path.lineTo(23.31, 12.00);
        path.lineTo(20.00, 8.69);
        path.close();
        path.moveTo(18.00, 14.48);
        path.verticalLineTo(18.00);
        path.horizontalLineTo(14.48);
        path.lineTo(12.00, 20.48);
        path.lineTo(9.52, 18.00);
        path.horizontalLineTo(6.00);
        path.verticalLineTo(14.48);
        path.lineTo(3.52, 12.00);
        path.lineTo(6.00, 9.52);
        path.verticalLineTo(6.00);
        path.horizontalLineTo(9.52);
        path.lineTo(12.00, 3.52);
        path.lineTo(14.48, 6.00);
        path.horizontalLineTo(18.00);
        path.verticalLineTo(9.52);
        path.lineTo(20.48, 12.00);
        path.lineTo(18.00, 14.48);
        path.close();
        path.moveTo(12.00, 6.50);
        path.curveTo(8.97, 6.50, 6.50, 8.97, 6.50, 12.00);
        path.curveTo(6.50, 15.03, 8.97, 17.50, 12.00, 17.50);
        path.curveTo(15.03, 17.50, 17.50, 15.03, 17.50, 12.00);
        path.curveTo(17.50, 8.97, 15.03, 6.50, 12.00, 6.50);
        path.close();
        path.moveTo(12.00, 15.50);
        path.curveTo(10.07, 15.50, 8.50, 13.93, 8.50, 12.00);
        path.curveTo(8.50, 10.07, 10.07, 8.50, 12.00, 8.50);
        path.curveTo(13.93, 8.50, 15.50, 10.07, 15.50, 12.00);
        path.curveTo(15.50, 13.93, 13.93, 15.50, 12.00, 15.50);
        path.close();
        return path;
    }
}
