// Generated by XIcons
// 2025-08-14 22:11:17
package cn.enaium.xicons.swing.icons.material;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class ContentPasteGoRound extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(5.00, 5.00);
        path.horizontalLineTo(7.00);
        path.verticalLineTo(6.00);
        path.curveTo(7.00, 7.10, 7.90, 8.00, 9.00, 8.00);
        path.horizontalLineTo(15.00);
        path.curveTo(16.10, 8.00, 17.00, 7.10, 17.00, 6.00);
        path.verticalLineTo(5.00);
        path.horizontalLineTo(19.00);
        path.verticalLineTo(11.00);
        path.horizontalLineTo(21.00);
        path.verticalLineTo(5.00);
        path.curveTo(21.00, 3.90, 20.10, 3.00, 19.00, 3.00);
        path.horizontalLineTo(14.82);
        path.curveTo(14.40, 1.84, 13.30, 1.00, 12.00, 1.00);
        path.curveTo(10.70, 1.00, 9.60, 1.84, 9.18, 3.00);
        path.horizontalLineTo(5.00);
        path.curveTo(3.90, 3.00, 3.00, 3.90, 3.00, 5.00);
        path.verticalLineTo(19.00);
        path.curveTo(3.00, 20.10, 3.90, 21.00, 5.00, 21.00);
        path.horizontalLineTo(10.00);
        path.verticalLineTo(19.00);
        path.horizontalLineTo(5.00);
        path.verticalLineTo(5.00);
        path.close();
        path.moveTo(12.00, 3.00);
        path.curveTo(12.55, 3.00, 13.00, 3.45, 13.00, 4.00);
        path.curveTo(13.00, 4.55, 12.55, 5.00, 12.00, 5.00);
        path.curveTo(11.45, 5.00, 11.00, 4.55, 11.00, 4.00);
        path.curveTo(11.00, 3.45, 11.45, 3.00, 12.00, 3.00);
        path.close();
        path.moveTo(21.29, 16.29);
        path.lineTo(18.71, 13.71);
        path.arcTo(1.00, 1.00, 0.00, true, false, 17.30, 15.12);
        path.lineTo(18.17, 16.00);
        path.horizontalLineTo(13.00);
        path.curveTo(12.45, 16.00, 12.00, 16.45, 12.00, 17.00);
        path.curveTo(12.00, 17.55, 12.45, 18.00, 13.00, 18.00);
        path.horizontalLineTo(18.17);
        path.lineTo(17.30, 18.88);
        path.arcTo(1.00, 1.00, 0.00, true, false, 18.71, 20.29);
        path.lineTo(21.29, 17.71);
        path.curveTo(21.68, 17.31, 21.68, 16.68, 21.29, 16.29);
        path.close();
        return path;
    }
}
