// Generated by XIcons
// 2025-08-14 22:11:19
package cn.enaium.xicons.swing.icons.material;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class DonutLargeOutlined extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(13.00, 5.08);
        path.arcTo(7.00, 7.00, 0.00, false, true, 18.92, 11.00);
        path.horizontalLineTo(21.95);
        path.curveTo(21.48, 6.28, 17.72, 2.52, 13.00, 2.05);
        path.verticalLineTo(5.08);
        path.close();
        path.moveTo(18.92, 13.00);
        path.arcTo(7.00, 7.00, 0.00, false, true, 13.00, 18.92);
        path.verticalLineTo(21.95);
        path.curveTo(17.72, 21.48, 21.48, 17.72, 21.95, 13.00);
        path.horizontalLineTo(18.92);
        path.close();
        path.moveTo(11.00, 18.92);
        path.curveTo(7.61, 18.43, 5.00, 15.52, 5.00, 12.00);
        path.curveTo(5.00, 8.48, 7.61, 5.57, 11.00, 5.08);
        path.verticalLineTo(2.05);
        path.curveTo(5.95, 2.55, 2.00, 6.81, 2.00, 12.00);
        path.curveTo(2.00, 17.19, 5.95, 21.45, 11.00, 21.95);
        path.verticalLineTo(18.92);
        path.close();
        return path;
    }
}
