// Generated by XIcons
// 2025-08-14 22:11:20
package cn.enaium.xicons.swing.icons.material;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class FlipCameraIosOutlined extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(20.00, 5.00);
        path.horizontalLineTo(16.83);
        path.lineTo(15.00, 3.00);
        path.horizontalLineTo(9.00);
        path.lineTo(7.17, 5.00);
        path.horizontalLineTo(4.00);
        path.curveTo(2.90, 5.00, 2.00, 5.90, 2.00, 7.00);
        path.verticalLineTo(19.00);
        path.curveTo(2.00, 20.10, 2.90, 21.00, 4.00, 21.00);
        path.horizontalLineTo(20.00);
        path.curveTo(21.10, 21.00, 22.00, 20.10, 22.00, 19.00);
        path.verticalLineTo(7.00);
        path.curveTo(22.00, 5.90, 21.10, 5.00, 20.00, 5.00);
        path.close();
        path.moveTo(20.00, 19.00);
        path.horizontalLineTo(4.00);
        path.verticalLineTo(7.00);
        path.horizontalLineTo(8.05);
        path.lineTo(8.64, 6.35);
        path.lineTo(9.88, 5.00);
        path.horizontalLineTo(14.12);
        path.lineTo(15.36, 6.35);
        path.lineTo(15.95, 7.00);
        path.horizontalLineTo(20.00);
        path.verticalLineTo(19.00);
        path.close();
        path.moveTo(12.00, 17.00);
        path.curveTo(9.79, 17.00, 8.00, 15.21, 8.00, 13.00);
        path.horizontalLineTo(10.00);
        path.lineTo(7.50, 10.50);
        path.lineTo(5.00, 13.00);
        path.horizontalLineTo(7.00);
        path.curveTo(7.00, 15.76, 9.24, 18.00, 12.00, 18.00);
        path.curveTo(12.86, 18.00, 13.65, 17.76, 14.36, 17.38);
        path.lineTo(13.62, 16.64);
        path.curveTo(13.13, 16.87, 12.58, 17.00, 12.00, 17.00);
        path.close();
        path.moveTo(12.00, 8.00);
        path.curveTo(11.14, 8.00, 10.35, 8.24, 9.64, 8.62);
        path.lineTo(10.38, 9.35);
        path.curveTo(10.87, 9.13, 11.42, 9.00, 12.00, 9.00);
        path.curveTo(14.21, 9.00, 16.00, 10.79, 16.00, 13.00);
        path.horizontalLineTo(14.00);
        path.lineTo(16.50, 15.50);
        path.lineTo(19.00, 13.00);
        path.horizontalLineTo(17.00);
        path.curveTo(17.00, 10.24, 14.76, 8.00, 12.00, 8.00);
        path.close();
        return path;
    }
}
