// Generated by XIcons
// 2025-08-14 22:11:21
package cn.enaium.xicons.swing.icons.material;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class GreaterThanTwotone extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(6.50, 17.50);
        path.lineTo(14.75, 12.00);
        path.lineTo(6.50, 6.50);
        path.lineTo(7.50, 5.00);
        path.lineTo(18.00, 12.00);
        path.lineTo(7.50, 19.00);
        path.close();
        return path;
    }
}
