// Generated by XIcons
// 2025-08-14 22:11:21
package cn.enaium.xicons.swing.icons.material;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class HeightTwotone extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(13.00, 6.99);
        path.horizontalLineTo(16.00);
        path.lineTo(12.00, 3.00);
        path.lineTo(8.00, 6.99);
        path.horizontalLineTo(11.00);
        path.verticalLineTo(17.01);
        path.horizontalLineTo(8.00);
        path.lineTo(12.00, 21.00);
        path.lineTo(16.00, 17.01);
        path.horizontalLineTo(13.00);
        path.close();
        return path;
    }
}
