// Generated by XIcons
// 2025-08-14 22:11:25
package cn.enaium.xicons.swing.icons.material;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class NoiseControlOffFilled extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        return path;
    }
}
