// Generated by XIcons
// 2025-08-14 22:11:25
package cn.enaium.xicons.swing.icons.material;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class NotificationAddRound extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(10.00, 20.00);
        path.horizontalLineTo(14.00);
        path.curveTo(14.00, 21.10, 13.10, 22.00, 12.00, 22.00);
        path.curveTo(10.90, 22.00, 10.00, 21.10, 10.00, 20.00);
        path.close();
        path.moveTo(14.00, 9.00);
        path.curveTo(14.00, 11.61, 15.67, 13.83, 18.00, 14.66);
        path.verticalLineTo(17.00);
        path.horizontalLineTo(19.00);
        path.curveTo(19.55, 17.00, 20.00, 17.45, 20.00, 18.00);
        path.curveTo(20.00, 18.55, 19.55, 19.00, 19.00, 19.00);
        path.horizontalLineTo(5.00);
        path.curveTo(4.45, 19.00, 4.00, 18.55, 4.00, 18.00);
        path.curveTo(4.00, 17.45, 4.45, 17.00, 5.00, 17.00);
        path.horizontalLineTo(6.00);
        path.verticalLineTo(10.00);
        path.curveTo(6.00, 7.21, 7.91, 4.86, 10.50, 4.20);
        path.verticalLineTo(3.50);
        path.curveTo(10.50, 2.67, 11.17, 2.00, 12.00, 2.00);
        path.curveTo(12.83, 2.00, 13.50, 2.67, 13.50, 3.50);
        path.verticalLineTo(4.20);
        path.curveTo(14.21, 4.38, 14.86, 4.69, 15.45, 5.10);
        path.arcTo(5.90, 5.90, 0.00, false, false, 14.00, 9.00);
        path.close();
        path.moveTo(23.00, 8.00);
        path.horizontalLineTo(21.00);
        path.verticalLineTo(6.00);
        path.curveTo(21.00, 5.45, 20.55, 5.00, 20.00, 5.00);
        path.curveTo(19.45, 5.00, 19.00, 5.45, 19.00, 6.00);
        path.verticalLineTo(8.00);
        path.horizontalLineTo(17.00);
        path.curveTo(16.45, 8.00, 16.00, 8.45, 16.00, 9.00);
        path.curveTo(16.00, 9.55, 16.45, 10.00, 17.00, 10.00);
        path.horizontalLineTo(19.00);
        path.verticalLineTo(12.00);
        path.curveTo(19.00, 12.55, 19.45, 13.00, 20.00, 13.00);
        path.curveTo(20.55, 13.00, 21.00, 12.55, 21.00, 12.00);
        path.verticalLineTo(10.00);
        path.horizontalLineTo(23.00);
        path.curveTo(23.55, 10.00, 24.00, 9.55, 24.00, 9.00);
        path.curveTo(24.00, 8.45, 23.55, 8.00, 23.00, 8.00);
        path.close();
        return path;
    }
}
