// Generated by XIcons
// 2025-08-14 22:11:25
package cn.enaium.xicons.swing.icons.material;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class OfflineBoltFilled extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(12.00, 2.02);
        path.curveTo(6.49, 2.02, 2.02, 6.49, 2.02, 12.00);
        path.curveTo(2.02, 17.51, 6.49, 21.98, 12.00, 21.98);
        path.curveTo(17.51, 21.98, 21.98, 17.51, 21.98, 12.00);
        path.curveTo(21.98, 6.49, 17.51, 2.02, 12.00, 2.02);
        path.close();
        path.moveTo(11.48, 20.00);
        path.verticalLineTo(13.74);
        path.horizontalLineTo(8.00);
        path.lineTo(13.00, 4.00);
        path.verticalLineTo(10.26);
        path.horizontalLineTo(16.35);
        path.lineTo(11.48, 20.00);
        path.close();
        return path;
    }
}
