// Generated by XIcons
// 2025-08-14 22:11:26
package cn.enaium.xicons.swing.icons.material;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class PermScanWifiFilled extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(12.00, 3.00);
        path.curveTo(6.95, 3.00, 3.15, 4.85, 0.00, 7.23);
        path.lineTo(12.00, 22.00);
        path.lineTo(24.00, 7.25);
        path.curveTo(20.85, 4.87, 17.05, 3.00, 12.00, 3.00);
        path.close();
        path.moveTo(13.00, 16.00);
        path.horizontalLineTo(11.00);
        path.verticalLineTo(10.00);
        path.horizontalLineTo(13.00);
        path.verticalLineTo(16.00);
        path.close();
        path.moveTo(11.00, 8.00);
        path.verticalLineTo(6.00);
        path.horizontalLineTo(13.00);
        path.verticalLineTo(8.00);
        path.horizontalLineTo(11.00);
        path.close();
        return path;
    }
}
