// Generated by XIcons
// 2025-08-14 22:11:27
package cn.enaium.xicons.swing.icons.material;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class PrivacyTipOutlined extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(12.00, 3.19);
        path.lineTo(19.00, 6.30);
        path.verticalLineTo(11.00);
        path.curveTo(19.00, 15.52, 16.02, 19.69, 12.00, 20.93);
        path.curveTo(7.98, 19.69, 5.00, 15.52, 5.00, 11.00);
        path.verticalLineTo(6.30);
        path.lineTo(12.00, 3.19);
        path.moveTo(12.00, 1.00);
        path.lineTo(3.00, 5.00);
        path.verticalLineTo(11.00);
        path.curveTo(3.00, 16.55, 6.84, 21.74, 12.00, 23.00);
        path.curveTo(17.16, 21.74, 21.00, 16.55, 21.00, 11.00);
        path.verticalLineTo(5.00);
        path.lineTo(12.00, 1.00);
        path.close();
        path.moveTo(11.00, 7.00);
        path.horizontalLineTo(13.00);
        path.verticalLineTo(9.00);
        path.horizontalLineTo(11.00);
        path.verticalLineTo(7.00);
        path.close();
        path.moveTo(11.00, 11.00);
        path.horizontalLineTo(13.00);
        path.verticalLineTo(17.00);
        path.horizontalLineTo(11.00);
        path.verticalLineTo(11.00);
        path.close();
        return path;
    }
}
