// Generated by XIcons
// 2025-08-14 22:11:27
package cn.enaium.xicons.swing.icons.material;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class RawOnRound extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(6.50, 9.00);
        path.horizontalLineTo(4.00);
        path.curveTo(3.45, 9.00, 3.00, 9.45, 3.00, 10.00);
        path.verticalLineTo(14.31);
        path.curveTo(3.00, 14.69, 3.31, 15.00, 3.69, 15.00);
        path.horizontalLineTo(3.80);
        path.curveTo(4.18, 15.00, 4.49, 14.69, 4.49, 14.31);
        path.verticalLineTo(13.00);
        path.horizontalLineTo(5.59);
        path.lineTo(6.31, 14.59);
        path.curveTo(6.43, 14.84, 6.68, 15.00, 6.95, 15.00);
        path.curveTo(7.45, 15.00, 7.78, 14.49, 7.59, 14.03);
        path.lineTo(7.10, 12.90);
        path.curveTo(7.60, 12.60, 8.00, 12.10, 8.00, 11.50);
        path.verticalLineTo(10.50);
        path.curveTo(8.00, 9.68, 7.32, 9.00, 6.50, 9.00);
        path.close();
        path.moveTo(6.50, 11.50);
        path.horizontalLineTo(4.50);
        path.verticalLineTo(10.50);
        path.horizontalLineTo(6.50);
        path.verticalLineTo(11.50);
        path.close();
        path.moveTo(11.50, 9.00);
        path.curveTo(10.77, 9.00, 10.13, 9.50, 9.95, 10.21);
        path.lineTo(8.98, 14.10);
        path.curveTo(8.86, 14.56, 9.21, 15.00, 9.68, 15.00);
        path.curveTo(10.01, 15.00, 10.30, 14.77, 10.38, 14.45);
        path.lineTo(10.62, 13.50);
        path.horizontalLineTo(12.37);
        path.lineTo(12.60, 14.45);
        path.arcTo(0.73, 0.73, 0.00, false, false, 14.02, 14.10);
        path.lineTo(13.05, 10.22);
        path.curveTo(12.87, 9.50, 12.23, 9.00, 11.50, 9.00);
        path.close();
        path.moveTo(11.00, 12.00);
        path.lineTo(11.25, 11.00);
        path.horizontalLineTo(11.75);
        path.lineTo(12.00, 12.00);
        path.horizontalLineTo(11.00);
        path.close();
        path.moveTo(19.84, 9.55);
        path.lineTo(19.24, 12.00);
        path.lineTo(18.68, 9.74);
        path.arcTo(0.95, 0.95, 0.00, false, false, 17.74, 9.00);
        path.curveTo(17.29, 9.00, 16.90, 9.30, 16.80, 9.74);
        path.lineTo(16.24, 12.00);
        path.lineTo(15.64, 9.55);
        path.arcTo(0.73, 0.73, 0.00, false, false, 14.22, 9.90);
        path.lineTo(15.31, 14.28);
        path.curveTo(15.43, 14.70, 15.81, 15.00, 16.24, 15.00);
        path.curveTo(16.67, 15.00, 17.05, 14.70, 17.16, 14.28);
        path.lineTo(17.74, 11.96);
        path.lineTo(18.32, 14.28);
        path.curveTo(18.43, 14.70, 18.81, 15.00, 19.24, 15.00);
        path.curveTo(19.67, 15.00, 20.05, 14.70, 20.16, 14.28);
        path.lineTo(21.25, 9.90);
        path.arcTo(0.72, 0.72, 0.00, false, false, 20.55, 9.00);
        path.arcTo(0.73, 0.73, 0.00, false, false, 19.84, 9.55);
        path.close();
        return path;
    }
}
