// Generated by XIcons
// 2025-08-14 22:11:28
package cn.enaium.xicons.swing.icons.material;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class ScatterPlotOutlined extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(7.00, 18.00);
        path.curveTo(4.79, 18.00, 3.00, 16.21, 3.00, 14.00);
        path.curveTo(3.00, 11.79, 4.79, 10.00, 7.00, 10.00);
        path.curveTo(9.21, 10.00, 11.00, 11.79, 11.00, 14.00);
        path.curveTo(11.00, 16.21, 9.21, 18.00, 7.00, 18.00);
        path.close();
        path.moveTo(7.00, 12.00);
        path.curveTo(5.90, 12.00, 5.00, 12.90, 5.00, 14.00);
        path.curveTo(5.00, 15.10, 5.90, 16.00, 7.00, 16.00);
        path.curveTo(8.10, 16.00, 9.00, 15.10, 9.00, 14.00);
        path.curveTo(9.00, 12.90, 8.10, 12.00, 7.00, 12.00);
        path.close();
        path.moveTo(11.00, 10.00);
        path.curveTo(8.79, 10.00, 7.00, 8.21, 7.00, 6.00);
        path.curveTo(7.00, 3.79, 8.79, 2.00, 11.00, 2.00);
        path.curveTo(13.21, 2.00, 15.00, 3.79, 15.00, 6.00);
        path.curveTo(15.00, 8.21, 13.21, 10.00, 11.00, 10.00);
        path.close();
        path.moveTo(11.00, 4.00);
        path.curveTo(9.90, 4.00, 9.00, 4.90, 9.00, 6.00);
        path.curveTo(9.00, 7.10, 9.90, 8.00, 11.00, 8.00);
        path.curveTo(12.10, 8.00, 13.00, 7.10, 13.00, 6.00);
        path.curveTo(13.00, 4.90, 12.10, 4.00, 11.00, 4.00);
        path.close();
        path.moveTo(16.60, 21.60);
        path.curveTo(14.39, 21.60, 12.60, 19.81, 12.60, 17.60);
        path.curveTo(12.60, 15.39, 14.39, 13.60, 16.60, 13.60);
        path.curveTo(18.81, 13.60, 20.60, 15.39, 20.60, 17.60);
        path.curveTo(20.60, 19.81, 18.81, 21.60, 16.60, 21.60);
        path.close();
        path.moveTo(16.60, 15.60);
        path.curveTo(15.50, 15.60, 14.60, 16.50, 14.60, 17.60);
        path.curveTo(14.60, 18.70, 15.50, 19.60, 16.60, 19.60);
        path.curveTo(17.70, 19.60, 18.60, 18.70, 18.60, 17.60);
        path.curveTo(18.60, 16.50, 17.70, 15.60, 16.60, 15.60);
        path.close();
        return path;
    }
}
