// Generated by XIcons
// 2025-08-14 22:11:29
package cn.enaium.xicons.swing.icons.material;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class StreetviewSharp extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(12.56, 14.33);
        path.curveTo(12.22, 14.60, 12.00, 15.03, 12.00, 15.50);
        path.verticalLineTo(21.00);
        path.horizontalLineTo(19.00);
        path.curveTo(20.10, 21.00, 21.00, 20.10, 21.00, 19.00);
        path.verticalLineTo(13.02);
        path.curveTo(20.06, 12.69, 19.05, 12.50, 18.00, 12.50);
        path.curveTo(15.97, 12.50, 14.07, 13.20, 12.56, 14.33);
        path.close();
        path.moveTo(11.50, 6.00);
        path.curveTo(11.50, 4.92, 11.77, 3.90, 12.24, 3.00);
        path.horizontalLineTo(5.00);
        path.curveTo(3.90, 3.00, 3.00, 3.90, 3.00, 5.00);
        path.verticalLineTo(19.00);
        path.curveTo(3.00, 19.55, 3.23, 20.05, 3.59, 20.41);
        path.lineTo(13.41, 10.59);
        path.arcTo(6.44, 6.44, 0.00, false, true, 11.50, 6.00);
        path.close();
        return path;
    }
}
