// Generated by XIcons
// 2025-08-14 22:11:31
package cn.enaium.xicons.swing.icons.material;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class VideocamSharp extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(17.00, 10.50);
        path.verticalLineTo(6.00);
        path.horizontalLineTo(3.00);
        path.verticalLineTo(18.00);
        path.horizontalLineTo(17.00);
        path.verticalLineTo(13.50);
        path.lineTo(21.00, 17.50);
        path.verticalLineTo(6.50);
        path.lineTo(17.00, 10.50);
        path.close();
        return path;
    }
}
