// Generated by XIcons
// 2025-08-14 22:11:32
package cn.enaium.xicons.swing.icons.material;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class WifiCallingRound extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(22.00, 4.95);
        path.curveTo(21.79, 4.78, 19.67, 3.00, 16.50, 3.00);
        path.curveTo(13.32, 3.00, 11.21, 4.78, 11.00, 4.95);
        path.lineTo(16.50, 12.00);
        path.lineTo(22.00, 4.95);
        path.close();
        path.moveTo(19.20, 15.28);
        path.lineTo(16.66, 14.99);
        path.arcTo(1.99, 1.99, 0.00, false, false, 15.02, 15.56);
        path.lineTo(13.18, 17.40);
        path.arcTo(15.05, 15.05, 0.00, false, true, 6.59, 10.81);
        path.lineTo(8.44, 8.96);
        path.curveTo(8.87, 8.53, 9.08, 7.92, 9.01, 7.32);
        path.lineTo(8.72, 4.80);
        path.arcTo(2.00, 2.00, 0.00, false, false, 6.73, 3.03);
        path.horizontalLineTo(5.00);
        path.curveTo(3.87, 3.03, 2.93, 3.97, 3.00, 5.10);
        path.curveTo(3.53, 13.64, 10.36, 20.47, 18.90, 21.00);
        path.curveTo(20.03, 21.07, 20.97, 20.13, 20.97, 19.00);
        path.verticalLineTo(17.27);
        path.curveTo(20.97, 16.25, 20.21, 15.40, 19.20, 15.28);
        path.close();
        return path;
    }
}
