// Generated by XIcons
// 2025-08-14 22:08:54
package cn.enaium.xicons.jfx.icons.antd;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class UsbTwotone extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(759.90, 504.00);
        path.horizontalLineTo(264.10);
        path.curveTo(237.60, 504.00, 216.00, 523.70, 216.00, 548.00);
        path.verticalLineTo(840.00);
        path.horizontalLineTo(808.00);
        path.verticalLineTo(548.00);
        path.curveTo(808.00, 523.70, 786.40, 504.00, 759.90, 504.00);
        path.close();
        path.moveTo(456.00, 248.00);
        path.horizontalLineTo(408.00);
        path.curveTo(403.60, 248.00, 400.00, 251.60, 400.00, 256.00);
        path.verticalLineTo(304.00);
        path.curveTo(400.00, 308.40, 403.60, 312.00, 408.00, 312.00);
        path.horizontalLineTo(456.00);
        path.curveTo(460.40, 312.00, 464.00, 308.40, 464.00, 304.00);
        path.verticalLineTo(256.00);
        path.curveTo(464.00, 251.60, 460.40, 248.00, 456.00, 248.00);
        path.close();
        path.moveTo(616.00, 248.00);
        path.horizontalLineTo(568.00);
        path.curveTo(563.60, 248.00, 560.00, 251.60, 560.00, 256.00);
        path.verticalLineTo(304.00);
        path.curveTo(560.00, 308.40, 563.60, 312.00, 568.00, 312.00);
        path.horizontalLineTo(616.00);
        path.curveTo(620.40, 312.00, 624.00, 308.40, 624.00, 304.00);
        path.verticalLineTo(256.00);
        path.curveTo(624.00, 251.60, 620.40, 248.00, 616.00, 248.00);
        path.close();
        path.moveTo(760.00, 432.00);
        path.verticalLineTo(144.00);
        path.curveTo(760.00, 126.30, 745.70, 112.00, 728.00, 112.00);
        path.horizontalLineTo(296.00);
        path.curveTo(278.30, 112.00, 264.00, 126.30, 264.00, 144.00);
        path.verticalLineTo(432.00);
        path.curveTo(197.80, 432.00, 144.00, 484.10, 144.00, 548.00);
        path.verticalLineTo(904.00);
        path.curveTo(144.00, 908.40, 147.60, 912.00, 152.00, 912.00);
        path.horizontalLineTo(872.00);
        path.curveTo(876.40, 912.00, 880.00, 908.40, 880.00, 904.00);
        path.verticalLineTo(548.00);
        path.curveTo(880.00, 484.10, 826.20, 432.00, 760.00, 432.00);
        path.close();
        path.moveTo(336.00, 184.00);
        path.horizontalLineTo(688.00);
        path.verticalLineTo(432.00);
        path.horizontalLineTo(336.00);
        path.verticalLineTo(184.00);
        path.close();
        path.moveTo(808.00, 840.00);
        path.horizontalLineTo(216.00);
        path.verticalLineTo(548.00);
        path.curveTo(216.00, 523.70, 237.60, 504.00, 264.10, 504.00);
        path.horizontalLineTo(759.90);
        path.curveTo(786.40, 504.00, 808.00, 523.70, 808.00, 548.00);
        path.verticalLineTo(840.00);
        path.close();
        path.scale(0.0234375, 0.0234375);
        return path;
    }
}
