// Generated by XIcons
// 2025-08-14 22:09:15
package cn.enaium.xicons.jfx.icons.ionicons5;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class ChevronUpCircle extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(256.00, 48.00);
        path.curveTo(141.13, 48.00, 48.00, 141.13, 48.00, 256.00);
        path.curveTo(48.00, 370.87, 141.13, 464.00, 256.00, 464.00);
        path.curveTo(370.87, 464.00, 464.00, 370.87, 464.00, 256.00);
        path.curveTo(464.00, 141.13, 370.87, 48.00, 256.00, 48.00);
        path.close();
        path.moveTo(363.31, 307.31);
        path.arcTo(16.00, 16.00, 0.00, false, true, 340.69, 307.31);
        path.lineTo(256.00, 222.63);
        path.lineTo(171.31, 307.31);
        path.arcTo(16.00, 16.00, 0.00, false, true, 148.69, 284.69);
        path.lineTo(244.69, 188.69);
        path.arcTo(16.00, 16.00, 0.00, false, true, 267.31, 188.69);
        path.lineTo(363.31, 284.69);
        path.arcTo(16.00, 16.00, 0.00, false, true, 363.31, 307.31);
        path.close();
        path.scale(0.046875, 0.046875);
        return path;
    }
}
