// Generated by XIcons
// 2025-08-14 22:09:16
package cn.enaium.xicons.jfx.icons.ionicons5;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class GitCommitOutline extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(160.00, 256.00);
        path.horizontalLineTo(48.00);
        path.moveTo(464.00, 256.00);
        path.horizontalLineTo(352.00);
        path.scale(0.046875, 0.046875);
        return path;
    }
}
