// Generated by XIcons
// 2025-08-14 22:09:16
package cn.enaium.xicons.jfx.icons.ionicons5;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class GitCompareOutline extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(304.00, 160.00);
        path.lineTo(240.00, 96.00);
        path.lineTo(304.00, 32.00);
        path.moveTo(207.00, 352.00);
        path.lineTo(271.00, 416.00);
        path.lineTo(207.00, 480.00);
        path.moveTo(256.00, 96.00);
        path.horizontalLineTo(340.00);
        path.arcTo(60.00, 60.00, 0.00, false, true, 400.00, 156.00);
        path.verticalLineTo(368.00);
        path.moveTo(255.00, 416.00);
        path.horizontalLineTo(171.00);
        path.arcTo(60.00, 60.00, 0.00, false, true, 111.00, 356.00);
        path.verticalLineTo(144.00);
        path.scale(0.046875, 0.046875);
        return path;
    }
}
