// Generated by XIcons
// 2025-08-14 22:09:16
package cn.enaium.xicons.jfx.icons.ionicons5;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class LogoAmplify extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(112.31, 268.00);
        path.lineTo(152.67, 199.31);
        path.lineTo(187.32, 258.31);
        path.lineTo(119.78, 373.31);
        path.horizontalLineTo(254.78);
        path.lineTo(289.31, 432.00);
        path.horizontalLineTo(16.00);
        path.close();
        path.moveTo(170.88, 168.24);
        path.lineTo(204.15, 111.57);
        path.lineTo(392.44, 432.00);
        path.horizontalLineTo(325.76);
        path.close();
        path.moveTo(222.67, 80.00);
        path.horizontalLineTo(289.26);
        path.lineTo(496.00, 432.00);
        path.horizontalLineTo(429.32);
        path.close();
        path.scale(0.046875, 0.046875);
        return path;
    }
}
