// Generated by XIcons
// 2025-08-14 22:09:17
package cn.enaium.xicons.jfx.icons.ionicons5;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class OpenOutline extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(384.00, 224.00);
        path.verticalLineTo(408.00);
        path.arcTo(40.00, 40.00, 0.00, false, true, 344.00, 448.00);
        path.horizontalLineTo(104.00);
        path.arcTo(40.00, 40.00, 0.00, false, true, 64.00, 408.00);
        path.verticalLineTo(168.00);
        path.arcTo(40.00, 40.00, 0.00, false, true, 104.00, 128.00);
        path.horizontalLineTo(271.48);
        path.moveTo(336.00, 64.00);
        path.horizontalLineTo(448.00);
        path.verticalLineTo(176.00);
        path.moveTo(224.00, 288.00);
        path.lineTo(440.00, 72.00);
        path.scale(0.046875, 0.046875);
        return path;
    }
}
