// Generated by XIcons
// 2025-08-14 22:09:18
package cn.enaium.xicons.jfx.icons.ionicons5;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class TrainOutline extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(344.00, 48.00);
        path.horizontalLineTo(320.00);
        path.arcTo(16.00, 16.00, 0.00, false, false, 304.00, 32.00);
        path.horizontalLineTo(208.00);
        path.arcTo(16.00, 16.00, 0.00, false, false, 192.00, 48.00);
        path.horizontalLineTo(168.00);
        path.arcTo(56.16, 56.16, 0.00, false, false, 112.00, 104.00);
        path.verticalLineTo(351.00);
        path.curveTo(112.00, 386.30, 256.00, 416.00, 256.00, 416.00);
        path.curveTo(256.00, 416.00, 400.00, 386.30, 400.00, 351.00);
        path.verticalLineTo(104.00);
        path.arcTo(56.00, 56.00, 0.00, false, false, 344.00, 48.00);
        path.close();
        path.moveTo(256.00, 352.00);
        path.arcTo(48.00, 48.00, 0.00, true, true, 304.00, 304.00);
        path.arcTo(48.00, 48.00, 0.00, false, true, 256.00, 352.00);
        path.close();
        path.moveTo(352.00, 192.00);
        path.arcTo(16.00, 16.00, 0.00, false, true, 336.00, 208.00);
        path.horizontalLineTo(176.00);
        path.arcTo(16.00, 16.00, 0.00, false, true, 160.00, 192.00);
        path.verticalLineTo(128.00);
        path.arcTo(16.00, 16.00, 0.00, false, true, 176.00, 112.00);
        path.horizontalLineTo(336.00);
        path.arcTo(16.00, 16.00, 0.00, false, true, 352.00, 128.00);
        path.close();
        path.moveTo(144.00, 464.00);
        path.horizontalLineTo(368.00);
        path.moveTo(336.00, 432.00);
        path.lineTo(384.00, 480.00);
        path.moveTo(176.00, 432.00);
        path.lineTo(128.00, 480.00);
        path.scale(0.046875, 0.046875);
        return path;
    }
}
