[versions]
javafx = "0.1.0"
javapoet = "0.19.0"
kotlinpoet = "2.3.0"
flatlaf = "3.7.2"

[libraries]
javapoet = { module = "com.palantir.javapoet:javapoet", version.ref = "javapoet" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
flatlaf = { module = "com.formdev:flatlaf", version.ref = "flatlaf" }

[plugins]
javafx = { id = "org.openjfx.javafxplugin", version.ref = "javafx" }