// Generated by XIcons
// 2025-08-14 22:10:45
package cn.enaium.xicons.swing.icons.fa;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class Fax extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(480.00, 160.00);
        path.verticalLineTo(77.25);
        path.arcTo(32.00, 32.00, 0.00, false, false, 470.62, 54.62);
        path.lineTo(425.37, 9.37);
        path.arcTo(32.00, 32.00, 0.00, false, false, 402.75, 0.00);
        path.horizontalLineTo(160.00);
        path.arcTo(32.00, 32.00, 0.00, false, false, 128.00, 32.00);
        path.verticalLineTo(480.00);
        path.arcTo(32.00, 32.00, 0.00, false, false, 160.00, 512.00);
        path.horizontalLineTo(480.00);
        path.arcTo(32.00, 32.00, 0.00, false, false, 512.00, 480.00);
        path.verticalLineTo(192.00);
        path.arcTo(32.00, 32.00, 0.00, false, false, 480.00, 160.00);
        path.close();
        path.moveTo(288.00, 432.00);
        path.arcTo(16.00, 16.00, 0.00, false, true, 272.00, 448.00);
        path.horizontalLineTo(240.00);
        path.arcTo(16.00, 16.00, 0.00, false, true, 224.00, 432.00);
        path.verticalLineTo(400.00);
        path.arcTo(16.00, 16.00, 0.00, false, true, 240.00, 384.00);
        path.horizontalLineTo(272.00);
        path.arcTo(16.00, 16.00, 0.00, false, true, 288.00, 400.00);
        path.close();
        path.moveTo(288.00, 304.00);
        path.arcTo(16.00, 16.00, 0.00, false, true, 272.00, 320.00);
        path.horizontalLineTo(240.00);
        path.arcTo(16.00, 16.00, 0.00, false, true, 224.00, 304.00);
        path.verticalLineTo(272.00);
        path.arcTo(16.00, 16.00, 0.00, false, true, 240.00, 256.00);
        path.horizontalLineTo(272.00);
        path.arcTo(16.00, 16.00, 0.00, false, true, 288.00, 272.00);
        path.close();
        path.moveTo(416.00, 432.00);
        path.arcTo(16.00, 16.00, 0.00, false, true, 400.00, 448.00);
        path.horizontalLineTo(368.00);
        path.arcTo(16.00, 16.00, 0.00, false, true, 352.00, 432.00);
        path.verticalLineTo(400.00);
        path.arcTo(16.00, 16.00, 0.00, false, true, 368.00, 384.00);
        path.horizontalLineTo(400.00);
        path.arcTo(16.00, 16.00, 0.00, false, true, 416.00, 400.00);
        path.close();
        path.moveTo(416.00, 304.00);
        path.arcTo(16.00, 16.00, 0.00, false, true, 400.00, 320.00);
        path.horizontalLineTo(368.00);
        path.arcTo(16.00, 16.00, 0.00, false, true, 352.00, 304.00);
        path.verticalLineTo(272.00);
        path.arcTo(16.00, 16.00, 0.00, false, true, 368.00, 256.00);
        path.horizontalLineTo(400.00);
        path.arcTo(16.00, 16.00, 0.00, false, true, 416.00, 272.00);
        path.close();
        path.moveTo(416.00, 192.00);
        path.horizontalLineTo(192.00);
        path.verticalLineTo(64.00);
        path.horizontalLineTo(352.00);
        path.verticalLineTo(112.00);
        path.arcTo(16.00, 16.00, 0.00, false, false, 368.00, 128.00);
        path.horizontalLineTo(416.00);
        path.close();
        path.moveTo(64.00, 128.00);
        path.horizontalLineTo(32.00);
        path.arcTo(32.00, 32.00, 0.00, false, false, 0.00, 160.00);
        path.verticalLineTo(480.00);
        path.arcTo(32.00, 32.00, 0.00, false, false, 32.00, 512.00);
        path.horizontalLineTo(64.00);
        path.arcTo(32.00, 32.00, 0.00, false, false, 96.00, 480.00);
        path.verticalLineTo(160.00);
        path.arcTo(32.00, 32.00, 0.00, false, false, 64.00, 128.00);
        path.close();
        path.scale(0.046875, 0.046875);
        return path;
    }
}
