// Generated by XIcons
// 2025-08-14 22:10:47
package cn.enaium.xicons.swing.icons.fa;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class TextHeight extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(304.00, 32.00);
        path.horizontalLineTo(16.00);
        path.arcTo(16.00, 16.00, 0.00, false, false, 0.00, 48.00);
        path.verticalLineTo(144.00);
        path.arcTo(16.00, 16.00, 0.00, false, false, 16.00, 160.00);
        path.horizontalLineTo(48.00);
        path.arcTo(16.00, 16.00, 0.00, false, false, 64.00, 144.00);
        path.verticalLineTo(112.00);
        path.horizontalLineTo(120.00);
        path.verticalLineTo(416.00);
        path.horizontalLineTo(80.00);
        path.arcTo(16.00, 16.00, 0.00, false, false, 64.00, 432.00);
        path.verticalLineTo(464.00);
        path.arcTo(16.00, 16.00, 0.00, false, false, 80.00, 480.00);
        path.horizontalLineTo(240.00);
        path.arcTo(16.00, 16.00, 0.00, false, false, 256.00, 464.00);
        path.verticalLineTo(432.00);
        path.arcTo(16.00, 16.00, 0.00, false, false, 240.00, 416.00);
        path.horizontalLineTo(200.00);
        path.verticalLineTo(112.00);
        path.horizontalLineTo(256.00);
        path.verticalLineTo(144.00);
        path.arcTo(16.00, 16.00, 0.00, false, false, 272.00, 160.00);
        path.horizontalLineTo(304.00);
        path.arcTo(16.00, 16.00, 0.00, false, false, 320.00, 144.00);
        path.verticalLineTo(48.00);
        path.arcTo(16.00, 16.00, 0.00, false, false, 304.00, 32.00);
        path.close();
        path.moveTo(560.00, 368.00);
        path.horizontalLineTo(512.00);
        path.verticalLineTo(144.00);
        path.horizontalLineTo(560.00);
        path.curveTo(574.31, 144.00, 581.33, 126.69, 571.31, 116.69);
        path.lineTo(491.31, 36.69);
        path.arcTo(16.00, 16.00, 0.00, false, false, 468.69, 36.69);
        path.lineTo(388.69, 116.69);
        path.curveTo(379.36, 126.00, 384.36, 144.00, 400.00, 144.00);
        path.horizontalLineTo(448.00);
        path.verticalLineTo(368.00);
        path.horizontalLineTo(400.00);
        path.curveTo(385.69, 368.00, 378.68, 385.31, 388.69, 395.31);
        path.lineTo(468.69, 475.31);
        path.arcTo(16.00, 16.00, 0.00, false, false, 491.31, 475.31);
        path.lineTo(571.31, 395.31);
        path.curveTo(580.64, 386.00, 575.64, 368.00, 560.00, 368.00);
        path.close();
        path.scale(0.041666666666666664, 0.041666666666666664);
        return path;
    }
}
