// Generated by XIcons
// 2025-08-14 22:10:51
package cn.enaium.xicons.swing.icons.fluent;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class AlertSnoozeRegular extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(12.00, 3.50);
        path.curveTo(8.90, 3.50, 6.00, 5.93, 6.00, 9.75);
        path.verticalLineTo(13.90);
        path.lineTo(4.68, 17.00);
        path.horizontalLineTo(19.35);
        path.lineTo(18.00, 13.91);
        path.verticalLineTo(11.75);
        path.arcTo(0.75, 0.75, 0.00, false, true, 19.50, 11.75);
        path.verticalLineTo(13.59);
        path.lineTo(20.88, 16.75);
        path.arcTo(1.25, 1.25, 0.00, false, true, 19.73, 18.50);
        path.horizontalLineTo(15.00);
        path.arcTo(3.00, 3.00, 0.00, false, true, 9.00, 18.50);
        path.horizontalLineTo(4.31);
        path.arcTo(1.25, 1.25, 0.00, false, true, 3.16, 16.76);
        path.lineTo(4.50, 13.60);
        path.verticalLineTo(9.75);
        path.curveTo(4.50, 5.07, 8.10, 2.00, 12.00, 2.00);
        path.curveTo(12.86, 2.00, 13.71, 2.15, 14.50, 2.43);
        path.arcTo(0.75, 0.75, 0.00, false, true, 14.00, 3.84);
        path.arcTo(5.96, 5.96, 0.00, false, false, 12.00, 3.50);
        path.close();
        path.moveTo(12.00, 20.00);
        path.curveTo(12.83, 20.00, 13.50, 19.33, 13.50, 18.50);
        path.horizontalLineTo(10.50);
        path.curveTo(10.50, 19.33, 11.17, 20.00, 12.00, 20.00);
        path.close();
        path.moveTo(15.25, 7.00);
        path.horizontalLineTo(12.75);
        path.lineTo(12.65, 7.01);
        path.arcTo(0.75, 0.75, 0.00, false, false, 12.75, 8.50);
        path.horizontalLineTo(13.79);
        path.lineTo(12.14, 10.81);
        path.lineTo(12.08, 10.90);
        path.arcTo(0.75, 0.75, 0.00, false, false, 12.75, 12.00);
        path.horizontalLineTo(15.25);
        path.lineTo(15.35, 11.99);
        path.arcTo(0.75, 0.75, 0.00, false, false, 15.25, 10.50);
        path.horizontalLineTo(14.21);
        path.lineTo(15.86, 8.19);
        path.lineTo(15.92, 8.10);
        path.arcTo(0.75, 0.75, 0.00, false, false, 15.25, 7.00);
        path.close();
        path.moveTo(21.25, 2.00);
        path.horizontalLineTo(17.75);
        path.lineTo(17.65, 2.01);
        path.arcTo(0.75, 0.75, 0.00, false, false, 17.75, 3.50);
        path.horizontalLineTo(19.88);
        path.lineTo(17.12, 7.85);
        path.lineTo(17.07, 7.94);
        path.arcTo(0.75, 0.75, 0.00, false, false, 17.75, 9.00);
        path.horizontalLineTo(21.25);
        path.lineTo(21.35, 8.99);
        path.arcTo(0.75, 0.75, 0.00, false, false, 21.25, 7.50);
        path.horizontalLineTo(19.12);
        path.lineTo(21.88, 3.15);
        path.lineTo(21.93, 3.06);
        path.arcTo(0.75, 0.75, 0.00, false, false, 21.25, 2.00);
        path.close();
        return path;
    }
}
