// Generated by XIcons
// 2025-08-14 22:10:51
package cn.enaium.xicons.swing.icons.fluent;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class ArrowMaximizeVerticalFilled extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(15.21, 6.21);
        path.arcTo(1.00, 1.00, 0.00, false, true, 13.79, 6.21);
        path.lineTo(13.00, 5.41);
        path.verticalLineTo(9.00);
        path.arcTo(1.00, 1.00, 0.00, true, true, 11.00, 9.00);
        path.verticalLineTo(5.41);
        path.lineTo(10.21, 6.21);
        path.arcTo(1.00, 1.00, 0.00, false, true, 8.79, 4.79);
        path.lineTo(11.29, 2.29);
        path.arcTo(1.00, 1.00, 0.00, false, true, 12.00, 2.00);
        path.horizontalLineTo(12.00);
        path.curveTo(12.26, 2.00, 12.51, 2.10, 12.71, 2.29);
        path.lineTo(15.21, 4.79);
        path.arcTo(1.00, 1.00, 0.00, false, true, 15.21, 6.21);
        path.close();
        path.moveTo(5.00, 11.00);
        path.arcTo(1.00, 1.00, 0.00, true, false, 5.00, 13.00);
        path.horizontalLineTo(19.00);
        path.arcTo(1.00, 1.00, 0.00, true, false, 19.00, 11.00);
        path.horizontalLineTo(5.00);
        path.close();
        path.moveTo(12.01, 22.00);
        path.arcTo(1.00, 1.00, 0.00, false, false, 12.71, 21.71);
        path.lineTo(15.21, 19.21);
        path.arcTo(1.00, 1.00, 0.00, false, false, 13.79, 17.79);
        path.lineTo(13.00, 18.59);
        path.verticalLineTo(15.00);
        path.arcTo(1.00, 1.00, 0.00, true, false, 11.00, 15.00);
        path.verticalLineTo(18.59);
        path.lineTo(10.21, 17.79);
        path.arcTo(1.00, 1.00, 0.00, false, false, 8.79, 19.21);
        path.lineTo(11.29, 21.71);
        path.curveTo(11.49, 21.90, 11.74, 22.00, 11.99, 22.00);
        return path;
    }
}
