// Generated by XIcons
// 2025-08-14 22:10:51
package cn.enaium.xicons.swing.icons.fluent;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class ArrowStepInLeftRegular extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(15.29, 16.23);
        path.arcTo(0.75, 0.75, 0.00, false, true, 14.21, 17.27);
        path.lineTo(9.71, 12.52);
        path.arcTo(0.75, 0.75, 0.00, false, true, 9.71, 11.48);
        path.lineTo(14.21, 6.73);
        path.arcTo(0.75, 0.75, 0.00, false, true, 15.29, 7.77);
        path.lineTo(11.99, 11.25);
        path.horizontalLineTo(21.25);
        path.arcTo(0.75, 0.75, 0.00, false, true, 21.25, 12.75);
        path.horizontalLineTo(11.99);
        path.lineTo(15.29, 16.23);
        path.close();
        path.moveTo(2.00, 12.00);
        path.arcTo(3.00, 3.00, 0.00, true, true, 8.00, 12.00);
        path.arcTo(3.00, 3.00, 0.00, false, true, 2.00, 12.00);
        path.close();
        path.moveTo(3.50, 12.00);
        path.arcTo(1.50, 1.50, 0.00, true, false, 6.50, 12.00);
        path.arcTo(1.50, 1.50, 0.00, false, false, 3.50, 12.00);
        path.close();
        return path;
    }
}
