// Generated by XIcons
// 2025-08-14 22:10:51
package cn.enaium.xicons.swing.icons.fluent;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class ArrowCounterclockwiseRegular extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(12.00, 4.50);
        path.arcTo(7.50, 7.50, 0.00, true, true, 4.58, 10.89);
        path.curveTo(4.65, 10.44, 4.32, 10.00, 3.86, 10.00);
        path.arcTo(0.75, 0.75, 0.00, false, false, 3.11, 10.62);
        path.arcTo(9.00, 9.00, 0.00, true, false, 6.00, 5.29);
        path.verticalLineTo(4.25);
        path.arcTo(0.75, 0.75, 0.00, false, false, 4.50, 4.25);
        path.verticalLineTo(7.25);
        path.curveTo(4.50, 7.66, 4.84, 8.00, 5.25, 8.00);
        path.horizontalLineTo(8.25);
        path.arcTo(0.75, 0.75, 0.00, false, false, 8.25, 6.50);
        path.horizontalLineTo(6.90);
        path.arcTo(7.47, 7.47, 0.00, false, true, 12.00, 4.50);
        path.close();
        return path;
    }
}
