// Generated by XIcons
// 2025-08-14 22:10:52
package cn.enaium.xicons.swing.icons.fluent;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class BookExclamationMarkFilled extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(4.00, 4.50);
        path.verticalLineTo(19.50);
        path.arcTo(2.50, 2.50, 0.00, false, false, 6.50, 22.00);
        path.horizontalLineTo(19.75);
        path.arcTo(0.75, 0.75, 0.00, false, false, 19.75, 20.50);
        path.horizontalLineTo(6.50);
        path.arcTo(1.00, 1.00, 0.00, false, true, 5.50, 19.50);
        path.horizontalLineTo(19.75);
        path.arcTo(0.75, 0.75, 0.00, false, false, 20.50, 18.75);
        path.verticalLineTo(4.50);
        path.arcTo(2.50, 2.50, 0.00, false, false, 18.00, 2.00);
        path.horizontalLineTo(6.50);
        path.arcTo(2.50, 2.50, 0.00, false, false, 4.00, 4.50);
        path.close();
        path.moveTo(11.50, 11.75);
        path.verticalLineTo(6.75);
        path.arcTo(0.75, 0.75, 0.00, false, true, 13.00, 6.75);
        path.verticalLineTo(11.75);
        path.arcTo(0.75, 0.75, 0.00, false, true, 11.50, 11.75);
        path.close();
        path.moveTo(13.25, 14.50);
        path.arcTo(1.00, 1.00, 0.00, true, true, 11.25, 14.50);
        path.arcTo(1.00, 1.00, 0.00, false, true, 13.25, 14.50);
        path.close();
        return path;
    }
}
