// Generated by XIcons
// 2025-08-14 22:10:52
package cn.enaium.xicons.swing.icons.fluent;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class CaretRightFilled extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(9.00, 17.90);
        path.curveTo(9.00, 18.97, 10.27, 19.55, 11.07, 18.84);
        path.lineTo(17.38, 13.32);
        path.arcTo(1.75, 1.75, 0.00, false, false, 17.38, 10.68);
        path.lineTo(11.07, 5.16);
        path.curveTo(10.27, 4.45, 9.00, 5.03, 9.00, 6.10);
        path.verticalLineTo(17.90);
        path.close();
        return path;
    }
}
