// Generated by XIcons
// 2025-08-14 22:10:54
package cn.enaium.xicons.swing.icons.fluent;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class GuitarFilled extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(18.49, 3.43);
        path.lineTo(19.68, 2.25);
        path.arcTo(1.00, 1.00, 0.00, false, true, 21.09, 2.25);
        path.lineTo(21.80, 2.95);
        path.arcTo(1.00, 1.00, 0.00, false, true, 21.80, 4.37);
        path.lineTo(20.61, 5.55);
        path.lineTo(18.49, 3.43);
        path.close();
        path.moveTo(17.43, 4.49);
        path.lineTo(13.61, 8.31);
        path.lineTo(13.45, 8.15);
        path.arcTo(2.75, 2.75, 0.00, false, false, 9.05, 8.87);
        path.lineTo(8.63, 9.70);
        path.arcTo(0.61, 0.61, 0.00, false, true, 7.97, 10.03);
        path.lineTo(7.90, 10.01);
        path.arcTo(4.71, 4.71, 0.00, false, false, 3.21, 11.80);
        path.arcTo(6.03, 6.03, 0.00, false, false, 3.77, 19.68);
        path.lineTo(4.36, 20.28);
        path.arcTo(6.03, 6.03, 0.00, false, false, 12.24, 20.84);
        path.arcTo(4.71, 4.71, 0.00, false, false, 14.03, 16.15);
        path.lineTo(14.02, 16.08);
        path.arcTo(0.61, 0.61, 0.00, false, true, 14.34, 15.41);
        path.lineTo(15.18, 15.00);
        path.arcTo(2.75, 2.75, 0.00, false, false, 15.89, 10.59);
        path.lineTo(15.73, 10.43);
        path.lineTo(19.55, 6.61);
        path.lineTo(17.43, 4.49);
        path.close();
        path.moveTo(9.44, 14.56);
        path.arcTo(1.50, 1.50, 0.00, true, true, 11.56, 12.44);
        path.arcTo(1.50, 1.50, 0.00, false, true, 9.44, 14.56);
        path.close();
        return path;
    }
}
