// Generated by XIcons
// 2025-08-14 22:10:54
package cn.enaium.xicons.swing.icons.fluent;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class IncognitoFilled extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(17.50, 11.75);
        path.arcTo(4.75, 4.75, 0.00, true, true, 12.99, 18.00);
        path.horizontalLineTo(11.01);
        path.arcTo(4.75, 4.75, 0.00, false, true, 1.75, 16.50);
        path.arcTo(4.75, 4.75, 0.00, false, true, 11.22, 16.00);
        path.horizontalLineTo(12.78);
        path.arcTo(4.75, 4.75, 0.00, false, true, 17.50, 11.75);
        path.close();
        path.moveTo(6.50, 13.75);
        path.arcTo(2.75, 2.75, 0.00, true, false, 6.50, 19.25);
        path.arcTo(2.75, 2.75, 0.00, false, false, 6.50, 13.75);
        path.close();
        path.moveTo(17.50, 13.75);
        path.arcTo(2.75, 2.75, 0.00, true, false, 17.50, 19.25);
        path.arcTo(2.75, 2.75, 0.00, false, false, 17.50, 13.75);
        path.close();
        path.moveTo(15.51, 3.00);
        path.arcTo(2.75, 2.75, 0.00, false, true, 18.15, 4.96);
        path.lineTo(19.15, 8.31);
        path.curveTo(19.95, 8.44, 20.72, 8.60, 21.48, 8.78);
        path.arcTo(1.00, 1.00, 0.00, true, true, 21.02, 10.72);
        path.curveTo(18.27, 10.08, 15.26, 9.75, 12.00, 9.75);
        path.curveTo(8.74, 9.75, 5.74, 10.08, 2.98, 10.72);
        path.arcTo(1.00, 1.00, 0.00, false, true, 2.52, 8.78);
        path.arcTo(35.88, 35.88, 0.00, false, true, 4.85, 8.31);
        path.lineTo(5.85, 4.96);
        path.arcTo(2.75, 2.75, 0.00, false, true, 8.49, 3.00);
        path.horizontalLineTo(15.51);
        path.close();
        return path;
    }
}
