// Generated by XIcons
// 2025-08-14 22:10:56
package cn.enaium.xicons.swing.icons.fluent;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class SplitVerticalFilled extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(12.50, 2.75);
        path.arcTo(0.75, 0.75, 0.00, false, false, 11.00, 2.75);
        path.verticalLineTo(21.25);
        path.arcTo(0.75, 0.75, 0.00, false, false, 12.50, 21.25);
        path.verticalLineTo(2.75);
        path.close();
        path.moveTo(2.00, 6.25);
        path.arcTo(2.25, 2.25, 0.00, false, true, 4.25, 4.00);
        path.horizontalLineTo(10.00);
        path.verticalLineTo(20.00);
        path.horizontalLineTo(4.25);
        path.arcTo(2.25, 2.25, 0.00, false, true, 2.00, 17.75);
        path.verticalLineTo(6.25);
        path.close();
        path.moveTo(19.25, 20.00);
        path.horizontalLineTo(13.50);
        path.verticalLineTo(4.00);
        path.horizontalLineTo(19.25);
        path.arcTo(2.25, 2.25, 0.00, false, true, 21.50, 6.25);
        path.verticalLineTo(17.75);
        path.arcTo(2.25, 2.25, 0.00, false, true, 19.25, 20.00);
        path.close();
        return path;
    }
}
