// Generated by XIcons
// 2025-08-14 22:10:56
package cn.enaium.xicons.swing.icons.fluent;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class StarAddRegular extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(10.79, 3.10);
        path.curveTo(11.28, 2.10, 12.71, 2.10, 13.21, 3.10);
        path.lineTo(15.57, 7.88);
        path.lineTo(20.84, 8.65);
        path.curveTo(21.95, 8.81, 22.39, 10.17, 21.59, 10.95);
        path.lineTo(20.68, 11.83);
        path.arcTo(6.46, 6.46, 0.00, false, false, 19.17, 11.21);
        path.lineTo(20.32, 10.09);
        path.lineTo(15.27, 9.35);
        path.arcTo(1.35, 1.35, 0.00, false, true, 14.26, 8.61);
        path.lineTo(12.00, 4.04);
        path.lineTo(9.74, 8.61);
        path.arcTo(1.35, 1.35, 0.00, false, true, 8.72, 9.35);
        path.lineTo(3.67, 10.09);
        path.lineTo(7.33, 13.65);
        path.curveTo(7.65, 13.96, 7.79, 14.41, 7.72, 14.84);
        path.lineTo(6.85, 19.87);
        path.lineTo(11.00, 17.69);
        path.curveTo(11.02, 18.23, 11.10, 18.76, 11.24, 19.26);
        path.lineTo(7.28, 21.34);
        path.curveTo(6.29, 21.86, 5.14, 21.02, 5.32, 19.92);
        path.lineTo(6.22, 14.67);
        path.lineTo(2.41, 10.95);
        path.curveTo(1.61, 10.17, 2.05, 8.81, 3.16, 8.65);
        path.lineTo(8.43, 7.88);
        path.lineTo(10.79, 3.10);
        path.close();
        path.moveTo(23.00, 17.50);
        path.arcTo(5.50, 5.50, 0.00, true, false, 12.00, 17.50);
        path.arcTo(5.50, 5.50, 0.00, false, false, 23.00, 17.50);
        path.close();
        path.moveTo(18.00, 18.00);
        path.lineTo(18.00, 20.50);
        path.arcTo(0.50, 0.50, 0.00, true, true, 17.00, 20.50);
        path.verticalLineTo(18.00);
        path.horizontalLineTo(14.50);
        path.arcTo(0.50, 0.50, 0.00, false, true, 14.50, 17.00);
        path.horizontalLineTo(17.00);
        path.verticalLineTo(14.50);
        path.arcTo(0.50, 0.50, 0.00, false, true, 18.00, 14.50);
        path.verticalLineTo(17.00);
        path.horizontalLineTo(20.50);
        path.arcTo(0.50, 0.50, 0.00, false, true, 20.50, 18.00);
        path.horizontalLineTo(18.00);
        path.close();
        return path;
    }
}
