// Generated by XIcons
// 2025-08-14 22:11:02
package cn.enaium.xicons.swing.icons.ionicons5;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class DesktopOutline extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(304.00, 448.00);
        path.lineTo(296.00, 384.00);
        path.horizontalLineTo(216.00);
        path.lineTo(208.00, 448.00);
        path.horizontalLineTo(304.00);
        path.close();
        path.moveTo(368.00, 448.00);
        path.horizontalLineTo(144.00);
        path.moveTo(32.00, 304.00);
        path.verticalLineTo(352.00);
        path.arcTo(32.09, 32.09, 0.00, false, false, 64.00, 384.00);
        path.horizontalLineTo(448.00);
        path.arcTo(32.09, 32.09, 0.00, false, false, 480.00, 352.00);
        path.verticalLineTo(304.00);
        path.close();
        path.moveTo(256.00, 368.00);
        path.arcTo(16.00, 16.00, 0.00, true, true, 272.00, 352.00);
        path.arcTo(16.00, 16.00, 0.00, false, true, 256.00, 368.00);
        path.close();
        path.scale(0.046875, 0.046875);
        return path;
    }
}
