// Generated by XIcons
// 2025-08-14 22:11:03
package cn.enaium.xicons.swing.icons.ionicons5;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class QrCode extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(448.00, 32.00);
        path.horizontalLineTo(304.00);
        path.arcTo(32.00, 32.00, 0.00, false, false, 272.00, 64.00);
        path.verticalLineTo(208.00);
        path.arcTo(32.00, 32.00, 0.00, false, false, 304.00, 240.00);
        path.horizontalLineTo(448.00);
        path.arcTo(32.00, 32.00, 0.00, false, false, 480.00, 208.00);
        path.verticalLineTo(64.00);
        path.arcTo(32.00, 32.00, 0.00, false, false, 448.00, 32.00);
        path.close();
        path.moveTo(416.00, 168.00);
        path.arcTo(8.00, 8.00, 0.00, false, true, 408.00, 176.00);
        path.horizontalLineTo(344.00);
        path.arcTo(8.00, 8.00, 0.00, false, true, 336.00, 168.00);
        path.verticalLineTo(104.00);
        path.arcTo(8.00, 8.00, 0.00, false, true, 344.00, 96.00);
        path.horizontalLineTo(408.00);
        path.arcTo(8.00, 8.00, 0.00, false, true, 416.00, 104.00);
        path.close();
        path.moveTo(208.00, 32.00);
        path.horizontalLineTo(64.00);
        path.arcTo(32.00, 32.00, 0.00, false, false, 32.00, 64.00);
        path.verticalLineTo(208.00);
        path.arcTo(32.00, 32.00, 0.00, false, false, 64.00, 240.00);
        path.horizontalLineTo(208.00);
        path.arcTo(32.00, 32.00, 0.00, false, false, 240.00, 208.00);
        path.verticalLineTo(64.00);
        path.arcTo(32.00, 32.00, 0.00, false, false, 208.00, 32.00);
        path.close();
        path.moveTo(176.00, 168.00);
        path.arcTo(8.00, 8.00, 0.00, false, true, 168.00, 176.00);
        path.horizontalLineTo(104.00);
        path.arcTo(8.00, 8.00, 0.00, false, true, 96.00, 168.00);
        path.verticalLineTo(104.00);
        path.arcTo(8.00, 8.00, 0.00, false, true, 104.00, 96.00);
        path.horizontalLineTo(168.00);
        path.arcTo(8.00, 8.00, 0.00, false, true, 176.00, 104.00);
        path.close();
        path.moveTo(208.00, 272.00);
        path.horizontalLineTo(64.00);
        path.arcTo(32.00, 32.00, 0.00, false, false, 32.00, 304.00);
        path.verticalLineTo(448.00);
        path.arcTo(32.00, 32.00, 0.00, false, false, 64.00, 480.00);
        path.horizontalLineTo(208.00);
        path.arcTo(32.00, 32.00, 0.00, false, false, 240.00, 448.00);
        path.verticalLineTo(304.00);
        path.arcTo(32.00, 32.00, 0.00, false, false, 208.00, 272.00);
        path.close();
        path.moveTo(176.00, 408.00);
        path.arcTo(8.00, 8.00, 0.00, false, true, 168.00, 416.00);
        path.horizontalLineTo(104.00);
        path.arcTo(8.00, 8.00, 0.00, false, true, 96.00, 408.00);
        path.verticalLineTo(344.00);
        path.arcTo(8.00, 8.00, 0.00, false, true, 104.00, 336.00);
        path.horizontalLineTo(168.00);
        path.arcTo(8.00, 8.00, 0.00, false, true, 176.00, 344.00);
        path.close();
        path.scale(0.046875, 0.046875);
        return path;
    }
}
