// Generated by XIcons
// 2025-08-14 22:11:03
package cn.enaium.xicons.swing.icons.ionicons5;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class Recording extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(380.79, 144.05);
        path.curveTo(321.69, 145.70, 273.67, 193.76, 272.00, 252.86);
        path.arcTo(111.64, 111.64, 0.00, false, false, 302.36, 332.63);
        path.arcTo(2.00, 2.00, 0.00, false, true, 301.00, 336.00);
        path.horizontalLineTo(211.00);
        path.arcTo(2.00, 2.00, 0.00, false, true, 209.56, 332.63);
        path.arcTo(111.64, 111.64, 0.00, false, false, 240.00, 252.86);
        path.curveTo(238.37, 193.76, 190.35, 145.70, 131.25, 144.05);
        path.arcTo(112.12, 112.12, 0.00, false, false, 16.00, 255.53);
        path.curveTo(15.75, 317.77, 67.00, 368.00, 129.24, 368.00);
        path.horizontalLineTo(382.76);
        path.curveTo(445.00, 368.00, 496.25, 317.77, 496.00, 255.53);
        path.arcTo(112.12, 112.12, 0.00, false, false, 380.79, 144.05);
        path.close();
        path.scale(0.046875, 0.046875);
        return path;
    }
}
