// Generated by XIcons
// 2025-08-17 11:04:14
package cn.enaium.xicons.compose.fluent

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.FluentIcons

public val FluentIcons.Regular.ArrowDownload: ImageVector
    get() {
        if (_ArrowDownload != null) {
            return _ArrowDownload!!
        }
        _ArrowDownload = ImageVector.Builder(
            name = "ArrowDownload",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(18.25f, 20.50f)
                arcTo(0.75f, 0.75f, 0.00f, true, true, 18.25f, 22.00f)
                lineTo(5.25f, 22.01f)
                arcTo(0.75f, 0.75f, 0.00f, true, true, 5.25f, 20.51f)
                lineTo(18.25f, 20.50f)
                close()
                moveTo(11.65f, 2.01f)
                lineTo(11.75f, 2.01f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 12.49f, 2.66f)
                lineTo(12.50f, 2.76f)
                lineTo(12.50f, 16.44f)
                lineTo(16.22f, 12.72f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 17.20f, 12.65f)
                lineTo(17.28f, 12.72f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 17.35f, 13.70f)
                lineTo(17.28f, 13.78f)
                lineTo(12.28f, 18.78f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 11.31f, 18.85f)
                lineTo(11.22f, 18.78f)
                lineTo(6.22f, 13.78f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 7.20f, 12.65f)
                lineTo(7.28f, 12.72f)
                lineTo(11.00f, 16.44f)
                lineTo(11.00f, 2.76f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 11.65f, 2.01f)
                lineTo(11.75f, 2.01f)
                lineTo(11.65f, 2.01f)
                close()
            }
        }.build()
        return _ArrowDownload!!
    }

private var _ArrowDownload: ImageVector? = null
