// Generated by XIcons
// 2025-08-17 11:04:15
package cn.enaium.xicons.compose.fluent

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.FluentIcons

public val FluentIcons.Filled.ArrowPrevious: ImageVector
    get() {
        if (_ArrowPrevious != null) {
            return _ArrowPrevious!!
        }
        _ArrowPrevious = ImageVector.Builder(
            name = "ArrowPrevious",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(6.00f, 3.00f)
                arcTo(1.00f, 1.00f, 0.00f, false, false, 5.01f, 3.88f)
                lineTo(5.00f, 4.00f)
                verticalLineTo(20.00f)
                arcTo(1.00f, 1.00f, 0.00f, false, false, 6.99f, 20.12f)
                lineTo(7.00f, 20.00f)
                verticalLineTo(4.00f)
                arcTo(1.00f, 1.00f, 0.00f, false, false, 6.00f, 3.00f)
                close()
                moveTo(18.71f, 3.29f)
                arcTo(1.00f, 1.00f, 0.00f, false, false, 17.39f, 3.21f)
                lineTo(17.29f, 3.29f)
                lineTo(9.29f, 11.29f)
                arcTo(1.00f, 1.00f, 0.00f, false, false, 9.21f, 12.61f)
                lineTo(9.29f, 12.71f)
                lineTo(17.29f, 20.71f)
                arcTo(1.00f, 1.00f, 0.00f, false, false, 18.79f, 19.39f)
                lineTo(18.71f, 19.29f)
                lineTo(11.41f, 12.00f)
                lineTo(18.71f, 4.71f)
                arcTo(1.00f, 1.00f, 0.00f, false, false, 18.71f, 3.29f)
                close()
            }
        }.build()
        return _ArrowPrevious!!
    }

private var _ArrowPrevious: ImageVector? = null
