// Generated by XIcons
// 2025-08-17 11:04:16
package cn.enaium.xicons.compose.fluent

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.FluentIcons

public val FluentIcons.Filled.ClipboardArrowRight: ImageVector
    get() {
        if (_ClipboardArrowRight != null) {
            return _ClipboardArrowRight!!
        }
        _ClipboardArrowRight = ImageVector.Builder(
            name = "ClipboardArrowRight",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(10.25f, 2.00f)
                horizontalLineTo(13.75f)
                arcTo(2.25f, 2.25f, 0.00f, false, true, 15.99f, 4.00f)
                horizontalLineTo(17.75f)
                arcTo(2.25f, 2.25f, 0.00f, false, true, 20.00f, 6.25f)
                verticalLineTo(11.50f)
                arcTo(6.50f, 6.50f, 0.00f, false, false, 12.81f, 22.00f)
                horizontalLineTo(6.25f)
                arcTo(2.25f, 2.25f, 0.00f, false, true, 4.00f, 19.75f)
                verticalLineTo(6.25f)
                arcTo(2.25f, 2.25f, 0.00f, false, true, 6.25f, 4.00f)
                horizontalLineTo(8.01f)
                arcTo(2.25f, 2.25f, 0.00f, false, true, 10.25f, 2.00f)
                close()
                moveTo(13.75f, 3.50f)
                horizontalLineTo(10.25f)
                arcTo(0.75f, 0.75f, 0.00f, false, false, 10.25f, 5.00f)
                horizontalLineTo(13.75f)
                arcTo(0.75f, 0.75f, 0.00f, false, false, 13.75f, 3.50f)
                close()
                moveTo(23.00f, 17.50f)
                arcTo(5.50f, 5.50f, 0.00f, true, true, 12.00f, 17.50f)
                arcTo(5.50f, 5.50f, 0.00f, false, true, 23.00f, 17.50f)
                close()
                moveTo(14.50f, 17.00f)
                arcTo(0.50f, 0.50f, 0.00f, false, false, 14.50f, 18.00f)
                horizontalLineTo(19.29f)
                lineTo(17.65f, 19.65f)
                arcTo(0.50f, 0.50f, 0.00f, false, false, 18.35f, 20.35f)
                lineTo(20.85f, 17.85f)
                arcTo(0.50f, 0.50f, 0.00f, false, false, 20.85f, 17.15f)
                lineTo(18.35f, 14.65f)
                arcTo(0.50f, 0.50f, 0.00f, false, false, 17.65f, 15.35f)
                lineTo(19.29f, 17.00f)
                horizontalLineTo(14.50f)
                close()
            }
        }.build()
        return _ClipboardArrowRight!!
    }

private var _ClipboardArrowRight: ImageVector? = null
