// Generated by XIcons
// 2025-08-17 11:04:17
package cn.enaium.xicons.compose.fluent

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.FluentIcons

public val FluentIcons.Filled.ClockPause: ImageVector
    get() {
        if (_ClockPause != null) {
            return _ClockPause!!
        }
        _ClockPause = ImageVector.Builder(
            name = "ClockPause",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(15.75f, 13.50f)
                horizontalLineTo(11.75f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 11.61f, 13.49f)
                arcTo(6.47f, 6.47f, 0.00f, false, true, 13.00f, 17.50f)
                arcTo(6.48f, 6.48f, 0.00f, false, true, 11.22f, 21.97f)
                curveTo(11.48f, 21.99f, 11.74f, 22.00f, 12.00f, 22.00f)
                curveTo(17.52f, 22.00f, 22.00f, 17.52f, 22.00f, 12.00f)
                curveTo(22.00f, 6.48f, 17.52f, 2.00f, 12.00f, 2.00f)
                curveTo(6.48f, 2.00f, 2.00f, 6.48f, 2.00f, 12.00f)
                curveTo(2.00f, 12.26f, 2.01f, 12.52f, 2.03f, 12.78f)
                arcTo(6.48f, 6.48f, 0.00f, false, true, 6.50f, 11.00f)
                curveTo(8.25f, 11.00f, 9.83f, 11.69f, 11.00f, 12.81f)
                arcTo(0.79f, 0.79f, 0.00f, false, true, 11.00f, 12.75f)
                verticalLineTo(6.75f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 12.50f, 6.75f)
                verticalLineTo(12.00f)
                horizontalLineTo(15.75f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 15.75f, 13.50f)
                close()
                moveTo(12.00f, 17.50f)
                arcTo(5.50f, 5.50f, 0.00f, true, true, 1.00f, 17.50f)
                arcTo(5.50f, 5.50f, 0.00f, false, true, 12.00f, 17.50f)
                close()
                moveTo(4.50f, 14.50f)
                arcTo(0.50f, 0.50f, 0.00f, false, false, 4.00f, 15.00f)
                verticalLineTo(20.00f)
                arcTo(0.50f, 0.50f, 0.00f, false, false, 5.00f, 20.00f)
                verticalLineTo(15.00f)
                arcTo(0.50f, 0.50f, 0.00f, false, false, 4.50f, 14.50f)
                close()
                moveTo(8.50f, 14.50f)
                arcTo(0.50f, 0.50f, 0.00f, false, false, 8.00f, 15.00f)
                verticalLineTo(20.00f)
                arcTo(0.50f, 0.50f, 0.00f, false, false, 9.00f, 20.00f)
                verticalLineTo(15.00f)
                arcTo(0.50f, 0.50f, 0.00f, false, false, 8.50f, 14.50f)
                close()
            }
        }.build()
        return _ClockPause!!
    }

private var _ClockPause: ImageVector? = null
