// Generated by XIcons
// 2025-08-17 11:04:17
package cn.enaium.xicons.compose.fluent

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.FluentIcons

public val FluentIcons.Filled.CurrencyDollarRupee: ImageVector
    get() {
        if (_CurrencyDollarRupee != null) {
            return _CurrencyDollarRupee!!
        }
        _CurrencyDollarRupee = ImageVector.Builder(
            name = "CurrencyDollarRupee",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(7.50f, 3.00f)
                verticalLineTo(3.11f)
                arcTo(4.50f, 4.50f, 0.00f, false, true, 11.00f, 7.50f)
                verticalLineTo(8.37f)
                arcTo(1.00f, 1.00f, 0.00f, true, true, 9.00f, 8.37f)
                verticalLineTo(7.50f)
                arcTo(2.50f, 2.50f, 0.00f, false, false, 7.50f, 5.21f)
                verticalLineTo(11.37f)
                lineTo(8.21f, 11.70f)
                arcTo(4.88f, 4.88f, 0.00f, false, true, 11.00f, 16.11f)
                verticalLineTo(16.48f)
                arcTo(4.50f, 4.50f, 0.00f, false, true, 7.50f, 20.87f)
                verticalLineTo(20.99f)
                arcTo(1.00f, 1.00f, 0.00f, false, true, 5.50f, 20.99f)
                verticalLineTo(20.87f)
                arcTo(4.50f, 4.50f, 0.00f, false, true, 2.00f, 16.48f)
                verticalLineTo(15.63f)
                arcTo(1.00f, 1.00f, 0.00f, true, true, 4.00f, 15.63f)
                verticalLineTo(16.48f)
                arcTo(2.50f, 2.50f, 0.00f, false, false, 5.50f, 18.77f)
                verticalLineTo(12.63f)
                lineTo(4.80f, 12.30f)
                arcTo(4.88f, 4.88f, 0.00f, false, true, 2.00f, 7.88f)
                verticalLineTo(7.50f)
                arcTo(4.50f, 4.50f, 0.00f, false, true, 5.50f, 3.11f)
                verticalLineTo(3.00f)
                arcTo(1.00f, 1.00f, 0.00f, false, true, 7.50f, 3.00f)
                close()
                moveTo(5.50f, 5.21f)
                arcTo(2.50f, 2.50f, 0.00f, false, false, 4.00f, 7.50f)
                verticalLineTo(7.88f)
                curveTo(4.00f, 8.94f, 4.58f, 9.91f, 5.50f, 10.41f)
                verticalLineTo(5.21f)
                close()
                moveTo(7.50f, 13.58f)
                verticalLineTo(18.77f)
                arcTo(2.50f, 2.50f, 0.00f, false, false, 9.00f, 16.48f)
                verticalLineTo(16.11f)
                curveTo(9.00f, 15.05f, 8.42f, 14.08f, 7.50f, 13.58f)
                close()
                moveTo(13.00f, 3.00f)
                arcTo(1.00f, 1.00f, 0.00f, false, false, 12.99f, 5.00f)
                horizontalLineTo(15.50f)
                curveTo(16.32f, 5.00f, 17.04f, 5.39f, 17.50f, 6.00f)
                horizontalLineTo(13.00f)
                arcTo(1.00f, 1.00f, 0.00f, true, false, 13.00f, 8.00f)
                horizontalLineTo(17.95f)
                arcTo(2.50f, 2.50f, 0.00f, false, true, 15.50f, 10.00f)
                horizontalLineTo(13.00f)
                arcTo(1.00f, 1.00f, 0.00f, false, false, 12.18f, 11.57f)
                lineTo(19.18f, 21.57f)
                arcTo(1.00f, 1.00f, 0.00f, false, false, 20.82f, 20.43f)
                lineTo(14.92f, 12.00f)
                horizontalLineTo(15.50f)
                arcTo(4.50f, 4.50f, 0.00f, false, false, 19.97f, 8.00f)
                horizontalLineTo(21.00f)
                arcTo(1.00f, 1.00f, 0.00f, true, false, 21.00f, 6.00f)
                horizontalLineTo(19.74f)
                arcTo(4.48f, 4.48f, 0.00f, false, false, 19.24f, 5.00f)
                horizontalLineTo(21.00f)
                arcTo(1.00f, 1.00f, 0.00f, true, false, 21.00f, 3.00f)
                horizontalLineTo(13.00f)
                close()
            }
        }.build()
        return _CurrencyDollarRupee!!
    }

private var _CurrencyDollarRupee: ImageVector? = null
