// Generated by XIcons
// 2025-08-17 11:04:19
package cn.enaium.xicons.compose.fluent

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.FluentIcons

public val FluentIcons.Filled.FlagOff: ImageVector
    get() {
        if (_FlagOff != null) {
            return _FlagOff!!
        }
        _FlagOff = ImageVector.Builder(
            name = "FlagOff",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(2.50f, 2.50f)
                lineTo(20.50f, 20.50f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 19.44f, 21.56f)
                lineTo(14.38f, 16.50f)
                horizontalLineTo(4.50f)
                verticalLineTo(21.25f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 3.85f, 21.99f)
                lineTo(3.75f, 22.00f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 3.01f, 21.35f)
                lineTo(3.00f, 21.25f)
                verticalLineTo(5.12f)
                lineTo(1.44f, 3.56f)
                arcTo(0.75f, 0.75f, 0.00f, true, true, 2.50f, 2.50f)
                close()
                moveTo(5.12f, 3.00f)
                horizontalLineTo(20.25f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 20.85f, 4.20f)
                lineTo(16.69f, 9.75f)
                lineTo(20.85f, 15.30f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 20.25f, 16.50f)
                horizontalLineTo(18.62f)
                lineTo(5.12f, 3.00f)
                close()
            }
        }.build()
        return _FlagOff!!
    }

private var _FlagOff: ImageVector? = null
