// Generated by XIcons
// 2025-08-17 11:04:19
package cn.enaium.xicons.compose.fluent

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.FluentIcons

public val FluentIcons.Filled.Fps0: ImageVector
    get() {
        if (_Fps0 != null) {
            return _Fps0!!
        }
        _Fps0 = ImageVector.Builder(
            name = "Fps0",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(2.15f, 6.18f)
                arcTo(1.00f, 1.00f, 0.00f, false, false, 3.44f, 5.64f)
                arcTo(1.12f, 1.12f, 0.00f, false, true, 3.66f, 5.37f)
                curveTo(3.83f, 5.21f, 4.16f, 5.00f, 4.77f, 5.00f)
                curveTo(5.19f, 5.00f, 5.51f, 5.13f, 5.71f, 5.30f)
                curveTo(5.89f, 5.45f, 6.02f, 5.67f, 6.02f, 6.00f)
                curveTo(6.02f, 6.55f, 5.84f, 6.87f, 5.59f, 7.12f)
                curveTo(5.29f, 7.44f, 4.87f, 7.68f, 4.27f, 8.02f)
                curveTo(3.73f, 8.33f, 3.02f, 8.74f, 2.47f, 9.35f)
                curveTo(1.89f, 10.01f, 1.52f, 10.86f, 1.52f, 12.00f)
                arcTo(1.00f, 1.00f, 0.00f, false, false, 2.52f, 13.00f)
                horizontalLineTo(7.01f)
                arcTo(1.00f, 1.00f, 0.00f, false, false, 7.01f, 11.00f)
                horizontalLineTo(3.74f)
                curveTo(3.81f, 10.88f, 3.88f, 10.78f, 3.97f, 10.68f)
                curveTo(4.27f, 10.35f, 4.68f, 10.09f, 5.26f, 9.76f)
                lineTo(5.37f, 9.70f)
                curveTo(5.88f, 9.41f, 6.52f, 9.04f, 7.03f, 8.51f)
                curveTo(7.62f, 7.90f, 8.01f, 7.09f, 8.01f, 6.00f)
                curveTo(8.01f, 5.09f, 7.63f, 4.31f, 7.00f, 3.77f)
                curveTo(6.39f, 3.25f, 5.59f, 3.00f, 4.77f, 3.00f)
                curveTo(3.63f, 3.00f, 2.83f, 3.42f, 2.32f, 3.89f)
                arcTo(3.11f, 3.11f, 0.00f, false, false, 1.65f, 4.75f)
                arcTo(2.02f, 2.02f, 0.00f, false, false, 1.60f, 4.86f)
                lineTo(1.60f, 4.87f)
                lineTo(1.59f, 4.87f)
                verticalLineTo(4.88f)
                lineTo(1.59f, 4.88f)
                curveTo(1.59f, 4.88f, 1.38f, 5.40f, 1.59f, 4.88f)
                arcTo(1.00f, 1.00f, 0.00f, false, false, 2.15f, 6.18f)
                close()
                moveTo(16.01f, 6.00f)
                curveTo(16.01f, 4.34f, 17.35f, 3.00f, 19.00f, 3.00f)
                arcTo(3.00f, 3.00f, 0.00f, false, true, 22.00f, 6.00f)
                verticalLineTo(10.00f)
                curveTo(22.00f, 11.66f, 20.66f, 13.00f, 19.00f, 13.00f)
                arcTo(3.00f, 3.00f, 0.00f, false, true, 16.01f, 10.00f)
                verticalLineTo(6.00f)
                close()
                moveTo(19.00f, 5.00f)
                arcTo(1.00f, 1.00f, 0.00f, false, false, 18.00f, 6.00f)
                verticalLineTo(10.00f)
                arcTo(1.00f, 1.00f, 0.00f, true, false, 20.00f, 10.00f)
                verticalLineTo(6.00f)
                arcTo(1.00f, 1.00f, 0.00f, false, false, 19.00f, 5.00f)
                close()
                moveTo(4.77f, 15.00f)
                arcTo(0.75f, 0.75f, 0.00f, false, false, 4.02f, 15.75f)
                verticalLineTo(21.23f)
                arcTo(0.75f, 0.75f, 0.00f, true, false, 5.52f, 21.23f)
                verticalLineTo(19.50f)
                horizontalLineTo(7.27f)
                arcTo(0.75f, 0.75f, 0.00f, false, false, 7.27f, 18.00f)
                horizontalLineTo(5.52f)
                verticalLineTo(16.50f)
                horizontalLineTo(7.77f)
                arcTo(0.75f, 0.75f, 0.00f, false, false, 7.77f, 15.00f)
                horizontalLineTo(4.77f)
                close()
                moveTo(9.51f, 15.75f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 10.26f, 15.00f)
                horizontalLineTo(11.76f)
                arcTo(2.25f, 2.25f, 0.00f, false, true, 14.01f, 17.25f)
                arcTo(2.25f, 2.25f, 0.00f, false, true, 11.76f, 19.50f)
                horizontalLineTo(11.01f)
                verticalLineTo(21.25f)
                arcTo(0.75f, 0.75f, 0.00f, true, true, 9.51f, 21.25f)
                verticalLineTo(15.75f)
                close()
                moveTo(11.01f, 18.00f)
                horizontalLineTo(11.76f)
                arcTo(0.75f, 0.75f, 0.00f, false, false, 11.76f, 16.50f)
                horizontalLineTo(11.01f)
                verticalLineTo(18.00f)
                close()
                moveTo(17.38f, 15.00f)
                arcTo(2.12f, 2.12f, 0.00f, false, false, 15.26f, 17.13f)
                curveTo(15.26f, 18.30f, 16.21f, 19.25f, 17.38f, 19.25f)
                horizontalLineTo(17.88f)
                arcTo(0.63f, 0.63f, 0.00f, false, true, 17.88f, 20.50f)
                horizontalLineTo(17.25f)
                arcTo(0.50f, 0.50f, 0.00f, false, true, 16.75f, 20.00f)
                arcTo(0.75f, 0.75f, 0.00f, true, false, 15.26f, 20.00f)
                curveTo(15.26f, 21.11f, 16.15f, 22.00f, 17.25f, 22.00f)
                horizontalLineTo(17.88f)
                arcTo(2.12f, 2.12f, 0.00f, false, false, 20.00f, 19.88f)
                curveTo(20.00f, 18.70f, 19.05f, 17.75f, 17.88f, 17.75f)
                horizontalLineTo(17.38f)
                arcTo(0.63f, 0.63f, 0.00f, false, true, 17.38f, 16.50f)
                horizontalLineTo(18.00f)
                arcTo(0.50f, 0.50f, 0.00f, false, true, 18.50f, 17.00f)
                arcTo(0.75f, 0.75f, 0.00f, true, false, 20.00f, 17.00f)
                curveTo(20.00f, 15.90f, 19.11f, 15.00f, 18.00f, 15.00f)
                horizontalLineTo(17.38f)
                close()
                moveTo(15.01f, 3.99f)
                arcTo(1.00f, 1.00f, 0.00f, true, false, 13.01f, 4.01f)
                lineTo(13.03f, 7.00f)
                horizontalLineTo(11.01f)
                verticalLineTo(4.00f)
                arcTo(1.00f, 1.00f, 0.00f, true, false, 9.01f, 4.00f)
                verticalLineTo(8.00f)
                arcTo(1.00f, 1.00f, 0.00f, false, false, 10.01f, 9.00f)
                horizontalLineTo(13.03f)
                verticalLineTo(12.00f)
                arcTo(1.00f, 1.00f, 0.00f, true, false, 15.03f, 12.00f)
                verticalLineTo(7.41f)
                curveTo(15.03f, 7.38f, 15.03f, 7.34f, 15.02f, 7.31f)
                lineTo(15.01f, 3.99f)
                close()
            }
        }.build()
        return _Fps0!!
    }

private var _Fps0: ImageVector? = null
