// Generated by XIcons
// 2025-08-17 11:04:21
package cn.enaium.xicons.compose.fluent

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.FluentIcons

public val FluentIcons.Filled.MailInboxDismiss: ImageVector
    get() {
        if (_MailInboxDismiss != null) {
            return _MailInboxDismiss!!
        }
        _MailInboxDismiss = ImageVector.Builder(
            name = "MailInboxDismiss",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(22.00f, 6.50f)
                arcTo(5.50f, 5.50f, 0.00f, true, true, 11.00f, 6.50f)
                arcTo(5.50f, 5.50f, 0.00f, false, true, 22.00f, 6.50f)
                close()
                moveTo(14.85f, 4.15f)
                arcTo(0.50f, 0.50f, 0.00f, false, false, 14.15f, 4.85f)
                lineTo(15.79f, 6.50f)
                lineTo(14.15f, 8.15f)
                arcTo(0.50f, 0.50f, 0.00f, false, false, 14.85f, 8.85f)
                lineTo(16.50f, 7.21f)
                lineTo(18.15f, 8.85f)
                arcTo(0.50f, 0.50f, 0.00f, false, false, 18.85f, 8.15f)
                lineTo(17.21f, 6.50f)
                lineTo(18.85f, 4.85f)
                arcTo(0.50f, 0.50f, 0.00f, false, false, 18.15f, 4.15f)
                lineTo(16.50f, 5.79f)
                lineTo(14.85f, 4.15f)
                close()
                moveTo(19.50f, 14.00f)
                verticalLineTo(12.27f)
                arcTo(6.52f, 6.52f, 0.00f, false, false, 21.00f, 11.19f)
                verticalLineTo(18.75f)
                arcTo(3.25f, 3.25f, 0.00f, false, true, 17.75f, 22.00f)
                horizontalLineTo(6.25f)
                arcTo(3.25f, 3.25f, 0.00f, false, true, 3.00f, 18.75f)
                verticalLineTo(7.25f)
                arcTo(3.25f, 3.25f, 0.00f, false, true, 6.25f, 4.00f)
                horizontalLineTo(10.50f)
                arcTo(6.45f, 6.45f, 0.00f, false, false, 10.08f, 5.50f)
                horizontalLineTo(6.25f)
                arcTo(1.75f, 1.75f, 0.00f, false, false, 4.50f, 7.25f)
                verticalLineTo(14.00f)
                horizontalLineTo(9.00f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 9.74f, 14.65f)
                lineTo(9.75f, 14.75f)
                arcTo(2.25f, 2.25f, 0.00f, false, false, 14.25f, 14.75f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 15.00f, 14.00f)
                horizontalLineTo(19.50f)
                close()
            }
        }.build()
        return _MailInboxDismiss!!
    }

private var _MailInboxDismiss: ImageVector? = null
