// Generated by XIcons
// 2025-08-17 11:04:21
package cn.enaium.xicons.compose.fluent

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.FluentIcons

public val FluentIcons.Filled.Microscope: ImageVector
    get() {
        if (_Microscope != null) {
            return _Microscope!!
        }
        _Microscope = ImageVector.Builder(
            name = "Microscope",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(8.00f, 2.75f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 8.75f, 2.00f)
                horizontalLineTo(10.25f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 11.00f, 2.75f)
                verticalLineTo(3.00f)
                horizontalLineTo(12.25f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 13.00f, 3.75f)
                verticalLineTo(5.54f)
                curveTo(13.01f, 5.54f, 13.02f, 5.54f, 13.03f, 5.54f)
                arcTo(8.25f, 8.25f, 0.00f, false, true, 16.99f, 20.50f)
                horizontalLineTo(20.25f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 20.25f, 22.00f)
                horizontalLineTo(3.75f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 3.75f, 20.50f)
                horizontalLineTo(12.28f)
                arcTo(6.75f, 6.75f, 0.00f, false, false, 13.00f, 7.04f)
                verticalLineTo(12.25f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 12.25f, 13.00f)
                horizontalLineTo(11.50f)
                verticalLineTo(14.00f)
                arcTo(2.00f, 2.00f, 0.00f, true, true, 7.50f, 14.00f)
                verticalLineTo(13.00f)
                horizontalLineTo(6.75f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 6.00f, 12.25f)
                verticalLineTo(3.75f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 6.75f, 3.00f)
                horizontalLineTo(8.00f)
                verticalLineTo(2.75f)
                close()
                moveTo(9.00f, 13.00f)
                verticalLineTo(14.00f)
                arcTo(0.50f, 0.50f, 0.00f, false, false, 10.00f, 14.00f)
                verticalLineTo(13.00f)
                horizontalLineTo(9.00f)
                close()
                moveTo(5.75f, 17.50f)
                arcTo(0.75f, 0.75f, 0.00f, false, false, 5.75f, 19.00f)
                horizontalLineTo(13.25f)
                arcTo(0.75f, 0.75f, 0.00f, false, false, 13.25f, 17.50f)
                horizontalLineTo(5.75f)
                close()
            }
        }.build()
        return _Microscope!!
    }

private var _Microscope: ImageVector? = null
