// Generated by XIcons
// 2025-08-17 11:04:21
package cn.enaium.xicons.compose.fluent

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.FluentIcons

public val FluentIcons.Filled.PersonSwap: ImageVector
    get() {
        if (_PersonSwap != null) {
            return _PersonSwap!!
        }
        _PersonSwap = ImageVector.Builder(
            name = "PersonSwap",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(15.75f, 14.00f)
                arcTo(2.25f, 2.25f, 0.00f, false, true, 18.00f, 16.25f)
                verticalLineTo(17.17f)
                curveTo(18.00f, 17.45f, 17.96f, 17.73f, 17.87f, 18.00f)
                horizontalLineTo(15.84f)
                arcTo(1.75f, 1.75f, 0.00f, false, false, 13.01f, 16.02f)
                lineTo(10.51f, 18.52f)
                arcTo(1.75f, 1.75f, 0.00f, false, false, 10.51f, 21.00f)
                lineTo(11.45f, 21.93f)
                curveTo(10.98f, 21.97f, 10.50f, 22.00f, 10.00f, 22.00f)
                curveTo(6.58f, 22.00f, 4.05f, 20.93f, 2.51f, 18.76f)
                arcTo(2.75f, 2.75f, 0.00f, false, true, 2.00f, 17.17f)
                verticalLineTo(16.25f)
                arcTo(2.25f, 2.25f, 0.00f, false, true, 4.25f, 14.00f)
                horizontalLineTo(15.75f)
                close()
                moveTo(10.00f, 2.00f)
                arcTo(5.00f, 5.00f, 0.00f, true, true, 10.00f, 12.00f)
                arcTo(5.00f, 5.00f, 0.00f, false, true, 10.00f, 2.00f)
                close()
                moveTo(14.78f, 17.78f)
                arcTo(0.75f, 0.75f, 0.00f, false, false, 13.72f, 16.72f)
                lineTo(11.22f, 19.22f)
                arcTo(0.75f, 0.75f, 0.00f, false, false, 11.22f, 20.28f)
                lineTo(13.72f, 22.78f)
                arcTo(0.75f, 0.75f, 0.00f, false, false, 14.78f, 21.72f)
                lineTo(13.56f, 20.50f)
                horizontalLineTo(20.44f)
                lineTo(19.22f, 21.72f)
                arcTo(0.75f, 0.75f, 0.00f, false, false, 20.28f, 22.78f)
                lineTo(22.78f, 20.28f)
                arcTo(0.75f, 0.75f, 0.00f, false, false, 22.78f, 19.22f)
                lineTo(20.28f, 16.72f)
                arcTo(0.75f, 0.75f, 0.00f, true, false, 19.22f, 17.78f)
                lineTo(20.44f, 19.00f)
                horizontalLineTo(13.56f)
                lineTo(14.78f, 17.78f)
                close()
            }
        }.build()
        return _PersonSwap!!
    }

private var _PersonSwap: ImageVector? = null
