// Generated by XIcons
// 2025-08-17 11:04:21
package cn.enaium.xicons.compose.fluent

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.FluentIcons

public val FluentIcons.Filled.PersonSupport: ImageVector
    get() {
        if (_PersonSupport != null) {
            return _PersonSupport!!
        }
        _PersonSupport = ImageVector.Builder(
            name = "PersonSupport",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(20.00f, 16.25f)
                arcTo(2.25f, 2.25f, 0.00f, false, false, 17.75f, 14.00f)
                horizontalLineTo(6.25f)
                arcTo(2.25f, 2.25f, 0.00f, false, false, 4.00f, 16.25f)
                verticalLineTo(17.17f)
                curveTo(4.00f, 17.74f, 4.18f, 18.30f, 4.51f, 18.76f)
                curveTo(6.05f, 20.93f, 8.58f, 22.00f, 12.00f, 22.00f)
                curveTo(15.42f, 22.00f, 17.94f, 20.93f, 19.49f, 18.76f)
                arcTo(2.75f, 2.75f, 0.00f, false, false, 20.00f, 17.17f)
                verticalLineTo(16.25f)
                close()
                moveTo(17.00f, 7.00f)
                arcTo(5.00f, 5.00f, 0.00f, false, false, 7.97f, 4.03f)
                arcTo(0.75f, 0.75f, 0.00f, false, false, 7.75f, 4.00f)
                horizontalLineTo(5.25f)
                arcTo(0.75f, 0.75f, 0.00f, false, false, 4.50f, 4.75f)
                verticalLineTo(10.25f)
                arcTo(2.75f, 2.75f, 0.00f, false, false, 7.25f, 13.00f)
                horizontalLineTo(7.50f)
                verticalLineTo(13.00f)
                horizontalLineTo(7.51f)
                arcTo(1.00f, 1.00f, 0.00f, true, false, 6.72f, 11.39f)
                arcTo(1.25f, 1.25f, 0.00f, false, true, 6.00f, 10.25f)
                verticalLineTo(10.00f)
                horizontalLineTo(6.75f)
                curveTo(7.13f, 10.00f, 7.48f, 9.88f, 7.77f, 9.67f)
                arcTo(5.00f, 5.00f, 0.00f, false, false, 17.00f, 7.00f)
                close()
                moveTo(7.00f, 6.90f)
                arcTo(5.11f, 5.11f, 0.00f, false, false, 7.00f, 7.11f)
                verticalLineTo(8.25f)
                arcTo(0.25f, 0.25f, 0.00f, false, true, 6.75f, 8.50f)
                horizontalLineTo(6.00f)
                verticalLineTo(5.50f)
                horizontalLineTo(7.00f)
                verticalLineTo(6.90f)
                close()
            }
        }.build()
        return _PersonSupport!!
    }

private var _PersonSupport: ImageVector? = null
