// Generated by XIcons
// 2025-08-17 11:04:24
package cn.enaium.xicons.compose.fluent

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.FluentIcons

public val FluentIcons.Filled.StarThreeQuarter: ImageVector
    get() {
        if (_StarThreeQuarter != null) {
            return _StarThreeQuarter!!
        }
        _StarThreeQuarter = ImageVector.Builder(
            name = "StarThreeQuarter",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(13.21f, 3.10f)
                lineTo(15.00f, 6.73f)
                verticalLineTo(6.73f)
                lineTo(15.57f, 7.88f)
                lineTo(20.84f, 8.65f)
                curveTo(21.95f, 8.81f, 22.39f, 10.17f, 21.59f, 10.95f)
                lineTo(17.77f, 14.67f)
                lineTo(18.67f, 19.92f)
                curveTo(18.86f, 21.02f, 17.71f, 21.86f, 16.71f, 21.34f)
                lineTo(12.00f, 18.86f)
                lineTo(7.29f, 21.34f)
                arcTo(1.34f, 1.34f, 0.00f, false, true, 6.66f, 21.50f)
                curveTo(5.87f, 21.50f, 5.18f, 20.79f, 5.33f, 19.92f)
                lineTo(6.23f, 14.67f)
                lineTo(2.41f, 10.95f)
                curveTo(1.61f, 10.17f, 2.05f, 8.81f, 3.16f, 8.65f)
                lineTo(8.43f, 7.88f)
                lineTo(10.79f, 3.10f)
                curveTo(11.04f, 2.60f, 11.52f, 2.35f, 12.00f, 2.35f)
                curveTo(12.48f, 2.35f, 12.96f, 2.60f, 13.21f, 3.10f)
                close()
                moveTo(15.00f, 9.28f)
                verticalLineTo(18.75f)
                lineTo(17.14f, 19.87f)
                lineTo(16.28f, 14.84f)
                arcTo(1.35f, 1.35f, 0.00f, false, true, 16.67f, 13.65f)
                lineTo(20.32f, 10.09f)
                lineTo(15.27f, 9.35f)
                arcTo(1.35f, 1.35f, 0.00f, false, true, 15.00f, 9.28f)
                close()
            }
        }.build()
        return _StarThreeQuarter!!
    }

private var _StarThreeQuarter: ImageVector? = null
