// Generated by XIcons
// 2025-08-17 11:04:25
package cn.enaium.xicons.compose.fluent

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.FluentIcons

public val FluentIcons.Filled.TextIndentIncreaseLtr: ImageVector
    get() {
        if (_TextIndentIncreaseLtr != null) {
            return _TextIndentIncreaseLtr!!
        }
        _TextIndentIncreaseLtr = ImageVector.Builder(
            name = "TextIndentIncreaseLtr",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(9.00f, 16.00f)
                horizontalLineTo(17.50f)
                arcTo(1.00f, 1.00f, 0.00f, false, true, 17.62f, 17.99f)
                lineTo(17.50f, 18.00f)
                horizontalLineTo(9.00f)
                arcTo(1.00f, 1.00f, 0.00f, false, true, 8.88f, 16.01f)
                lineTo(9.00f, 16.00f)
                horizontalLineTo(17.50f)
                horizontalLineTo(9.00f)
                close()
                moveTo(2.29f, 9.29f)
                arcTo(1.00f, 1.00f, 0.00f, false, true, 3.61f, 9.21f)
                lineTo(3.71f, 9.29f)
                lineTo(5.71f, 11.29f)
                arcTo(1.00f, 1.00f, 0.00f, false, true, 5.79f, 12.61f)
                lineTo(5.71f, 12.71f)
                lineTo(3.71f, 14.71f)
                arcTo(1.00f, 1.00f, 0.00f, false, true, 2.21f, 13.39f)
                lineTo(2.29f, 13.29f)
                lineTo(3.59f, 12.00f)
                lineTo(2.29f, 10.71f)
                arcTo(1.00f, 1.00f, 0.00f, false, true, 2.29f, 9.29f)
                close()
                moveTo(9.00f, 11.00f)
                lineTo(20.50f, 11.00f)
                arcTo(1.00f, 1.00f, 0.00f, false, true, 20.62f, 12.99f)
                lineTo(20.50f, 13.00f)
                lineTo(9.00f, 13.00f)
                arcTo(1.00f, 1.00f, 0.00f, false, true, 8.88f, 11.01f)
                lineTo(9.00f, 11.00f)
                lineTo(20.50f, 11.00f)
                lineTo(9.00f, 11.00f)
                close()
                moveTo(9.00f, 6.00f)
                horizontalLineTo(17.50f)
                arcTo(1.00f, 1.00f, 0.00f, false, true, 17.62f, 7.99f)
                lineTo(17.50f, 8.00f)
                horizontalLineTo(9.00f)
                arcTo(1.00f, 1.00f, 0.00f, false, true, 8.88f, 6.01f)
                lineTo(9.00f, 6.00f)
                horizontalLineTo(17.50f)
                horizontalLineTo(9.00f)
                close()
            }
        }.build()
        return _TextIndentIncreaseLtr!!
    }

private var _TextIndentIncreaseLtr: ImageVector? = null
