// Generated by XIcons
// 2025-08-17 11:04:25
package cn.enaium.xicons.compose.fluent

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.FluentIcons

public val FluentIcons.Regular.TextIndentDecreaseLtr: ImageVector
    get() {
        if (_TextIndentDecreaseLtr != null) {
            return _TextIndentDecreaseLtr!!
        }
        _TextIndentDecreaseLtr = ImageVector.Builder(
            name = "TextIndentDecreaseLtr",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(17.75f, 16.00f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 17.75f, 17.50f)
                horizontalLineTo(8.75f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 8.75f, 16.00f)
                horizontalLineTo(17.75f)
                close()
                moveTo(2.72f, 11.22f)
                lineTo(4.72f, 9.22f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 5.85f, 10.20f)
                lineTo(5.78f, 10.28f)
                lineTo(4.31f, 11.75f)
                lineTo(5.78f, 13.22f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 4.80f, 14.35f)
                lineTo(4.72f, 14.28f)
                lineTo(2.72f, 12.28f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 2.65f, 11.30f)
                lineTo(2.72f, 11.22f)
                lineTo(4.72f, 9.22f)
                lineTo(2.72f, 11.22f)
                close()
                moveTo(20.75f, 11.00f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 20.75f, 12.50f)
                horizontalLineTo(8.75f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 8.75f, 11.00f)
                horizontalLineTo(20.75f)
                close()
                moveTo(17.75f, 6.00f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 17.75f, 7.50f)
                horizontalLineTo(8.75f)
                arcTo(0.75f, 0.75f, 0.00f, false, true, 8.75f, 6.00f)
                horizontalLineTo(17.75f)
                close()
            }
        }.build()
        return _TextIndentDecreaseLtr!!
    }

private var _TextIndentDecreaseLtr: ImageVector? = null
