// Generated by XIcons
// 2025-08-14 22:09:23
package cn.enaium.xicons.jfx.icons.material;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class AddBoxRound extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(19.00, 3.00);
        path.horizontalLineTo(5.00);
        path.arcTo(2.00, 2.00, 0.00, false, false, 3.00, 5.00);
        path.verticalLineTo(19.00);
        path.arcTo(2.00, 2.00, 0.00, false, false, 5.00, 21.00);
        path.horizontalLineTo(19.00);
        path.curveTo(20.10, 21.00, 21.00, 20.10, 21.00, 19.00);
        path.verticalLineTo(5.00);
        path.curveTo(21.00, 3.90, 20.10, 3.00, 19.00, 3.00);
        path.close();
        path.moveTo(16.00, 13.00);
        path.horizontalLineTo(13.00);
        path.verticalLineTo(16.00);
        path.curveTo(13.00, 16.55, 12.55, 17.00, 12.00, 17.00);
        path.curveTo(11.45, 17.00, 11.00, 16.55, 11.00, 16.00);
        path.verticalLineTo(13.00);
        path.horizontalLineTo(8.00);
        path.curveTo(7.45, 13.00, 7.00, 12.55, 7.00, 12.00);
        path.curveTo(7.00, 11.45, 7.45, 11.00, 8.00, 11.00);
        path.horizontalLineTo(11.00);
        path.verticalLineTo(8.00);
        path.curveTo(11.00, 7.45, 11.45, 7.00, 12.00, 7.00);
        path.curveTo(12.55, 7.00, 13.00, 7.45, 13.00, 8.00);
        path.verticalLineTo(11.00);
        path.horizontalLineTo(16.00);
        path.curveTo(16.55, 11.00, 17.00, 11.45, 17.00, 12.00);
        path.curveTo(17.00, 12.55, 16.55, 13.00, 16.00, 13.00);
        path.close();
        return path;
    }
}
