// Generated by XIcons
// 2025-08-14 22:09:24
package cn.enaium.xicons.jfx.icons.material;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class AllInclusiveRound extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(20.22, 6.86);
        path.curveTo(18.22, 6.26, 16.16, 6.82, 14.83, 8.15);
        path.lineTo(12.00, 10.66);
        path.lineTo(10.48, 12.00);
        path.horizontalLineTo(10.49);
        path.lineTo(7.80, 14.39);
        path.curveTo(6.99, 15.20, 5.85, 15.54, 4.68, 15.31);
        path.arcTo(3.35, 3.35, 0.00, false, true, 2.11, 12.82);
        path.arcTo(3.39, 3.39, 0.00, false, true, 5.40, 8.62);
        path.curveTo(6.31, 8.62, 7.16, 8.97, 7.84, 9.65);
        path.lineTo(8.31, 10.06);
        path.curveTo(8.69, 10.40, 9.26, 10.40, 9.64, 10.06);
        path.curveTo(10.09, 9.66, 10.09, 8.96, 9.64, 8.56);
        path.lineTo(9.22, 8.20);
        path.arcTo(5.37, 5.37, 0.00, false, false, 5.40, 6.62);
        path.curveTo(2.42, 6.62, 0.00, 9.04, 0.00, 12.00);
        path.curveTo(0.00, 14.96, 2.42, 17.38, 5.40, 17.38);
        path.curveTo(6.84, 17.38, 8.20, 16.82, 9.17, 15.85);
        path.lineTo(12.00, 13.35);
        path.lineTo(12.01, 13.36);
        path.lineTo(13.52, 12.00);
        path.horizontalLineTo(13.51);
        path.lineTo(16.20, 9.61);
        path.curveTo(17.01, 8.80, 18.15, 8.46, 19.32, 8.69);
        path.curveTo(20.57, 8.94, 21.60, 9.94, 21.89, 11.18);
        path.arcTo(3.39, 3.39, 0.00, false, true, 18.60, 15.38);
        path.curveTo(17.70, 15.38, 16.84, 15.03, 16.16, 14.35);
        path.lineTo(15.68, 13.93);
        path.arcTo(1.00, 1.00, 0.00, false, false, 14.35, 13.93);
        path.curveTo(13.90, 14.33, 13.90, 15.03, 14.35, 15.43);
        path.lineTo(14.77, 15.80);
        path.arcTo(5.39, 5.39, 0.00, false, false, 18.59, 17.37);
        path.curveTo(21.86, 17.37, 24.45, 14.47, 23.92, 11.12);
        path.curveTo(23.62, 9.13, 22.15, 7.43, 20.22, 6.86);
        path.close();
        return path;
    }
}
