// Generated by XIcons
// 2025-08-14 22:09:26
package cn.enaium.xicons.jfx.icons.material;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class CloudQueueOutlined extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(19.35, 10.04);
        path.arcTo(7.49, 7.49, 0.00, false, false, 12.00, 4.00);
        path.curveTo(9.11, 4.00, 6.60, 5.64, 5.35, 8.04);
        path.arcTo(5.99, 5.99, 0.00, false, false, 0.00, 14.00);
        path.curveTo(0.00, 17.31, 2.69, 20.00, 6.00, 20.00);
        path.horizontalLineTo(19.00);
        path.curveTo(21.76, 20.00, 24.00, 17.76, 24.00, 15.00);
        path.curveTo(24.00, 12.36, 21.95, 10.22, 19.35, 10.04);
        path.close();
        path.moveTo(19.00, 18.00);
        path.horizontalLineTo(6.00);
        path.curveTo(3.79, 18.00, 2.00, 16.21, 2.00, 14.00);
        path.curveTo(2.00, 11.79, 3.79, 10.00, 6.00, 10.00);
        path.horizontalLineTo(6.71);
        path.curveTo(7.37, 7.69, 9.48, 6.00, 12.00, 6.00);
        path.curveTo(15.04, 6.00, 17.50, 8.46, 17.50, 11.50);
        path.verticalLineTo(12.00);
        path.horizontalLineTo(19.00);
        path.curveTo(20.66, 12.00, 22.00, 13.34, 22.00, 15.00);
        path.curveTo(22.00, 16.66, 20.66, 18.00, 19.00, 18.00);
        path.close();
        return path;
    }
}
