// Generated by XIcons
// 2025-08-14 22:09:29
package cn.enaium.xicons.jfx.icons.material;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class FlagRound extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(14.40, 6.00);
        path.lineTo(14.16, 4.80);
        path.curveTo(14.07, 4.34, 13.66, 4.00, 13.18, 4.00);
        path.horizontalLineTo(6.00);
        path.curveTo(5.45, 4.00, 5.00, 4.45, 5.00, 5.00);
        path.verticalLineTo(20.00);
        path.curveTo(5.00, 20.55, 5.45, 21.00, 6.00, 21.00);
        path.curveTo(6.55, 21.00, 7.00, 20.55, 7.00, 20.00);
        path.verticalLineTo(14.00);
        path.horizontalLineTo(12.60);
        path.lineTo(12.84, 15.20);
        path.curveTo(12.93, 15.67, 13.34, 16.00, 13.82, 16.00);
        path.horizontalLineTo(19.00);
        path.curveTo(19.55, 16.00, 20.00, 15.55, 20.00, 15.00);
        path.verticalLineTo(7.00);
        path.curveTo(20.00, 6.45, 19.55, 6.00, 19.00, 6.00);
        path.horizontalLineTo(14.40);
        path.close();
        return path;
    }
}
