// Generated by XIcons
// 2025-08-14 22:09:30
package cn.enaium.xicons.jfx.icons.material;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class HotelClassTwotone extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(11.00, 8.89);
        path.lineTo(11.94, 12.00);
        path.horizontalLineTo(14.76);
        path.lineTo(12.49, 13.62);
        path.lineTo(13.42, 16.63);
        path.lineTo(11.00, 14.79);
        path.lineTo(8.58, 16.63);
        path.lineTo(9.51, 13.62);
        path.lineTo(7.24, 12.00);
        path.horizontalLineTo(10.06);
        path.close();
        path.moveTo(11.00, 8.89);
        path.lineTo(11.94, 12.00);
        path.horizontalLineTo(14.76);
        path.lineTo(12.49, 13.62);
        path.lineTo(13.42, 16.63);
        path.lineTo(11.00, 14.79);
        path.lineTo(8.58, 16.63);
        path.lineTo(9.51, 13.62);
        path.lineTo(7.24, 12.00);
        path.horizontalLineTo(10.06);
        path.lineTo(11.00, 8.89);
        path.close();
        path.moveTo(8.58, 10.00);
        path.horizontalLineTo(1.00);
        path.lineTo(7.17, 14.41);
        path.lineTo(4.83, 22.00);
        path.lineTo(11.00, 17.31);
        path.lineTo(17.18, 22.00);
        path.lineTo(14.83, 14.41);
        path.lineTo(21.00, 10.00);
        path.horizontalLineTo(13.42);
        path.lineTo(11.00, 2.00);
        path.lineTo(8.58, 10.00);
        path.close();
        path.moveTo(21.36, 22.00);
        path.lineTo(19.50, 15.99);
        path.lineTo(23.68, 13.00);
        path.horizontalLineTo(20.24);
        path.lineTo(17.16, 15.20);
        path.lineTo(18.62, 19.92);
        path.lineTo(21.36, 22.00);
        path.close();
        path.moveTo(17.00, 8.00);
        path.lineTo(15.18, 2.00);
        path.lineTo(14.14, 5.45);
        path.lineTo(14.91, 8.00);
        path.horizontalLineTo(17.00);
        path.close();
        return path;
    }
}
