// Generated by XIcons
// 2025-08-14 22:09:33
package cn.enaium.xicons.jfx.icons.material;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class LockClockTwotone extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(11.29, 20.00);
        path.horizontalLineTo(6.00);
        path.verticalLineTo(10.00);
        path.horizontalLineTo(18.00);
        path.verticalLineTo(11.00);
        path.curveTo(18.70, 11.00, 19.37, 11.10, 20.00, 11.29);
        path.verticalLineTo(10.00);
        path.curveTo(20.00, 8.90, 19.10, 8.00, 18.00, 8.00);
        path.horizontalLineTo(17.00);
        path.verticalLineTo(6.00);
        path.curveTo(17.00, 3.24, 14.76, 1.00, 12.00, 1.00);
        path.curveTo(9.24, 1.00, 7.00, 3.24, 7.00, 6.00);
        path.verticalLineTo(8.00);
        path.horizontalLineTo(6.00);
        path.curveTo(4.90, 8.00, 4.00, 8.90, 4.00, 10.00);
        path.verticalLineTo(20.00);
        path.curveTo(4.00, 21.10, 4.90, 22.00, 6.00, 22.00);
        path.horizontalLineTo(12.26);
        path.curveTo(11.84, 21.40, 11.51, 20.72, 11.29, 20.00);
        path.close();
        path.moveTo(9.00, 6.00);
        path.curveTo(9.00, 4.34, 10.34, 3.00, 12.00, 3.00);
        path.curveTo(13.66, 3.00, 15.00, 4.34, 15.00, 6.00);
        path.verticalLineTo(8.00);
        path.horizontalLineTo(9.00);
        path.verticalLineTo(6.00);
        path.close();
        path.moveTo(11.00, 18.00);
        path.curveTo(11.00, 14.13, 14.13, 11.00, 18.00, 11.00);
        path.verticalLineTo(10.00);
        path.horizontalLineTo(6.00);
        path.verticalLineTo(20.00);
        path.horizontalLineTo(11.29);
        path.curveTo(11.10, 19.37, 11.00, 18.70, 11.00, 18.00);
        path.close();
        path.moveTo(18.00, 13.00);
        path.curveTo(15.24, 13.00, 13.00, 15.24, 13.00, 18.00);
        path.curveTo(13.00, 20.76, 15.24, 23.00, 18.00, 23.00);
        path.curveTo(20.76, 23.00, 23.00, 20.76, 23.00, 18.00);
        path.curveTo(23.00, 15.24, 20.76, 13.00, 18.00, 13.00);
        path.close();
        path.moveTo(19.65, 20.35);
        path.lineTo(17.50, 18.20);
        path.verticalLineTo(15.00);
        path.horizontalLineTo(18.50);
        path.verticalLineTo(17.79);
        path.lineTo(20.35, 19.64);
        path.lineTo(19.65, 20.35);
        path.close();
        return path;
    }
}
