// Generated by XIcons
// 2025-08-14 22:09:33
package cn.enaium.xicons.jfx.icons.material;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class Md17MpSharp extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(3.00, 3.00);
        path.verticalLineTo(21.00);
        path.horizontalLineTo(21.00);
        path.verticalLineTo(3.00);
        path.horizontalLineTo(3.00);
        path.close();
        path.moveTo(7.00, 5.50);
        path.horizontalLineTo(10.00);
        path.verticalLineTo(11.50);
        path.horizontalLineTo(8.50);
        path.verticalLineTo(7.00);
        path.horizontalLineTo(7.00);
        path.verticalLineTo(5.50);
        path.close();
        path.moveTo(12.50, 18.50);
        path.horizontalLineTo(11.00);
        path.verticalLineTo(14.00);
        path.horizontalLineTo(10.00);
        path.verticalLineTo(17.00);
        path.horizontalLineTo(8.50);
        path.verticalLineTo(14.00);
        path.horizontalLineTo(7.50);
        path.verticalLineTo(18.50);
        path.horizontalLineTo(6.00);
        path.verticalLineTo(12.50);
        path.horizontalLineTo(12.50);
        path.verticalLineTo(18.50);
        path.close();
        path.moveTo(12.00, 7.00);
        path.verticalLineTo(5.50);
        path.horizontalLineTo(16.87);
        path.lineTo(15.00, 11.50);
        path.horizontalLineTo(13.25);
        path.lineTo(14.62, 7.00);
        path.horizontalLineTo(12.00);
        path.close();
        path.moveTo(18.00, 17.00);
        path.horizontalLineTo(15.00);
        path.verticalLineTo(18.50);
        path.horizontalLineTo(13.50);
        path.verticalLineTo(12.50);
        path.horizontalLineTo(18.00);
        path.verticalLineTo(17.00);
        path.close();
        path.moveTo(15.00, 14.00);
        path.horizontalLineTo(16.50);
        path.verticalLineTo(15.50);
        path.horizontalLineTo(15.00);
        path.close();
        return path;
    }
}
