// Generated by XIcons
// 2025-08-14 22:09:34
package cn.enaium.xicons.jfx.icons.material;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class MonochromePhotosRound extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(20.00, 5.00);
        path.horizontalLineTo(16.80);
        path.lineTo(15.60, 3.66);
        path.curveTo(15.22, 3.24, 14.68, 3.00, 14.11, 3.00);
        path.horizontalLineTo(9.89);
        path.curveTo(9.32, 3.00, 8.78, 3.24, 8.40, 3.66);
        path.lineTo(7.20, 5.00);
        path.horizontalLineTo(4.00);
        path.curveTo(2.90, 5.00, 2.00, 5.90, 2.00, 7.00);
        path.verticalLineTo(19.00);
        path.curveTo(2.00, 20.10, 2.90, 21.00, 4.00, 21.00);
        path.horizontalLineTo(20.00);
        path.curveTo(21.10, 21.00, 22.00, 20.10, 22.00, 19.00);
        path.verticalLineTo(7.00);
        path.curveTo(22.00, 5.90, 21.10, 5.00, 20.00, 5.00);
        path.close();
        path.moveTo(20.00, 18.00);
        path.curveTo(20.00, 18.55, 19.55, 19.00, 19.00, 19.00);
        path.horizontalLineTo(12.00);
        path.verticalLineTo(18.00);
        path.curveTo(9.20, 18.00, 7.00, 15.80, 7.00, 13.00);
        path.curveTo(7.00, 10.20, 9.20, 8.00, 12.00, 8.00);
        path.verticalLineTo(7.00);
        path.horizontalLineTo(19.00);
        path.curveTo(19.55, 7.00, 20.00, 7.45, 20.00, 8.00);
        path.verticalLineTo(18.00);
        path.close();
        path.moveTo(17.00, 13.00);
        path.curveTo(17.00, 10.20, 14.80, 8.00, 12.00, 8.00);
        path.verticalLineTo(9.80);
        path.curveTo(13.80, 9.80, 15.20, 11.20, 15.20, 13.00);
        path.curveTo(15.20, 14.80, 13.80, 16.20, 12.00, 16.20);
        path.verticalLineTo(18.00);
        path.curveTo(14.80, 18.00, 17.00, 15.80, 17.00, 13.00);
        path.close();
        path.moveTo(8.80, 13.00);
        path.curveTo(8.80, 14.80, 10.20, 16.20, 12.00, 16.20);
        path.verticalLineTo(9.80);
        path.curveTo(10.20, 9.80, 8.80, 11.20, 8.80, 13.00);
        path.close();
        return path;
    }
}
