// Generated by XIcons
// 2025-08-14 22:09:37
package cn.enaium.xicons.jfx.icons.material;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class PieChartOutlined extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(12.00, 2.00);
        path.curveTo(6.48, 2.00, 2.00, 6.48, 2.00, 12.00);
        path.curveTo(2.00, 17.52, 6.48, 22.00, 12.00, 22.00);
        path.curveTo(17.52, 22.00, 22.00, 17.52, 22.00, 12.00);
        path.curveTo(22.00, 6.48, 17.52, 2.00, 12.00, 2.00);
        path.close();
        path.moveTo(19.93, 11.00);
        path.horizontalLineTo(13.00);
        path.verticalLineTo(4.07);
        path.curveTo(16.61, 4.52, 19.48, 7.39, 19.93, 11.00);
        path.close();
        path.moveTo(4.00, 12.00);
        path.curveTo(4.00, 7.93, 7.06, 4.56, 11.00, 4.07);
        path.verticalLineTo(19.93);
        path.curveTo(7.06, 19.44, 4.00, 16.07, 4.00, 12.00);
        path.close();
        path.moveTo(13.00, 19.93);
        path.verticalLineTo(13.00);
        path.horizontalLineTo(19.93);
        path.arcTo(8.00, 8.00, 0.00, false, true, 13.00, 19.93);
        path.close();
        return path;
    }
}
