// Generated by XIcons
// 2025-08-14 22:09:43
package cn.enaium.xicons.jfx.icons.material;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class SyncDisabledSharp extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(10.00, 6.35);
        path.verticalLineTo(4.26);
        path.curveTo(9.34, 4.43, 8.71, 4.69, 8.12, 5.01);
        path.lineTo(9.62, 6.51);
        path.curveTo(9.75, 6.46, 9.87, 6.40, 10.00, 6.35);
        path.close();
        path.moveTo(20.00, 12.00);
        path.curveTo(20.00, 9.79, 19.09, 7.80, 17.64, 6.36);
        path.lineTo(20.00, 4.00);
        path.horizontalLineTo(14.00);
        path.verticalLineTo(10.00);
        path.lineTo(16.24, 7.76);
        path.arcTo(6.00, 6.00, 0.00, false, true, 18.00, 12.00);
        path.curveTo(18.00, 12.85, 17.81, 13.65, 17.49, 14.38);
        path.lineTo(18.99, 15.88);
        path.arcTo(7.92, 7.92, 0.00, false, false, 20.00, 12.00);
        path.close();
        path.moveTo(4.27, 4.00);
        path.lineTo(2.86, 5.41);
        path.lineTo(5.22, 7.77);
        path.arcTo(7.93, 7.93, 0.00, false, false, 6.36, 17.64);
        path.lineTo(4.00, 20.00);
        path.horizontalLineTo(10.00);
        path.verticalLineTo(14.00);
        path.lineTo(7.76, 16.24);
        path.arcTo(6.00, 6.00, 0.00, false, true, 6.00, 12.00);
        path.curveTo(6.00, 11.00, 6.25, 10.06, 6.68, 9.23);
        path.lineTo(14.76, 17.31);
        path.curveTo(14.51, 17.44, 14.26, 17.55, 14.00, 17.65);
        path.verticalLineTo(19.74);
        path.curveTo(14.80, 19.53, 15.55, 19.20, 16.23, 18.78);
        path.lineTo(18.81, 21.36);
        path.lineTo(20.22, 19.95);
        path.lineTo(4.27, 4.00);
        path.close();
        return path;
    }
}
