// Generated by XIcons
// 2025-08-14 22:09:43
package cn.enaium.xicons.jfx.icons.material;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class TrackChangesRound extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(18.32, 5.68);
        path.curveTo(17.96, 6.04, 17.93, 6.60, 18.25, 7.00);
        path.curveTo(19.70, 8.82, 20.46, 11.31, 19.78, 13.92);
        path.curveTo(18.99, 16.97, 16.60, 19.25, 13.57, 19.86);
        path.curveTo(8.47, 20.87, 4.00, 16.93, 4.00, 12.00);
        path.curveTo(4.00, 7.92, 7.05, 4.56, 11.00, 4.07);
        path.verticalLineTo(6.09);
        path.arcTo(6.00, 6.00, 0.00, false, false, 6.07, 12.92);
        path.curveTo(6.46, 15.53, 8.63, 17.63, 11.25, 17.95);
        path.arcTo(6.00, 6.00, 0.00, false, false, 16.97, 8.64);
        path.curveTo(16.63, 8.14, 15.90, 8.11, 15.47, 8.53);
        path.lineTo(15.46, 8.54);
        path.curveTo(15.12, 8.88, 15.09, 9.41, 15.35, 9.81);
        path.curveTo(15.95, 10.73, 16.19, 11.91, 15.84, 13.13);
        path.arcTo(3.99, 3.99, 0.00, false, true, 12.90, 15.90);
        path.arcTo(4.00, 4.00, 0.00, false, true, 8.00, 12.00);
        path.curveTo(8.00, 10.14, 9.28, 8.59, 11.00, 8.14);
        path.verticalLineTo(10.28);
        path.curveTo(10.40, 10.63, 10.00, 11.26, 10.00, 12.00);
        path.curveTo(10.00, 13.10, 10.90, 14.00, 12.00, 14.00);
        path.curveTo(13.10, 14.00, 14.00, 13.10, 14.00, 12.00);
        path.curveTo(14.00, 11.26, 13.60, 10.62, 13.00, 10.28);
        path.verticalLineTo(2.71);
        path.curveTo(13.00, 2.32, 12.68, 2.00, 12.29, 2.00);
        path.curveTo(6.93, 1.80, 2.31, 6.06, 2.02, 11.40);
        path.curveTo(1.66, 17.95, 7.43, 23.22, 14.03, 21.80);
        path.curveTo(17.91, 20.97, 20.91, 18.00, 21.78, 14.13);
        path.curveTo(22.49, 10.97, 21.58, 7.97, 19.81, 5.76);
        path.arcTo(1.00, 1.00, 0.00, false, false, 18.32, 5.68);
        path.close();
        return path;
    }
}
