// Generated by XIcons
// 2025-08-17 11:04:29
package cn.enaium.xicons.compose.ionicons5

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.Ionicons5Icons

public val Ionicons5Icons.Default.BowlingBallOutline: ImageVector
    get() {
        if (_BowlingBallOutline != null) {
            return _BowlingBallOutline!!
        }
        _BowlingBallOutline = ImageVector.Builder(
            name = "BowlingBallOutline",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.046875f, scaleY = 0.046875f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                }
            }
        }.build()
        return _BowlingBallOutline!!
    }

private var _BowlingBallOutline: ImageVector? = null
