// Generated by XIcons
// 2025-08-17 11:04:29
package cn.enaium.xicons.compose.ionicons5

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.Ionicons5Icons

public val Ionicons5Icons.Default.Chatbox: ImageVector
    get() {
        if (_Chatbox != null) {
            return _Chatbox!!
        }
        _Chatbox = ImageVector.Builder(
            name = "Chatbox",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.046875f, scaleY = 0.046875f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(144.00f, 464.00f)
                    arcTo(16.00f, 16.00f, 0.00f, false, true, 128.00f, 448.00f)
                    verticalLineTo(384.00f)
                    horizontalLineTo(104.00f)
                    arcTo(72.08f, 72.08f, 0.00f, false, true, 32.00f, 312.00f)
                    verticalLineTo(120.00f)
                    arcTo(72.08f, 72.08f, 0.00f, false, true, 104.00f, 48.00f)
                    horizontalLineTo(408.00f)
                    arcTo(72.08f, 72.08f, 0.00f, false, true, 480.00f, 120.00f)
                    verticalLineTo(312.00f)
                    arcTo(72.08f, 72.08f, 0.00f, false, true, 408.00f, 384.00f)
                    horizontalLineTo(245.74f)
                    lineTo(154.25f, 460.29f)
                    arcTo(16.05f, 16.05f, 0.00f, false, true, 144.00f, 464.00f)
                    close()
                }
            }
        }.build()
        return _Chatbox!!
    }

private var _Chatbox: ImageVector? = null
