// Generated by XIcons
// 2025-08-17 11:04:30
package cn.enaium.xicons.compose.ionicons5

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.Ionicons5Icons

public val Ionicons5Icons.Default.Enter: ImageVector
    get() {
        if (_Enter != null) {
            return _Enter!!
        }
        _Enter = ImageVector.Builder(
            name = "Enter",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.046875f, scaleY = 0.046875f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(160.00f, 136.00f)
                    verticalLineTo(240.00f)
                    horizontalLineTo(313.37f)
                    lineTo(260.69f, 187.31f)
                    arcTo(16.00f, 16.00f, 0.00f, false, true, 283.31f, 164.69f)
                    lineTo(363.31f, 244.69f)
                    arcTo(16.00f, 16.00f, 0.00f, false, true, 363.31f, 267.31f)
                    lineTo(283.31f, 347.31f)
                    arcTo(16.00f, 16.00f, 0.00f, false, true, 260.69f, 324.69f)
                    lineTo(313.37f, 272.00f)
                    horizontalLineTo(160.00f)
                    verticalLineTo(376.00f)
                    arcTo(56.06f, 56.06f, 0.00f, false, false, 216.00f, 432.00f)
                    horizontalLineTo(424.00f)
                    arcTo(56.06f, 56.06f, 0.00f, false, false, 480.00f, 376.00f)
                    verticalLineTo(136.00f)
                    arcTo(56.06f, 56.06f, 0.00f, false, false, 424.00f, 80.00f)
                    horizontalLineTo(216.00f)
                    arcTo(56.06f, 56.06f, 0.00f, false, false, 160.00f, 136.00f)
                    close()
                    moveTo(48.00f, 240.00f)
                    arcTo(16.00f, 16.00f, 0.00f, false, false, 48.00f, 272.00f)
                    horizontalLineTo(160.00f)
                    verticalLineTo(240.00f)
                    close()
                }
            }
        }.build()
        return _Enter!!
    }

private var _Enter: ImageVector? = null
