// Generated by XIcons
// 2025-08-17 11:04:30
package cn.enaium.xicons.compose.ionicons5

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.Ionicons5Icons

public val Ionicons5Icons.Default.FastFoodOutline: ImageVector
    get() {
        if (_FastFoodOutline != null) {
            return _FastFoodOutline!!
        }
        _FastFoodOutline = ImageVector.Builder(
            name = "FastFoodOutline",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.046875f, scaleY = 0.046875f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(322.00f, 416.00f)
                    curveTo(322.00f, 451.35f, 301.35f, 480.00f, 266.00f, 480.00f)
                    horizontalLineTo(134.00f)
                    curveTo(98.65f, 480.00f, 78.00f, 451.35f, 78.00f, 416.00f)
                    moveTo(336.00f, 336.00f)
                    curveTo(353.67f, 336.00f, 368.00f, 353.91f, 368.00f, 376.00f)
                    horizontalLineTo(368.00f)
                    curveTo(368.00f, 398.09f, 353.67f, 416.00f, 336.00f, 416.00f)
                    horizontalLineTo(64.00f)
                    curveTo(46.33f, 416.00f, 32.00f, 398.09f, 32.00f, 376.00f)
                    horizontalLineTo(32.00f)
                    curveTo(32.00f, 353.91f, 46.33f, 336.00f, 64.00f, 336.00f)
                    moveTo(344.00f, 336.00f)
                    horizontalLineTo(179.31f)
                    arcTo(8.00f, 8.00f, 0.00f, false, false, 173.66f, 338.34f)
                    lineTo(146.83f, 365.17f)
                    arcTo(4.00f, 4.00f, 0.00f, false, true, 141.17f, 365.17f)
                    lineTo(114.34f, 338.34f)
                    arcTo(8.00f, 8.00f, 0.00f, false, false, 108.69f, 336.00f)
                    horizontalLineTo(56.00f)
                    arcTo(24.00f, 24.00f, 0.00f, false, true, 32.00f, 312.00f)
                    horizontalLineTo(32.00f)
                    arcTo(24.00f, 24.00f, 0.00f, false, true, 56.00f, 288.00f)
                    horizontalLineTo(344.00f)
                    arcTo(24.00f, 24.00f, 0.00f, false, true, 368.00f, 312.00f)
                    horizontalLineTo(368.00f)
                    arcTo(24.00f, 24.00f, 0.00f, false, true, 344.00f, 336.00f)
                    close()
                    moveTo(64.00f, 276.00f)
                    verticalLineTo(275.78f)
                    curveTo(64.00f, 220.78f, 109.00f, 192.00f, 164.00f, 192.00f)
                    horizontalLineTo(236.00f)
                    curveTo(291.00f, 192.00f, 336.00f, 221.00f, 336.00f, 276.00f)
                    verticalLineTo(275.78f)
                    moveTo(241.00f, 112.00f)
                    lineTo(248.44f, 175.97f)
                    moveTo(256.00f, 480.00f)
                    horizontalLineTo(395.31f)
                    arcTo(32.00f, 32.00f, 0.00f, false, false, 427.22f, 450.39f)
                    lineTo(463.00f, 112.00f)
                    moveTo(368.00f, 112.00f)
                    lineTo(384.00f, 48.00f)
                    lineTo(431.00f, 32.00f)
                    moveTo(224.00f, 112.00f)
                    horizontalLineTo(480.00f)
                }
            }
        }.build()
        return _FastFoodOutline!!
    }

private var _FastFoodOutline: ImageVector? = null
