// Generated by XIcons
// 2025-08-17 11:04:30
package cn.enaium.xicons.compose.ionicons5

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.Ionicons5Icons

public val Ionicons5Icons.Sharp.Glasses: ImageVector
    get() {
        if (_Glasses != null) {
            return _Glasses!!
        }
        _Glasses = ImageVector.Builder(
            name = "Glasses",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.046875f, scaleY = 0.046875f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(496.00f, 176.00f)
                    horizontalLineTo(16.00f)
                    verticalLineTo(240.00f)
                    horizontalLineTo(37.24f)
                    lineTo(49.68f, 352.00f)
                    horizontalLineTo(221.55f)
                    lineTo(240.00f, 241.32f)
                    verticalLineTo(240.00f)
                    arcTo(16.00f, 16.00f, 0.00f, false, true, 272.00f, 240.00f)
                    verticalLineTo(241.32f)
                    lineTo(290.45f, 352.00f)
                    horizontalLineTo(462.32f)
                    lineTo(474.76f, 240.00f)
                    horizontalLineTo(496.00f)
                    close()
                }
            }
        }.build()
        return _Glasses!!
    }

private var _Glasses: ImageVector? = null
