// Generated by XIcons
// 2025-08-17 11:04:30
package cn.enaium.xicons.compose.ionicons5

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.Ionicons5Icons

public val Ionicons5Icons.Default.HelpBuoy: ImageVector
    get() {
        if (_HelpBuoy != null) {
            return _HelpBuoy!!
        }
        _HelpBuoy = ImageVector.Builder(
            name = "HelpBuoy",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.046875f, scaleY = 0.046875f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(414.39f, 97.61f)
                    arcTo(224.00f, 224.00f, 0.00f, true, false, 97.61f, 414.39f)
                    arcTo(224.00f, 224.00f, 0.00f, true, false, 414.39f, 97.61f)
                    close()
                    moveTo(192.13f, 260.18f)
                    arcTo(64.00f, 64.00f, 0.00f, true, true, 251.82f, 319.87f)
                    arcTo(64.07f, 64.07f, 0.00f, false, true, 192.13f, 260.18f)
                    close()
                    moveTo(432.13f, 193.54f)
                    lineTo(335.76f, 199.38f)
                    arcTo(4.06f, 4.06f, 0.00f, false, true, 332.32f, 197.79f)
                    arcTo(96.00f, 96.00f, 0.00f, false, false, 314.25f, 179.72f)
                    arcTo(4.06f, 4.06f, 0.00f, false, true, 312.66f, 176.28f)
                    lineTo(318.50f, 79.91f)
                    arcTo(4.00f, 4.00f, 0.00f, false, true, 323.92f, 76.40f)
                    arcTo(193.00f, 193.00f, 0.00f, false, true, 435.60f, 188.12f)
                    arcTo(4.00f, 4.00f, 0.00f, false, true, 432.09f, 193.54f)
                    close()
                    moveTo(193.54f, 79.91f)
                    lineTo(199.38f, 176.28f)
                    arcTo(4.06f, 4.06f, 0.00f, false, true, 197.79f, 179.72f)
                    arcTo(96.00f, 96.00f, 0.00f, false, false, 179.72f, 197.79f)
                    arcTo(4.06f, 4.06f, 0.00f, false, true, 176.28f, 199.38f)
                    lineTo(79.91f, 193.54f)
                    arcTo(4.00f, 4.00f, 0.00f, false, true, 76.40f, 188.12f)
                    arcTo(193.00f, 193.00f, 0.00f, false, true, 188.12f, 76.40f)
                    arcTo(4.00f, 4.00f, 0.00f, false, true, 193.54f, 79.91f)
                    close()
                    moveTo(79.91f, 318.46f)
                    lineTo(176.28f, 312.62f)
                    arcTo(4.06f, 4.06f, 0.00f, false, true, 179.72f, 314.21f)
                    arcTo(96.00f, 96.00f, 0.00f, false, false, 197.79f, 332.28f)
                    arcTo(4.06f, 4.06f, 0.00f, false, true, 199.38f, 335.72f)
                    lineTo(193.54f, 432.09f)
                    arcTo(4.00f, 4.00f, 0.00f, false, true, 188.12f, 435.60f)
                    arcTo(193.00f, 193.00f, 0.00f, false, true, 76.40f, 323.88f)
                    arcTo(4.00f, 4.00f, 0.00f, false, true, 79.91f, 318.46f)
                    close()
                    moveTo(318.46f, 432.09f)
                    lineTo(312.62f, 335.72f)
                    arcTo(4.06f, 4.06f, 0.00f, false, true, 314.21f, 332.28f)
                    arcTo(96.00f, 96.00f, 0.00f, false, false, 332.28f, 314.21f)
                    arcTo(4.06f, 4.06f, 0.00f, false, true, 335.72f, 312.62f)
                    lineTo(432.09f, 318.46f)
                    arcTo(4.00f, 4.00f, 0.00f, false, true, 435.60f, 323.88f)
                    arcTo(193.00f, 193.00f, 0.00f, false, true, 323.88f, 435.60f)
                    arcTo(4.00f, 4.00f, 0.00f, false, true, 318.46f, 432.09f)
                    close()
                }
            }
        }.build()
        return _HelpBuoy!!
    }

private var _HelpBuoy: ImageVector? = null
