// Generated by XIcons
// 2025-08-17 11:04:30
package cn.enaium.xicons.compose.ionicons5

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.Ionicons5Icons

public val Ionicons5Icons.Default.IdCardOutline: ImageVector
    get() {
        if (_IdCardOutline != null) {
            return _IdCardOutline!!
        }
        _IdCardOutline = ImageVector.Builder(
            name = "IdCardOutline",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.046875f, scaleY = 0.046875f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(208.00f, 80.00f)
                    horizontalLineTo(304.00f)
                    moveTo(333.48f, 284.51f)
                    arcTo(39.65f, 39.65f, 0.00f, false, false, 304.00f, 272.00f)
                    curveTo(292.40f, 272.00f, 281.91f, 276.41f, 274.46f, 284.43f)
                    curveTo(267.01f, 292.45f, 263.26f, 303.55f, 264.12f, 315.43f)
                    curveTo(265.83f, 338.91f, 283.72f, 358.00f, 304.00f, 358.00f)
                    curveTo(324.28f, 358.00f, 342.14f, 338.91f, 343.87f, 315.45f)
                    curveTo(344.75f, 303.67f, 341.05f, 292.68f, 333.48f, 284.51f)
                    close()
                    moveTo(371.69f, 448.00f)
                    horizontalLineTo(236.31f)
                    arcTo(12.05f, 12.05f, 0.00f, false, true, 227.00f, 443.83f)
                    arcTo(13.00f, 13.00f, 0.00f, false, true, 224.24f, 432.91f)
                    curveTo(227.49f, 415.35f, 237.62f, 400.60f, 253.54f, 390.25f)
                    curveTo(267.68f, 381.06f, 285.60f, 376.00f, 304.00f, 376.00f)
                    curveTo(322.40f, 376.00f, 340.32f, 381.06f, 354.46f, 390.25f)
                    curveTo(370.38f, 400.60f, 380.51f, 415.35f, 383.76f, 432.91f)
                    arcTo(13.00f, 13.00f, 0.00f, false, true, 381.00f, 443.83f)
                    arcTo(12.05f, 12.05f, 0.00f, false, true, 371.69f, 448.00f)
                    close()
                }
            }
        }.build()
        return _IdCardOutline!!
    }

private var _IdCardOutline: ImageVector? = null
