// Generated by XIcons
// 2025-08-17 11:04:30
package cn.enaium.xicons.compose.ionicons5

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.Ionicons5Icons

public val Ionicons5Icons.Default.LogoFacebook: ImageVector
    get() {
        if (_LogoFacebook != null) {
            return _LogoFacebook!!
        }
        _LogoFacebook = ImageVector.Builder(
            name = "LogoFacebook",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.046875f, scaleY = 0.046875f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(480.00f, 257.35f)
                    curveTo(480.00f, 133.65f, 379.70f, 33.35f, 256.00f, 33.35f)
                    curveTo(132.30f, 33.35f, 32.00f, 133.65f, 32.00f, 257.35f)
                    curveTo(32.00f, 369.15f, 113.90f, 461.82f, 221.00f, 478.64f)
                    verticalLineTo(322.12f)
                    horizontalLineTo(164.11f)
                    verticalLineTo(257.35f)
                    horizontalLineTo(221.00f)
                    verticalLineTo(208.00f)
                    curveTo(221.00f, 151.87f, 254.45f, 120.84f, 305.61f, 120.84f)
                    curveTo(330.12f, 120.84f, 355.76f, 125.22f, 355.76f, 125.22f)
                    verticalLineTo(180.35f)
                    horizontalLineTo(327.50f)
                    curveTo(299.69f, 180.35f, 290.99f, 197.61f, 290.99f, 215.35f)
                    verticalLineTo(257.35f)
                    horizontalLineTo(353.11f)
                    lineTo(343.19f, 322.12f)
                    horizontalLineTo(291.00f)
                    verticalLineTo(478.66f)
                    curveTo(398.10f, 461.85f, 480.00f, 369.18f, 480.00f, 257.35f)
                    close()
                }
            }
        }.build()
        return _LogoFacebook!!
    }

private var _LogoFacebook: ImageVector? = null
