// Generated by XIcons
// 2025-08-17 11:04:02
package cn.enaium.xicons.compose.fa

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.FaIcons

public val FaIcons.Default.AngleRight: ImageVector
    get() {
        if (_AngleRight != null) {
            return _AngleRight!!
        }
        _AngleRight = ImageVector.Builder(
            name = "AngleRight",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.09375f, scaleY = 0.046875f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(224.30f, 273.00f)
                    lineTo(88.30f, 409.00f)
                    curveTo(78.90f, 418.40f, 63.70f, 418.40f, 54.40f, 409.00f)
                    lineTo(31.80f, 386.40f)
                    curveTo(22.40f, 377.00f, 22.40f, 361.80f, 31.80f, 352.50f)
                    lineTo(128.20f, 256.10f)
                    lineTo(31.80f, 159.70f)
                    curveTo(22.40f, 150.30f, 22.40f, 135.10f, 31.80f, 125.80f)
                    lineTo(54.30f, 103.00f)
                    curveTo(63.70f, 93.60f, 78.90f, 93.60f, 88.20f, 103.00f)
                    lineTo(224.20f, 239.00f)
                    curveTo(233.70f, 248.40f, 233.70f, 263.60f, 224.30f, 273.00f)
                    close()
                }
            }
        }.build()
        return _AngleRight!!
    }

private var _AngleRight: ImageVector? = null
