// Generated by XIcons
// 2025-08-17 11:04:04
package cn.enaium.xicons.compose.fa

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.FaIcons

public val FaIcons.Default.FacebookMessenger: ImageVector
    get() {
        if (_FacebookMessenger != null) {
            return _FacebookMessenger!!
        }
        _FacebookMessenger = ImageVector.Builder(
            name = "FacebookMessenger",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.046875f, scaleY = 0.046875f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(256.55f, 8.00f)
                    curveTo(116.52f, 8.00f, 8.00f, 110.34f, 8.00f, 248.57f)
                    curveTo(8.00f, 320.87f, 37.71f, 383.35f, 86.07f, 426.51f)
                    curveTo(94.42f, 434.02f, 92.70f, 438.37f, 94.12f, 484.74f)
                    arcTo(19.92f, 19.92f, 0.00f, false, false, 122.00f, 502.31f)
                    curveTo(174.91f, 479.01f, 175.59f, 477.17f, 184.56f, 479.61f)
                    curveTo(337.85f, 521.80f, 504.00f, 423.70f, 504.00f, 248.57f)
                    curveTo(504.00f, 110.34f, 396.59f, 8.00f, 256.55f, 8.00f)
                    close()
                    moveTo(405.79f, 193.13f)
                    lineTo(332.79f, 308.70f)
                    arcTo(37.37f, 37.37f, 0.00f, false, true, 278.88f, 318.63f)
                    lineTo(220.80f, 275.16f)
                    arcTo(15.00f, 15.00f, 0.00f, false, false, 202.80f, 275.16f)
                    lineTo(124.43f, 334.60f)
                    curveTo(113.97f, 342.53f, 100.27f, 330.00f, 107.32f, 318.93f)
                    lineTo(180.32f, 203.36f)
                    arcTo(37.36f, 37.36f, 0.00f, false, true, 234.23f, 193.43f)
                    lineTo(292.29f, 236.89f)
                    arcTo(15.00f, 15.00f, 0.00f, false, false, 310.29f, 236.89f)
                    lineTo(388.70f, 177.51f)
                    curveTo(399.14f, 169.53f, 412.84f, 182.05f, 405.79f, 193.13f)
                    close()
                }
            }
        }.build()
        return _FacebookMessenger!!
    }

private var _FacebookMessenger: ImageVector? = null
