// Generated by XIcons
// 2025-08-17 11:04:04
package cn.enaium.xicons.compose.fa

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.FaIcons

public val FaIcons.Default.FileCode: ImageVector
    get() {
        if (_FileCode != null) {
            return _FileCode!!
        }
        _FileCode = ImageVector.Builder(
            name = "FileCode",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.0625f, scaleY = 0.046875f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(384.00f, 121.94f)
                    verticalLineTo(128.00f)
                    horizontalLineTo(256.00f)
                    verticalLineTo(0.00f)
                    horizontalLineTo(262.06f)
                    curveTo(268.42f, 0.00f, 274.53f, 2.53f, 279.03f, 7.03f)
                    lineTo(376.97f, 104.97f)
                    arcTo(24.01f, 24.01f, 0.00f, false, true, 384.00f, 121.94f)
                    close()
                    moveTo(248.00f, 160.00f)
                    curveTo(234.80f, 160.00f, 224.00f, 149.20f, 224.00f, 136.00f)
                    verticalLineTo(0.00f)
                    horizontalLineTo(24.00f)
                    curveTo(10.75f, 0.00f, 0.00f, 10.75f, 0.00f, 24.00f)
                    verticalLineTo(488.00f)
                    curveTo(0.00f, 501.26f, 10.75f, 512.00f, 24.00f, 512.00f)
                    horizontalLineTo(360.00f)
                    curveTo(373.26f, 512.00f, 384.00f, 501.26f, 384.00f, 488.00f)
                    verticalLineTo(160.00f)
                    horizontalLineTo(248.00f)
                    close()
                    moveTo(123.21f, 400.51f)
                    arcTo(5.40f, 5.40f, 0.00f, false, true, 115.57f, 400.75f)
                    lineTo(50.71f, 339.94f)
                    arcTo(5.40f, 5.40f, 0.00f, false, true, 50.71f, 332.06f)
                    lineTo(115.57f, 271.25f)
                    arcTo(5.40f, 5.40f, 0.00f, false, true, 123.21f, 271.49f)
                    lineTo(142.79f, 292.38f)
                    arcTo(5.40f, 5.40f, 0.00f, false, true, 142.41f, 300.13f)
                    lineTo(101.65f, 336.00f)
                    lineTo(142.41f, 371.87f)
                    arcTo(5.40f, 5.40f, 0.00f, false, true, 142.79f, 379.62f)
                    lineTo(123.21f, 400.51f)
                    close()
                    moveTo(174.50f, 450.98f)
                    lineTo(147.05f, 443.01f)
                    arcTo(5.40f, 5.40f, 0.00f, false, true, 143.37f, 436.32f)
                    lineTo(204.81f, 224.70f)
                    arcTo(5.40f, 5.40f, 0.00f, false, true, 211.50f, 221.01f)
                    lineTo(238.95f, 228.98f)
                    arcTo(5.40f, 5.40f, 0.00f, false, true, 242.63f, 235.68f)
                    lineTo(181.19f, 447.30f)
                    arcTo(5.40f, 5.40f, 0.00f, false, true, 174.50f, 450.98f)
                    close()
                    moveTo(335.29f, 339.94f)
                    lineTo(270.43f, 400.75f)
                    arcTo(5.40f, 5.40f, 0.00f, false, true, 262.79f, 400.51f)
                    lineTo(243.21f, 379.62f)
                    arcTo(5.40f, 5.40f, 0.00f, false, true, 243.59f, 371.87f)
                    lineTo(284.35f, 336.00f)
                    lineTo(243.59f, 300.13f)
                    arcTo(5.40f, 5.40f, 0.00f, false, true, 243.22f, 292.38f)
                    lineTo(262.80f, 271.49f)
                    arcTo(5.40f, 5.40f, 0.00f, false, true, 270.43f, 271.25f)
                    lineTo(335.29f, 332.06f)
                    arcTo(5.40f, 5.40f, 0.00f, false, true, 335.29f, 339.94f)
                    close()
                }
            }
        }.build()
        return _FileCode!!
    }

private var _FileCode: ImageVector? = null
