// Generated by XIcons
// 2025-08-17 11:04:04
package cn.enaium.xicons.compose.fa

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.FaIcons

public val FaIcons.Default.FontAwesomeAlt: ImageVector
    get() {
        if (_FontAwesomeAlt != null) {
            return _FontAwesomeAlt!!
        }
        _FontAwesomeAlt = ImageVector.Builder(
            name = "FontAwesomeAlt",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.05357142857142857f, scaleY = 0.046875f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(400.00f, 32.00f)
                    horizontalLineTo(48.00f)
                    arcTo(48.00f, 48.00f, 0.00f, false, false, 0.00f, 80.00f)
                    verticalLineTo(432.00f)
                    arcTo(48.00f, 48.00f, 0.00f, false, false, 48.00f, 480.00f)
                    horizontalLineTo(400.00f)
                    arcTo(48.00f, 48.00f, 0.00f, false, false, 448.00f, 432.00f)
                    verticalLineTo(80.00f)
                    arcTo(48.00f, 48.00f, 0.00f, false, false, 400.00f, 32.00f)
                    close()
                    moveTo(416.00f, 432.00f)
                    arcTo(16.00f, 16.00f, 0.00f, false, true, 400.00f, 448.00f)
                    horizontalLineTo(48.00f)
                    arcTo(16.00f, 16.00f, 0.00f, false, true, 32.00f, 432.00f)
                    verticalLineTo(80.00f)
                    arcTo(16.00f, 16.00f, 0.00f, false, true, 48.00f, 64.00f)
                    horizontalLineTo(400.00f)
                    arcTo(16.00f, 16.00f, 0.00f, false, true, 416.00f, 80.00f)
                    close()
                    moveTo(201.60f, 152.00f)
                    curveTo(176.20f, 152.00f, 164.20f, 162.40f, 144.00f, 166.40f)
                    verticalLineTo(160.00f)
                    arcTo(16.00f, 16.00f, 0.00f, false, false, 112.00f, 160.00f)
                    verticalLineTo(352.00f)
                    arcTo(16.00f, 16.00f, 0.00f, false, false, 144.00f, 352.00f)
                    verticalLineTo(198.40f)
                    curveTo(164.20f, 194.40f, 176.20f, 184.00f, 201.60f, 184.00f)
                    curveTo(233.00f, 184.00f, 244.80f, 200.00f, 276.20f, 200.00f)
                    curveTo(286.40f, 200.00f, 294.00f, 198.60f, 304.00f, 195.40f)
                    verticalLineTo(291.40f)
                    curveTo(294.00f, 294.60f, 286.40f, 296.00f, 276.20f, 296.00f)
                    curveTo(244.80f, 296.00f, 232.80f, 280.00f, 201.60f, 280.00f)
                    arcTo(85.90f, 85.90f, 0.00f, false, false, 176.00f, 284.00f)
                    verticalLineTo(316.00f)
                    arcTo(80.00f, 80.00f, 0.00f, false, true, 201.60f, 312.00f)
                    curveTo(233.00f, 312.00f, 244.80f, 328.00f, 276.20f, 328.00f)
                    curveTo(294.80f, 328.00f, 304.40f, 323.20f, 336.00f, 312.00f)
                    verticalLineTo(152.00f)
                    curveTo(304.40f, 163.20f, 294.80f, 168.00f, 276.20f, 168.00f)
                    curveTo(244.80f, 168.00f, 232.80f, 152.00f, 201.60f, 152.00f)
                    close()
                }
            }
        }.build()
        return _FontAwesomeAlt!!
    }

private var _FontAwesomeAlt: ImageVector? = null
