// Generated by XIcons
// 2025-08-17 11:04:05
package cn.enaium.xicons.compose.fa

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.FaIcons

public val FaIcons.Default.HandPointer: ImageVector
    get() {
        if (_HandPointer != null) {
            return _HandPointer!!
        }
        _HandPointer = ImageVector.Builder(
            name = "HandPointer",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.05357142857142857f, scaleY = 0.046875f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(448.00f, 240.00f)
                    verticalLineTo(336.00f)
                    curveTo(448.00f, 339.08f, 447.64f, 342.16f, 446.94f, 345.16f)
                    lineTo(414.94f, 481.16f)
                    curveTo(410.69f, 499.23f, 394.56f, 512.00f, 376.00f, 512.00f)
                    horizontalLineTo(168.00f)
                    arcTo(40.00f, 40.00f, 0.00f, false, true, 135.65f, 495.53f)
                    lineTo(7.65f, 319.53f)
                    curveTo(-5.34f, 301.66f, -1.39f, 276.64f, 16.48f, 263.65f)
                    curveTo(34.34f, 250.66f, 59.36f, 254.61f, 72.35f, 272.47f)
                    lineTo(104.00f, 315.99f)
                    verticalLineTo(40.00f)
                    curveTo(104.00f, 17.91f, 121.91f, 0.00f, 144.00f, 0.00f)
                    curveTo(166.09f, 0.00f, 184.00f, 17.91f, 184.00f, 40.00f)
                    verticalLineTo(240.00f)
                    horizontalLineTo(192.00f)
                    verticalLineTo(200.00f)
                    curveTo(192.00f, 177.91f, 209.91f, 160.00f, 232.00f, 160.00f)
                    curveTo(254.09f, 160.00f, 272.00f, 177.91f, 272.00f, 200.00f)
                    verticalLineTo(240.00f)
                    horizontalLineTo(280.00f)
                    verticalLineTo(216.00f)
                    curveTo(280.00f, 193.91f, 297.91f, 176.00f, 320.00f, 176.00f)
                    curveTo(342.09f, 176.00f, 360.00f, 193.91f, 360.00f, 216.00f)
                    verticalLineTo(240.00f)
                    horizontalLineTo(368.00f)
                    curveTo(368.00f, 217.91f, 385.91f, 200.00f, 408.00f, 200.00f)
                    curveTo(430.09f, 200.00f, 448.00f, 217.91f, 448.00f, 240.00f)
                    close()
                    moveTo(192.00f, 320.00f)
                    horizontalLineTo(184.00f)
                    verticalLineTo(416.00f)
                    horizontalLineTo(192.00f)
                    verticalLineTo(320.00f)
                    close()
                    moveTo(280.00f, 320.00f)
                    horizontalLineTo(272.00f)
                    verticalLineTo(416.00f)
                    horizontalLineTo(280.00f)
                    verticalLineTo(320.00f)
                    close()
                    moveTo(368.00f, 320.00f)
                    horizontalLineTo(360.00f)
                    verticalLineTo(416.00f)
                    horizontalLineTo(368.00f)
                    verticalLineTo(320.00f)
                    close()
                }
            }
        }.build()
        return _HandPointer!!
    }

private var _HandPointer: ImageVector? = null
