// Generated by XIcons
// 2025-08-17 11:04:05
package cn.enaium.xicons.compose.fa

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.FaIcons

public val FaIcons.Default.Itunes: ImageVector
    get() {
        if (_Itunes != null) {
            return _Itunes!!
        }
        _Itunes = ImageVector.Builder(
            name = "Itunes",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.05357142857142857f, scaleY = 0.046875f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(223.60f, 80.30f)
                    curveTo(129.00f, 80.30f, 52.50f, 157.00f, 52.50f, 251.50f)
                    curveTo(52.50f, 346.00f, 129.00f, 422.80f, 223.60f, 422.80f)
                    curveTo(318.20f, 422.80f, 394.80f, 346.10f, 394.80f, 251.60f)
                    curveTo(394.80f, 157.00f, 318.10f, 80.30f, 223.60f, 80.30f)
                    close()
                    moveTo(303.00f, 320.30f)
                    curveTo(299.80f, 333.90f, 289.50f, 341.50f, 275.70f, 344.10f)
                    curveTo(263.60f, 346.30f, 253.50f, 346.90f, 243.80f, 339.10f)
                    curveTo(232.00f, 329.10f, 231.80f, 312.70f, 242.40f, 302.30f)
                    curveTo(250.80f, 294.30f, 262.70f, 292.70f, 280.40f, 289.50f)
                    curveTo(283.40f, 289.00f, 286.00f, 288.30f, 288.10f, 285.80f)
                    curveTo(291.30f, 282.20f, 290.30f, 283.80f, 290.30f, 205.00f)
                    curveTo(290.30f, 199.40f, 287.60f, 197.90f, 281.90f, 198.90f)
                    curveTo(277.90f, 199.60f, 190.00f, 216.00f, 190.00f, 216.00f)
                    curveTo(185.00f, 217.10f, 183.30f, 218.60f, 183.30f, 224.30f)
                    curveTo(183.30f, 340.40f, 183.80f, 335.10f, 182.10f, 342.80f)
                    curveTo(180.00f, 351.80f, 174.50f, 358.60f, 167.20f, 362.40f)
                    curveTo(158.90f, 367.00f, 143.80f, 369.00f, 135.80f, 367.60f)
                    curveTo(114.40f, 363.60f, 106.90f, 338.90f, 121.40f, 324.70f)
                    curveTo(129.80f, 316.70f, 141.70f, 315.10f, 159.40f, 311.90f)
                    curveTo(162.40f, 311.40f, 165.00f, 310.70f, 167.10f, 308.20f)
                    curveTo(172.10f, 302.50f, 168.00f, 181.20f, 169.70f, 174.50f)
                    curveTo(170.10f, 171.90f, 171.20f, 169.70f, 173.20f, 168.10f)
                    curveTo(175.30f, 166.40f, 179.00f, 165.40f, 179.90f, 165.40f)
                    curveTo(280.90f, 146.40f, 293.20f, 144.00f, 295.00f, 144.00f)
                    curveTo(300.70f, 143.60f, 304.00f, 147.00f, 304.00f, 152.70f)
                    curveTo(303.90f, 323.30f, 304.40f, 314.10f, 303.00f, 320.30f)
                    close()
                    moveTo(345.20f, 32.00f)
                    horizontalLineTo(102.80f)
                    curveTo(45.90f, 32.00f, 0.00f, 77.90f, 0.00f, 134.80f)
                    verticalLineTo(377.20f)
                    curveTo(0.00f, 434.10f, 45.90f, 480.00f, 102.80f, 480.00f)
                    horizontalLineTo(345.20f)
                    curveTo(402.20f, 480.00f, 448.00f, 434.10f, 448.00f, 377.20f)
                    verticalLineTo(134.80f)
                    curveTo(448.00f, 77.90f, 402.10f, 32.00f, 345.20f, 32.00f)
                    close()
                    moveTo(223.60f, 444.00f)
                    curveTo(117.30f, 444.00f, 31.10f, 357.80f, 31.10f, 251.50f)
                    curveTo(31.10f, 145.20f, 117.30f, 59.00f, 223.60f, 59.00f)
                    curveTo(329.90f, 59.00f, 416.10f, 145.20f, 416.10f, 251.50f)
                    curveTo(416.10f, 357.80f, 329.90f, 444.00f, 223.60f, 444.00f)
                    close()
                }
            }
        }.build()
        return _Itunes!!
    }

private var _Itunes: ImageVector? = null
