// Generated by XIcons
// 2025-08-17 11:04:06
package cn.enaium.xicons.compose.fa

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.FaIcons

public val FaIcons.Default.PhoneAlt: ImageVector
    get() {
        if (_PhoneAlt != null) {
            return _PhoneAlt!!
        }
        _PhoneAlt = ImageVector.Builder(
            name = "PhoneAlt",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.046875f, scaleY = 0.046875f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(497.39f, 361.80f)
                    lineTo(385.39f, 313.80f)
                    arcTo(24.00f, 24.00f, 0.00f, false, false, 357.39f, 320.70f)
                    lineTo(307.79f, 381.30f)
                    arcTo(370.66f, 370.66f, 0.00f, false, true, 130.60f, 204.11f)
                    lineTo(191.20f, 154.51f)
                    arcTo(23.94f, 23.94f, 0.00f, false, false, 198.10f, 126.51f)
                    lineTo(150.10f, 14.51f)
                    arcTo(24.16f, 24.16f, 0.00f, false, false, 122.60f, 0.61f)
                    lineTo(18.60f, 24.61f)
                    arcTo(24.00f, 24.00f, 0.00f, false, false, 0.00f, 48.00f)
                    curveTo(0.00f, 304.50f, 207.90f, 512.00f, 464.00f, 512.00f)
                    arcTo(24.00f, 24.00f, 0.00f, false, false, 487.40f, 493.40f)
                    lineTo(511.40f, 389.40f)
                    arcTo(24.29f, 24.29f, 0.00f, false, false, 497.39f, 361.80f)
                    close()
                }
            }
        }.build()
        return _PhoneAlt!!
    }

private var _PhoneAlt: ImageVector? = null
