// Generated by XIcons
// 2025-08-17 11:04:07
package cn.enaium.xicons.compose.fa

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.FaIcons

public val FaIcons.Default.PowerOff: ImageVector
    get() {
        if (_PowerOff != null) {
            return _PowerOff!!
        }
        _PowerOff = ImageVector.Builder(
            name = "PowerOff",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.046875f, scaleY = 0.046875f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(400.00f, 54.10f)
                    curveTo(463.00f, 99.10f, 504.00f, 172.70f, 504.00f, 256.00f)
                    curveTo(504.00f, 392.80f, 393.20f, 503.70f, 256.50f, 504.00f)
                    curveTo(120.00f, 504.30f, 8.20f, 393.00f, 8.00f, 256.40f)
                    curveTo(7.90f, 173.10f, 48.90f, 99.30f, 111.80f, 54.20f)
                    curveTo(123.50f, 45.90f, 139.80f, 49.40f, 146.80f, 61.90f)
                    lineTo(162.60f, 90.00f)
                    curveTo(168.50f, 100.50f, 165.70f, 113.80f, 156.00f, 121.00f)
                    curveTo(114.50f, 151.80f, 88.00f, 200.60f, 88.00f, 255.90f)
                    curveTo(87.90f, 348.20f, 162.50f, 424.00f, 256.00f, 424.00f)
                    curveTo(347.60f, 424.00f, 424.60f, 349.80f, 424.00f, 254.90f)
                    curveTo(423.70f, 203.10f, 399.30f, 153.10f, 355.90f, 120.90f)
                    curveTo(346.20f, 113.70f, 343.50f, 100.40f, 349.40f, 90.00f)
                    lineTo(365.20f, 61.90f)
                    curveTo(372.20f, 49.50f, 388.40f, 45.80f, 400.00f, 54.10f)
                    close()
                    moveTo(296.00f, 264.00f)
                    verticalLineTo(24.00f)
                    curveTo(296.00f, 10.70f, 285.30f, 0.00f, 272.00f, 0.00f)
                    horizontalLineTo(240.00f)
                    curveTo(226.70f, 0.00f, 216.00f, 10.70f, 216.00f, 24.00f)
                    verticalLineTo(264.00f)
                    curveTo(216.00f, 277.30f, 226.70f, 288.00f, 240.00f, 288.00f)
                    horizontalLineTo(272.00f)
                    curveTo(285.30f, 288.00f, 296.00f, 277.30f, 296.00f, 264.00f)
                    close()
                }
            }
        }.build()
        return _PowerOff!!
    }

private var _PowerOff: ImageVector? = null
