// Generated by XIcons
// 2025-08-17 11:04:08
package cn.enaium.xicons.compose.fa

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.FaIcons

public val FaIcons.Default.Suitcase: ImageVector
    get() {
        if (_Suitcase != null) {
            return _Suitcase!!
        }
        _Suitcase = ImageVector.Builder(
            name = "Suitcase",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.046875f, scaleY = 0.046875f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(128.00f, 480.00f)
                    horizontalLineTo(384.00f)
                    verticalLineTo(80.00f)
                    curveTo(384.00f, 53.50f, 362.50f, 32.00f, 336.00f, 32.00f)
                    horizontalLineTo(176.00f)
                    curveTo(149.50f, 32.00f, 128.00f, 53.50f, 128.00f, 80.00f)
                    verticalLineTo(480.00f)
                    close()
                    moveTo(192.00f, 96.00f)
                    horizontalLineTo(320.00f)
                    verticalLineTo(128.00f)
                    horizontalLineTo(192.00f)
                    verticalLineTo(96.00f)
                    close()
                    moveTo(512.00f, 176.00f)
                    verticalLineTo(432.00f)
                    curveTo(512.00f, 458.50f, 490.50f, 480.00f, 464.00f, 480.00f)
                    horizontalLineTo(416.00f)
                    verticalLineTo(128.00f)
                    horizontalLineTo(464.00f)
                    curveTo(490.50f, 128.00f, 512.00f, 149.50f, 512.00f, 176.00f)
                    close()
                    moveTo(96.00f, 480.00f)
                    horizontalLineTo(48.00f)
                    curveTo(21.50f, 480.00f, 0.00f, 458.50f, 0.00f, 432.00f)
                    verticalLineTo(176.00f)
                    curveTo(0.00f, 149.50f, 21.50f, 128.00f, 48.00f, 128.00f)
                    horizontalLineTo(96.00f)
                    verticalLineTo(480.00f)
                    close()
                }
            }
        }.build()
        return _Suitcase!!
    }

private var _Suitcase: ImageVector? = null
