// Generated by XIcons
// 2025-08-17 11:04:08
package cn.enaium.xicons.compose.fa

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.FaIcons

public val FaIcons.Default.Th: ImageVector
    get() {
        if (_Th != null) {
            return _Th!!
        }
        _Th = ImageVector.Builder(
            name = "Th",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.046875f, scaleY = 0.046875f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(149.33f, 56.00f)
                    verticalLineTo(136.00f)
                    curveTo(149.33f, 149.26f, 138.59f, 160.00f, 125.33f, 160.00f)
                    horizontalLineTo(24.00f)
                    curveTo(10.75f, 160.00f, 0.00f, 149.26f, 0.00f, 136.00f)
                    verticalLineTo(56.00f)
                    curveTo(0.00f, 42.75f, 10.75f, 32.00f, 24.00f, 32.00f)
                    horizontalLineTo(125.33f)
                    curveTo(138.59f, 32.00f, 149.33f, 42.75f, 149.33f, 56.00f)
                    close()
                    moveTo(330.67f, 296.00f)
                    verticalLineTo(216.00f)
                    curveTo(330.67f, 202.75f, 319.92f, 192.00f, 306.67f, 192.00f)
                    horizontalLineTo(205.33f)
                    curveTo(192.08f, 192.00f, 181.33f, 202.75f, 181.33f, 216.00f)
                    verticalLineTo(296.00f)
                    curveTo(181.33f, 309.26f, 192.08f, 320.00f, 205.33f, 320.00f)
                    horizontalLineTo(306.67f)
                    curveTo(319.92f, 320.00f, 330.67f, 309.26f, 330.67f, 296.00f)
                    close()
                    moveTo(362.67f, 56.00f)
                    verticalLineTo(136.00f)
                    curveTo(362.67f, 149.26f, 373.41f, 160.00f, 386.67f, 160.00f)
                    horizontalLineTo(488.00f)
                    curveTo(501.26f, 160.00f, 512.00f, 149.26f, 512.00f, 136.00f)
                    verticalLineTo(56.00f)
                    curveTo(512.00f, 42.75f, 501.26f, 32.00f, 488.00f, 32.00f)
                    horizontalLineTo(386.67f)
                    curveTo(373.41f, 32.00f, 362.67f, 42.75f, 362.67f, 56.00f)
                    close()
                    moveTo(330.67f, 136.00f)
                    verticalLineTo(56.00f)
                    curveTo(330.67f, 42.75f, 319.92f, 32.00f, 306.67f, 32.00f)
                    horizontalLineTo(205.33f)
                    curveTo(192.08f, 32.00f, 181.33f, 42.75f, 181.33f, 56.00f)
                    verticalLineTo(136.00f)
                    curveTo(181.33f, 149.26f, 192.08f, 160.00f, 205.33f, 160.00f)
                    horizontalLineTo(306.67f)
                    curveTo(319.92f, 160.00f, 330.67f, 149.26f, 330.67f, 136.00f)
                    close()
                    moveTo(125.33f, 192.00f)
                    horizontalLineTo(24.00f)
                    curveTo(10.75f, 192.00f, 0.00f, 202.75f, 0.00f, 216.00f)
                    verticalLineTo(296.00f)
                    curveTo(0.00f, 309.26f, 10.75f, 320.00f, 24.00f, 320.00f)
                    horizontalLineTo(125.33f)
                    curveTo(138.59f, 320.00f, 149.33f, 309.26f, 149.33f, 296.00f)
                    verticalLineTo(216.00f)
                    curveTo(149.33f, 202.75f, 138.59f, 192.00f, 125.33f, 192.00f)
                    close()
                    moveTo(0.00f, 376.00f)
                    verticalLineTo(456.00f)
                    curveTo(0.00f, 469.26f, 10.75f, 480.00f, 24.00f, 480.00f)
                    horizontalLineTo(125.33f)
                    curveTo(138.59f, 480.00f, 149.33f, 469.26f, 149.33f, 456.00f)
                    verticalLineTo(376.00f)
                    curveTo(149.33f, 362.75f, 138.59f, 352.00f, 125.33f, 352.00f)
                    horizontalLineTo(24.00f)
                    curveTo(10.75f, 352.00f, 0.00f, 362.75f, 0.00f, 376.00f)
                    close()
                    moveTo(386.67f, 320.00f)
                    horizontalLineTo(488.00f)
                    curveTo(501.26f, 320.00f, 512.00f, 309.26f, 512.00f, 296.00f)
                    verticalLineTo(216.00f)
                    curveTo(512.00f, 202.75f, 501.26f, 192.00f, 488.00f, 192.00f)
                    horizontalLineTo(386.67f)
                    curveTo(373.41f, 192.00f, 362.67f, 202.75f, 362.67f, 216.00f)
                    verticalLineTo(296.00f)
                    curveTo(362.67f, 309.26f, 373.41f, 320.00f, 386.67f, 320.00f)
                    close()
                    moveTo(386.67f, 480.00f)
                    horizontalLineTo(488.00f)
                    curveTo(501.26f, 480.00f, 512.00f, 469.26f, 512.00f, 456.00f)
                    verticalLineTo(376.00f)
                    curveTo(512.00f, 362.75f, 501.26f, 352.00f, 488.00f, 352.00f)
                    horizontalLineTo(386.67f)
                    curveTo(373.41f, 352.00f, 362.67f, 362.75f, 362.67f, 376.00f)
                    verticalLineTo(456.00f)
                    curveTo(362.67f, 469.26f, 373.41f, 480.00f, 386.67f, 480.00f)
                    close()
                    moveTo(181.33f, 376.00f)
                    verticalLineTo(456.00f)
                    curveTo(181.33f, 469.26f, 192.08f, 480.00f, 205.33f, 480.00f)
                    horizontalLineTo(306.67f)
                    curveTo(319.92f, 480.00f, 330.67f, 469.26f, 330.67f, 456.00f)
                    verticalLineTo(376.00f)
                    curveTo(330.67f, 362.75f, 319.92f, 352.00f, 306.67f, 352.00f)
                    horizontalLineTo(205.33f)
                    curveTo(192.08f, 352.00f, 181.33f, 362.75f, 181.33f, 376.00f)
                    close()
                }
            }
        }.build()
        return _Th!!
    }

private var _Th: ImageVector? = null
