// Generated by XIcons
// 2025-08-14 22:09:13
package cn.enaium.xicons.jfx.icons.ionicons4;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class IosPhotos extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(464.00, 144.00);
        path.horizontalLineTo(128.00);
        path.curveTo(110.40, 144.00, 96.00, 158.40, 96.00, 176.00);
        path.verticalLineTo(416.00);
        path.curveTo(96.00, 433.60, 110.40, 448.00, 128.00, 448.00);
        path.horizontalLineTo(464.00);
        path.curveTo(481.60, 448.00, 496.00, 433.60, 496.00, 416.00);
        path.verticalLineTo(176.00);
        path.curveTo(496.00, 158.40, 481.60, 144.00, 464.00, 144.00);
        path.close();
        path.moveTo(100.00, 116.00);
        path.horizontalLineTo(432.00);
        path.verticalLineTo(96.00);
        path.curveTo(432.00, 78.40, 417.60, 64.00, 400.00, 64.00);
        path.horizontalLineTo(48.00);
        path.curveTo(30.40, 64.00, 16.00, 78.40, 16.00, 96.00);
        path.verticalLineTo(352.00);
        path.curveTo(16.00, 369.60, 30.40, 384.00, 48.00, 384.00);
        path.horizontalLineTo(68.00);
        path.verticalLineTo(148.00);
        path.curveTo(68.00, 130.40, 82.40, 116.00, 100.00, 116.00);
        path.close();
        path.scale(0.046875, 0.046875);
        return path;
    }
}
