// Generated by XIcons
// 2025-08-14 22:11:33
package cn.enaium.xicons.swing.icons.tabler;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class Calculator extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(8.00, 14.00);
        path.verticalLineTo(14.01);
        path.moveTo(12.00, 14.00);
        path.verticalLineTo(14.01);
        path.moveTo(16.00, 14.00);
        path.verticalLineTo(14.01);
        path.moveTo(8.00, 17.00);
        path.verticalLineTo(17.01);
        path.moveTo(12.00, 17.00);
        path.verticalLineTo(17.01);
        path.moveTo(16.00, 17.00);
        path.verticalLineTo(17.01);
        return path;
    }
}
