// Generated by XIcons
// 2025-08-14 22:11:34
package cn.enaium.xicons.swing.icons.tabler;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class Currency extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(4.00, 4.00);
        path.lineTo(7.00, 7.00);
        path.moveTo(20.00, 4.00);
        path.lineTo(17.00, 7.00);
        path.moveTo(4.00, 20.00);
        path.lineTo(7.00, 17.00);
        path.moveTo(20.00, 20.00);
        path.lineTo(17.00, 17.00);
        return path;
    }
}
