// Generated by XIcons
// 2025-08-14 22:11:34
package cn.enaium.xicons.swing.icons.tabler;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class HandMove extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(8.00, 13.00);
        path.verticalLineTo(4.50);
        path.arcTo(1.50, 1.50, 0.00, false, true, 11.00, 4.50);
        path.verticalLineTo(12.00);
        path.moveTo(11.00, 11.50);
        path.verticalLineTo(9.50);
        path.arcTo(1.50, 1.50, 0.00, false, true, 14.00, 9.50);
        path.verticalLineTo(12.00);
        path.moveTo(14.00, 10.50);
        path.arcTo(1.50, 1.50, 0.00, false, true, 17.00, 10.50);
        path.verticalLineTo(12.00);
        path.moveTo(17.00, 11.50);
        path.arcTo(1.50, 1.50, 0.00, false, true, 20.00, 11.50);
        path.verticalLineTo(16.00);
        path.arcTo(6.00, 6.00, 0.00, false, true, 14.00, 22.00);
        path.horizontalLineTo(12.00);
        path.horizontalLineTo(12.21);
        path.arcTo(6.00, 6.00, 0.00, false, true, 7.20, 19.30);
        path.lineTo(7.00, 19.00);
        path.curveTo(6.69, 18.52, 5.59, 16.61, 3.71, 13.27);
        path.arcTo(1.50, 1.50, 0.00, false, true, 4.25, 11.25);
        path.arcTo(1.87, 1.87, 0.00, false, true, 6.53, 11.53);
        path.lineTo(8.00, 13.00);
        path.moveTo(2.54, 5.59);
        path.arcTo(13.49, 13.49, 0.00, false, true, 5.00, 4.17);
        path.moveTo(14.00, 3.46);
        path.arcTo(13.44, 13.44, 0.00, false, true, 17.69, 5.07);
        return path;
    }
}
