// Generated by XIcons
// 2025-08-14 22:11:34
package cn.enaium.xicons.swing.icons.tabler;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class Package extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(12.00, 3.00);
        path.lineTo(20.00, 7.50);
        path.verticalLineTo(16.50);
        path.lineTo(12.00, 21.00);
        path.lineTo(4.00, 16.50);
        path.verticalLineTo(7.50);
        path.lineTo(12.00, 3.00);
        path.moveTo(12.00, 12.00);
        path.lineTo(20.00, 7.50);
        path.moveTo(12.00, 12.00);
        path.verticalLineTo(21.00);
        path.moveTo(12.00, 12.00);
        path.lineTo(4.00, 7.50);
        path.moveTo(16.00, 5.25);
        path.lineTo(8.00, 9.75);
        return path;
    }
}
