// Generated by XIcons
// 2025-08-17 11:04:26
package cn.enaium.xicons.compose.ionicons4

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.Ionicons4Icons

public val Ionicons4Icons.Default.IosAt: ImageVector
    get() {
        if (_IosAt != null) {
            return _IosAt!!
        }
        _IosAt = ImageVector.Builder(
            name = "IosAt",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.046875f, scaleY = 0.046875f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(448.00f, 234.30f)
                    curveTo(448.00f, 308.40f, 413.30f, 355.10f, 358.40f, 355.10f)
                    curveTo(330.30f, 355.10f, 308.90f, 340.10f, 305.20f, 317.80f)
                    horizontalLineTo(301.20f)
                    curveTo(291.30f, 341.00f, 270.90f, 353.70f, 243.50f, 353.70f)
                    curveTo(194.70f, 353.70f, 162.10f, 314.60f, 162.10f, 256.40f)
                    curveTo(162.10f, 200.50f, 194.90f, 161.60f, 242.80f, 161.60f)
                    curveTo(267.40f, 161.60f, 288.30f, 174.00f, 297.50f, 194.30f)
                    horizontalLineTo(301.50f)
                    verticalLineTo(166.50f)
                    horizontalLineTo(341.40f)
                    verticalLineTo(295.80f)
                    curveTo(341.40f, 311.90f, 350.30f, 321.60f, 366.30f, 321.60f)
                    curveTo(394.00f, 321.60f, 411.60f, 288.00f, 411.60f, 235.80f)
                    curveTo(411.60f, 152.50f, 349.20f, 96.80f, 257.00f, 96.80f)
                    curveTo(165.80f, 96.80f, 100.80f, 163.30f, 100.80f, 257.40f)
                    curveTo(100.80f, 353.60f, 165.10f, 415.00f, 265.20f, 415.00f)
                    curveTo(284.80f, 415.00f, 304.50f, 413.30f, 319.60f, 410.40f)
                    curveTo(329.40f, 408.60f, 338.40f, 416.00f, 338.40f, 425.90f)
                    verticalLineTo(425.90f)
                    curveTo(338.40f, 433.20f, 333.40f, 439.60f, 326.30f, 441.30f)
                    curveTo(308.10f, 445.60f, 286.20f, 448.10f, 263.60f, 448.10f)
                    curveTo(141.90f, 448.00f, 64.00f, 372.80f, 64.00f, 256.10f)
                    curveTo(64.00f, 142.20f, 143.50f, 64.00f, 259.40f, 64.00f)
                    curveTo(370.80f, 64.00f, 448.00f, 133.50f, 448.00f, 234.30f)
                    close()
                    moveTo(205.20f, 257.30f)
                    curveTo(205.20f, 294.30f, 222.60f, 316.70f, 250.90f, 316.70f)
                    curveTo(280.70f, 316.70f, 299.50f, 293.70f, 299.50f, 257.30f)
                    curveTo(299.50f, 220.90f, 280.70f, 198.40f, 251.40f, 198.40f)
                    curveTo(222.30f, 198.40f, 205.20f, 220.20f, 205.20f, 257.30f)
                    close()
                }
            }
        }.build()
        return _IosAt!!
    }

private var _IosAt: ImageVector? = null
