// Generated by XIcons
// 2025-08-17 11:04:26
package cn.enaium.xicons.compose.ionicons4

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.Ionicons4Icons

public val Ionicons4Icons.Default.IosHourglass: ImageVector
    get() {
        if (_IosHourglass != null) {
            return _IosHourglass!!
        }
        _IosHourglass = ImageVector.Builder(
            name = "IosHourglass",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.046875f, scaleY = 0.046875f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(415.60f, 434.00f)
                    horizontalLineTo(410.50f)
                    curveTo(404.00f, 434.00f, 398.50f, 433.10f, 397.80f, 426.60f)
                    curveTo(397.80f, 426.60f, 397.80f, 426.50f, 397.80f, 426.50f)
                    curveTo(383.20f, 290.60f, 297.60f, 288.00f, 297.60f, 256.00f)
                    curveTo(297.60f, 224.00f, 383.30f, 221.40f, 397.80f, 85.50f)
                    lineTo(397.80f, 85.40f)
                    curveTo(398.50f, 78.90f, 404.00f, 78.00f, 410.50f, 78.00f)
                    horizontalLineTo(415.60f)
                    curveTo(423.10f, 78.00f, 429.60f, 72.20f, 430.00f, 64.70f)
                    curveTo(430.40f, 56.70f, 424.00f, 50.00f, 416.00f, 50.00f)
                    lineTo(96.40f, 50.00f)
                    curveTo(88.90f, 50.00f, 82.40f, 55.80f, 82.00f, 63.30f)
                    curveTo(81.60f, 71.30f, 88.00f, 78.00f, 96.00f, 78.00f)
                    horizontalLineTo(101.50f)
                    curveTo(108.00f, 78.00f, 113.50f, 78.90f, 114.20f, 85.40f)
                    lineTo(114.20f, 85.50f)
                    curveTo(128.80f, 221.40f, 214.40f, 224.00f, 214.40f, 256.00f)
                    curveTo(214.40f, 288.00f, 128.70f, 290.60f, 114.20f, 426.50f)
                    lineTo(114.20f, 426.60f)
                    curveTo(113.50f, 433.10f, 108.00f, 434.00f, 101.50f, 434.00f)
                    horizontalLineTo(96.40f)
                    curveTo(88.90f, 434.00f, 82.40f, 439.80f, 82.00f, 447.30f)
                    curveTo(81.60f, 455.30f, 88.00f, 462.00f, 96.00f, 462.00f)
                    horizontalLineTo(416.00f)
                    curveTo(424.00f, 462.00f, 430.40f, 455.40f, 430.00f, 447.30f)
                    curveTo(429.60f, 439.80f, 423.10f, 434.00f, 415.60f, 434.00f)
                    close()
                    moveTo(163.30f, 399.80f)
                    curveTo(192.00f, 320.00f, 242.90f, 329.70f, 242.90f, 298.20f)
                    curveTo(242.90f, 267.00f, 242.90f, 258.90f, 242.90f, 242.60f)
                    curveTo(242.90f, 223.20f, 206.10f, 209.70f, 183.10f, 178.20f)
                    curveTo(179.30f, 173.00f, 183.10f, 165.80f, 189.60f, 165.80f)
                    horizontalLineTo(322.50f)
                    curveTo(329.00f, 165.80f, 332.90f, 172.80f, 329.20f, 178.00f)
                    curveTo(306.60f, 209.60f, 269.10f, 223.20f, 269.10f, 242.60f)
                    curveTo(269.10f, 260.50f, 269.10f, 267.00f, 269.10f, 298.20f)
                    curveTo(269.10f, 329.40f, 318.00f, 320.90f, 348.90f, 399.80f)
                    curveTo(351.70f, 406.90f, 349.60f, 415.80f, 342.00f, 415.80f)
                    horizontalLineTo(170.20f)
                    curveTo(162.50f, 415.80f, 160.70f, 407.00f, 163.30f, 399.80f)
                    close()
                }
            }
        }.build()
        return _IosHourglass!!
    }

private var _IosHourglass: ImageVector? = null
