// Generated by XIcons
// 2025-08-17 11:04:26
package cn.enaium.xicons.compose.ionicons4

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.Ionicons4Icons

public val Ionicons4Icons.Default.IosPaw: ImageVector
    get() {
        if (_IosPaw != null) {
            return _IosPaw!!
        }
        _IosPaw = ImageVector.Builder(
            name = "IosPaw",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.046875f, scaleY = 0.046875f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(324.30f, 80.30f)
                    curveTo(323.10f, 80.10f, 321.90f, 80.00f, 320.70f, 80.00f)
                    verticalLineTo(80.30f)
                    verticalLineTo(80.40f)
                    verticalLineTo(80.10f)
                    curveTo(320.60f, 80.10f, 320.50f, 80.10f, 320.30f, 80.10f)
                    curveTo(298.30f, 80.10f, 277.40f, 106.00f, 272.50f, 140.40f)
                    curveTo(267.20f, 177.00f, 281.90f, 209.40f, 305.20f, 212.80f)
                    curveTo(306.50f, 213.00f, 307.90f, 213.10f, 309.20f, 213.10f)
                    curveTo(331.20f, 213.10f, 352.10f, 187.20f, 357.00f, 152.80f)
                    curveTo(362.30f, 116.10f, 347.60f, 83.70f, 324.30f, 80.30f)
                    close()
                    moveTo(320.60f, 80.00f)
                    lineTo(320.60f, 80.00f)
                    lineTo(320.60f, 80.00f)
                    close()
                    moveTo(442.30f, 169.40f)
                    curveTo(438.80f, 168.00f, 435.20f, 167.30f, 431.40f, 167.30f)
                    curveTo(431.30f, 167.30f, 431.10f, 167.30f, 431.00f, 167.30f)
                    lineTo(431.00f, 167.30f)
                    lineTo(431.00f, 167.30f)
                    curveTo(411.30f, 167.60f, 389.20f, 186.50f, 377.60f, 215.10f)
                    curveTo(363.70f, 249.30f, 370.10f, 284.30f, 392.00f, 293.30f)
                    curveTo(395.50f, 294.70f, 399.10f, 295.40f, 402.90f, 295.40f)
                    curveTo(422.70f, 295.40f, 445.10f, 276.40f, 456.80f, 247.60f)
                    curveTo(470.60f, 213.40f, 464.10f, 178.40f, 442.30f, 169.40f)
                    close()
                    moveTo(327.60f, 295.40f)
                    curveTo(299.80f, 251.80f, 287.80f, 235.40f, 256.00f, 235.40f)
                    curveTo(224.20f, 235.40f, 212.10f, 251.90f, 184.30f, 295.40f)
                    curveTo(160.50f, 332.60f, 112.40f, 335.70f, 100.40f, 367.30f)
                    curveTo(98.00f, 372.90f, 96.80f, 379.00f, 96.80f, 385.50f)
                    curveTo(96.80f, 411.20f, 117.60f, 432.00f, 143.20f, 432.00f)
                    curveTo(175.00f, 432.00f, 218.30f, 408.00f, 256.10f, 408.00f)
                    curveTo(293.90f, 408.00f, 337.00f, 432.00f, 368.80f, 432.00f)
                    curveTo(394.40f, 432.00f, 415.10f, 411.20f, 415.10f, 385.50f)
                    curveTo(415.10f, 379.00f, 413.80f, 372.90f, 411.40f, 367.30f)
                    curveTo(399.40f, 335.60f, 351.40f, 332.60f, 327.60f, 295.40f)
                    close()
                    moveTo(202.80f, 213.00f)
                    curveTo(204.10f, 213.00f, 205.50f, 212.90f, 206.80f, 212.70f)
                    curveTo(230.20f, 209.30f, 244.80f, 176.90f, 239.50f, 140.30f)
                    curveTo(234.50f, 105.80f, 213.60f, 80.00f, 191.70f, 80.00f)
                    curveTo(190.40f, 80.00f, 189.00f, 80.10f, 187.70f, 80.30f)
                    curveTo(164.30f, 83.70f, 149.70f, 116.10f, 155.00f, 152.70f)
                    curveTo(160.00f, 187.10f, 180.90f, 213.00f, 202.80f, 213.00f)
                    close()
                    moveTo(120.10f, 293.30f)
                    curveTo(142.00f, 284.30f, 148.40f, 249.30f, 134.50f, 215.10f)
                    curveTo(122.80f, 186.30f, 100.40f, 167.30f, 80.60f, 167.30f)
                    curveTo(76.80f, 167.30f, 73.20f, 168.00f, 69.70f, 169.40f)
                    curveTo(47.80f, 178.40f, 41.40f, 213.40f, 55.30f, 247.60f)
                    curveTo(67.00f, 276.40f, 89.40f, 295.40f, 109.20f, 295.40f)
                    curveTo(113.00f, 295.40f, 116.60f, 294.70f, 120.10f, 293.30f)
                    close()
                }
            }
        }.build()
        return _IosPaw!!
    }

private var _IosPaw: ImageVector? = null
