// Generated by XIcons
// 2025-08-17 11:04:27
package cn.enaium.xicons.compose.ionicons4

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.Ionicons4Icons

public val Ionicons4Icons.Default.LogoYen: ImageVector
    get() {
        if (_LogoYen != null) {
            return _LogoYen!!
        }
        _LogoYen = ImageVector.Builder(
            name = "LogoYen",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.046875f, scaleY = 0.046875f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(448.00f, 32.00f)
                    horizontalLineTo(368.00f)
                    lineTo(256.00f, 253.13f)
                    lineTo(144.00f, 32.00f)
                    horizontalLineTo(64.00f)
                    lineTo(176.37f, 240.00f)
                    horizontalLineTo(128.00f)
                    verticalLineTo(288.00f)
                    horizontalLineTo(201.56f)
                    lineTo(216.00f, 319.00f)
                    verticalLineTo(336.00f)
                    horizontalLineTo(128.00f)
                    verticalLineTo(384.00f)
                    horizontalLineTo(216.00f)
                    verticalLineTo(480.00f)
                    horizontalLineTo(296.00f)
                    verticalLineTo(384.00f)
                    horizontalLineTo(384.00f)
                    verticalLineTo(336.00f)
                    horizontalLineTo(296.00f)
                    verticalLineTo(319.00f)
                    lineTo(310.89f, 288.00f)
                    horizontalLineTo(384.00f)
                    verticalLineTo(240.00f)
                    horizontalLineTo(335.71f)
                    lineTo(448.00f, 32.00f)
                    close()
                }
            }
        }.build()
        return _LogoYen!!
    }

private var _LogoYen: ImageVector? = null
