// Generated by XIcons
// 2025-08-17 11:04:27
package cn.enaium.xicons.compose.ionicons4

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.Ionicons4Icons

public val Ionicons4Icons.Default.LogoSlack: ImageVector
    get() {
        if (_LogoSlack != null) {
            return _LogoSlack!!
        }
        _LogoSlack = ImageVector.Builder(
            name = "LogoSlack",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.046875f, scaleY = 0.046875f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(475.90f, 190.00f)
                    curveTo(426.40f, 25.00f, 355.00f, -13.40f, 190.00f, 36.10f)
                    curveTo(25.00f, 85.60f, -13.40f, 157.00f, 36.10f, 322.00f)
                    curveTo(85.60f, 487.00f, 157.00f, 525.40f, 322.00f, 475.90f)
                    curveTo(487.00f, 426.40f, 525.40f, 355.00f, 475.90f, 190.00f)
                    close()
                    moveTo(392.60f, 297.10f)
                    lineTo(361.50f, 307.50f)
                    lineTo(372.20f, 339.70f)
                    curveTo(376.40f, 352.70f, 369.50f, 366.90f, 356.50f, 371.20f)
                    curveTo(353.80f, 372.00f, 350.70f, 372.70f, 348.10f, 372.40f)
                    curveTo(338.10f, 372.00f, 328.50f, 365.50f, 325.10f, 355.50f)
                    lineTo(314.40f, 323.30f)
                    lineTo(250.30f, 344.80f)
                    lineTo(261.00f, 377.00f)
                    curveTo(265.20f, 390.00f, 258.30f, 404.20f, 245.30f, 408.50f)
                    curveTo(242.60f, 409.30f, 239.50f, 410.00f, 236.90f, 409.70f)
                    curveTo(226.90f, 409.30f, 217.30f, 402.80f, 213.90f, 392.80f)
                    lineTo(203.00f, 360.40f)
                    lineTo(172.00f, 370.70f)
                    curveTo(169.30f, 371.50f, 166.20f, 372.20f, 163.60f, 371.90f)
                    curveTo(153.60f, 371.50f, 144.00f, 365.00f, 140.60f, 355.00f)
                    curveTo(136.40f, 342.00f, 143.30f, 327.80f, 156.30f, 323.50f)
                    lineTo(187.40f, 313.10f)
                    lineTo(166.70f, 251.30f)
                    lineTo(135.60f, 261.70f)
                    curveTo(132.90f, 262.50f, 129.80f, 263.20f, 127.20f, 262.90f)
                    curveTo(117.20f, 262.50f, 107.60f, 256.00f, 104.20f, 246.00f)
                    curveTo(100.00f, 233.00f, 106.90f, 218.80f, 119.90f, 214.50f)
                    lineTo(151.00f, 204.10f)
                    lineTo(140.10f, 172.00f)
                    curveTo(135.90f, 159.00f, 142.80f, 144.80f, 155.80f, 140.50f)
                    curveTo(168.80f, 136.30f, 183.00f, 143.20f, 187.30f, 156.20f)
                    lineTo(198.00f, 188.40f)
                    lineTo(262.10f, 166.90f)
                    lineTo(251.40f, 134.70f)
                    curveTo(247.20f, 121.70f, 254.10f, 107.50f, 267.10f, 103.20f)
                    curveTo(280.10f, 99.00f, 294.30f, 105.90f, 298.60f, 118.90f)
                    lineTo(309.30f, 151.10f)
                    lineTo(340.40f, 140.70f)
                    curveTo(353.40f, 136.50f, 367.60f, 143.40f, 371.90f, 156.40f)
                    curveTo(376.10f, 169.40f, 369.20f, 183.60f, 356.20f, 187.90f)
                    lineTo(325.10f, 198.30f)
                    lineTo(345.80f, 260.10f)
                    lineTo(376.90f, 249.70f)
                    curveTo(389.90f, 245.50f, 404.10f, 252.40f, 408.40f, 265.40f)
                    curveTo(412.60f, 278.60f, 405.70f, 292.80f, 392.60f, 297.10f)
                    close()
                }
            }
        }.build()
        return _LogoSlack!!
    }

private var _LogoSlack: ImageVector? = null
