// Generated by XIcons
// 2025-08-14 22:09:01
package cn.enaium.xicons.jfx.icons.fa;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class ClosedCaptioning extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(464.00, 64.00);
        path.horizontalLineTo(48.00);
        path.curveTo(21.50, 64.00, 0.00, 85.50, 0.00, 112.00);
        path.verticalLineTo(400.00);
        path.curveTo(0.00, 426.50, 21.50, 448.00, 48.00, 448.00);
        path.horizontalLineTo(464.00);
        path.curveTo(490.50, 448.00, 512.00, 426.50, 512.00, 400.00);
        path.verticalLineTo(112.00);
        path.curveTo(512.00, 85.50, 490.50, 64.00, 464.00, 64.00);
        path.close();
        path.moveTo(218.10, 287.70);
        path.curveTo(220.90, 285.20, 225.20, 285.60, 227.30, 288.60);
        path.lineTo(246.80, 316.30);
        path.curveTo(248.50, 318.70, 248.30, 321.90, 246.30, 324.00);
        path.curveTo(192.70, 380.80, 73.50, 356.10, 73.50, 256.10);
        path.curveTo(73.50, 158.80, 195.20, 136.60, 246.00, 186.00);
        path.curveTo(248.10, 188.00, 248.50, 189.20, 247.00, 191.70);
        path.lineTo(229.50, 222.20);
        path.curveTo(227.60, 225.30, 223.30, 226.20, 220.40, 223.90);
        path.curveTo(179.60, 191.90, 125.80, 209.00, 125.80, 255.10);
        path.curveTo(125.90, 303.10, 176.90, 325.60, 218.10, 287.70);
        path.close();
        path.moveTo(408.50, 287.70);
        path.curveTo(411.30, 285.20, 415.60, 285.60, 417.70, 288.60);
        path.lineTo(437.20, 316.30);
        path.curveTo(438.90, 318.70, 438.70, 321.90, 436.70, 324.00);
        path.curveTo(383.20, 380.90, 264.00, 356.10, 264.00, 256.10);
        path.curveTo(264.00, 158.80, 385.70, 136.60, 436.50, 186.00);
        path.curveTo(438.60, 188.00, 439.00, 189.20, 437.50, 191.70);
        path.lineTo(420.00, 222.20);
        path.curveTo(418.10, 225.30, 413.80, 226.20, 410.90, 223.90);
        path.curveTo(370.10, 191.90, 316.30, 209.00, 316.30, 255.10);
        path.curveTo(316.30, 303.10, 367.30, 325.60, 408.50, 287.70);
        path.close();
        path.scale(0.046875, 0.046875);
        return path;
    }
}
