// Generated by XIcons
// 2025-08-14 22:09:03
package cn.enaium.xicons.jfx.icons.fa;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class UserTie extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(224.00, 256.00);
        path.curveTo(294.70, 256.00, 352.00, 198.70, 352.00, 128.00);
        path.curveTo(352.00, 57.30, 294.70, 0.00, 224.00, 0.00);
        path.curveTo(153.30, 0.00, 96.00, 57.30, 96.00, 128.00);
        path.curveTo(96.00, 198.70, 153.30, 256.00, 224.00, 256.00);
        path.close();
        path.moveTo(319.80, 288.60);
        path.lineTo(272.00, 480.00);
        path.lineTo(240.00, 344.00);
        path.lineTo(272.00, 288.00);
        path.horizontalLineTo(176.00);
        path.lineTo(208.00, 344.00);
        path.lineTo(176.00, 480.00);
        path.lineTo(128.20, 288.60);
        path.curveTo(56.90, 292.00, 0.00, 350.30, 0.00, 422.40);
        path.verticalLineTo(464.00);
        path.curveTo(0.00, 490.50, 21.50, 512.00, 48.00, 512.00);
        path.horizontalLineTo(400.00);
        path.curveTo(426.50, 512.00, 448.00, 490.50, 448.00, 464.00);
        path.verticalLineTo(422.40);
        path.curveTo(448.00, 350.30, 391.10, 292.00, 319.80, 288.60);
        path.close();
        path.scale(0.05357142857142857, 0.05357142857142857);
        return path;
    }
}
