// Generated by XIcons
// 2025-08-17 11:05:10
package cn.enaium.xicons.compose.tabler

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.TablerIcons

public val TablerIcons.Default.AlertOctagon: ImageVector
    get() {
        if (_AlertOctagon != null) {
            return _AlertOctagon!!
        }
        _AlertOctagon = ImageVector.Builder(
            name = "AlertOctagon",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(8.70f, 3.00f)
                horizontalLineTo(15.30f)
                curveTo(15.60f, 3.00f, 15.80f, 3.10f, 16.00f, 3.30f)
                lineTo(20.70f, 8.00f)
                curveTo(20.90f, 8.20f, 21.00f, 8.40f, 21.00f, 8.70f)
                verticalLineTo(15.30f)
                curveTo(21.00f, 15.60f, 20.90f, 15.80f, 20.70f, 16.00f)
                lineTo(16.00f, 20.70f)
                curveTo(15.80f, 20.90f, 15.60f, 21.00f, 15.30f, 21.00f)
                horizontalLineTo(8.70f)
                curveTo(8.40f, 21.00f, 8.20f, 20.90f, 8.00f, 20.70f)
                lineTo(3.30f, 16.00f)
                curveTo(3.10f, 15.80f, 3.00f, 15.60f, 3.00f, 15.30f)
                verticalLineTo(8.70f)
                curveTo(3.00f, 8.40f, 3.10f, 8.20f, 3.30f, 8.00f)
                lineTo(8.00f, 3.30f)
                curveTo(8.20f, 3.10f, 8.40f, 3.00f, 8.70f, 3.00f)
                close()
                moveTo(12.00f, 8.00f)
                verticalLineTo(12.00f)
                moveTo(12.00f, 16.00f)
                horizontalLineTo(12.01f)
            }
        }.build()
        return _AlertOctagon!!
    }

private var _AlertOctagon: ImageVector? = null
