// Generated by XIcons
// 2025-08-17 11:05:10
package cn.enaium.xicons.compose.tabler

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.TablerIcons

public val TablerIcons.Default.Braces: ImageVector
    get() {
        if (_Braces != null) {
            return _Braces!!
        }
        _Braces = ImageVector.Builder(
            name = "Braces",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(7.00f, 4.00f)
                arcTo(2.00f, 2.00f, 0.00f, false, false, 5.00f, 6.00f)
                verticalLineTo(9.00f)
                arcTo(2.00f, 3.00f, 0.00f, false, true, 3.00f, 12.00f)
                arcTo(2.00f, 3.00f, 0.00f, false, true, 5.00f, 15.00f)
                verticalLineTo(18.00f)
                arcTo(2.00f, 2.00f, 0.00f, false, false, 7.00f, 20.00f)
                moveTo(17.00f, 4.00f)
                arcTo(2.00f, 2.00f, 0.00f, false, true, 19.00f, 6.00f)
                verticalLineTo(9.00f)
                arcTo(2.00f, 3.00f, 0.00f, false, false, 21.00f, 12.00f)
                arcTo(2.00f, 3.00f, 0.00f, false, false, 19.00f, 15.00f)
                verticalLineTo(18.00f)
                arcTo(2.00f, 2.00f, 0.00f, false, true, 17.00f, 20.00f)
            }
        }.build()
        return _Braces!!
    }

private var _Braces: ImageVector? = null
