// Generated by XIcons
// 2025-08-17 11:05:10
package cn.enaium.xicons.compose.tabler

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.TablerIcons

public val TablerIcons.Default.BrandNytimes: ImageVector
    get() {
        if (_BrandNytimes != null) {
            return _BrandNytimes!!
        }
        _BrandNytimes = ImageVector.Builder(
            name = "BrandNytimes",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(11.04f, 5.06f)
                arcTo(8.00f, 8.00f, 0.00f, true, false, 19.74f, 15.02f)
                moveTo(12.00f, 21.00f)
                verticalLineTo(10.00f)
                lineTo(4.50f, 14.00f)
                moveTo(17.50f, 3.00f)
                arcTo(2.50f, 2.50f, 0.00f, true, true, 17.50f, 8.00f)
                lineTo(6.50f, 3.00f)
                arcTo(2.50f, 2.50f, 0.00f, false, false, 5.83f, 7.91f)
                moveTo(9.00f, 12.00f)
                verticalLineTo(20.00f)
                moveTo(16.00f, 13.00f)
                horizontalLineTo(15.99f)
            }
        }.build()
        return _BrandNytimes!!
    }

private var _BrandNytimes: ImageVector? = null
