// Generated by XIcons
// 2025-08-17 11:05:10
package cn.enaium.xicons.compose.tabler

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.TablerIcons

public val TablerIcons.Default.BrandCss3: ImageVector
    get() {
        if (_BrandCss3 != null) {
            return _BrandCss3!!
        }
        _BrandCss3 = ImageVector.Builder(
            name = "BrandCss3",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(20.00f, 4.00f)
                lineTo(18.00f, 18.50f)
                lineTo(12.00f, 20.50f)
                lineTo(6.00f, 18.50f)
                lineTo(4.00f, 4.00f)
                close()
                moveTo(8.50f, 8.00f)
                horizontalLineTo(15.50f)
                lineTo(11.00f, 12.00f)
                horizontalLineTo(15.00f)
                lineTo(14.50f, 15.50f)
                lineTo(12.00f, 16.25f)
                lineTo(9.50f, 15.50f)
                lineTo(9.40f, 15.00f)
            }
        }.build()
        return _BrandCss3!!
    }

private var _BrandCss3: ImageVector? = null
