// Generated by XIcons
// 2025-08-17 11:05:11
package cn.enaium.xicons.compose.tabler

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.TablerIcons

public val TablerIcons.Default.CurrencyNaira: ImageVector
    get() {
        if (_CurrencyNaira != null) {
            return _CurrencyNaira!!
        }
        _CurrencyNaira = ImageVector.Builder(
            name = "CurrencyNaira",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(7.00f, 18.00f)
                verticalLineTo(7.05f)
                arcTo(1.05f, 1.05f, 0.00f, false, true, 8.97f, 6.54f)
                lineTo(15.03f, 17.46f)
                arcTo(1.05f, 1.05f, 0.00f, false, false, 17.00f, 16.95f)
                verticalLineTo(6.00f)
                moveTo(5.00f, 10.00f)
                horizontalLineTo(19.00f)
                moveTo(5.00f, 14.00f)
                horizontalLineTo(19.00f)
            }
        }.build()
        return _CurrencyNaira!!
    }

private var _CurrencyNaira: ImageVector? = null
