// Generated by XIcons
// 2025-08-17 11:05:11
package cn.enaium.xicons.compose.tabler

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.TablerIcons

public val TablerIcons.Default.Eyeglass: ImageVector
    get() {
        if (_Eyeglass != null) {
            return _Eyeglass!!
        }
        _Eyeglass = ImageVector.Builder(
            name = "Eyeglass",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(8.00f, 4.00f)
                horizontalLineTo(6.00f)
                lineTo(3.00f, 14.00f)
                moveTo(16.00f, 4.00f)
                horizontalLineTo(18.00f)
                lineTo(21.00f, 14.00f)
                moveTo(10.00f, 16.00f)
                horizontalLineTo(14.00f)
                moveTo(21.00f, 16.50f)
                arcTo(3.50f, 3.50f, 0.00f, false, true, 14.00f, 16.50f)
                verticalLineTo(14.00f)
                horizontalLineTo(21.00f)
                verticalLineTo(16.50f)
                moveTo(10.00f, 16.50f)
                arcTo(3.50f, 3.50f, 0.00f, false, true, 3.00f, 16.50f)
                verticalLineTo(14.00f)
                horizontalLineTo(10.00f)
                verticalLineTo(16.50f)
            }
        }.build()
        return _Eyeglass!!
    }

private var _Eyeglass: ImageVector? = null
