// Generated by XIcons
// 2025-08-17 11:05:11
package cn.enaium.xicons.compose.tabler

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.TablerIcons

public val TablerIcons.Default.Man: ImageVector
    get() {
        if (_Man != null) {
            return _Man!!
        }
        _Man = ImageVector.Builder(
            name = "Man",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(10.00f, 22.00f)
                verticalLineTo(17.00f)
                lineTo(9.00f, 16.00f)
                verticalLineTo(12.00f)
                arcTo(1.00f, 1.00f, 0.00f, false, true, 10.00f, 11.00f)
                horizontalLineTo(14.00f)
                arcTo(1.00f, 1.00f, 0.00f, false, true, 15.00f, 12.00f)
                verticalLineTo(16.00f)
                lineTo(14.00f, 17.00f)
                verticalLineTo(22.00f)
            }
        }.build()
        return _Man!!
    }

private var _Man: ImageVector? = null
