// Generated by XIcons
// 2025-08-17 11:05:11
package cn.enaium.xicons.compose.tabler

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.TablerIcons

public val TablerIcons.Default.Planet: ImageVector
    get() {
        if (_Planet != null) {
            return _Planet!!
        }
        _Planet = ImageVector.Builder(
            name = "Planet",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(18.82f, 13.58f)
                curveTo(21.11f, 15.72f, 22.36f, 17.58f, 21.91f, 18.48f)
                curveTo(21.16f, 19.94f, 16.12f, 18.22f, 10.65f, 14.64f)
                curveTo(5.18f, 11.06f, 1.35f, 6.98f, 2.09f, 5.52f)
                curveTo(2.56f, 4.61f, 5.02f, 5.08f, 7.90f, 6.32f)
            }
        }.build()
        return _Planet!!
    }

private var _Planet: ImageVector? = null
