// Generated by XIcons
// 2025-08-17 11:05:12
package cn.enaium.xicons.compose.tabler

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.TablerIcons

public val TablerIcons.Default.ZoomQuestion: ImageVector
    get() {
        if (_ZoomQuestion != null) {
            return _ZoomQuestion!!
        }
        _ZoomQuestion = ImageVector.Builder(
            name = "ZoomQuestion",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(21.00f, 21.00f)
                lineTo(15.00f, 15.00f)
                moveTo(10.00f, 13.00f)
                verticalLineTo(13.01f)
                moveTo(10.00f, 10.00f)
                arcTo(1.50f, 1.50f, 0.00f, true, false, 8.86f, 7.53f)
            }
        }.build()
        return _ZoomQuestion!!
    }

private var _ZoomQuestion: ImageVector? = null
