// Generated by XIcons
// 2025-08-17 11:04:40
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Round.AddAlert: ImageVector
    get() {
        if (_AddAlert != null) {
            return _AddAlert!!
        }
        _AddAlert = ImageVector.Builder(
            name = "AddAlert",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(12.00f, 22.00f)
                curveTo(13.10f, 22.00f, 14.00f, 21.10f, 14.00f, 20.00f)
                horizontalLineTo(10.00f)
                curveTo(10.00f, 21.10f, 10.90f, 22.00f, 12.00f, 22.00f)
                close()
                moveTo(19.00f, 17.00f)
                horizontalLineTo(18.00f)
                verticalLineTo(10.00f)
                curveTo(18.00f, 7.21f, 16.09f, 4.86f, 13.50f, 4.20f)
                verticalLineTo(3.50f)
                curveTo(13.50f, 2.67f, 12.83f, 2.00f, 12.00f, 2.00f)
                curveTo(11.17f, 2.00f, 10.50f, 2.67f, 10.50f, 3.50f)
                verticalLineTo(4.20f)
                curveTo(7.91f, 4.86f, 6.00f, 7.21f, 6.00f, 10.00f)
                verticalLineTo(17.00f)
                horizontalLineTo(5.00f)
                curveTo(4.45f, 17.00f, 4.00f, 17.45f, 4.00f, 18.00f)
                curveTo(4.00f, 18.55f, 4.45f, 19.00f, 5.00f, 19.00f)
                horizontalLineTo(19.00f)
                curveTo(19.55f, 19.00f, 20.00f, 18.55f, 20.00f, 18.00f)
                curveTo(20.00f, 17.45f, 19.55f, 17.00f, 19.00f, 17.00f)
                close()
                moveTo(14.00f, 13.00f)
                horizontalLineTo(13.00f)
                verticalLineTo(14.00f)
                curveTo(13.00f, 14.55f, 12.55f, 15.00f, 12.00f, 15.00f)
                curveTo(11.45f, 15.00f, 11.00f, 14.55f, 11.00f, 14.00f)
                verticalLineTo(13.00f)
                horizontalLineTo(10.00f)
                curveTo(9.45f, 13.00f, 9.00f, 12.55f, 9.00f, 12.00f)
                curveTo(9.00f, 11.45f, 9.45f, 11.00f, 10.00f, 11.00f)
                horizontalLineTo(11.00f)
                verticalLineTo(10.00f)
                curveTo(11.00f, 9.45f, 11.45f, 9.00f, 12.00f, 9.00f)
                curveTo(12.55f, 9.00f, 13.00f, 9.45f, 13.00f, 10.00f)
                verticalLineTo(11.00f)
                horizontalLineTo(14.00f)
                curveTo(14.55f, 11.00f, 15.00f, 11.45f, 15.00f, 12.00f)
                curveTo(15.00f, 12.55f, 14.55f, 13.00f, 14.00f, 13.00f)
                close()
            }
        }.build()
        return _AddAlert!!
    }

private var _AddAlert: ImageVector? = null
