// Generated by XIcons
// 2025-08-17 11:04:40
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Round.AddLocationAlt: ImageVector
    get() {
        if (_AddLocationAlt != null) {
            return _AddLocationAlt!!
        }
        _AddLocationAlt = ImageVector.Builder(
            name = "AddLocationAlt",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(19.00f, 0.00f)
                curveTo(19.55f, 0.00f, 20.00f, 0.45f, 20.00f, 1.00f)
                verticalLineTo(3.00f)
                horizontalLineTo(22.00f)
                curveTo(22.55f, 3.00f, 23.00f, 3.45f, 23.00f, 4.00f)
                curveTo(23.00f, 4.55f, 22.55f, 5.00f, 22.00f, 5.00f)
                horizontalLineTo(20.00f)
                verticalLineTo(7.00f)
                curveTo(20.00f, 7.55f, 19.55f, 8.00f, 19.00f, 8.00f)
                curveTo(18.45f, 8.00f, 18.00f, 7.55f, 18.00f, 7.00f)
                verticalLineTo(5.00f)
                horizontalLineTo(16.00f)
                curveTo(15.45f, 5.00f, 15.00f, 4.55f, 15.00f, 4.00f)
                curveTo(15.00f, 3.45f, 15.45f, 3.00f, 16.00f, 3.00f)
                horizontalLineTo(18.00f)
                verticalLineTo(1.00f)
                curveTo(18.00f, 0.45f, 18.45f, 0.00f, 19.00f, 0.00f)
                close()
                moveTo(12.00f, 12.00f)
                curveTo(13.10f, 12.00f, 14.00f, 11.10f, 14.00f, 10.00f)
                curveTo(14.00f, 8.90f, 13.10f, 8.00f, 12.00f, 8.00f)
                curveTo(10.90f, 8.00f, 10.00f, 8.90f, 10.00f, 10.00f)
                curveTo(10.00f, 11.10f, 10.90f, 12.00f, 12.00f, 12.00f)
                close()
                moveTo(14.72f, 2.47f)
                curveTo(14.28f, 2.83f, 14.00f, 3.38f, 14.00f, 4.00f)
                curveTo(14.00f, 5.10f, 14.90f, 6.00f, 16.00f, 6.00f)
                horizontalLineTo(17.00f)
                verticalLineTo(7.00f)
                curveTo(17.00f, 8.10f, 17.90f, 9.00f, 19.00f, 9.00f)
                curveTo(19.32f, 9.00f, 19.62f, 8.92f, 19.89f, 8.79f)
                curveTo(19.96f, 9.24f, 20.00f, 9.71f, 20.00f, 10.20f)
                curveTo(20.00f, 13.38f, 17.55f, 17.12f, 12.66f, 21.43f)
                curveTo(12.28f, 21.76f, 11.71f, 21.76f, 11.33f, 21.43f)
                curveTo(6.45f, 17.12f, 4.00f, 13.38f, 4.00f, 10.20f)
                curveTo(4.00f, 5.22f, 7.80f, 2.00f, 12.00f, 2.00f)
                curveTo(12.94f, 2.00f, 13.86f, 2.16f, 14.72f, 2.47f)
                close()
            }
        }.build()
        return _AddLocationAlt!!
    }

private var _AddLocationAlt: ImageVector? = null
