// Generated by XIcons
// 2025-08-17 11:04:40
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Sharp.AdUnits: ImageVector
    get() {
        if (_AdUnits != null) {
            return _AdUnits!!
        }
        _AdUnits = ImageVector.Builder(
            name = "AdUnits",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(19.00f, 1.00f)
                horizontalLineTo(5.00f)
                verticalLineTo(23.00f)
                horizontalLineTo(19.00f)
                verticalLineTo(1.00f)
                close()
                moveTo(17.00f, 19.00f)
                horizontalLineTo(7.00f)
                verticalLineTo(5.00f)
                horizontalLineTo(17.00f)
                verticalLineTo(19.00f)
                close()
                moveTo(8.00f, 6.00f)
                horizontalLineTo(16.00f)
                verticalLineTo(8.00f)
                horizontalLineTo(8.00f)
                close()
            }
        }.build()
        return _AdUnits!!
    }

private var _AdUnits: ImageVector? = null
