// Generated by XIcons
// 2025-08-17 11:04:41
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Round.AirlineSeatFlat: ImageVector
    get() {
        if (_AirlineSeatFlat != null) {
            return _AirlineSeatFlat!!
        }
        _AirlineSeatFlat = ImageVector.Builder(
            name = "AirlineSeatFlat",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(22.00f, 11.00f)
                verticalLineTo(13.00f)
                horizontalLineTo(9.00f)
                verticalLineTo(9.00f)
                curveTo(9.00f, 7.90f, 9.90f, 7.00f, 11.00f, 7.00f)
                horizontalLineTo(18.00f)
                curveTo(20.21f, 7.00f, 22.00f, 8.79f, 22.00f, 11.00f)
                close()
                moveTo(2.00f, 15.00f)
                curveTo(2.00f, 15.55f, 2.45f, 16.00f, 3.00f, 16.00f)
                horizontalLineTo(8.00f)
                verticalLineTo(17.00f)
                curveTo(8.00f, 17.55f, 8.45f, 18.00f, 9.00f, 18.00f)
                horizontalLineTo(15.00f)
                curveTo(15.55f, 18.00f, 16.00f, 17.55f, 16.00f, 17.00f)
                verticalLineTo(16.00f)
                horizontalLineTo(21.00f)
                curveTo(21.55f, 16.00f, 22.00f, 15.55f, 22.00f, 15.00f)
                curveTo(22.00f, 14.45f, 21.55f, 14.00f, 21.00f, 14.00f)
                horizontalLineTo(3.00f)
                curveTo(2.45f, 14.00f, 2.00f, 14.45f, 2.00f, 15.00f)
                close()
                moveTo(7.14f, 12.10f)
                arcTo(3.00f, 3.00f, 0.00f, false, false, 7.10f, 7.86f)
                arcTo(3.00f, 3.00f, 0.00f, false, false, 2.86f, 7.90f)
                arcTo(3.00f, 3.00f, 0.00f, false, false, 2.90f, 12.14f)
                arcTo(3.00f, 3.00f, 0.00f, false, false, 7.14f, 12.10f)
                close()
            }
        }.build()
        return _AirlineSeatFlat!!
    }

private var _AirlineSeatFlat: ImageVector? = null
