// Generated by XIcons
// 2025-08-17 11:04:42
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Filled.Audiotrack: ImageVector
    get() {
        if (_Audiotrack != null) {
            return _Audiotrack!!
        }
        _Audiotrack = ImageVector.Builder(
            name = "Audiotrack",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(12.00f, 3.00f)
                verticalLineTo(12.28f)
                arcTo(4.39f, 4.39f, 0.00f, false, false, 10.50f, 12.00f)
                curveTo(8.01f, 12.00f, 6.00f, 14.01f, 6.00f, 16.50f)
                curveTo(6.00f, 18.99f, 8.01f, 21.00f, 10.50f, 21.00f)
                curveTo(12.81f, 21.00f, 14.70f, 19.25f, 14.95f, 17.00f)
                horizontalLineTo(15.00f)
                verticalLineTo(6.00f)
                horizontalLineTo(19.00f)
                verticalLineTo(3.00f)
                horizontalLineTo(12.00f)
                close()
            }
        }.build()
        return _Audiotrack!!
    }

private var _Audiotrack: ImageVector? = null
