// Generated by XIcons
// 2025-08-17 11:04:42
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Round.Ballot: ImageVector
    get() {
        if (_Ballot != null) {
            return _Ballot!!
        }
        _Ballot = ImageVector.Builder(
            name = "Ballot",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(14.00f, 9.50f)
                horizontalLineTo(17.00f)
                curveTo(17.55f, 9.50f, 18.00f, 9.05f, 18.00f, 8.50f)
                curveTo(18.00f, 7.95f, 17.55f, 7.50f, 17.00f, 7.50f)
                horizontalLineTo(14.00f)
                curveTo(13.45f, 7.50f, 13.00f, 7.95f, 13.00f, 8.50f)
                curveTo(13.00f, 9.05f, 13.45f, 9.50f, 14.00f, 9.50f)
                close()
                moveTo(14.00f, 16.50f)
                horizontalLineTo(17.00f)
                curveTo(17.55f, 16.50f, 18.00f, 16.05f, 18.00f, 15.50f)
                curveTo(18.00f, 14.95f, 17.55f, 14.50f, 17.00f, 14.50f)
                horizontalLineTo(14.00f)
                curveTo(13.45f, 14.50f, 13.00f, 14.95f, 13.00f, 15.50f)
                curveTo(13.00f, 16.05f, 13.45f, 16.50f, 14.00f, 16.50f)
                close()
                moveTo(19.00f, 21.00f)
                horizontalLineTo(5.00f)
                curveTo(3.90f, 21.00f, 3.00f, 20.10f, 3.00f, 19.00f)
                verticalLineTo(5.00f)
                curveTo(3.00f, 3.90f, 3.90f, 3.00f, 5.00f, 3.00f)
                horizontalLineTo(19.00f)
                curveTo(20.10f, 3.00f, 21.00f, 3.90f, 21.00f, 5.00f)
                verticalLineTo(19.00f)
                curveTo(21.00f, 20.10f, 20.10f, 21.00f, 19.00f, 21.00f)
                close()
                moveTo(7.00f, 11.00f)
                horizontalLineTo(10.00f)
                curveTo(10.55f, 11.00f, 11.00f, 10.55f, 11.00f, 10.00f)
                verticalLineTo(7.00f)
                curveTo(11.00f, 6.45f, 10.55f, 6.00f, 10.00f, 6.00f)
                horizontalLineTo(7.00f)
                curveTo(6.45f, 6.00f, 6.00f, 6.45f, 6.00f, 7.00f)
                verticalLineTo(10.00f)
                curveTo(6.00f, 10.55f, 6.45f, 11.00f, 7.00f, 11.00f)
                close()
                moveTo(7.00f, 7.00f)
                horizontalLineTo(10.00f)
                verticalLineTo(10.00f)
                horizontalLineTo(7.00f)
                verticalLineTo(7.00f)
                close()
                moveTo(7.00f, 18.00f)
                horizontalLineTo(10.00f)
                curveTo(10.55f, 18.00f, 11.00f, 17.55f, 11.00f, 17.00f)
                verticalLineTo(14.00f)
                curveTo(11.00f, 13.45f, 10.55f, 13.00f, 10.00f, 13.00f)
                horizontalLineTo(7.00f)
                curveTo(6.45f, 13.00f, 6.00f, 13.45f, 6.00f, 14.00f)
                verticalLineTo(17.00f)
                curveTo(6.00f, 17.55f, 6.45f, 18.00f, 7.00f, 18.00f)
                close()
                moveTo(7.00f, 14.00f)
                horizontalLineTo(10.00f)
                verticalLineTo(17.00f)
                horizontalLineTo(7.00f)
                verticalLineTo(14.00f)
                close()
            }
        }.build()
        return _Ballot!!
    }

private var _Ballot: ImageVector? = null
