// Generated by XIcons
// 2025-08-17 11:04:43
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Outlined.Bookmark: ImageVector
    get() {
        if (_Bookmark != null) {
            return _Bookmark!!
        }
        _Bookmark = ImageVector.Builder(
            name = "Bookmark",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(17.00f, 3.00f)
                horizontalLineTo(7.00f)
                curveTo(5.90f, 3.00f, 5.00f, 3.90f, 5.00f, 5.00f)
                verticalLineTo(21.00f)
                lineTo(12.00f, 18.00f)
                lineTo(19.00f, 21.00f)
                verticalLineTo(5.00f)
                curveTo(19.00f, 3.90f, 18.10f, 3.00f, 17.00f, 3.00f)
                close()
            }
        }.build()
        return _Bookmark!!
    }

private var _Bookmark: ImageVector? = null
