// Generated by XIcons
// 2025-08-17 11:04:43
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Twotone.BookOnline: ImageVector
    get() {
        if (_BookOnline != null) {
            return _BookOnline!!
        }
        _BookOnline = ImageVector.Builder(
            name = "BookOnline",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(17.00f, 4.00f)
                horizontalLineTo(7.00f)
                verticalLineTo(3.00f)
                horizontalLineTo(17.00f)
                verticalLineTo(4.00f)
                close()
                moveTo(17.00f, 21.00f)
                horizontalLineTo(7.00f)
                verticalLineTo(20.00f)
                horizontalLineTo(17.00f)
                verticalLineTo(21.00f)
                close()
                moveTo(17.00f, 4.00f)
                horizontalLineTo(7.00f)
                verticalLineTo(3.00f)
                horizontalLineTo(17.00f)
                verticalLineTo(4.00f)
                close()
                moveTo(17.00f, 21.00f)
                horizontalLineTo(7.00f)
                verticalLineTo(20.00f)
                horizontalLineTo(17.00f)
                verticalLineTo(21.00f)
                close()
                moveTo(17.00f, 1.00f)
                horizontalLineTo(7.00f)
                curveTo(5.90f, 1.00f, 5.00f, 1.90f, 5.00f, 3.00f)
                verticalLineTo(21.00f)
                curveTo(5.00f, 22.10f, 5.90f, 23.00f, 7.00f, 23.00f)
                horizontalLineTo(17.00f)
                curveTo(18.10f, 23.00f, 19.00f, 22.10f, 19.00f, 21.00f)
                verticalLineTo(3.00f)
                curveTo(19.00f, 1.90f, 18.10f, 1.00f, 17.00f, 1.00f)
                close()
                moveTo(7.00f, 6.00f)
                horizontalLineTo(17.00f)
                verticalLineTo(18.00f)
                horizontalLineTo(7.00f)
                verticalLineTo(6.00f)
                close()
                moveTo(16.00f, 11.00f)
                verticalLineTo(9.14f)
                curveTo(16.00f, 8.51f, 15.55f, 8.00f, 15.00f, 8.00f)
                horizontalLineTo(9.00f)
                curveTo(8.45f, 8.00f, 8.00f, 8.51f, 8.00f, 9.14f)
                verticalLineTo(11.10f)
                curveTo(8.55f, 11.10f, 9.00f, 11.55f, 9.00f, 12.10f)
                curveTo(9.00f, 12.65f, 8.55f, 13.10f, 8.00f, 13.10f)
                verticalLineTo(14.86f)
                curveTo(8.00f, 15.49f, 8.45f, 16.00f, 9.00f, 16.00f)
                horizontalLineTo(15.00f)
                curveTo(15.55f, 16.00f, 16.00f, 15.49f, 16.00f, 14.86f)
                verticalLineTo(13.00f)
                curveTo(15.45f, 13.00f, 15.00f, 12.55f, 15.00f, 12.00f)
                curveTo(15.00f, 11.45f, 15.45f, 11.00f, 16.00f, 11.00f)
                close()
                moveTo(12.50f, 14.50f)
                horizontalLineTo(11.50f)
                verticalLineTo(13.50f)
                horizontalLineTo(12.50f)
                verticalLineTo(14.50f)
                close()
                moveTo(12.50f, 12.50f)
                horizontalLineTo(11.50f)
                verticalLineTo(11.50f)
                horizontalLineTo(12.50f)
                verticalLineTo(12.50f)
                close()
                moveTo(12.50f, 10.50f)
                horizontalLineTo(11.50f)
                verticalLineTo(9.50f)
                horizontalLineTo(12.50f)
                verticalLineTo(10.50f)
                close()
            }
        }.build()
        return _BookOnline!!
    }

private var _BookOnline: ImageVector? = null
