// Generated by XIcons
// 2025-08-17 11:04:43
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Twotone.BrokenImage: ImageVector
    get() {
        if (_BrokenImage != null) {
            return _BrokenImage!!
        }
        _BrokenImage = ImageVector.Builder(
            name = "BrokenImage",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(13.99f, 15.41f)
                lineTo(9.99f, 11.41f)
                lineTo(5.99f, 15.41f)
                lineTo(5.00f, 14.42f)
                verticalLineTo(19.00f)
                horizontalLineTo(19.00f)
                verticalLineTo(12.43f)
                lineTo(17.99f, 11.42f)
                close()
                moveTo(5.00f, 11.59f)
                lineTo(5.99f, 12.59f)
                lineTo(9.99f, 8.59f)
                lineTo(13.99f, 12.59f)
                lineTo(17.99f, 8.58f)
                lineTo(19.00f, 9.59f)
                verticalLineTo(5.00f)
                horizontalLineTo(5.00f)
                close()
                moveTo(19.00f, 3.00f)
                horizontalLineTo(5.00f)
                curveTo(3.90f, 3.00f, 3.00f, 3.90f, 3.00f, 5.00f)
                verticalLineTo(19.00f)
                curveTo(3.00f, 20.10f, 3.90f, 21.00f, 5.00f, 21.00f)
                horizontalLineTo(19.00f)
                curveTo(20.10f, 21.00f, 21.00f, 20.10f, 21.00f, 19.00f)
                verticalLineTo(5.00f)
                curveTo(21.00f, 3.90f, 20.10f, 3.00f, 19.00f, 3.00f)
                close()
                moveTo(19.00f, 19.00f)
                horizontalLineTo(5.00f)
                verticalLineTo(14.42f)
                lineTo(5.99f, 15.41f)
                lineTo(9.99f, 11.41f)
                lineTo(13.99f, 15.41f)
                lineTo(17.99f, 11.42f)
                lineTo(19.00f, 12.43f)
                verticalLineTo(19.00f)
                close()
                moveTo(19.00f, 9.59f)
                lineTo(17.99f, 8.58f)
                lineTo(13.99f, 12.59f)
                lineTo(9.99f, 8.59f)
                lineTo(5.99f, 12.59f)
                lineTo(5.00f, 11.59f)
                verticalLineTo(5.00f)
                horizontalLineTo(19.00f)
                verticalLineTo(9.59f)
                close()
            }
        }.build()
        return _BrokenImage!!
    }

private var _BrokenImage: ImageVector? = null
