// Generated by XIcons
// 2025-08-17 11:04:44
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Outlined.Calculate: ImageVector
    get() {
        if (_Calculate != null) {
            return _Calculate!!
        }
        _Calculate = ImageVector.Builder(
            name = "Calculate",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(19.00f, 3.00f)
                horizontalLineTo(5.00f)
                curveTo(3.90f, 3.00f, 3.00f, 3.90f, 3.00f, 5.00f)
                verticalLineTo(19.00f)
                curveTo(3.00f, 20.10f, 3.90f, 21.00f, 5.00f, 21.00f)
                horizontalLineTo(19.00f)
                curveTo(20.10f, 21.00f, 21.00f, 20.10f, 21.00f, 19.00f)
                verticalLineTo(5.00f)
                curveTo(21.00f, 3.90f, 20.10f, 3.00f, 19.00f, 3.00f)
                close()
                moveTo(19.00f, 19.00f)
                horizontalLineTo(5.00f)
                verticalLineTo(5.00f)
                horizontalLineTo(19.00f)
                verticalLineTo(19.00f)
                close()
                moveTo(6.25f, 7.72f)
                horizontalLineTo(11.25f)
                verticalLineTo(9.22f)
                horizontalLineTo(6.25f)
                close()
                moveTo(13.00f, 15.75f)
                horizontalLineTo(18.00f)
                verticalLineTo(17.25f)
                horizontalLineTo(13.00f)
                close()
                moveTo(13.00f, 13.25f)
                horizontalLineTo(18.00f)
                verticalLineTo(14.75f)
                horizontalLineTo(13.00f)
                close()
                moveTo(8.00f, 18.00f)
                horizontalLineTo(9.50f)
                verticalLineTo(16.00f)
                horizontalLineTo(11.50f)
                verticalLineTo(14.50f)
                horizontalLineTo(9.50f)
                verticalLineTo(12.50f)
                horizontalLineTo(8.00f)
                verticalLineTo(14.50f)
                horizontalLineTo(6.00f)
                verticalLineTo(16.00f)
                horizontalLineTo(8.00f)
                close()
                moveTo(14.09f, 10.95f)
                lineTo(15.50f, 9.54f)
                lineTo(16.91f, 10.95f)
                lineTo(17.97f, 9.89f)
                lineTo(16.56f, 8.47f)
                lineTo(17.97f, 7.06f)
                lineTo(16.91f, 6.00f)
                lineTo(15.50f, 7.41f)
                lineTo(14.09f, 6.00f)
                lineTo(13.03f, 7.06f)
                lineTo(14.44f, 8.47f)
                lineTo(13.03f, 9.89f)
                close()
            }
        }.build()
        return _Calculate!!
    }

private var _Calculate: ImageVector? = null
