// Generated by XIcons
// 2025-08-17 11:04:44
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Twotone.CameraAlt: ImageVector
    get() {
        if (_CameraAlt != null) {
            return _CameraAlt!!
        }
        _CameraAlt = ImageVector.Builder(
            name = "CameraAlt",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(14.12f, 4.00f)
                horizontalLineTo(9.88f)
                lineTo(8.05f, 6.00f)
                horizontalLineTo(4.00f)
                verticalLineTo(18.00f)
                horizontalLineTo(20.00f)
                verticalLineTo(6.00f)
                horizontalLineTo(15.95f)
                lineTo(14.12f, 4.00f)
                close()
                moveTo(12.00f, 17.00f)
                curveTo(9.24f, 17.00f, 7.00f, 14.76f, 7.00f, 12.00f)
                curveTo(7.00f, 9.24f, 9.24f, 7.00f, 12.00f, 7.00f)
                curveTo(14.76f, 7.00f, 17.00f, 9.24f, 17.00f, 12.00f)
                curveTo(17.00f, 14.76f, 14.76f, 17.00f, 12.00f, 17.00f)
                close()
                moveTo(20.00f, 4.00f)
                horizontalLineTo(16.83f)
                lineTo(15.00f, 2.00f)
                horizontalLineTo(9.00f)
                lineTo(7.17f, 4.00f)
                horizontalLineTo(4.00f)
                curveTo(2.90f, 4.00f, 2.00f, 4.90f, 2.00f, 6.00f)
                verticalLineTo(18.00f)
                curveTo(2.00f, 19.10f, 2.90f, 20.00f, 4.00f, 20.00f)
                horizontalLineTo(20.00f)
                curveTo(21.10f, 20.00f, 22.00f, 19.10f, 22.00f, 18.00f)
                verticalLineTo(6.00f)
                curveTo(22.00f, 4.90f, 21.10f, 4.00f, 20.00f, 4.00f)
                close()
                moveTo(20.00f, 18.00f)
                horizontalLineTo(4.00f)
                verticalLineTo(6.00f)
                horizontalLineTo(8.05f)
                lineTo(9.88f, 4.00f)
                horizontalLineTo(14.12f)
                lineTo(15.95f, 6.00f)
                horizontalLineTo(20.00f)
                verticalLineTo(18.00f)
                close()
                moveTo(12.00f, 7.00f)
                curveTo(9.24f, 7.00f, 7.00f, 9.24f, 7.00f, 12.00f)
                curveTo(7.00f, 14.76f, 9.24f, 17.00f, 12.00f, 17.00f)
                curveTo(14.76f, 17.00f, 17.00f, 14.76f, 17.00f, 12.00f)
                curveTo(17.00f, 9.24f, 14.76f, 7.00f, 12.00f, 7.00f)
                close()
                moveTo(12.00f, 15.00f)
                curveTo(10.35f, 15.00f, 9.00f, 13.65f, 9.00f, 12.00f)
                curveTo(9.00f, 10.35f, 10.35f, 9.00f, 12.00f, 9.00f)
                curveTo(13.65f, 9.00f, 15.00f, 10.35f, 15.00f, 12.00f)
                curveTo(15.00f, 13.65f, 13.65f, 15.00f, 12.00f, 15.00f)
                close()
            }
        }.build()
        return _CameraAlt!!
    }

private var _CameraAlt: ImageVector? = null
