// Generated by XIcons
// 2025-08-17 11:04:44
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Filled.CarRepair: ImageVector
    get() {
        if (_CarRepair != null) {
            return _CarRepair!!
        }
        _CarRepair = ImageVector.Builder(
            name = "CarRepair",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(16.22f, 12.00f)
                curveTo(16.90f, 12.00f, 17.44f, 11.46f, 17.44f, 10.78f)
                curveTo(17.44f, 10.11f, 16.90f, 9.56f, 16.22f, 9.56f)
                curveTo(15.54f, 9.56f, 15.00f, 10.11f, 15.00f, 10.78f)
                curveTo(15.00f, 11.46f, 15.55f, 12.00f, 16.22f, 12.00f)
                close()
                moveTo(6.56f, 10.78f)
                curveTo(6.56f, 11.45f, 7.10f, 12.00f, 7.78f, 12.00f)
                curveTo(8.46f, 12.00f, 9.00f, 11.46f, 9.00f, 10.78f)
                curveTo(9.00f, 10.11f, 8.46f, 9.56f, 7.78f, 9.56f)
                curveTo(7.10f, 9.56f, 6.56f, 10.11f, 6.56f, 10.78f)
                close()
                moveTo(7.61f, 4.00f)
                lineTo(6.28f, 8.00f)
                horizontalLineTo(17.71f)
                lineTo(16.38f, 4.00f)
                horizontalLineTo(7.61f)
                close()
                moveTo(16.28f, 3.00f)
                curveTo(16.28f, 3.00f, 16.82f, 3.01f, 17.20f, 3.54f)
                curveTo(17.22f, 3.56f, 17.23f, 3.58f, 17.25f, 3.61f)
                curveTo(17.32f, 3.72f, 17.39f, 3.85f, 17.44f, 4.01f)
                curveTo(17.66f, 4.66f, 19.00f, 8.69f, 19.00f, 8.69f)
                verticalLineTo(15.19f)
                curveTo(19.00f, 15.64f, 18.65f, 16.00f, 18.22f, 16.00f)
                horizontalLineTo(17.78f)
                curveTo(17.35f, 16.00f, 17.00f, 15.64f, 17.00f, 15.19f)
                verticalLineTo(14.00f)
                horizontalLineTo(7.00f)
                verticalLineTo(15.19f)
                curveTo(7.00f, 15.64f, 6.65f, 16.00f, 6.22f, 16.00f)
                horizontalLineTo(5.78f)
                curveTo(5.35f, 16.00f, 5.00f, 15.64f, 5.00f, 15.19f)
                verticalLineTo(8.69f)
                curveTo(5.00f, 8.69f, 6.34f, 4.67f, 6.55f, 4.00f)
                curveTo(6.60f, 3.84f, 6.67f, 3.72f, 6.74f, 3.60f)
                curveTo(6.77f, 3.58f, 6.78f, 3.56f, 6.80f, 3.54f)
                curveTo(7.18f, 3.01f, 7.72f, 3.00f, 7.72f, 3.00f)
                horizontalLineTo(16.28f)
                close()
                moveTo(4.00f, 17.01f)
                horizontalLineTo(20.00f)
                verticalLineTo(19.00f)
                horizontalLineTo(13.00f)
                verticalLineTo(22.00f)
                horizontalLineTo(11.00f)
                verticalLineTo(19.00f)
                horizontalLineTo(4.00f)
                verticalLineTo(17.01f)
                close()
            }
        }.build()
        return _CarRepair!!
    }

private var _CarRepair: ImageVector? = null
