// Generated by XIcons
// 2025-08-17 11:04:45
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Round.ChevronLeft: ImageVector
    get() {
        if (_ChevronLeft != null) {
            return _ChevronLeft!!
        }
        _ChevronLeft = ImageVector.Builder(
            name = "ChevronLeft",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(14.71f, 6.71f)
                arcTo(1.00f, 1.00f, 0.00f, false, false, 13.30f, 6.71f)
                lineTo(8.71f, 11.30f)
                arcTo(1.00f, 1.00f, 0.00f, false, false, 8.71f, 12.71f)
                lineTo(13.30f, 17.30f)
                arcTo(1.00f, 1.00f, 0.00f, true, false, 14.71f, 15.89f)
                lineTo(10.83f, 12.00f)
                lineTo(14.71f, 8.12f)
                curveTo(15.10f, 7.73f, 15.09f, 7.09f, 14.71f, 6.71f)
                close()
            }
        }.build()
        return _ChevronLeft!!
    }

private var _ChevronLeft: ImageVector? = null
