// Generated by XIcons
// 2025-08-17 11:04:45
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Round.CloseFullscreen: ImageVector
    get() {
        if (_CloseFullscreen != null) {
            return _CloseFullscreen!!
        }
        _CloseFullscreen = ImageVector.Builder(
            name = "CloseFullscreen",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(21.29f, 4.12f)
                lineTo(16.70f, 8.71f)
                lineTo(18.29f, 10.30f)
                curveTo(18.92f, 10.93f, 18.47f, 12.01f, 17.58f, 12.01f)
                horizontalLineTo(13.00f)
                curveTo(12.45f, 12.01f, 12.00f, 11.56f, 12.00f, 11.01f)
                verticalLineTo(6.41f)
                curveTo(12.00f, 5.52f, 13.08f, 5.07f, 13.71f, 5.70f)
                lineTo(15.30f, 7.29f)
                lineTo(19.89f, 2.70f)
                arcTo(1.00f, 1.00f, 0.00f, false, true, 21.30f, 2.70f)
                curveTo(21.68f, 3.10f, 21.68f, 3.73f, 21.29f, 4.12f)
                close()
                moveTo(4.12f, 21.29f)
                lineTo(8.71f, 16.70f)
                lineTo(10.30f, 18.29f)
                curveTo(10.93f, 18.92f, 12.01f, 18.47f, 12.01f, 17.58f)
                verticalLineTo(13.00f)
                curveTo(12.01f, 12.45f, 11.56f, 12.00f, 11.01f, 12.00f)
                horizontalLineTo(6.41f)
                curveTo(5.52f, 12.00f, 5.07f, 13.08f, 5.70f, 13.71f)
                lineTo(7.29f, 15.30f)
                lineTo(2.70f, 19.89f)
                arcTo(1.00f, 1.00f, 0.00f, false, false, 2.70f, 21.30f)
                curveTo(3.10f, 21.68f, 3.73f, 21.68f, 4.12f, 21.29f)
                close()
            }
        }.build()
        return _CloseFullscreen!!
    }

private var _CloseFullscreen: ImageVector? = null
