// Generated by XIcons
// 2025-08-17 11:04:46
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Twotone.CrueltyFree: ImageVector
    get() {
        if (_CrueltyFree != null) {
            return _CrueltyFree!!
        }
        _CrueltyFree = ImageVector.Builder(
            name = "CrueltyFree",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(16.88f, 4.03f)
                curveTo(16.94f, 4.20f, 17.00f, 4.51f, 17.00f, 5.00f)
                curveTo(17.00f, 7.84f, 15.89f, 10.24f, 14.93f, 11.78f)
                curveTo(14.55f, 11.52f, 14.10f, 11.30f, 13.53f, 11.16f)
                curveTo(13.77f, 6.64f, 15.97f, 4.33f, 16.88f, 4.03f)
                close()
                moveTo(7.00f, 5.00f)
                curveTo(7.00f, 4.51f, 7.06f, 4.20f, 7.12f, 4.03f)
                curveTo(8.03f, 4.33f, 10.23f, 6.64f, 10.48f, 11.16f)
                curveTo(9.90f, 11.30f, 9.45f, 11.51f, 9.08f, 11.78f)
                curveTo(8.11f, 10.24f, 7.00f, 7.84f, 7.00f, 5.00f)
                close()
                moveTo(16.00f, 15.77f)
                curveTo(15.56f, 15.41f, 15.39f, 15.25f, 14.70f, 14.40f)
                curveTo(13.94f, 13.45f, 13.61f, 13.00f, 12.00f, 13.00f)
                curveTo(10.39f, 13.00f, 10.06f, 13.45f, 9.30f, 14.40f)
                curveTo(8.61f, 15.25f, 8.44f, 15.41f, 8.00f, 15.77f)
                curveTo(7.43f, 16.26f, 7.00f, 16.80f, 7.00f, 17.50f)
                arcTo(2.50f, 2.50f, 0.00f, false, false, 9.50f, 20.00f)
                curveTo(10.50f, 20.00f, 11.30f, 19.67f, 11.72f, 19.44f)
                curveTo(11.30f, 19.26f, 11.00f, 18.73f, 11.00f, 18.50f)
                curveTo(11.00f, 18.22f, 11.45f, 18.00f, 12.00f, 18.00f)
                curveTo(12.55f, 18.00f, 13.00f, 18.22f, 13.00f, 18.50f)
                curveTo(13.00f, 18.73f, 12.70f, 19.26f, 12.28f, 19.44f)
                curveTo(12.70f, 19.67f, 13.50f, 20.00f, 14.50f, 20.00f)
                arcTo(2.50f, 2.50f, 0.00f, false, false, 17.00f, 17.50f)
                curveTo(17.00f, 16.80f, 16.57f, 16.26f, 16.00f, 15.77f)
                close()
                moveTo(10.50f, 16.75f)
                curveTo(10.22f, 16.75f, 10.00f, 16.41f, 10.00f, 16.00f)
                curveTo(10.00f, 15.59f, 10.22f, 15.25f, 10.50f, 15.25f)
                curveTo(10.78f, 15.25f, 11.00f, 15.59f, 11.00f, 16.00f)
                curveTo(11.00f, 16.41f, 10.78f, 16.75f, 10.50f, 16.75f)
                close()
                moveTo(13.50f, 16.75f)
                curveTo(13.22f, 16.75f, 13.00f, 16.41f, 13.00f, 16.00f)
                curveTo(13.00f, 15.59f, 13.22f, 15.25f, 13.50f, 15.25f)
                curveTo(13.78f, 15.25f, 14.00f, 15.59f, 14.00f, 16.00f)
                curveTo(14.00f, 16.41f, 13.78f, 16.75f, 13.50f, 16.75f)
                close()
                moveTo(17.00f, 14.00f)
                curveTo(16.76f, 13.76f, 16.56f, 13.51f, 16.35f, 13.25f)
                curveTo(17.51f, 11.50f, 19.00f, 8.56f, 19.00f, 5.00f)
                curveTo(19.00f, 3.05f, 18.26f, 2.00f, 17.00f, 2.00f)
                curveTo(15.46f, 2.00f, 13.04f, 4.06f, 12.00f, 7.97f)
                curveTo(10.96f, 4.06f, 8.54f, 2.00f, 7.00f, 2.00f)
                curveTo(5.74f, 2.00f, 5.00f, 3.05f, 5.00f, 5.00f)
                curveTo(5.00f, 8.56f, 6.49f, 11.50f, 7.65f, 13.25f)
                curveTo(7.44f, 13.51f, 7.24f, 13.76f, 7.00f, 14.00f)
                curveTo(6.75f, 14.25f, 5.00f, 15.39f, 5.00f, 17.50f)
                curveTo(5.00f, 19.98f, 7.02f, 22.00f, 9.50f, 22.00f)
                curveTo(11.00f, 22.00f, 12.00f, 21.50f, 12.00f, 21.50f)
                curveTo(12.00f, 21.50f, 13.00f, 22.00f, 14.50f, 22.00f)
                curveTo(16.98f, 22.00f, 19.00f, 19.98f, 19.00f, 17.50f)
                curveTo(19.00f, 15.39f, 17.25f, 14.25f, 17.00f, 14.00f)
                close()
                moveTo(16.88f, 4.03f)
                curveTo(16.94f, 4.20f, 17.00f, 4.51f, 17.00f, 5.00f)
                curveTo(17.00f, 7.84f, 15.89f, 10.24f, 14.93f, 11.78f)
                curveTo(14.55f, 11.52f, 14.10f, 11.30f, 13.53f, 11.16f)
                curveTo(13.77f, 6.64f, 15.97f, 4.33f, 16.88f, 4.03f)
                close()
                moveTo(7.00f, 5.00f)
                curveTo(7.00f, 4.51f, 7.06f, 4.20f, 7.12f, 4.03f)
                curveTo(8.03f, 4.33f, 10.23f, 6.64f, 10.48f, 11.16f)
                curveTo(9.90f, 11.30f, 9.45f, 11.51f, 9.08f, 11.78f)
                curveTo(8.11f, 10.24f, 7.00f, 7.84f, 7.00f, 5.00f)
                close()
                moveTo(14.50f, 20.00f)
                curveTo(13.50f, 20.00f, 12.70f, 19.67f, 12.28f, 19.44f)
                curveTo(12.70f, 19.26f, 13.00f, 18.73f, 13.00f, 18.50f)
                curveTo(13.00f, 18.22f, 12.55f, 18.00f, 12.00f, 18.00f)
                curveTo(11.45f, 18.00f, 11.00f, 18.22f, 11.00f, 18.50f)
                curveTo(11.00f, 18.73f, 11.30f, 19.26f, 11.72f, 19.44f)
                curveTo(11.30f, 19.67f, 10.50f, 20.00f, 9.50f, 20.00f)
                arcTo(2.50f, 2.50f, 0.00f, false, true, 7.00f, 17.50f)
                curveTo(7.00f, 16.80f, 7.43f, 16.26f, 8.00f, 15.77f)
                curveTo(8.44f, 15.41f, 8.61f, 15.25f, 9.30f, 14.40f)
                curveTo(10.06f, 13.45f, 10.39f, 13.00f, 12.00f, 13.00f)
                curveTo(13.61f, 13.00f, 13.94f, 13.45f, 14.70f, 14.40f)
                curveTo(15.39f, 15.25f, 15.56f, 15.41f, 16.00f, 15.77f)
                curveTo(16.57f, 16.26f, 17.00f, 16.80f, 17.00f, 17.50f)
                arcTo(2.50f, 2.50f, 0.00f, false, true, 14.50f, 20.00f)
                close()
                moveTo(14.00f, 16.00f)
                curveTo(14.00f, 16.41f, 13.78f, 16.75f, 13.50f, 16.75f)
                curveTo(13.22f, 16.75f, 13.00f, 16.41f, 13.00f, 16.00f)
                curveTo(13.00f, 15.59f, 13.22f, 15.25f, 13.50f, 15.25f)
                curveTo(13.78f, 15.25f, 14.00f, 15.59f, 14.00f, 16.00f)
                close()
                moveTo(11.00f, 16.00f)
                curveTo(11.00f, 16.41f, 10.78f, 16.75f, 10.50f, 16.75f)
                curveTo(10.22f, 16.75f, 10.00f, 16.41f, 10.00f, 16.00f)
                curveTo(10.00f, 15.59f, 10.22f, 15.25f, 10.50f, 15.25f)
                curveTo(10.78f, 15.25f, 11.00f, 15.59f, 11.00f, 16.00f)
                close()
            }
        }.build()
        return _CrueltyFree!!
    }

private var _CrueltyFree: ImageVector? = null
