// Generated by XIcons
// 2025-08-17 11:04:47
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Twotone.Details: ImageVector
    get() {
        if (_Details != null) {
            return _Details!!
        }
        _Details = ImageVector.Builder(
            name = "Details",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(13.00f, 8.92f)
                lineTo(18.60f, 19.00f)
                horizontalLineTo(13.00f)
                verticalLineTo(8.92f)
                close()
                moveTo(11.00f, 8.92f)
                verticalLineTo(19.00f)
                horizontalLineTo(5.40f)
                lineTo(11.00f, 8.92f)
                close()
                moveTo(12.00f, 3.00f)
                lineTo(2.00f, 21.00f)
                horizontalLineTo(22.00f)
                lineTo(12.00f, 3.00f)
                close()
                moveTo(13.00f, 8.92f)
                lineTo(18.60f, 19.00f)
                horizontalLineTo(13.00f)
                verticalLineTo(8.92f)
                close()
                moveTo(11.00f, 8.92f)
                verticalLineTo(19.00f)
                horizontalLineTo(5.40f)
                lineTo(11.00f, 8.92f)
                close()
            }
        }.build()
        return _Details!!
    }

private var _Details: ImageVector? = null
