// Generated by XIcons
// 2025-08-17 11:04:47
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Outlined.DeveloperBoardOff: ImageVector
    get() {
        if (_DeveloperBoardOff != null) {
            return _DeveloperBoardOff!!
        }
        _DeveloperBoardOff = ImageVector.Builder(
            name = "DeveloperBoardOff",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(7.83f, 5.00f)
                horizontalLineTo(18.00f)
                verticalLineTo(15.17f)
                lineTo(19.83f, 17.00f)
                horizontalLineTo(22.00f)
                verticalLineTo(15.00f)
                horizontalLineTo(20.00f)
                verticalLineTo(13.00f)
                horizontalLineTo(22.00f)
                verticalLineTo(11.00f)
                horizontalLineTo(20.00f)
                verticalLineTo(9.00f)
                horizontalLineTo(22.00f)
                verticalLineTo(7.00f)
                horizontalLineTo(20.00f)
                verticalLineTo(5.00f)
                curveTo(20.00f, 3.90f, 19.10f, 3.00f, 18.00f, 3.00f)
                horizontalLineTo(5.83f)
                lineTo(7.83f, 5.00f)
                close()
                moveTo(12.00f, 9.17f)
                verticalLineTo(7.00f)
                horizontalLineTo(16.00f)
                verticalLineTo(10.00f)
                horizontalLineTo(12.83f)
                lineTo(12.00f, 9.17f)
                close()
                moveTo(9.83f, 7.00f)
                horizontalLineTo(11.00f)
                verticalLineTo(8.17f)
                lineTo(9.83f, 7.00f)
                close()
                moveTo(13.83f, 11.00f)
                horizontalLineTo(16.00f)
                verticalLineTo(13.17f)
                lineTo(13.83f, 11.00f)
                close()
                moveTo(18.00f, 21.00f)
                curveTo(18.06f, 21.00f, 18.11f, 21.00f, 18.16f, 20.99f)
                lineTo(20.48f, 23.31f)
                lineTo(21.89f, 21.90f)
                lineTo(2.10f, 2.10f)
                lineTo(0.69f, 3.51f)
                lineTo(2.01f, 4.83f)
                curveTo(2.00f, 4.89f, 2.00f, 4.94f, 2.00f, 5.00f)
                verticalLineTo(19.00f)
                curveTo(2.00f, 20.10f, 2.90f, 21.00f, 4.00f, 21.00f)
                horizontalLineTo(18.00f)
                close()
                moveTo(4.00f, 19.00f)
                verticalLineTo(6.83f)
                lineTo(6.00f, 8.83f)
                verticalLineTo(12.00f)
                horizontalLineTo(9.17f)
                lineTo(10.17f, 13.00f)
                horizontalLineTo(6.00f)
                verticalLineTo(17.00f)
                horizontalLineTo(11.00f)
                verticalLineTo(13.83f)
                lineTo(12.00f, 14.83f)
                verticalLineTo(17.00f)
                horizontalLineTo(14.17f)
                lineTo(16.17f, 19.00f)
                horizontalLineTo(4.00f)
                close()
            }
        }.build()
        return _DeveloperBoardOff!!
    }

private var _DeveloperBoardOff: ImageVector? = null
