// Generated by XIcons
// 2025-08-17 11:04:49
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Round.Elderly: ImageVector
    get() {
        if (_Elderly != null) {
            return _Elderly!!
        }
        _Elderly = ImageVector.Builder(
            name = "Elderly",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(11.50f, 3.50f)
                curveTo(11.50f, 2.40f, 12.40f, 1.50f, 13.50f, 1.50f)
                curveTo(14.60f, 1.50f, 15.50f, 2.40f, 15.50f, 3.50f)
                curveTo(15.50f, 4.60f, 14.60f, 5.50f, 13.50f, 5.50f)
                curveTo(12.40f, 5.50f, 11.50f, 4.60f, 11.50f, 3.50f)
                close()
                moveTo(18.53f, 11.00f)
                curveTo(16.96f, 11.01f, 15.59f, 10.10f, 14.93f, 8.79f)
                lineTo(14.14f, 7.12f)
                curveTo(13.97f, 6.77f, 13.70f, 6.47f, 13.34f, 6.27f)
                arcTo(2.00f, 2.00f, 0.00f, false, false, 11.40f, 6.24f)
                verticalLineTo(6.23f)
                lineTo(7.01f, 8.73f)
                curveTo(6.39f, 9.08f, 6.00f, 9.74f, 6.00f, 10.46f)
                verticalLineTo(13.00f)
                curveTo(6.00f, 13.55f, 6.45f, 14.00f, 7.00f, 14.00f)
                curveTo(7.55f, 14.00f, 8.00f, 13.55f, 8.00f, 13.00f)
                verticalLineTo(10.46f)
                lineTo(9.50f, 9.61f)
                curveTo(9.18f, 10.71f, 9.00f, 11.85f, 9.00f, 13.00f)
                verticalLineTo(18.33f)
                lineTo(7.00f, 21.00f)
                curveTo(6.67f, 21.44f, 6.76f, 22.07f, 7.20f, 22.40f)
                curveTo(7.64f, 22.73f, 8.27f, 22.64f, 8.60f, 22.20f)
                lineTo(10.64f, 19.48f)
                curveTo(10.87f, 19.17f, 11.01f, 18.79f, 11.04f, 18.40f)
                lineTo(11.22f, 15.46f)
                lineTo(13.00f, 18.00f)
                verticalLineTo(22.00f)
                curveTo(13.00f, 22.55f, 13.45f, 23.00f, 14.00f, 23.00f)
                curveTo(14.55f, 23.00f, 15.00f, 22.55f, 15.00f, 22.00f)
                verticalLineTo(17.13f)
                curveTo(15.00f, 16.72f, 14.87f, 16.32f, 14.64f, 15.98f)
                lineTo(13.04f, 13.69f)
                verticalLineTo(13.68f)
                curveTo(12.93f, 12.52f, 13.11f, 11.36f, 13.50f, 10.28f)
                arcTo(6.02f, 6.02f, 0.00f, false, false, 17.01f, 12.80f)
                verticalLineTo(13.00f)
                curveTo(17.01f, 13.28f, 17.23f, 13.50f, 17.51f, 13.50f)
                curveTo(17.79f, 13.50f, 18.00f, 13.28f, 18.00f, 13.00f)
                verticalLineTo(12.50f)
                curveTo(18.00f, 12.22f, 18.22f, 12.00f, 18.50f, 12.00f)
                curveTo(18.78f, 12.00f, 19.00f, 12.22f, 19.00f, 12.50f)
                verticalLineTo(22.50f)
                curveTo(19.00f, 22.78f, 19.22f, 23.00f, 19.50f, 23.00f)
                curveTo(19.78f, 23.00f, 20.00f, 22.78f, 20.00f, 22.50f)
                verticalLineTo(12.50f)
                curveTo(20.00f, 11.68f, 19.34f, 10.99f, 18.53f, 11.00f)
                close()
            }
        }.build()
        return _Elderly!!
    }

private var _Elderly: ImageVector? = null
