// Generated by XIcons
// 2025-08-17 11:04:49
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Round.ElderlyWoman: ImageVector
    get() {
        if (_ElderlyWoman != null) {
            return _ElderlyWoman!!
        }
        _ElderlyWoman = ImageVector.Builder(
            name = "ElderlyWoman",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(18.52f, 11.00f)
                curveTo(16.95f, 11.00f, 15.58f, 10.10f, 14.92f, 8.79f)
                lineTo(14.13f, 7.12f)
                curveTo(14.12f, 7.10f, 13.63f, 6.00f, 12.34f, 6.00f)
                curveTo(8.72f, 6.00f, 6.00f, 16.69f, 6.00f, 19.00f)
                horizontalLineTo(8.50f)
                lineTo(7.00f, 21.00f)
                curveTo(6.67f, 21.44f, 6.76f, 22.07f, 7.20f, 22.40f)
                curveTo(7.64f, 22.73f, 8.27f, 22.64f, 8.60f, 22.20f)
                lineTo(11.00f, 19.00f)
                horizontalLineTo(13.00f)
                verticalLineTo(22.00f)
                curveTo(13.00f, 22.55f, 13.45f, 23.00f, 14.00f, 23.00f)
                curveTo(14.55f, 23.00f, 15.00f, 22.55f, 15.00f, 22.00f)
                verticalLineTo(19.29f)
                curveTo(15.00f, 19.07f, 14.96f, 18.86f, 14.90f, 18.65f)
                lineTo(13.00f, 13.00f)
                lineTo(13.49f, 10.29f)
                arcTo(6.02f, 6.02f, 0.00f, false, false, 17.00f, 12.81f)
                verticalLineTo(13.00f)
                curveTo(17.00f, 13.28f, 17.22f, 13.50f, 17.50f, 13.50f)
                curveTo(17.78f, 13.50f, 18.00f, 13.28f, 18.00f, 13.00f)
                verticalLineTo(12.50f)
                curveTo(18.00f, 12.22f, 18.22f, 12.00f, 18.50f, 12.00f)
                curveTo(18.78f, 12.00f, 19.00f, 12.22f, 19.00f, 12.50f)
                verticalLineTo(22.50f)
                curveTo(19.00f, 22.78f, 19.22f, 23.00f, 19.50f, 23.00f)
                curveTo(19.78f, 23.00f, 20.00f, 22.78f, 20.00f, 22.50f)
                verticalLineTo(12.50f)
                curveTo(20.00f, 11.71f, 19.38f, 11.00f, 18.52f, 11.00f)
                close()
                moveTo(11.60f, 2.91f)
                curveTo(11.54f, 3.10f, 11.50f, 3.29f, 11.50f, 3.50f)
                curveTo(11.50f, 4.60f, 12.40f, 5.50f, 13.50f, 5.50f)
                curveTo(14.60f, 5.50f, 15.50f, 4.60f, 15.50f, 3.50f)
                curveTo(15.50f, 2.40f, 14.60f, 1.50f, 13.50f, 1.50f)
                curveTo(13.29f, 1.50f, 13.10f, 1.54f, 12.91f, 1.60f)
                curveTo(12.76f, 1.25f, 12.41f, 1.00f, 12.00f, 1.00f)
                curveTo(11.45f, 1.00f, 11.00f, 1.45f, 11.00f, 2.00f)
                curveTo(11.00f, 2.41f, 11.25f, 2.76f, 11.60f, 2.91f)
                close()
            }
        }.build()
        return _ElderlyWoman!!
    }

private var _ElderlyWoman: ImageVector? = null
