// Generated by XIcons
// 2025-08-17 11:04:49
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Filled.FaceRetouchingNatural: ImageVector
    get() {
        if (_FaceRetouchingNatural != null) {
            return _FaceRetouchingNatural!!
        }
        _FaceRetouchingNatural = ImageVector.Builder(
            name = "FaceRetouchingNatural",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(20.77f, 8.58f)
                lineTo(19.85f, 10.59f)
                curveTo(19.94f, 11.05f, 20.00f, 11.52f, 20.00f, 12.00f)
                curveTo(20.00f, 16.41f, 16.41f, 20.00f, 12.00f, 20.00f)
                curveTo(7.59f, 20.00f, 4.00f, 16.41f, 4.00f, 12.00f)
                curveTo(4.00f, 11.95f, 4.01f, 11.90f, 4.00f, 11.86f)
                curveTo(6.60f, 10.88f, 8.69f, 8.87f, 9.74f, 6.31f)
                arcTo(10.00f, 10.00f, 0.00f, false, false, 17.50f, 10.00f)
                curveTo(17.95f, 10.00f, 18.39f, 9.96f, 18.83f, 9.90f)
                lineTo(18.23f, 8.58f)
                lineTo(17.35f, 6.65f)
                lineTo(15.42f, 5.77f)
                lineTo(12.63f, 4.50f)
                lineTo(15.42f, 3.23f)
                lineTo(16.13f, 2.91f)
                arcTo(9.86f, 9.86f, 0.00f, false, false, 12.00f, 2.00f)
                curveTo(6.48f, 2.00f, 2.00f, 6.48f, 2.00f, 12.00f)
                curveTo(2.00f, 17.52f, 6.48f, 22.00f, 12.00f, 22.00f)
                curveTo(17.52f, 22.00f, 22.00f, 17.52f, 22.00f, 12.00f)
                curveTo(22.00f, 10.53f, 21.67f, 9.13f, 21.10f, 7.87f)
                lineTo(20.77f, 8.58f)
                close()
                moveTo(20.60f, 5.60f)
                lineTo(19.50f, 8.00f)
                lineTo(18.40f, 5.60f)
                lineTo(16.00f, 4.50f)
                lineTo(18.40f, 3.40f)
                lineTo(19.50f, 1.00f)
                lineTo(20.60f, 3.40f)
                lineTo(23.00f, 4.50f)
                close()
            }
        }.build()
        return _FaceRetouchingNatural!!
    }

private var _FaceRetouchingNatural: ImageVector? = null
