// Generated by XIcons
// 2025-08-17 11:04:50
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Outlined.FindReplace: ImageVector
    get() {
        if (_FindReplace != null) {
            return _FindReplace!!
        }
        _FindReplace = ImageVector.Builder(
            name = "FindReplace",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(11.00f, 6.00f)
                curveTo(12.38f, 6.00f, 13.63f, 6.56f, 14.54f, 7.46f)
                lineTo(12.00f, 10.00f)
                horizontalLineTo(18.00f)
                verticalLineTo(4.00f)
                lineTo(15.95f, 6.05f)
                arcTo(6.98f, 6.98f, 0.00f, false, false, 11.00f, 4.00f)
                curveTo(7.47f, 4.00f, 4.57f, 6.61f, 4.08f, 10.00f)
                horizontalLineTo(6.10f)
                arcTo(5.00f, 5.00f, 0.00f, false, true, 11.00f, 6.00f)
                close()
                moveTo(16.64f, 15.14f)
                arcTo(6.89f, 6.89f, 0.00f, false, false, 17.92f, 12.00f)
                horizontalLineTo(15.90f)
                arcTo(5.00f, 5.00f, 0.00f, false, true, 11.00f, 16.00f)
                curveTo(9.62f, 16.00f, 8.37f, 15.44f, 7.46f, 14.54f)
                lineTo(10.00f, 12.00f)
                horizontalLineTo(4.00f)
                verticalLineTo(18.00f)
                lineTo(6.05f, 15.95f)
                arcTo(6.98f, 6.98f, 0.00f, false, false, 11.00f, 18.00f)
                curveTo(12.55f, 18.00f, 13.98f, 17.49f, 15.14f, 16.64f)
                lineTo(20.00f, 21.49f)
                lineTo(21.49f, 20.00f)
                lineTo(16.64f, 15.14f)
                close()
            }
        }.build()
        return _FindReplace!!
    }

private var _FindReplace: ImageVector? = null
