// Generated by XIcons
// 2025-08-17 11:04:52
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Round.FormatColorReset: ImageVector
    get() {
        if (_FormatColorReset != null) {
            return _FormatColorReset!!
        }
        _FormatColorReset = ImageVector.Builder(
            name = "FormatColorReset",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(18.00f, 14.00f)
                curveTo(18.00f, 10.91f, 14.40f, 6.12f, 12.77f, 4.13f)
                arcTo(1.00f, 1.00f, 0.00f, false, false, 11.22f, 4.13f)
                curveTo(10.76f, 4.70f, 10.14f, 5.49f, 9.49f, 6.40f)
                lineTo(17.93f, 14.84f)
                curveTo(17.97f, 14.56f, 18.00f, 14.28f, 18.00f, 14.00f)
                close()
                moveTo(19.29f, 19.01f)
                lineTo(6.12f, 5.84f)
                arcTo(1.00f, 1.00f, 0.00f, true, false, 4.71f, 7.25f)
                lineTo(7.32f, 9.86f)
                curveTo(6.55f, 11.33f, 6.00f, 12.79f, 6.00f, 14.00f)
                curveTo(6.00f, 17.31f, 8.69f, 20.00f, 12.00f, 20.00f)
                curveTo(13.52f, 20.00f, 14.90f, 19.43f, 15.95f, 18.50f)
                lineTo(17.87f, 20.42f)
                curveTo(18.26f, 20.81f, 18.89f, 20.81f, 19.28f, 20.42f)
                curveTo(19.68f, 20.04f, 19.68f, 19.40f, 19.29f, 19.01f)
                close()
            }
        }.build()
        return _FormatColorReset!!
    }

private var _FormatColorReset: ImageVector? = null
