// Generated by XIcons
// 2025-08-17 11:04:53
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Sharp.HdrOn: ImageVector
    get() {
        if (_HdrOn != null) {
            return _HdrOn!!
        }
        _HdrOn = ImageVector.Builder(
            name = "HdrOn",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(21.00f, 12.90f)
                verticalLineTo(9.00f)
                horizontalLineTo(16.00f)
                verticalLineTo(15.00f)
                horizontalLineTo(17.50f)
                verticalLineTo(13.00f)
                horizontalLineTo(18.60f)
                lineTo(19.50f, 15.00f)
                horizontalLineTo(21.00f)
                lineTo(20.10f, 12.90f)
                horizontalLineTo(21.00f)
                close()
                moveTo(19.50f, 11.50f)
                horizontalLineTo(17.50f)
                verticalLineTo(10.50f)
                horizontalLineTo(19.50f)
                verticalLineTo(11.50f)
                close()
                moveTo(6.50f, 11.00f)
                horizontalLineTo(4.50f)
                verticalLineTo(9.00f)
                horizontalLineTo(3.00f)
                verticalLineTo(15.00f)
                horizontalLineTo(4.50f)
                verticalLineTo(12.50f)
                horizontalLineTo(6.50f)
                verticalLineTo(15.00f)
                horizontalLineTo(8.00f)
                verticalLineTo(9.00f)
                horizontalLineTo(6.50f)
                verticalLineTo(11.00f)
                close()
                moveTo(13.00f, 9.00f)
                horizontalLineTo(9.50f)
                verticalLineTo(15.00f)
                horizontalLineTo(13.00f)
                curveTo(13.80f, 15.00f, 14.50f, 14.30f, 14.50f, 13.50f)
                verticalLineTo(10.50f)
                curveTo(14.50f, 9.70f, 13.80f, 9.00f, 13.00f, 9.00f)
                close()
                moveTo(13.00f, 13.50f)
                horizontalLineTo(11.00f)
                verticalLineTo(10.50f)
                horizontalLineTo(13.00f)
                verticalLineTo(13.50f)
                close()
            }
        }.build()
        return _HdrOn!!
    }

private var _HdrOn: ImageVector? = null
