// Generated by XIcons
// 2025-08-17 11:04:54
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Round.IosShare: ImageVector
    get() {
        if (_IosShare != null) {
            return _IosShare!!
        }
        _IosShare = ImageVector.Builder(
            name = "IosShare",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(18.00f, 8.00f)
                horizontalLineTo(16.00f)
                curveTo(15.45f, 8.00f, 15.00f, 8.45f, 15.00f, 9.00f)
                curveTo(15.00f, 9.55f, 15.45f, 10.00f, 16.00f, 10.00f)
                horizontalLineTo(18.00f)
                verticalLineTo(21.00f)
                horizontalLineTo(6.00f)
                verticalLineTo(10.00f)
                horizontalLineTo(8.00f)
                curveTo(8.55f, 10.00f, 9.00f, 9.55f, 9.00f, 9.00f)
                curveTo(9.00f, 8.45f, 8.55f, 8.00f, 8.00f, 8.00f)
                horizontalLineTo(6.00f)
                curveTo(4.90f, 8.00f, 4.00f, 8.90f, 4.00f, 10.00f)
                verticalLineTo(21.00f)
                curveTo(4.00f, 22.10f, 4.90f, 23.00f, 6.00f, 23.00f)
                horizontalLineTo(18.00f)
                curveTo(19.10f, 23.00f, 20.00f, 22.10f, 20.00f, 21.00f)
                verticalLineTo(10.00f)
                curveTo(20.00f, 8.90f, 19.10f, 8.00f, 18.00f, 8.00f)
                close()
                moveTo(12.00f, 16.00f)
                curveTo(12.55f, 16.00f, 13.00f, 15.55f, 13.00f, 15.00f)
                verticalLineTo(5.00f)
                horizontalLineTo(14.79f)
                curveTo(15.24f, 5.00f, 15.46f, 4.46f, 15.14f, 4.15f)
                lineTo(12.35f, 1.36f)
                curveTo(12.15f, 1.16f, 11.84f, 1.16f, 11.64f, 1.36f)
                lineTo(8.85f, 4.15f)
                arcTo(0.50f, 0.50f, 0.00f, false, false, 9.21f, 5.00f)
                horizontalLineTo(11.00f)
                verticalLineTo(15.00f)
                curveTo(11.00f, 15.55f, 11.45f, 16.00f, 12.00f, 16.00f)
                close()
            }
        }.build()
        return _IosShare!!
    }

private var _IosShare: ImageVector? = null
