// Generated by XIcons
// 2025-08-17 11:04:54
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Round.KeyboardDoubleArrowLeft: ImageVector
    get() {
        if (_KeyboardDoubleArrowLeft != null) {
            return _KeyboardDoubleArrowLeft!!
        }
        _KeyboardDoubleArrowLeft = ImageVector.Builder(
            name = "KeyboardDoubleArrowLeft",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(18.29f, 17.29f)
                arcTo(1.00f, 1.00f, 0.00f, false, false, 18.29f, 15.88f)
                lineTo(14.42f, 12.00f)
                lineTo(18.30f, 8.12f)
                arcTo(1.00f, 1.00f, 0.00f, true, false, 16.89f, 6.71f)
                lineTo(12.30f, 11.30f)
                arcTo(1.00f, 1.00f, 0.00f, false, false, 12.30f, 12.71f)
                lineTo(16.89f, 17.30f)
                curveTo(17.27f, 17.68f, 17.90f, 17.68f, 18.29f, 17.29f)
                close()
                moveTo(11.70f, 17.29f)
                arcTo(1.00f, 1.00f, 0.00f, false, false, 11.70f, 15.88f)
                lineTo(7.83f, 12.00f)
                lineTo(11.71f, 8.12f)
                arcTo(1.00f, 1.00f, 0.00f, true, false, 10.30f, 6.71f)
                lineTo(5.71f, 11.30f)
                arcTo(1.00f, 1.00f, 0.00f, false, false, 5.71f, 12.71f)
                lineTo(10.30f, 17.30f)
                curveTo(10.68f, 17.68f, 11.31f, 17.68f, 11.70f, 17.29f)
                close()
            }
        }.build()
        return _KeyboardDoubleArrowLeft!!
    }

private var _KeyboardDoubleArrowLeft: ImageVector? = null
