// Generated by XIcons
// 2025-08-17 11:04:55
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Outlined.LineStyle: ImageVector
    get() {
        if (_LineStyle != null) {
            return _LineStyle!!
        }
        _LineStyle = ImageVector.Builder(
            name = "LineStyle",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(3.00f, 16.00f)
                horizontalLineTo(8.00f)
                verticalLineTo(14.00f)
                horizontalLineTo(3.00f)
                verticalLineTo(16.00f)
                close()
                moveTo(9.50f, 16.00f)
                horizontalLineTo(14.50f)
                verticalLineTo(14.00f)
                horizontalLineTo(9.50f)
                verticalLineTo(16.00f)
                close()
                moveTo(16.00f, 16.00f)
                horizontalLineTo(21.00f)
                verticalLineTo(14.00f)
                horizontalLineTo(16.00f)
                verticalLineTo(16.00f)
                close()
                moveTo(3.00f, 20.00f)
                horizontalLineTo(5.00f)
                verticalLineTo(18.00f)
                horizontalLineTo(3.00f)
                verticalLineTo(20.00f)
                close()
                moveTo(7.00f, 20.00f)
                horizontalLineTo(9.00f)
                verticalLineTo(18.00f)
                horizontalLineTo(7.00f)
                verticalLineTo(20.00f)
                close()
                moveTo(11.00f, 20.00f)
                horizontalLineTo(13.00f)
                verticalLineTo(18.00f)
                horizontalLineTo(11.00f)
                verticalLineTo(20.00f)
                close()
                moveTo(15.00f, 20.00f)
                horizontalLineTo(17.00f)
                verticalLineTo(18.00f)
                horizontalLineTo(15.00f)
                verticalLineTo(20.00f)
                close()
                moveTo(19.00f, 20.00f)
                horizontalLineTo(21.00f)
                verticalLineTo(18.00f)
                horizontalLineTo(19.00f)
                verticalLineTo(20.00f)
                close()
                moveTo(3.00f, 12.00f)
                horizontalLineTo(11.00f)
                verticalLineTo(10.00f)
                horizontalLineTo(3.00f)
                verticalLineTo(12.00f)
                close()
                moveTo(13.00f, 12.00f)
                horizontalLineTo(21.00f)
                verticalLineTo(10.00f)
                horizontalLineTo(13.00f)
                verticalLineTo(12.00f)
                close()
                moveTo(3.00f, 4.00f)
                verticalLineTo(8.00f)
                horizontalLineTo(21.00f)
                verticalLineTo(4.00f)
                horizontalLineTo(3.00f)
                close()
            }
        }.build()
        return _LineStyle!!
    }

private var _LineStyle: ImageVector? = null
