// Generated by XIcons
// 2025-08-17 11:04:55
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Round.Looks3: ImageVector
    get() {
        if (_Looks3 != null) {
            return _Looks3!!
        }
        _Looks3 = ImageVector.Builder(
            name = "Looks3",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(19.00f, 3.00f)
                horizontalLineTo(5.01f)
                curveTo(3.91f, 3.00f, 3.01f, 3.90f, 3.01f, 5.00f)
                verticalLineTo(19.00f)
                curveTo(3.01f, 20.10f, 3.91f, 21.00f, 5.01f, 21.00f)
                horizontalLineTo(19.00f)
                curveTo(20.10f, 21.00f, 21.00f, 20.10f, 21.00f, 19.00f)
                verticalLineTo(5.00f)
                curveTo(21.00f, 3.90f, 20.10f, 3.00f, 19.00f, 3.00f)
                close()
                moveTo(15.01f, 10.50f)
                curveTo(15.01f, 11.33f, 14.34f, 12.00f, 13.51f, 12.00f)
                curveTo(14.34f, 12.00f, 15.01f, 12.67f, 15.01f, 13.50f)
                verticalLineTo(15.00f)
                arcTo(2.00f, 2.00f, 0.00f, false, true, 13.01f, 17.00f)
                horizontalLineTo(10.00f)
                curveTo(9.45f, 17.00f, 9.00f, 16.55f, 9.00f, 16.00f)
                curveTo(9.00f, 15.45f, 9.45f, 15.00f, 10.00f, 15.00f)
                horizontalLineTo(13.01f)
                lineTo(13.00f, 13.00f)
                horizontalLineTo(12.00f)
                curveTo(11.45f, 13.00f, 11.00f, 12.55f, 11.00f, 12.00f)
                curveTo(11.00f, 11.45f, 11.45f, 11.00f, 12.00f, 11.00f)
                horizontalLineTo(13.00f)
                lineTo(13.01f, 9.00f)
                horizontalLineTo(10.00f)
                curveTo(9.45f, 9.00f, 9.01f, 8.55f, 9.01f, 8.00f)
                curveTo(9.01f, 7.45f, 9.45f, 7.00f, 10.00f, 7.00f)
                horizontalLineTo(13.01f)
                curveTo(14.11f, 7.00f, 15.01f, 7.90f, 15.01f, 9.00f)
                verticalLineTo(10.50f)
                close()
            }
        }.build()
        return _Looks3!!
    }

private var _Looks3: ImageVector? = null
