// Generated by XIcons
// 2025-08-17 11:04:59
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Filled.NoMeetingRoom: ImageVector
    get() {
        if (_NoMeetingRoom != null) {
            return _NoMeetingRoom!!
        }
        _NoMeetingRoom = ImageVector.Builder(
            name = "NoMeetingRoom",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(11.00f, 11.00f)
                horizontalLineTo(10.00f)
                verticalLineTo(13.00f)
                horizontalLineTo(12.00f)
                verticalLineTo(12.00f)
                lineTo(21.73f, 21.73f)
                lineTo(20.46f, 23.00f)
                lineTo(14.00f, 16.54f)
                verticalLineTo(21.00f)
                horizontalLineTo(3.00f)
                verticalLineTo(19.00f)
                horizontalLineTo(5.00f)
                verticalLineTo(7.54f)
                lineTo(1.00f, 3.54f)
                lineTo(2.27f, 2.27f)
                lineTo(11.00f, 11.00f)
                close()
                moveTo(14.00f, 11.49f)
                lineTo(5.51f, 3.00f)
                horizontalLineTo(14.00f)
                verticalLineTo(4.00f)
                horizontalLineTo(19.00f)
                verticalLineTo(16.49f)
                lineTo(17.00f, 14.49f)
                verticalLineTo(6.00f)
                horizontalLineTo(14.00f)
                verticalLineTo(11.49f)
                close()
            }
        }.build()
        return _NoMeetingRoom!!
    }

private var _NoMeetingRoom: ImageVector? = null
