// Generated by XIcons
// 2025-08-17 11:04:59
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Filled.NoPhotography: ImageVector
    get() {
        if (_NoPhotography != null) {
            return _NoPhotography!!
        }
        _NoPhotography = ImageVector.Builder(
            name = "NoPhotography",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(10.94f, 8.12f)
                lineTo(7.48f, 4.66f)
                lineTo(9.00f, 3.00f)
                horizontalLineTo(15.00f)
                lineTo(16.83f, 5.00f)
                horizontalLineTo(20.00f)
                curveTo(21.10f, 5.00f, 22.00f, 5.90f, 22.00f, 7.00f)
                verticalLineTo(19.00f)
                curveTo(22.00f, 19.05f, 21.99f, 19.10f, 21.98f, 19.16f)
                lineTo(16.88f, 14.06f)
                curveTo(16.96f, 13.71f, 17.00f, 13.36f, 17.00f, 13.00f)
                curveTo(17.00f, 10.24f, 14.76f, 8.00f, 12.00f, 8.00f)
                curveTo(11.64f, 8.00f, 11.29f, 8.04f, 10.94f, 8.12f)
                close()
                moveTo(20.49f, 23.31f)
                lineTo(18.17f, 21.00f)
                horizontalLineTo(4.00f)
                curveTo(2.90f, 21.00f, 2.00f, 20.10f, 2.00f, 19.00f)
                verticalLineTo(7.00f)
                curveTo(2.00f, 6.41f, 2.27f, 5.88f, 2.68f, 5.51f)
                lineTo(0.68f, 3.51f)
                lineTo(2.10f, 2.10f)
                lineTo(21.90f, 21.90f)
                lineTo(20.49f, 23.31f)
                close()
                moveTo(14.49f, 17.32f)
                lineTo(12.99f, 15.82f)
                curveTo(12.67f, 15.92f, 12.35f, 16.00f, 12.00f, 16.00f)
                curveTo(10.34f, 16.00f, 9.00f, 14.66f, 9.00f, 13.00f)
                curveTo(9.00f, 12.65f, 9.08f, 12.33f, 9.19f, 12.02f)
                lineTo(7.69f, 10.52f)
                arcTo(4.74f, 4.74f, 0.00f, false, false, 7.00f, 13.00f)
                curveTo(7.00f, 15.76f, 9.24f, 18.00f, 12.00f, 18.00f)
                curveTo(12.91f, 18.00f, 13.76f, 17.75f, 14.49f, 17.32f)
                close()
            }
        }.build()
        return _NoPhotography!!
    }

private var _NoPhotography: ImageVector? = null
