// Generated by XIcons
// 2025-08-17 11:04:59
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Twotone.OutdoorGrill: ImageVector
    get() {
        if (_OutdoorGrill != null) {
            return _OutdoorGrill!!
        }
        _OutdoorGrill = ImageVector.Builder(
            name = "OutdoorGrill",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(16.58f, 10.00f)
                horizontalLineTo(7.42f)
                curveTo(8.19f, 11.76f, 9.96f, 13.00f, 12.00f, 13.00f)
                curveTo(14.04f, 13.00f, 15.81f, 11.76f, 16.58f, 10.00f)
                close()
                moveTo(17.00f, 22.00f)
                curveTo(18.66f, 22.00f, 20.00f, 20.66f, 20.00f, 19.00f)
                curveTo(20.00f, 17.34f, 18.66f, 16.00f, 17.00f, 16.00f)
                curveTo(15.70f, 16.00f, 14.60f, 16.84f, 14.18f, 18.00f)
                horizontalLineTo(9.14f)
                lineTo(11.13f, 14.94f)
                arcTo(6.36f, 6.36f, 0.00f, false, false, 12.87f, 14.94f)
                lineTo(13.89f, 16.51f)
                curveTo(14.31f, 15.98f, 14.85f, 15.56f, 15.49f, 15.30f)
                lineTo(14.89f, 14.37f)
                arcTo(6.99f, 6.99f, 0.00f, false, false, 19.00f, 8.00f)
                horizontalLineTo(5.00f)
                curveTo(5.00f, 10.84f, 6.69f, 13.27f, 9.12f, 14.37f)
                lineTo(5.17f, 20.45f)
                arcTo(1.00f, 1.00f, 0.00f, false, false, 5.46f, 21.83f)
                arcTo(1.00f, 1.00f, 0.00f, false, false, 6.84f, 21.54f)
                lineTo(7.84f, 19.99f)
                horizontalLineTo(14.18f)
                curveTo(14.60f, 21.16f, 15.70f, 22.00f, 17.00f, 22.00f)
                close()
                moveTo(17.00f, 18.00f)
                curveTo(17.55f, 18.00f, 18.00f, 18.45f, 18.00f, 19.00f)
                curveTo(18.00f, 19.55f, 17.55f, 20.00f, 17.00f, 20.00f)
                curveTo(16.45f, 20.00f, 16.00f, 19.55f, 16.00f, 19.00f)
                curveTo(16.00f, 18.45f, 16.45f, 18.00f, 17.00f, 18.00f)
                close()
                moveTo(7.42f, 10.00f)
                horizontalLineTo(16.58f)
                curveTo(15.81f, 11.76f, 14.04f, 13.00f, 12.00f, 13.00f)
                curveTo(9.96f, 13.00f, 8.19f, 11.76f, 7.42f, 10.00f)
                close()
                moveTo(9.41f, 7.00f)
                horizontalLineTo(10.41f)
                curveTo(10.56f, 5.85f, 10.64f, 5.36f, 9.52f, 4.04f)
                curveTo(9.10f, 3.54f, 8.84f, 3.27f, 9.06f, 2.00f)
                horizontalLineTo(8.07f)
                curveTo(7.86f, 3.11f, 8.10f, 4.05f, 8.96f, 4.96f)
                curveTo(9.18f, 5.20f, 9.75f, 5.63f, 9.41f, 7.00f)
                close()
                moveTo(11.89f, 7.00f)
                horizontalLineTo(12.89f)
                curveTo(13.04f, 5.85f, 13.12f, 5.36f, 12.00f, 4.04f)
                curveTo(11.58f, 3.54f, 11.32f, 3.26f, 11.54f, 2.00f)
                horizontalLineTo(10.55f)
                curveTo(10.34f, 3.11f, 10.58f, 4.05f, 11.44f, 4.96f)
                curveTo(11.67f, 5.20f, 12.24f, 5.63f, 11.89f, 7.00f)
                close()
                moveTo(14.41f, 7.00f)
                horizontalLineTo(15.41f)
                curveTo(15.56f, 5.85f, 15.64f, 5.36f, 14.52f, 4.04f)
                curveTo(14.10f, 3.54f, 13.84f, 3.27f, 14.06f, 2.00f)
                horizontalLineTo(13.07f)
                curveTo(12.86f, 3.11f, 13.10f, 4.05f, 13.96f, 4.96f)
                curveTo(14.18f, 5.20f, 14.75f, 5.63f, 14.41f, 7.00f)
                close()
            }
        }.build()
        return _OutdoorGrill!!
    }

private var _OutdoorGrill: ImageVector? = null
