// Generated by XIcons
// 2025-08-17 11:05:03
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Round.RecordVoiceOver: ImageVector
    get() {
        if (_RecordVoiceOver != null) {
            return _RecordVoiceOver!!
        }
        _RecordVoiceOver = ImageVector.Builder(
            name = "RecordVoiceOver",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(9.00f, 15.00f)
                curveTo(6.33f, 15.00f, 1.00f, 16.34f, 1.00f, 19.00f)
                verticalLineTo(20.00f)
                curveTo(1.00f, 20.55f, 1.45f, 21.00f, 2.00f, 21.00f)
                horizontalLineTo(16.00f)
                curveTo(16.55f, 21.00f, 17.00f, 20.55f, 17.00f, 20.00f)
                verticalLineTo(19.00f)
                curveTo(17.00f, 16.34f, 11.67f, 15.00f, 9.00f, 15.00f)
                close()
                moveTo(15.47f, 7.77f)
                curveTo(15.79f, 8.56f, 15.79f, 9.44f, 15.47f, 10.23f)
                curveTo(15.28f, 10.70f, 15.36f, 11.23f, 15.72f, 11.59f)
                lineTo(15.75f, 11.62f)
                curveTo(16.33f, 12.20f, 17.32f, 12.08f, 17.70f, 11.35f)
                curveTo(18.46f, 9.90f, 18.46f, 8.20f, 17.68f, 6.69f)
                curveTo(17.30f, 5.95f, 16.30f, 5.81f, 15.71f, 6.40f)
                lineTo(15.70f, 6.41f)
                curveTo(15.36f, 6.76f, 15.28f, 7.30f, 15.47f, 7.77f)
                close()
                moveTo(19.18f, 2.89f)
                curveTo(18.78f, 3.29f, 18.72f, 3.91f, 19.05f, 4.37f)
                curveTo(21.02f, 7.11f, 21.01f, 10.78f, 19.02f, 13.62f)
                curveTo(18.70f, 14.07f, 18.77f, 14.69f, 19.16f, 15.08f)
                lineTo(19.19f, 15.11f)
                curveTo(19.68f, 15.60f, 20.51f, 15.56f, 20.93f, 15.01f)
                curveTo(23.68f, 11.47f, 23.69f, 6.64f, 20.93f, 2.99f)
                curveTo(20.51f, 2.44f, 19.67f, 2.40f, 19.18f, 2.89f)
                close()
            }
        }.build()
        return _RecordVoiceOver!!
    }

private var _RecordVoiceOver: ImageVector? = null
