// Generated by XIcons
// 2025-08-17 11:05:03
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Sharp.RuleFolder: ImageVector
    get() {
        if (_RuleFolder != null) {
            return _RuleFolder!!
        }
        _RuleFolder = ImageVector.Builder(
            name = "RuleFolder",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(22.00f, 6.00f)
                horizontalLineTo(12.00f)
                lineTo(10.00f, 4.00f)
                horizontalLineTo(2.00f)
                verticalLineTo(20.00f)
                horizontalLineTo(22.00f)
                verticalLineTo(6.00f)
                close()
                moveTo(7.83f, 16.00f)
                lineTo(5.00f, 13.17f)
                lineTo(6.41f, 11.76f)
                lineTo(7.82f, 13.17f)
                lineTo(11.36f, 9.63f)
                lineTo(12.77f, 11.04f)
                lineTo(7.83f, 16.00f)
                close()
                moveTo(17.41f, 13.00f)
                lineTo(19.00f, 14.59f)
                lineTo(17.59f, 16.00f)
                lineTo(16.00f, 14.41f)
                lineTo(14.41f, 16.00f)
                lineTo(13.00f, 14.59f)
                lineTo(14.59f, 13.00f)
                lineTo(13.00f, 11.41f)
                lineTo(14.41f, 10.00f)
                lineTo(16.00f, 11.59f)
                lineTo(17.59f, 10.00f)
                lineTo(19.00f, 11.41f)
                lineTo(17.41f, 13.00f)
                close()
            }
        }.build()
        return _RuleFolder!!
    }

private var _RuleFolder: ImageVector? = null
