// Generated by XIcons
// 2025-08-17 11:05:04
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Round.Segment: ImageVector
    get() {
        if (_Segment != null) {
            return _Segment!!
        }
        _Segment = ImageVector.Builder(
            name = "Segment",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(10.00f, 18.00f)
                horizontalLineTo(20.00f)
                curveTo(20.55f, 18.00f, 21.00f, 17.55f, 21.00f, 17.00f)
                curveTo(21.00f, 16.45f, 20.55f, 16.00f, 20.00f, 16.00f)
                horizontalLineTo(10.00f)
                curveTo(9.45f, 16.00f, 9.00f, 16.45f, 9.00f, 17.00f)
                curveTo(9.00f, 17.55f, 9.45f, 18.00f, 10.00f, 18.00f)
                close()
                moveTo(3.00f, 7.00f)
                curveTo(3.00f, 7.55f, 3.45f, 8.00f, 4.00f, 8.00f)
                horizontalLineTo(20.00f)
                curveTo(20.55f, 8.00f, 21.00f, 7.55f, 21.00f, 7.00f)
                curveTo(21.00f, 6.45f, 20.55f, 6.00f, 20.00f, 6.00f)
                horizontalLineTo(4.00f)
                curveTo(3.45f, 6.00f, 3.00f, 6.45f, 3.00f, 7.00f)
                close()
                moveTo(10.00f, 13.00f)
                horizontalLineTo(20.00f)
                curveTo(20.55f, 13.00f, 21.00f, 12.55f, 21.00f, 12.00f)
                curveTo(21.00f, 11.45f, 20.55f, 11.00f, 20.00f, 11.00f)
                horizontalLineTo(10.00f)
                curveTo(9.45f, 11.00f, 9.00f, 11.45f, 9.00f, 12.00f)
                curveTo(9.00f, 12.55f, 9.45f, 13.00f, 10.00f, 13.00f)
                close()
            }
        }.build()
        return _Segment!!
    }

private var _Segment: ImageVector? = null
