// Generated by XIcons
// 2025-08-17 11:05:05
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Filled.SignalWifiBad: ImageVector
    get() {
        if (_SignalWifiBad != null) {
            return _SignalWifiBad!!
        }
        _SignalWifiBad = ImageVector.Builder(
            name = "SignalWifiBad",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(24.00f, 8.98f)
                arcTo(16.88f, 16.88f, 0.00f, false, false, 12.00f, 4.00f)
                curveTo(7.31f, 4.00f, 3.07f, 5.90f, 0.00f, 8.98f)
                lineTo(12.00f, 21.00f)
                verticalLineTo(12.00f)
                horizontalLineTo(20.99f)
                lineTo(24.00f, 8.98f)
                close()
                moveTo(19.59f, 14.00f)
                lineTo(17.50f, 16.09f)
                lineTo(15.41f, 14.00f)
                lineTo(14.00f, 15.41f)
                lineTo(16.09f, 17.50f)
                lineTo(14.00f, 19.59f)
                lineTo(15.41f, 21.00f)
                lineTo(17.50f, 18.92f)
                lineTo(19.59f, 21.00f)
                lineTo(21.00f, 19.59f)
                lineTo(18.92f, 17.50f)
                lineTo(21.00f, 15.41f)
                lineTo(19.59f, 14.00f)
                close()
            }
        }.build()
        return _SignalWifiBad!!
    }

private var _SignalWifiBad: ImageVector? = null
