// Generated by XIcons
// 2025-08-17 11:05:05
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Outlined.SportsRugby: ImageVector
    get() {
        if (_SportsRugby != null) {
            return _SportsRugby!!
        }
        _SportsRugby = ImageVector.Builder(
            name = "SportsRugby",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(20.49f, 3.51f)
                curveTo(19.93f, 2.95f, 18.34f, 2.54f, 16.33f, 2.54f)
                curveTo(13.25f, 2.54f, 9.18f, 3.50f, 6.35f, 6.33f)
                curveTo(1.66f, 11.03f, 2.10f, 19.07f, 3.51f, 20.49f)
                curveTo(4.07f, 21.05f, 5.66f, 21.46f, 7.67f, 21.46f)
                curveTo(10.75f, 21.46f, 14.82f, 20.50f, 17.65f, 17.67f)
                curveTo(22.34f, 12.97f, 21.90f, 4.93f, 20.49f, 3.51f)
                close()
                moveTo(5.71f, 18.29f)
                curveTo(6.34f, 16.40f, 7.87f, 13.30f, 10.58f, 10.59f)
                curveTo(13.26f, 7.91f, 16.36f, 6.36f, 18.28f, 5.71f)
                curveTo(17.65f, 7.60f, 16.12f, 10.70f, 13.40f, 13.41f)
                curveTo(10.74f, 16.09f, 7.64f, 17.64f, 5.71f, 18.29f)
                close()
                moveTo(7.76f, 7.76f)
                curveTo(10.40f, 5.12f, 14.10f, 4.64f, 15.79f, 4.57f)
                curveTo(13.74f, 5.51f, 11.33f, 7.03f, 9.18f, 9.18f)
                arcTo(23.21f, 23.21f, 0.00f, false, false, 4.57f, 15.81f)
                curveTo(4.66f, 13.33f, 5.44f, 10.07f, 7.76f, 7.76f)
                close()
                moveTo(16.24f, 16.24f)
                curveTo(13.60f, 18.88f, 9.90f, 19.36f, 8.21f, 19.43f)
                curveTo(10.26f, 18.49f, 12.67f, 16.97f, 14.82f, 14.82f)
                curveTo(16.98f, 12.66f, 18.49f, 10.24f, 19.44f, 8.19f)
                curveTo(19.34f, 10.67f, 18.56f, 13.93f, 16.24f, 16.24f)
                close()
            }
        }.build()
        return _SportsRugby!!
    }

private var _SportsRugby: ImageVector? = null
