// Generated by XIcons
// 2025-08-17 11:05:06
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Round.StopCircle: ImageVector
    get() {
        if (_StopCircle != null) {
            return _StopCircle!!
        }
        _StopCircle = ImageVector.Builder(
            name = "StopCircle",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(12.00f, 2.00f)
                curveTo(6.48f, 2.00f, 2.00f, 6.48f, 2.00f, 12.00f)
                curveTo(2.00f, 17.52f, 6.48f, 22.00f, 12.00f, 22.00f)
                curveTo(17.52f, 22.00f, 22.00f, 17.52f, 22.00f, 12.00f)
                curveTo(22.00f, 6.48f, 17.52f, 2.00f, 12.00f, 2.00f)
                close()
                moveTo(15.00f, 16.00f)
                horizontalLineTo(9.00f)
                curveTo(8.45f, 16.00f, 8.00f, 15.55f, 8.00f, 15.00f)
                verticalLineTo(9.00f)
                curveTo(8.00f, 8.45f, 8.45f, 8.00f, 9.00f, 8.00f)
                horizontalLineTo(15.00f)
                curveTo(15.55f, 8.00f, 16.00f, 8.45f, 16.00f, 9.00f)
                verticalLineTo(15.00f)
                curveTo(16.00f, 15.55f, 15.55f, 16.00f, 15.00f, 16.00f)
                close()
            }
        }.build()
        return _StopCircle!!
    }

private var _StopCircle: ImageVector? = null
