// Generated by XIcons
// 2025-08-17 11:05:06
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Filled.TempleHindu: ImageVector
    get() {
        if (_TempleHindu != null) {
            return _TempleHindu!!
        }
        _TempleHindu = ImageVector.Builder(
            name = "TempleHindu",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(6.60f, 11.00f)
                horizontalLineTo(17.40f)
                lineTo(16.50f, 8.00f)
                horizontalLineTo(7.50f)
                close()
                moveTo(20.00f, 11.00f)
                verticalLineTo(13.00f)
                horizontalLineTo(4.00f)
                verticalLineTo(11.00f)
                horizontalLineTo(2.00f)
                verticalLineTo(22.00f)
                horizontalLineTo(10.00f)
                verticalLineTo(17.00f)
                horizontalLineTo(14.00f)
                verticalLineTo(22.00f)
                horizontalLineTo(22.00f)
                verticalLineTo(11.00f)
                close()
                moveTo(15.90f, 6.00f)
                lineTo(15.00f, 3.00f)
                verticalLineTo(1.00f)
                horizontalLineTo(13.00f)
                verticalLineTo(3.00f)
                horizontalLineTo(10.97f)
                verticalLineTo(1.00f)
                horizontalLineTo(8.97f)
                verticalLineTo(3.12f)
                lineTo(8.10f, 6.00f)
                close()
            }
        }.build()
        return _TempleHindu!!
    }

private var _TempleHindu: ImageVector? = null
