// Generated by XIcons
// 2025-08-17 11:05:07
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Outlined.VideoCameraFront: ImageVector
    get() {
        if (_VideoCameraFront != null) {
            return _VideoCameraFront!!
        }
        _VideoCameraFront = ImageVector.Builder(
            name = "VideoCameraFront",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(18.00f, 10.48f)
                verticalLineTo(6.00f)
                curveTo(18.00f, 4.90f, 17.10f, 4.00f, 16.00f, 4.00f)
                horizontalLineTo(4.00f)
                curveTo(2.90f, 4.00f, 2.00f, 4.90f, 2.00f, 6.00f)
                verticalLineTo(18.00f)
                curveTo(2.00f, 19.10f, 2.90f, 20.00f, 4.00f, 20.00f)
                horizontalLineTo(16.00f)
                curveTo(17.10f, 20.00f, 18.00f, 19.10f, 18.00f, 18.00f)
                verticalLineTo(13.52f)
                lineTo(22.00f, 17.50f)
                verticalLineTo(6.50f)
                lineTo(18.00f, 10.48f)
                close()
                moveTo(16.00f, 9.69f)
                verticalLineTo(18.00f)
                horizontalLineTo(4.00f)
                verticalLineTo(6.00f)
                horizontalLineTo(16.00f)
                verticalLineTo(9.69f)
                close()
                moveTo(14.00f, 15.43f)
                curveTo(14.00f, 14.62f, 13.52f, 13.90f, 12.78f, 13.58f)
                arcTo(6.95f, 6.95f, 0.00f, false, false, 7.22f, 13.58f)
                arcTo(2.01f, 2.01f, 0.00f, false, false, 6.00f, 15.43f)
                verticalLineTo(16.00f)
                horizontalLineTo(14.00f)
                verticalLineTo(15.43f)
                close()
            }
        }.build()
        return _VideoCameraFront!!
    }

private var _VideoCameraFront: ImageVector? = null
