// Generated by XIcons
// 2025-08-17 11:05:08
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Filled.VisibilityOff: ImageVector
    get() {
        if (_VisibilityOff != null) {
            return _VisibilityOff!!
        }
        _VisibilityOff = ImageVector.Builder(
            name = "VisibilityOff",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(12.00f, 7.00f)
                curveTo(14.76f, 7.00f, 17.00f, 9.24f, 17.00f, 12.00f)
                curveTo(17.00f, 12.65f, 16.87f, 13.26f, 16.64f, 13.83f)
                lineTo(19.56f, 16.75f)
                curveTo(21.07f, 15.49f, 22.26f, 13.86f, 22.99f, 12.00f)
                curveTo(21.26f, 7.61f, 16.99f, 4.50f, 11.99f, 4.50f)
                curveTo(10.59f, 4.50f, 9.25f, 4.75f, 8.01f, 5.20f)
                lineTo(10.17f, 7.36f)
                curveTo(10.74f, 7.13f, 11.35f, 7.00f, 12.00f, 7.00f)
                close()
                moveTo(2.00f, 4.27f)
                lineTo(4.28f, 6.55f)
                lineTo(4.74f, 7.01f)
                arcTo(11.80f, 11.80f, 0.00f, false, false, 1.00f, 12.00f)
                curveTo(2.73f, 16.39f, 7.00f, 19.50f, 12.00f, 19.50f)
                curveTo(13.55f, 19.50f, 15.03f, 19.20f, 16.38f, 18.66f)
                lineTo(16.80f, 19.08f)
                lineTo(19.73f, 22.00f)
                lineTo(21.00f, 20.73f)
                lineTo(3.27f, 3.00f)
                lineTo(2.00f, 4.27f)
                close()
                moveTo(7.53f, 9.80f)
                lineTo(9.08f, 11.35f)
                curveTo(9.03f, 11.56f, 9.00f, 11.78f, 9.00f, 12.00f)
                curveTo(9.00f, 13.66f, 10.34f, 15.00f, 12.00f, 15.00f)
                curveTo(12.22f, 15.00f, 12.44f, 14.97f, 12.65f, 14.92f)
                lineTo(14.20f, 16.47f)
                curveTo(13.53f, 16.80f, 12.79f, 17.00f, 12.00f, 17.00f)
                curveTo(9.24f, 17.00f, 7.00f, 14.76f, 7.00f, 12.00f)
                curveTo(7.00f, 11.21f, 7.20f, 10.47f, 7.53f, 9.80f)
                close()
                moveTo(11.84f, 9.02f)
                lineTo(14.99f, 12.17f)
                lineTo(15.01f, 12.01f)
                curveTo(15.01f, 10.35f, 13.67f, 9.01f, 12.01f, 9.01f)
                lineTo(11.84f, 9.02f)
                close()
            }
        }.build()
        return _VisibilityOff!!
    }

private var _VisibilityOff: ImageVector? = null
