// Generated by XIcons
// 2025-08-17 11:05:08
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Sharp.Volcano: ImageVector
    get() {
        if (_Volcano != null) {
            return _Volcano!!
        }
        _Volcano = ImageVector.Builder(
            name = "Volcano",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(18.00f, 8.00f)
                horizontalLineTo(11.00f)
                lineTo(9.00f, 13.00f)
                horizontalLineTo(6.00f)
                lineTo(2.00f, 22.00f)
                horizontalLineTo(22.00f)
                close()
                moveTo(13.00f, 1.00f)
                horizontalLineTo(15.00f)
                verticalLineTo(5.00f)
                horizontalLineTo(13.00f)
                close()
                moveTo(16.12f, 5.47f)
                lineTo(18.95f, 2.64f)
                lineTo(20.36f, 4.05f)
                lineTo(17.54f, 6.88f)
                close()
                moveTo(7.64f, 4.05f)
                lineTo(9.05f, 2.64f)
                lineTo(11.88f, 5.46f)
                lineTo(10.47f, 6.88f)
                close()
            }
        }.build()
        return _Volcano!!
    }

private var _Volcano: ImageVector? = null
