// Generated by XIcons
// 2025-08-17 11:05:08
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Sharp.WaterDrop: ImageVector
    get() {
        if (_WaterDrop != null) {
            return _WaterDrop!!
        }
        _WaterDrop = ImageVector.Builder(
            name = "WaterDrop",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(12.00f, 2.00f)
                curveTo(6.67f, 6.55f, 4.00f, 10.48f, 4.00f, 13.80f)
                curveTo(4.00f, 18.78f, 7.80f, 22.00f, 12.00f, 22.00f)
                curveTo(16.20f, 22.00f, 20.00f, 18.78f, 20.00f, 13.80f)
                curveTo(20.00f, 10.48f, 17.33f, 6.55f, 12.00f, 2.00f)
                close()
                moveTo(13.00f, 18.91f)
                curveTo(12.68f, 18.97f, 12.35f, 19.00f, 12.00f, 19.00f)
                curveTo(9.31f, 19.00f, 7.12f, 17.06f, 7.00f, 14.00f)
                horizontalLineTo(8.50f)
                curveTo(8.58f, 16.07f, 10.00f, 17.50f, 12.00f, 17.50f)
                curveTo(12.35f, 17.50f, 12.69f, 17.46f, 13.00f, 17.37f)
                verticalLineTo(18.91f)
                close()
            }
        }.build()
        return _WaterDrop!!
    }

private var _WaterDrop: ImageVector? = null
