// Generated by XIcons
// 2025-08-17 11:05:08
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Sharp.WifiCalling: ImageVector
    get() {
        if (_WifiCalling != null) {
            return _WifiCalling!!
        }
        _WifiCalling = ImageVector.Builder(
            name = "WifiCalling",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(13.21f, 17.37f)
                arcTo(15.05f, 15.05f, 0.00f, false, true, 6.62f, 10.78f)
                lineTo(9.15f, 8.25f)
                lineTo(8.54f, 3.00f)
                horizontalLineTo(3.03f)
                curveTo(2.45f, 13.18f, 10.82f, 21.55f, 21.00f, 20.97f)
                verticalLineTo(15.46f)
                lineTo(15.73f, 14.85f)
                lineTo(13.21f, 17.37f)
                close()
                moveTo(22.00f, 4.95f)
                curveTo(21.79f, 4.78f, 19.67f, 3.00f, 16.50f, 3.00f)
                curveTo(13.32f, 3.00f, 11.21f, 4.78f, 11.00f, 4.95f)
                lineTo(16.50f, 12.00f)
                lineTo(22.00f, 4.95f)
                close()
            }
        }.build()
        return _WifiCalling!!
    }

private var _WifiCalling: ImageVector? = null
