// Generated by XIcons
// 2025-08-17 11:05:09
package cn.enaium.xicons.compose.material

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.MaterialIcons

public val MaterialIcons.Filled.ZoomOutMap: ImageVector
    get() {
        if (_ZoomOutMap != null) {
            return _ZoomOutMap!!
        }
        _ZoomOutMap = ImageVector.Builder(
            name = "ZoomOutMap",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                moveTo(15.00f, 3.00f)
                lineTo(17.30f, 5.30f)
                lineTo(14.41f, 8.17f)
                lineTo(15.83f, 9.59f)
                lineTo(18.70f, 6.70f)
                lineTo(21.00f, 9.00f)
                verticalLineTo(3.00f)
                horizontalLineTo(15.00f)
                close()
                moveTo(3.00f, 9.00f)
                lineTo(5.30f, 6.70f)
                lineTo(8.17f, 9.59f)
                lineTo(9.59f, 8.17f)
                lineTo(6.70f, 5.30f)
                lineTo(9.00f, 3.00f)
                horizontalLineTo(3.00f)
                verticalLineTo(9.00f)
                close()
                moveTo(9.00f, 21.00f)
                lineTo(6.70f, 18.70f)
                lineTo(9.59f, 15.83f)
                lineTo(8.17f, 14.41f)
                lineTo(5.30f, 17.30f)
                lineTo(3.00f, 15.00f)
                verticalLineTo(21.00f)
                horizontalLineTo(9.00f)
                close()
                moveTo(21.00f, 15.00f)
                lineTo(18.70f, 17.30f)
                lineTo(15.83f, 14.41f)
                lineTo(14.41f, 15.83f)
                lineTo(17.30f, 18.70f)
                lineTo(15.00f, 21.00f)
                horizontalLineTo(21.00f)
                verticalLineTo(15.00f)
                close()
            }
        }.build()
        return _ZoomOutMap!!
    }

private var _ZoomOutMap: ImageVector? = null
