// Generated by XIcons
// 2025-08-14 22:09:46
package cn.enaium.xicons.jfx.icons.tabler;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class Bookmarks extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(13.00, 7.00);
        path.arcTo(2.00, 2.00, 0.00, false, true, 15.00, 9.00);
        path.verticalLineTo(21.00);
        path.lineTo(10.00, 18.00);
        path.lineTo(5.00, 21.00);
        path.verticalLineTo(9.00);
        path.arcTo(2.00, 2.00, 0.00, false, true, 7.00, 7.00);
        path.horizontalLineTo(13.00);
        path.close();
        path.moveTo(9.27, 4.00);
        path.arcTo(2.00, 2.00, 0.00, false, true, 11.00, 3.00);
        path.horizontalLineTo(17.00);
        path.arcTo(2.00, 2.00, 0.00, false, true, 19.00, 5.00);
        path.verticalLineTo(17.00);
        path.lineTo(18.00, 16.40);
        return path;
    }
}
