// Generated by XIcons
// 2025-08-14 22:09:46
package cn.enaium.xicons.jfx.icons.tabler;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class Brightness extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(12.00, 3.00);
        path.verticalLineTo(21.00);
        path.moveTo(12.00, 9.00);
        path.lineTo(16.65, 4.35);
        path.moveTo(12.00, 14.30);
        path.lineTo(19.37, 6.93);
        path.moveTo(12.00, 19.60);
        path.lineTo(20.85, 10.75);
        return path;
    }
}
