// Generated by XIcons
// 2025-08-14 22:09:47
package cn.enaium.xicons.jfx.icons.tabler;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class Directions extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(9.00, 5.00);
        path.horizontalLineTo(19.00);
        path.lineTo(21.00, 7.00);
        path.lineTo(19.00, 9.00);
        path.horizontalLineTo(9.00);
        path.arcTo(1.00, 1.00, 0.00, false, true, 8.00, 8.00);
        path.verticalLineTo(6.00);
        path.arcTo(1.00, 1.00, 0.00, false, true, 9.00, 5.00);
        path.moveTo(13.00, 13.00);
        path.horizontalLineTo(6.00);
        path.lineTo(4.00, 15.00);
        path.lineTo(6.00, 17.00);
        path.horizontalLineTo(13.00);
        path.arcTo(1.00, 1.00, 0.00, false, false, 14.00, 16.00);
        path.verticalLineTo(14.00);
        path.arcTo(1.00, 1.00, 0.00, false, false, 13.00, 13.00);
        path.moveTo(12.00, 22.00);
        path.verticalLineTo(17.00);
        path.moveTo(12.00, 13.00);
        path.verticalLineTo(9.00);
        path.moveTo(12.00, 5.00);
        path.verticalLineTo(3.00);
        return path;
    }
}
