// Generated by XIcons
// 2025-08-14 22:09:47
package cn.enaium.xicons.jfx.icons.tabler;

import cn.enaium.xicons.jfx.utility.ExtendPath;
import cn.enaium.xicons.jfx.utility.PathIcon;

public class H5 extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(17.00, 18.00);
        path.horizontalLineTo(19.00);
        path.arcTo(2.00, 2.00, 0.00, true, false, 19.00, 14.00);
        path.horizontalLineTo(17.00);
        path.verticalLineTo(10.00);
        path.horizontalLineTo(21.00);
        path.moveTo(4.00, 6.00);
        path.verticalLineTo(18.00);
        path.moveTo(12.00, 6.00);
        path.verticalLineTo(18.00);
        path.moveTo(11.00, 18.00);
        path.horizontalLineTo(13.00);
        path.moveTo(3.00, 18.00);
        path.horizontalLineTo(5.00);
        path.moveTo(4.00, 12.00);
        path.horizontalLineTo(12.00);
        path.moveTo(3.00, 6.00);
        path.horizontalLineTo(5.00);
        path.moveTo(11.00, 6.00);
        path.horizontalLineTo(13.00);
        return path;
    }
}
