// Generated by XIcons
// 2025-08-14 22:10:59
package cn.enaium.xicons.swing.icons.ionicons4;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class IosJournal extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(92.10, 32.00);
        path.curveTo(76.60, 32.00, 64.00, 44.60, 64.00, 60.10);
        path.verticalLineTo(452.00);
        path.curveTo(64.00, 467.50, 76.60, 480.10, 92.10, 480.10);
        path.horizontalLineTo(432.00);
        path.curveTo(440.80, 480.10, 448.00, 472.90, 448.00, 464.10);
        path.lineTo(448.00, 464.10);
        path.curveTo(448.00, 455.30, 440.80, 448.10, 432.00, 448.10);
        path.horizontalLineTo(112.50);
        path.curveTo(104.30, 448.10, 97.10, 442.10, 96.10, 434.00);
        path.curveTo(95.00, 424.30, 102.60, 416.00, 112.00, 416.00);
        path.horizontalLineTo(320.00);
        path.verticalLineTo(32.00);
        path.horizontalLineTo(92.10);
        path.close();
        path.moveTo(432.00, 416.00);
        path.curveTo(440.80, 416.00, 448.00, 408.80, 448.00, 400.00);
        path.verticalLineTo(60.10);
        path.curveTo(448.00, 44.60, 435.40, 32.00, 419.90, 32.00);
        path.horizontalLineTo(368.00);
        path.verticalLineTo(416.00);
        path.horizontalLineTo(432.00);
        path.close();
        path.scale(0.046875, 0.046875);
        return path;
    }
}
