// Generated by XIcons
// 2025-08-14 22:10:59
package cn.enaium.xicons.swing.icons.ionicons4;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class LogoVimeo extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(476.90, 114.00);
        path.curveTo(471.90, 90.60, 459.40, 75.20, 436.30, 67.70);
        path.curveTo(413.20, 60.20, 371.40, 63.20, 342.20, 84.50);
        path.curveTo(312.30, 106.30, 294.60, 144.20, 288.40, 168.30);
        path.curveTo(303.10, 162.00, 312.40, 160.60, 327.40, 161.40);
        path.curveTo(342.40, 162.20, 351.90, 173.40, 352.30, 186.70);
        path.curveTo(352.60, 196.50, 352.10, 205.40, 348.70, 214.40);
        path.curveTo(337.90, 243.10, 321.00, 270.90, 301.10, 295.20);
        path.curveTo(298.20, 298.80, 294.70, 302.10, 291.10, 305.10);
        path.curveTo(280.90, 313.40, 272.30, 311.20, 265.70, 299.90);
        path.curveTo(260.30, 290.60, 256.70, 281.00, 253.50, 270.80);
        path.curveTo(241.10, 231.10, 236.70, 189.90, 229.70, 149.20);
        path.curveTo(226.40, 129.70, 222.70, 109.40, 211.70, 92.30);
        path.curveTo(200.10, 74.50, 183.10, 67.70, 161.70, 70.30);
        path.curveTo(147.00, 72.10, 124.80, 87.80, 113.90, 96.70);
        path.curveTo(113.90, 96.70, 57.90, 143.60, 32.10, 168.10);
        path.lineTo(53.30, 195.10);
        path.curveTo(53.30, 195.10, 71.20, 182.60, 80.80, 176.80);
        path.curveTo(86.50, 173.40, 93.20, 172.70, 98.00, 177.00);
        path.curveTo(102.50, 180.90, 107.60, 186.00, 110.30, 191.10);
        path.curveTo(116.00, 201.80, 121.50, 213.00, 125.00, 224.50);
        path.curveTo(138.20, 268.80, 150.50, 313.20, 162.80, 357.80);
        path.curveTo(169.10, 380.60, 176.70, 402.00, 190.80, 421.40);
        path.curveTo(210.10, 448.00, 230.40, 454.10, 261.70, 442.90);
        path.curveTo(287.10, 433.80, 308.30, 416.70, 327.70, 399.00);
        path.curveTo(360.80, 368.80, 386.80, 333.60, 413.20, 297.80);
        path.curveTo(433.60, 270.10, 450.50, 242.10, 464.60, 210.80);
        path.curveTo(478.50, 179.80, 484.00, 147.30, 476.90, 114.00);
        path.close();
        path.scale(0.046875, 0.046875);
        return path;
    }
}
