// Generated by XIcons
// 2025-08-14 22:10:59
package cn.enaium.xicons.swing.icons.ionicons4;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class MdBrowsers extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(424.00, 64.00);
        path.horizontalLineTo(88.00);
        path.curveTo(61.40, 64.00, 40.00, 85.60, 40.00, 112.00);
        path.verticalLineTo(400.00);
        path.curveTo(40.00, 426.40, 61.40, 448.00, 88.00, 448.00);
        path.horizontalLineTo(424.00);
        path.curveTo(450.40, 448.00, 472.00, 426.40, 472.00, 400.00);
        path.verticalLineTo(112.00);
        path.curveTo(472.00, 85.60, 450.60, 64.00, 424.00, 64.00);
        path.close();
        path.moveTo(424.00, 400.00);
        path.horizontalLineTo(88.00);
        path.verticalLineTo(176.00);
        path.horizontalLineTo(424.00);
        path.verticalLineTo(400.00);
        path.close();
        path.scale(0.046875, 0.046875);
        return path;
    }
}
