// Generated by XIcons
// 2025-08-14 22:10:59
package cn.enaium.xicons.swing.icons.ionicons4;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class MdGlasses extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(480.00, 176.00);
        path.horizontalLineTo(272.00);
        path.verticalLineTo(176.10);
        path.lineTo(240.00, 176.10);
        path.verticalLineTo(176.00);
        path.horizontalLineTo(32.00);
        path.verticalLineTo(224.00);
        path.horizontalLineTo(43.00);
        path.lineTo(48.00, 245.50);
        path.curveTo(64.00, 313.00, 88.50, 336.00, 144.00, 336.00);
        path.curveTo(199.50, 336.00, 240.00, 318.60, 240.00, 245.50);
        path.verticalLineTo(224.00);
        path.curveTo(240.00, 224.00, 241.50, 208.00, 256.00, 208.00);
        path.curveTo(270.50, 208.00, 272.00, 224.00, 272.00, 224.00);
        path.verticalLineTo(245.80);
        path.curveTo(272.00, 318.80, 314.10, 336.00, 369.00, 336.00);
        path.curveTo(423.90, 336.00, 448.00, 311.00, 464.00, 245.80);
        path.lineTo(469.00, 224.00);
        path.horizontalLineTo(480.00);
        path.verticalLineTo(176.00);
        path.lineTo(480.00, 176.00);
        path.lineTo(480.00, 176.00);
        path.close();
        path.scale(0.046875, 0.046875);
        return path;
    }
}
