// Generated by XIcons
// 2025-08-14 22:11:00
package cn.enaium.xicons.swing.icons.ionicons4;

import cn.enaium.xicons.swing.utility.ExtendPath;
import cn.enaium.xicons.swing.utility.PathIcon;

public class MdStarOutline extends PathIcon {
    public ExtendPath path() {
        ExtendPath path = new ExtendPath();
        path.moveTo(458.00, 210.41);
        path.lineTo(312.73, 197.93);
        path.lineTo(256.00, 64.00);
        path.lineTo(199.26, 197.93);
        path.lineTo(54.00, 210.41);
        path.lineTo(164.19, 305.93);
        path.lineTo(131.16, 448.00);
        path.lineTo(256.00, 372.69);
        path.lineTo(380.83, 448.00);
        path.lineTo(347.81, 305.93);
        path.lineTo(458.00, 210.41);
        path.close();
        path.moveTo(272.53, 345.29);
        path.lineTo(256.00, 335.31);
        path.lineTo(239.47, 345.29);
        path.lineTo(179.48, 381.48);
        path.lineTo(195.36, 313.18);
        path.lineTo(199.73, 294.39);
        path.lineTo(185.15, 281.75);
        path.lineTo(132.16, 235.81);
        path.lineTo(202.00, 229.82);
        path.lineTo(221.20, 228.17);
        path.lineTo(228.72, 210.42);
        path.lineTo(256.00, 146.04);
        path.lineTo(283.27, 210.41);
        path.lineTo(290.79, 228.17);
        path.lineTo(310.00, 229.82);
        path.lineTo(379.84, 235.81);
        path.lineTo(326.85, 281.75);
        path.lineTo(312.27, 294.39);
        path.lineTo(316.64, 313.18);
        path.lineTo(332.52, 381.48);
        path.lineTo(272.53, 345.29);
        path.close();
        path.scale(0.046875, 0.046875);
        return path;
    }
}
