// Generated by XIcons
// 2025-08-17 11:03:50
package cn.enaium.xicons.compose.carbon

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.CarbonIcons

public val CarbonIcons.Default.Analytics: ImageVector
    get() {
        if (_Analytics != null) {
            return _Analytics!!
        }
        _Analytics = ImageVector.Builder(
            name = "Analytics",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.75f, scaleY = 0.75f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(4.00f, 2.00f)
                    horizontalLineTo(2.00f)
                    verticalLineTo(28.00f)
                    arcTo(2.00f, 2.00f, 0.00f, false, false, 4.00f, 30.00f)
                    horizontalLineTo(30.00f)
                    verticalLineTo(28.00f)
                    horizontalLineTo(4.00f)
                    close()
                    moveTo(30.00f, 9.00f)
                    horizontalLineTo(23.00f)
                    verticalLineTo(11.00f)
                    horizontalLineTo(26.59f)
                    lineTo(19.00f, 18.59f)
                    lineTo(14.71f, 14.29f)
                    arcTo(1.00f, 1.00f, 0.00f, false, false, 13.29f, 14.29f)
                    lineTo(6.00f, 21.59f)
                    lineTo(7.41f, 23.00f)
                    lineTo(14.00f, 16.41f)
                    lineTo(18.29f, 20.71f)
                    arcTo(1.00f, 1.00f, 0.00f, false, false, 19.71f, 20.71f)
                    lineTo(28.00f, 12.41f)
                    verticalLineTo(16.00f)
                    horizontalLineTo(30.00f)
                    close()
                }
            }
        }.build()
        return _Analytics!!
    }

private var _Analytics: ImageVector? = null
