// Generated by XIcons
// 2025-08-17 11:03:52
package cn.enaium.xicons.compose.carbon

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.CarbonIcons

public val CarbonIcons.Default.DataCheck: ImageVector
    get() {
        if (_DataCheck != null) {
            return _DataCheck!!
        }
        _DataCheck = ImageVector.Builder(
            name = "DataCheck",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.75f, scaleY = 0.75f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(23.00f, 27.18f)
                    lineTo(20.41f, 24.59f)
                    lineTo(19.00f, 26.00f)
                    lineTo(23.00f, 30.00f)
                    lineTo(30.00f, 23.00f)
                    lineTo(28.59f, 21.59f)
                    lineTo(23.00f, 27.18f)
                    close()
                    moveTo(24.00f, 3.00f)
                    horizontalLineTo(8.00f)
                    arcTo(2.00f, 2.00f, 0.00f, false, false, 6.00f, 5.00f)
                    verticalLineTo(27.00f)
                    arcTo(2.00f, 2.00f, 0.00f, false, false, 8.00f, 29.00f)
                    horizontalLineTo(16.00f)
                    verticalLineTo(27.00f)
                    horizontalLineTo(8.00f)
                    verticalLineTo(21.00f)
                    horizontalLineTo(26.00f)
                    verticalLineTo(5.00f)
                    arcTo(2.00f, 2.00f, 0.00f, false, false, 24.00f, 3.00f)
                    close()
                    moveTo(24.00f, 19.00f)
                    horizontalLineTo(8.00f)
                    verticalLineTo(13.00f)
                    horizontalLineTo(24.00f)
                    close()
                    moveTo(24.00f, 11.00f)
                    horizontalLineTo(8.00f)
                    verticalLineTo(5.00f)
                    horizontalLineTo(24.00f)
                    close()
                }
            }
        }.build()
        return _DataCheck!!
    }

private var _DataCheck: ImageVector? = null
