// Generated by XIcons
// 2025-08-17 11:03:52
package cn.enaium.xicons.compose.carbon

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.CarbonIcons

public val CarbonIcons.Default.DewPoint: ImageVector
    get() {
        if (_DewPoint != null) {
            return _DewPoint!!
        }
        _DewPoint = ImageVector.Builder(
            name = "DewPoint",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.75f, scaleY = 0.75f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(24.00f, 10.00f)
                    arcTo(4.00f, 4.00f, 0.00f, true, true, 28.00f, 6.00f)
                    arcTo(4.01f, 4.01f, 0.00f, false, true, 24.00f, 10.00f)
                    close()
                    moveTo(24.00f, 4.00f)
                    arcTo(2.00f, 2.00f, 0.00f, true, false, 26.00f, 6.00f)
                    arcTo(2.00f, 2.00f, 0.00f, false, false, 24.00f, 4.00f)
                    close()
                    moveTo(14.50f, 30.00f)
                    arcTo(5.50f, 5.50f, 0.00f, false, true, 9.00f, 24.52f)
                    curveTo(9.00f, 21.08f, 13.34f, 3.51f, 13.53f, 2.76f)
                    arcTo(1.00f, 1.00f, 0.00f, false, true, 15.47f, 2.76f)
                    curveTo(15.66f, 3.51f, 20.00f, 21.08f, 20.00f, 24.52f)
                    arcTo(5.50f, 5.50f, 0.00f, false, true, 14.50f, 30.00f)
                    close()
                    moveTo(14.50f, 7.24f)
                    curveTo(13.04f, 13.38f, 11.00f, 22.41f, 11.00f, 24.52f)
                    arcTo(3.50f, 3.50f, 0.00f, false, false, 18.00f, 24.52f)
                    curveTo(18.00f, 22.41f, 15.96f, 13.38f, 14.50f, 7.24f)
                    close()
                }
            }
        }.build()
        return _DewPoint!!
    }

private var _DewPoint: ImageVector? = null
