// Generated by XIcons
// 2025-08-17 11:03:52
package cn.enaium.xicons.compose.carbon

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.CarbonIcons

public val CarbonIcons.Default.DirectionRight01: ImageVector
    get() {
        if (_DirectionRight01 != null) {
            return _DirectionRight01!!
        }
        _DirectionRight01 = ImageVector.Builder(
            name = "DirectionRight01",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.75f, scaleY = 0.75f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(19.00f, 4.00f)
                    lineTo(17.59f, 5.41f)
                    lineTo(22.17f, 10.00f)
                    horizontalLineTo(10.00f)
                    arcTo(2.00f, 2.00f, 0.00f, false, false, 8.00f, 12.00f)
                    verticalLineTo(28.00f)
                    horizontalLineTo(10.00f)
                    verticalLineTo(12.00f)
                    horizontalLineTo(22.17f)
                    lineTo(17.59f, 16.59f)
                    lineTo(19.00f, 18.00f)
                    lineTo(26.00f, 11.00f)
                    close()
                }
            }
        }.build()
        return _DirectionRight01!!
    }

private var _DirectionRight01: ImageVector? = null
