// Generated by XIcons
// 2025-08-17 11:03:52
package cn.enaium.xicons.compose.carbon

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.CarbonIcons

public val CarbonIcons.Default.Dna: ImageVector
    get() {
        if (_Dna != null) {
            return _Dna!!
        }
        _Dna = ImageVector.Builder(
            name = "Dna",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.75f, scaleY = 0.75f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(22.00f, 2.00f)
                    verticalLineTo(1.00f)
                    horizontalLineTo(20.00f)
                    verticalLineTo(2.00f)
                    arcTo(7.04f, 7.04f, 0.00f, false, true, 19.92f, 3.00f)
                    horizontalLineTo(12.08f)
                    arcTo(7.04f, 7.04f, 0.00f, false, true, 12.00f, 2.00f)
                    verticalLineTo(1.00f)
                    horizontalLineTo(10.00f)
                    verticalLineTo(2.00f)
                    curveTo(10.00f, 5.76f, 11.97f, 7.60f, 14.10f, 9.00f)
                    curveTo(11.97f, 10.40f, 10.00f, 12.25f, 10.00f, 16.00f)
                    curveTo(10.00f, 19.76f, 11.97f, 21.60f, 14.10f, 23.00f)
                    curveTo(11.97f, 24.40f, 10.00f, 26.25f, 10.00f, 30.00f)
                    verticalLineTo(31.00f)
                    horizontalLineTo(12.00f)
                    verticalLineTo(30.00f)
                    arcTo(7.04f, 7.04f, 0.00f, false, true, 12.08f, 29.00f)
                    horizontalLineTo(19.92f)
                    arcTo(7.04f, 7.04f, 0.00f, false, true, 20.00f, 30.00f)
                    verticalLineTo(31.00f)
                    horizontalLineTo(22.00f)
                    verticalLineTo(30.00f)
                    curveTo(22.00f, 26.25f, 20.03f, 24.40f, 17.90f, 23.00f)
                    curveTo(20.03f, 21.60f, 22.00f, 19.76f, 22.00f, 16.00f)
                    curveTo(22.00f, 12.25f, 20.03f, 10.40f, 17.90f, 9.00f)
                    curveTo(20.03f, 7.60f, 22.00f, 5.76f, 22.00f, 2.00f)
                    close()
                    moveTo(20.00f, 16.00f)
                    arcTo(7.04f, 7.04f, 0.00f, false, true, 19.92f, 17.00f)
                    horizontalLineTo(12.08f)
                    arcTo(6.32f, 6.32f, 0.00f, false, true, 12.08f, 15.00f)
                    horizontalLineTo(19.92f)
                    arcTo(7.04f, 7.04f, 0.00f, false, true, 20.00f, 16.00f)
                    close()
                    moveTo(19.24f, 27.00f)
                    horizontalLineTo(12.76f)
                    arcTo(8.91f, 8.91f, 0.00f, false, true, 16.00f, 24.17f)
                    arcTo(8.91f, 8.91f, 0.00f, false, true, 19.24f, 27.00f)
                    close()
                    moveTo(16.00f, 21.83f)
                    arcTo(8.91f, 8.91f, 0.00f, false, true, 12.76f, 19.00f)
                    horizontalLineTo(19.24f)
                    arcTo(8.91f, 8.91f, 0.00f, false, true, 16.00f, 21.83f)
                    close()
                    moveTo(19.24f, 13.00f)
                    horizontalLineTo(12.76f)
                    arcTo(8.91f, 8.91f, 0.00f, false, true, 16.00f, 10.17f)
                    arcTo(8.91f, 8.91f, 0.00f, false, true, 19.24f, 13.00f)
                    close()
                    moveTo(16.00f, 7.83f)
                    arcTo(8.91f, 8.91f, 0.00f, false, true, 12.76f, 5.00f)
                    horizontalLineTo(19.24f)
                    arcTo(8.91f, 8.91f, 0.00f, false, true, 16.00f, 7.83f)
                    close()
                }
            }
        }.build()
        return _Dna!!
    }

private var _Dna: ImageVector? = null
