// Generated by XIcons
// 2025-08-17 11:03:53
package cn.enaium.xicons.compose.carbon

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.CarbonIcons

public val CarbonIcons.Default.FilterRemove: ImageVector
    get() {
        if (_FilterRemove != null) {
            return _FilterRemove!!
        }
        _FilterRemove = ImageVector.Builder(
            name = "FilterRemove",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.75f, scaleY = 0.75f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(30.00f, 11.41f)
                    lineTo(28.59f, 10.00f)
                    lineTo(24.00f, 14.59f)
                    lineTo(19.41f, 10.00f)
                    lineTo(18.00f, 11.41f)
                    lineTo(22.59f, 16.00f)
                    lineTo(18.00f, 20.59f)
                    lineTo(19.42f, 22.00f)
                    lineTo(24.00f, 17.41f)
                    lineTo(28.59f, 22.00f)
                    lineTo(30.00f, 20.59f)
                    lineTo(25.41f, 16.00f)
                    lineTo(30.00f, 11.41f)
                    close()
                    moveTo(4.00f, 4.00f)
                    arcTo(2.00f, 2.00f, 0.00f, false, false, 2.00f, 6.00f)
                    verticalLineTo(9.17f)
                    arcTo(2.00f, 2.00f, 0.00f, false, false, 2.59f, 10.59f)
                    lineTo(10.00f, 18.00f)
                    verticalLineTo(26.00f)
                    arcTo(2.00f, 2.00f, 0.00f, false, false, 12.00f, 28.00f)
                    horizontalLineTo(16.00f)
                    arcTo(2.00f, 2.00f, 0.00f, false, false, 18.00f, 26.00f)
                    verticalLineTo(24.00f)
                    horizontalLineTo(16.00f)
                    verticalLineTo(26.00f)
                    horizontalLineTo(12.00f)
                    verticalLineTo(17.17f)
                    lineTo(11.41f, 16.59f)
                    lineTo(4.00f, 9.17f)
                    verticalLineTo(6.00f)
                    horizontalLineTo(24.00f)
                    verticalLineTo(8.00f)
                    horizontalLineTo(26.00f)
                    verticalLineTo(6.00f)
                    arcTo(2.00f, 2.00f, 0.00f, false, false, 24.00f, 4.00f)
                    close()
                }
            }
        }.build()
        return _FilterRemove!!
    }

private var _FilterRemove: ImageVector? = null
