// Generated by XIcons
// 2025-08-17 11:03:53
package cn.enaium.xicons.compose.carbon

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.CarbonIcons

public val CarbonIcons.Default.IbmCloud: ImageVector
    get() {
        if (_IbmCloud != null) {
            return _IbmCloud!!
        }
        _IbmCloud = ImageVector.Builder(
            name = "IbmCloud",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.75f, scaleY = 0.75f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(24.58f, 13.65f)
                    arcTo(9.73f, 9.73f, 0.00f, false, false, 6.29f, 17.54f)
                    arcTo(6.75f, 6.75f, 0.00f, false, false, 7.00f, 31.00f)
                    horizontalLineTo(23.00f)
                    arcTo(8.75f, 8.75f, 0.00f, false, false, 24.58f, 13.65f)
                    close()
                    moveTo(23.00f, 29.50f)
                    horizontalLineTo(7.00f)
                    arcTo(5.24f, 5.24f, 0.00f, false, true, 6.30f, 19.07f)
                    arcTo(9.73f, 9.73f, 0.00f, false, false, 7.40f, 22.86f)
                    arcTo(0.75f, 0.75f, 0.00f, true, false, 8.73f, 22.15f)
                    arcTo(8.25f, 8.25f, 0.00f, false, true, 22.75f, 13.51f)
                    arcTo(8.75f, 8.75f, 0.00f, false, false, 16.44f, 16.46f)
                    arcTo(0.75f, 0.75f, 0.00f, true, false, 17.56f, 17.46f)
                    arcTo(7.25f, 7.25f, 0.00f, true, true, 23.00f, 29.50f)
                    close()
                    moveTo(31.90f, 10.26f)
                    arcTo(0.76f, 0.76f, 0.00f, false, false, 30.86f, 9.98f)
                    lineTo(27.84f, 11.72f)
                    arcTo(0.76f, 0.76f, 0.00f, true, false, 28.60f, 13.04f)
                    lineTo(31.62f, 11.29f)
                    arcTo(0.76f, 0.76f, 0.00f, false, false, 31.90f, 10.26f)
                    close()
                    moveTo(22.68f, 7.87f)
                    arcTo(0.76f, 0.76f, 0.00f, false, false, 23.71f, 7.59f)
                    lineTo(25.46f, 4.57f)
                    arcTo(0.76f, 0.76f, 0.00f, false, false, 24.14f, 3.81f)
                    lineTo(22.40f, 6.83f)
                    arcTo(0.76f, 0.76f, 0.00f, false, false, 22.68f, 7.87f)
                    close()
                    moveTo(16.00f, 6.08f)
                    arcTo(0.76f, 0.76f, 0.00f, false, false, 16.76f, 5.32f)
                    verticalLineTo(1.84f)
                    arcTo(0.76f, 0.76f, 0.00f, true, false, 15.24f, 1.84f)
                    verticalLineTo(5.32f)
                    arcTo(0.76f, 0.76f, 0.00f, false, false, 16.00f, 6.08f)
                    close()
                    moveTo(8.29f, 7.59f)
                    arcTo(0.76f, 0.76f, 0.00f, false, false, 9.60f, 6.83f)
                    lineTo(7.86f, 3.81f)
                    arcTo(0.76f, 0.76f, 0.00f, true, false, 6.54f, 4.57f)
                    close()
                    moveTo(4.16f, 11.72f)
                    lineTo(1.14f, 9.98f)
                    arcTo(0.76f, 0.76f, 0.00f, true, false, 0.38f, 11.29f)
                    lineTo(3.40f, 13.04f)
                    arcTo(0.76f, 0.76f, 0.00f, true, false, 4.16f, 11.72f)
                    close()
                }
            }
        }.build()
        return _IbmCloud!!
    }

private var _IbmCloud: ImageVector? = null
