// Generated by XIcons
// 2025-08-17 11:03:55
package cn.enaium.xicons.compose.carbon

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.CarbonIcons

public val CarbonIcons.Default.Queued: ImageVector
    get() {
        if (_Queued != null) {
            return _Queued!!
        }
        _Queued = ImageVector.Builder(
            name = "Queued",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.75f, scaleY = 0.75f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(22.00f, 20.00f)
                    horizontalLineTo(30.00f)
                    verticalLineTo(22.00f)
                    horizontalLineTo(22.00f)
                    close()
                    moveTo(22.00f, 24.00f)
                    horizontalLineTo(30.00f)
                    verticalLineTo(26.00f)
                    horizontalLineTo(22.00f)
                    close()
                    moveTo(22.00f, 28.00f)
                    horizontalLineTo(30.00f)
                    verticalLineTo(30.00f)
                    horizontalLineTo(22.00f)
                    close()
                    moveTo(18.00f, 24.00f)
                    horizontalLineTo(20.00f)
                    verticalLineTo(26.00f)
                    horizontalLineTo(18.00f)
                    close()
                    moveTo(18.00f, 20.00f)
                    horizontalLineTo(20.00f)
                    verticalLineTo(22.00f)
                    horizontalLineTo(18.00f)
                    close()
                    moveTo(18.00f, 28.00f)
                    horizontalLineTo(20.00f)
                    verticalLineTo(30.00f)
                    horizontalLineTo(18.00f)
                    close()
                    moveTo(6.82f, 8.29f)
                    arcTo(12.08f, 12.08f, 0.00f, false, true, 10.01f, 5.62f)
                    lineTo(9.01f, 3.89f)
                    arcTo(14.09f, 14.09f, 0.00f, false, false, 5.28f, 7.01f)
                    close()
                    moveTo(25.19f, 8.29f)
                    lineTo(26.72f, 7.01f)
                    arcTo(14.09f, 14.09f, 0.00f, false, false, 22.99f, 3.89f)
                    lineTo(21.99f, 5.62f)
                    arcTo(12.08f, 12.08f, 0.00f, false, true, 25.19f, 8.29f)
                    close()
                    moveTo(4.74f, 11.90f)
                    lineTo(2.86f, 11.22f)
                    arcTo(13.90f, 13.90f, 0.00f, false, false, 2.00f, 16.00f)
                    horizontalLineTo(4.00f)
                    arcTo(11.92f, 11.92f, 0.00f, false, true, 4.74f, 11.90f)
                    close()
                    moveTo(6.82f, 23.71f)
                    arcTo(12.00f, 12.00f, 0.00f, false, true, 4.74f, 20.10f)
                    lineTo(2.86f, 20.78f)
                    arcTo(13.99f, 13.99f, 0.00f, false, false, 5.28f, 24.99f)
                    close()
                    moveTo(27.26f, 11.90f)
                    arcTo(11.92f, 11.92f, 0.00f, false, true, 28.00f, 16.00f)
                    horizontalLineTo(30.00f)
                    arcTo(13.90f, 13.90f, 0.00f, false, false, 29.14f, 11.22f)
                    close()
                    moveTo(13.92f, 27.81f)
                    arcTo(11.89f, 11.89f, 0.00f, false, true, 10.01f, 26.38f)
                    lineTo(9.01f, 28.11f)
                    arcTo(13.87f, 13.87f, 0.00f, false, false, 13.57f, 29.77f)
                    close()
                    moveTo(13.92f, 4.19f)
                    arcTo(11.30f, 11.30f, 0.00f, false, true, 18.08f, 4.19f)
                    lineTo(18.43f, 2.23f)
                    arcTo(13.19f, 13.19f, 0.00f, false, false, 13.57f, 2.23f)
                    close()
                }
            }
        }.build()
        return _Queued!!
    }

private var _Queued: ImageVector? = null
