// Generated by XIcons
// 2025-08-17 11:03:55
package cn.enaium.xicons.compose.carbon

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.CarbonIcons

public val CarbonIcons.Default.ReflectHorizontal: ImageVector
    get() {
        if (_ReflectHorizontal != null) {
            return _ReflectHorizontal!!
        }
        _ReflectHorizontal = ImageVector.Builder(
            name = "ReflectHorizontal",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.75f, scaleY = 0.75f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(19.39f, 15.21f)
                    lineTo(28.39f, 8.21f)
                    arcTo(1.00f, 1.00f, 0.00f, false, true, 30.00f, 9.00f)
                    verticalLineTo(23.00f)
                    arcTo(1.00f, 1.00f, 0.00f, false, true, 28.39f, 23.79f)
                    lineTo(19.39f, 16.79f)
                    arcTo(1.00f, 1.00f, 0.00f, false, true, 19.39f, 15.21f)
                    close()
                    moveTo(15.00f, 2.00f)
                    horizontalLineTo(17.00f)
                    verticalLineTo(30.00f)
                    horizontalLineTo(15.00f)
                    close()
                    moveTo(13.00f, 16.00f)
                    arcTo(1.00f, 1.00f, 0.00f, false, true, 12.61f, 16.79f)
                    lineTo(3.61f, 23.79f)
                    arcTo(1.00f, 1.00f, 0.00f, false, true, 2.00f, 23.00f)
                    verticalLineTo(9.00f)
                    arcTo(1.00f, 1.00f, 0.00f, false, true, 3.61f, 8.21f)
                    lineTo(12.61f, 15.21f)
                    arcTo(1.00f, 1.00f, 0.00f, false, true, 13.00f, 16.00f)
                    close()
                    moveTo(4.00f, 20.96f)
                    lineTo(10.37f, 16.00f)
                    lineTo(4.00f, 11.04f)
                    close()
                }
            }
        }.build()
        return _ReflectHorizontal!!
    }

private var _ReflectHorizontal: ImageVector? = null
