// Generated by XIcons
// 2025-08-17 11:03:57
package cn.enaium.xicons.compose.carbon

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.CarbonIcons

public val CarbonIcons.Default.SpineLabel: ImageVector
    get() {
        if (_SpineLabel != null) {
            return _SpineLabel!!
        }
        _SpineLabel = ImageVector.Builder(
            name = "SpineLabel",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.75f, scaleY = 0.75f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(3.00f, 11.00f)
                    verticalLineTo(13.00f)
                    horizontalLineTo(8.59f)
                    lineTo(2.29f, 19.29f)
                    lineTo(3.71f, 20.71f)
                    lineTo(10.00f, 14.41f)
                    verticalLineTo(20.00f)
                    horizontalLineTo(12.00f)
                    verticalLineTo(11.00f)
                    horizontalLineTo(3.00f)
                    close()
                    moveTo(26.00f, 13.00f)
                    horizontalLineTo(23.00f)
                    verticalLineTo(12.00f)
                    horizontalLineTo(21.00f)
                    verticalLineTo(13.00f)
                    horizontalLineTo(18.00f)
                    arcTo(2.00f, 2.00f, 0.00f, false, false, 16.00f, 15.00f)
                    verticalLineTo(17.00f)
                    arcTo(2.00f, 2.00f, 0.00f, false, false, 18.00f, 19.00f)
                    horizontalLineTo(21.00f)
                    verticalLineTo(20.00f)
                    horizontalLineTo(23.00f)
                    verticalLineTo(19.00f)
                    horizontalLineTo(26.00f)
                    arcTo(2.00f, 2.00f, 0.00f, false, false, 28.00f, 17.00f)
                    verticalLineTo(15.00f)
                    arcTo(2.00f, 2.00f, 0.00f, false, false, 26.00f, 13.00f)
                    close()
                    moveTo(18.00f, 17.00f)
                    verticalLineTo(15.00f)
                    horizontalLineTo(26.00f)
                    verticalLineTo(17.00f)
                    close()
                    moveTo(26.00f, 23.00f)
                    horizontalLineTo(23.00f)
                    verticalLineTo(22.00f)
                    horizontalLineTo(21.00f)
                    verticalLineTo(23.00f)
                    horizontalLineTo(18.00f)
                    arcTo(2.00f, 2.00f, 0.00f, false, false, 16.00f, 25.00f)
                    verticalLineTo(27.00f)
                    arcTo(2.00f, 2.00f, 0.00f, false, false, 18.00f, 29.00f)
                    horizontalLineTo(21.00f)
                    verticalLineTo(30.00f)
                    horizontalLineTo(23.00f)
                    verticalLineTo(29.00f)
                    horizontalLineTo(26.00f)
                    arcTo(2.00f, 2.00f, 0.00f, false, false, 28.00f, 27.00f)
                    verticalLineTo(25.00f)
                    arcTo(2.00f, 2.00f, 0.00f, false, false, 26.00f, 23.00f)
                    close()
                    moveTo(18.00f, 27.00f)
                    verticalLineTo(25.00f)
                    horizontalLineTo(26.00f)
                    verticalLineTo(27.00f)
                    close()
                    moveTo(26.00f, 3.00f)
                    horizontalLineTo(23.00f)
                    verticalLineTo(2.00f)
                    horizontalLineTo(21.00f)
                    verticalLineTo(3.00f)
                    horizontalLineTo(18.00f)
                    arcTo(2.00f, 2.00f, 0.00f, false, false, 16.00f, 5.00f)
                    verticalLineTo(7.00f)
                    arcTo(2.00f, 2.00f, 0.00f, false, false, 18.00f, 9.00f)
                    horizontalLineTo(21.00f)
                    verticalLineTo(10.00f)
                    horizontalLineTo(23.00f)
                    verticalLineTo(9.00f)
                    horizontalLineTo(26.00f)
                    arcTo(2.00f, 2.00f, 0.00f, false, false, 28.00f, 7.00f)
                    verticalLineTo(5.00f)
                    arcTo(2.00f, 2.00f, 0.00f, false, false, 26.00f, 3.00f)
                    close()
                    moveTo(18.00f, 7.00f)
                    verticalLineTo(5.00f)
                    horizontalLineTo(26.00f)
                    verticalLineTo(7.00f)
                    close()
                }
            }
        }.build()
        return _SpineLabel!!
    }

private var _SpineLabel: ImageVector? = null
