// Generated by XIcons
// 2025-08-17 11:03:58
package cn.enaium.xicons.compose.carbon

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.CarbonIcons

public val CarbonIcons.Default.TaskTools: ImageVector
    get() {
        if (_TaskTools != null) {
            return _TaskTools!!
        }
        _TaskTools = ImageVector.Builder(
            name = "TaskTools",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.75f, scaleY = 0.75f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(28.50f, 32.00f)
                    arcTo(3.48f, 3.48f, 0.00f, false, true, 26.03f, 30.98f)
                    lineTo(21.90f, 26.85f)
                    arcTo(6.50f, 6.50f, 0.00f, false, true, 14.55f, 17.89f)
                    lineTo(15.14f, 16.55f)
                    lineTo(19.29f, 20.71f)
                    arcTo(1.02f, 1.02f, 0.00f, false, false, 20.71f, 20.71f)
                    arcTo(1.00f, 1.00f, 0.00f, false, false, 20.71f, 19.29f)
                    lineTo(16.55f, 15.14f)
                    lineTo(17.89f, 14.55f)
                    arcTo(6.50f, 6.50f, 0.00f, false, true, 26.85f, 21.90f)
                    lineTo(30.98f, 26.03f)
                    arcTo(3.50f, 3.50f, 0.00f, false, true, 28.50f, 32.00f)
                    close()
                    moveTo(22.47f, 24.59f)
                    lineTo(27.44f, 29.56f)
                    arcTo(1.54f, 1.54f, 0.00f, false, false, 29.56f, 29.56f)
                    arcTo(1.50f, 1.50f, 0.00f, false, false, 29.56f, 27.44f)
                    lineTo(24.59f, 22.47f)
                    lineTo(24.78f, 21.89f)
                    arcTo(4.50f, 4.50f, 0.00f, false, false, 20.50f, 16.00f)
                    quadTo(20.37f, 16.00f, 20.25f, 16.01f)
                    lineTo(22.12f, 17.88f)
                    arcTo(3.00f, 3.00f, 0.00f, false, true, 22.12f, 22.12f)
                    arcTo(3.07f, 3.07f, 0.00f, false, true, 17.88f, 22.12f)
                    lineTo(16.01f, 20.25f)
                    quadTo(16.00f, 20.37f, 16.00f, 20.50f)
                    arcTo(4.50f, 4.50f, 0.00f, false, false, 21.89f, 24.78f)
                    close()
                    moveTo(25.00f, 5.00f)
                    horizontalLineTo(22.00f)
                    verticalLineTo(4.00f)
                    arcTo(2.01f, 2.01f, 0.00f, false, false, 20.00f, 2.00f)
                    horizontalLineTo(12.00f)
                    arcTo(2.01f, 2.01f, 0.00f, false, false, 10.00f, 4.00f)
                    verticalLineTo(5.00f)
                    horizontalLineTo(7.00f)
                    arcTo(2.01f, 2.01f, 0.00f, false, false, 5.00f, 7.00f)
                    verticalLineTo(28.00f)
                    arcTo(2.01f, 2.01f, 0.00f, false, false, 7.00f, 30.00f)
                    horizontalLineTo(14.00f)
                    verticalLineTo(28.00f)
                    horizontalLineTo(7.00f)
                    verticalLineTo(7.00f)
                    horizontalLineTo(10.00f)
                    verticalLineTo(10.00f)
                    horizontalLineTo(22.00f)
                    verticalLineTo(7.00f)
                    horizontalLineTo(25.00f)
                    verticalLineTo(12.00f)
                    horizontalLineTo(27.00f)
                    verticalLineTo(7.00f)
                    arcTo(2.01f, 2.01f, 0.00f, false, false, 25.00f, 5.00f)
                    close()
                    moveTo(20.00f, 8.00f)
                    horizontalLineTo(12.00f)
                    verticalLineTo(4.00f)
                    horizontalLineTo(20.00f)
                    close()
                }
            }
        }.build()
        return _TaskTools!!
    }

private var _TaskTools: ImageVector? = null
