// Generated by XIcons
// 2025-08-17 11:03:58
package cn.enaium.xicons.compose.carbon

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.CarbonIcons

public val CarbonIcons.Default.Tools: ImageVector
    get() {
        if (_Tools != null) {
            return _Tools!!
        }
        _Tools = ImageVector.Builder(
            name = "Tools",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.75f, scaleY = 0.75f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(12.10f, 2.00f)
                    arcTo(9.80f, 9.80f, 0.00f, false, false, 6.70f, 3.60f)
                    lineTo(13.10f, 10.00f)
                    arcTo(2.10f, 2.10f, 0.00f, false, true, 13.30f, 13.00f)
                    arcTo(2.10f, 2.10f, 0.00f, false, true, 10.30f, 12.80f)
                    lineTo(3.70f, 6.40f)
                    arcTo(9.84f, 9.84f, 0.00f, false, false, 2.00f, 12.10f)
                    arcTo(10.14f, 10.14f, 0.00f, false, false, 12.10f, 22.20f)
                    arcTo(10.90f, 10.90f, 0.00f, false, false, 14.70f, 21.90f)
                    lineTo(21.40f, 28.60f)
                    arcTo(5.00f, 5.00f, 0.00f, false, false, 28.50f, 21.50f)
                    lineTo(21.80f, 14.80f)
                    arcTo(10.90f, 10.90f, 0.00f, false, false, 22.10f, 12.20f)
                    arcTo(10.00f, 10.00f, 0.00f, false, false, 12.10f, 2.00f)
                    close()
                    moveTo(20.10f, 12.10f)
                    arcTo(7.61f, 7.61f, 0.00f, false, true, 19.80f, 14.20f)
                    lineTo(19.50f, 15.30f)
                    lineTo(20.30f, 16.10f)
                    lineTo(27.00f, 22.80f)
                    arcTo(2.88f, 2.88f, 0.00f, false, true, 27.90f, 24.90f)
                    arcTo(2.72f, 2.72f, 0.00f, false, true, 27.00f, 27.00f)
                    arcTo(2.90f, 2.90f, 0.00f, false, true, 22.80f, 27.00f)
                    lineTo(16.10f, 20.30f)
                    lineTo(15.30f, 19.50f)
                    lineTo(14.20f, 19.80f)
                    arcTo(7.61f, 7.61f, 0.00f, false, true, 12.10f, 20.10f)
                    arcTo(8.27f, 8.27f, 0.00f, false, true, 6.40f, 17.80f)
                    arcTo(7.63f, 7.63f, 0.00f, false, true, 4.00f, 12.10f)
                    arcTo(8.33f, 8.33f, 0.00f, false, true, 4.30f, 9.90f)
                    lineTo(8.70f, 14.30f)
                    arcTo(4.14f, 4.14f, 0.00f, false, false, 14.60f, 14.50f)
                    arcTo(4.14f, 4.14f, 0.00f, false, false, 14.40f, 8.60f)
                    lineTo(10.00f, 4.20f)
                    arcTo(6.45f, 6.45f, 0.00f, false, true, 12.00f, 3.90f)
                    arcTo(8.27f, 8.27f, 0.00f, false, true, 17.70f, 6.20f)
                    arcTo(8.49f, 8.49f, 0.00f, false, true, 20.10f, 12.10f)
                    close()
                }
            }
        }.build()
        return _Tools!!
    }

private var _Tools: ImageVector? = null
