// Generated by XIcons
// 2025-08-17 11:03:58
package cn.enaium.xicons.compose.carbon

import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import cn.enaium.xicons.compose.CarbonIcons

public val CarbonIcons.Default.TrafficFlow: ImageVector
    get() {
        if (_TrafficFlow != null) {
            return _TrafficFlow!!
        }
        _TrafficFlow = ImageVector.Builder(
            name = "TrafficFlow",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f
        ).apply {
            group(scaleX = 0.75f, scaleY = 0.75f) {
                path(fill = SolidColor(androidx.compose.ui.graphics.Color.Black)) {
                    moveTo(26.00f, 8.00f)
                    lineTo(22.00f, 4.00f)
                    lineTo(18.00f, 8.00f)
                    lineTo(19.41f, 9.42f)
                    lineTo(21.00f, 7.83f)
                    verticalLineTo(18.00f)
                    horizontalLineTo(23.00f)
                    verticalLineTo(7.83f)
                    lineTo(24.58f, 9.41f)
                    lineTo(26.00f, 8.00f)
                    close()
                    moveTo(12.59f, 22.58f)
                    lineTo(11.00f, 24.17f)
                    verticalLineTo(14.00f)
                    horizontalLineTo(9.00f)
                    verticalLineTo(24.17f)
                    lineTo(7.42f, 22.59f)
                    lineTo(6.00f, 24.00f)
                    lineTo(10.00f, 28.00f)
                    lineTo(14.00f, 24.00f)
                    lineTo(12.59f, 22.58f)
                    close()
                    moveTo(2.00f, 2.00f)
                    horizontalLineTo(4.00f)
                    verticalLineTo(30.00f)
                    horizontalLineTo(2.00f)
                    close()
                    moveTo(28.00f, 2.00f)
                    horizontalLineTo(30.00f)
                    verticalLineTo(30.00f)
                    horizontalLineTo(28.00f)
                    close()
                    moveTo(15.00f, 2.00f)
                    horizontalLineTo(17.00f)
                    verticalLineTo(6.00f)
                    horizontalLineTo(15.00f)
                    close()
                    moveTo(15.00f, 10.00f)
                    horizontalLineTo(17.00f)
                    verticalLineTo(14.00f)
                    horizontalLineTo(15.00f)
                    close()
                    moveTo(15.00f, 18.00f)
                    horizontalLineTo(17.00f)
                    verticalLineTo(22.00f)
                    horizontalLineTo(15.00f)
                    close()
                    moveTo(15.00f, 26.00f)
                    horizontalLineTo(17.00f)
                    verticalLineTo(30.00f)
                    horizontalLineTo(15.00f)
                    close()
                }
            }
        }.build()
        return _TrafficFlow!!
    }

private var _TrafficFlow: ImageVector? = null
